### ISSUE TITLE
The memory usage of the application has increased several times, indicating a possible memory leak.

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#3762] opened 2023-03-24 09:19 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I just upgraded to 2.3.2 and noticed a significant increase in memory usage (from less than a few hundred MB before, to a sudden spike of 6 GB now) after simply refreshing a list. I'm not sure if this is a known bug or if there are any plans to fix it. However, it's a serious issue for me as it's rendering my application unusable.

### How to reproduce

I conducted the verification on my code repository.
1. git clone https://github.com/BabySid/sid-desktop
2. reset 'main' to to any commit before 3.22.
3. build the application and click the menu: script runner, add some new script and save. and u can see memory usage is increasing to almost 4GB.
4. switch version to 2.2.4 and re-run the application, memory usage is less than 500MB.

Of course, the above solution is quite complicated. You can use the following example code to reproduce the issue.

```
package main

import (
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/theme"
    "fyne.io/fyne/v2/widget"
)

func main() {
    a := app.New()
    w := a.NewWindow("Hello")
    a.Settings().SetTheme(theme.LightTheme())
    txt := widget.NewMultiLineEntry()
    md := widget.NewRichTextFromMarkdown(``)
    sp := container.NewHSplit(txt, md)
    btn := widget.NewButton("haha", func() {
        
    })
    btn.Importance = widget.HighImportance

    txt.OnChanged = func(s string) {
        md.ParseMarkdown(s)
    }

    doc := container.NewBorder(btn, nil, nil, nil, sp)

    w.SetContent(doc)

    w.ShowAndRun()
}
``` 
After running the program, the initial memory usage is not high, around 40 MB. Then, by using the mouse to drag the split area back and forth, you can see that in version 2.3.0, the memory quickly increases to about 300 MB, while in version 2.2.4, the memory hardly increases at all.

### Screenshots

I tested two versions, 2.2.4 and 2.3.2. The former used around 40 MB of memory after the application startup, while the latter used 400 MB. this is the memory usage on 2.2.4

![image](https://user-images.githubusercontent.com/6658943/227474670-9728ff41-c7a9-42f9-83f4-f159392f3c83.png)
![image](https://user-images.githubusercontent.com/6658943/227474714-1885392a-7890-4283-97d6-6cddea25fafe.png)

Then I use pprof tools to capture some graph. these are the memory allocation graphs I obtained using pprof for both versions via the command 

```
go tool pprof  http://127.0.0.1:6060/debug/pprof/heap
(pprof) web
```
this is for 2.2.4
![2 2 4](https://user-images.githubusercontent.com/6658943/227475396-e9df94d7-0e34-4873-af0a-7b7ec43514c5.svg)

and this is for 2.3.2
![2 3 2](https://user-images.githubusercontent.com/6658943/227475418-c49b8f06-4e85-4673-966a-bf808b902db0.svg)

### Example code

```
package main

import (
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/theme"
    "fyne.io/fyne/v2/widget"
)

func main() {
    a := app.New()
    w := a.NewWindow("Hello")
    a.Settings().SetTheme(theme.LightTheme())
    txt := widget.NewMultiLineEntry()
    md := widget.NewRichTextFromMarkdown(``)
    sp := container.NewHSplit(txt, md)
    btn := widget.NewButton("haha", func() {
        
    })
    btn.Importance = widget.HighImportance

    txt.OnChanged = func(s string) {
        md.ParseMarkdown(s)
    }

    doc := container.NewBorder(btn, nil, nil, nil, sp)

    w.SetContent(doc)

    w.ShowAndRun()
}
```

### Fyne version

 fyne.io/fyne/v2 v2.3.2

### Go compiler version

go 1.19

### Operating system and version

Windows 10

**Comment by Bluebugs** [comment] 2023-03-24 23:26
If you do stop to move the horizontal split and wait for a minutes, does the memory go back down?

I am able to reproduce the problem partially here. It seems to be multiple things at the same time. On Windows the memory does climb very fast and the GC doesn't seems to kick in as fast as on Linux leading to higher memory between the two systems.

Also for each line of text added to the text entry, we can get 100MB of memory allocated (during the process of generating that line). I can not exactly reproduce the report from pprof above on Linux. My memory spike are in harfbuzz.

It might be something where having a cache in harfbuzz that does the allocation once would actually be better than GC the data for each call. I will have to look at this further and understand the code to see what is exactly going on.

**Comment by dweymouth** [comment] 2023-03-25 03:59
> It might be something where having a cache in harfbuzz that does the allocation once would actually be better than GC the data for each call.

I am not very familiar with the fyne internals at all, but I would think that using sync.Pool could be beneficial in a lot of places since the Go GC runs only every so often and UI interactions could result in a lot of object churn between GC cycles.

**Comment by andydotxyz** [comment] 2023-03-25 18:47
I cannot replicate on Linux either, it may be Windows specific somehow.
It seems that the font cache is not never hitting...

**Comment by andydotxyz** [comment] 2023-03-25 21:28
I cannot replicate the problem, but I suspect it could relate to https://github.com/go-text/typesetting/issues/47

**Comment by BabySid** [comment] 2023-03-27 02:14
> If you do stop to move the horizontal split and wait for a minutes, does the memory go back down?
> 
> I am able to reproduce the problem partially here. It seems to be multiple things at the same time. On Windows the memory does climb very fast and the GC doesn't seems to kick in as fast as on Linux leading to higher memory between the two systems.

When I  moved the split, the memory soared to over 570 megabytes, and then I stopped and waited for a few minutes,  the memory only decreased by 20 megabytes, maintaining it at 550 megabytes

**Comment by Bluebugs** [comment] 2023-03-27 02:17
And when you repeat this cycle of resize and wait, does it come back to 550M?

**Comment by BabySid** [comment] 2023-03-27 03:45
1. When the application just starts, the memory usage is over 70 megabytes.
2. When I move the split 10 times, the memory usage increases to 580 megabytes.
3. Then I stop the movement for about a minute, and the memory drops back to 564 megabytes.
4. Then I continue to move the spilit  5 times, and the memory usage increases to 647 megabytes.
5. When I stop the movement, and this time the memory drops back relatively quickly, but only to 578 megabytes.

**Comment by andydotxyz** [comment] 2023-03-28 09:06
Can you please test the latest `develop`? This issue may have been resolved with a recent `go-text` memory leak fix.

**Comment by BabySid** [comment] 2023-03-29 02:52
Good news, I tested using the develop branch and the memory usage has indeed decreased significantly. In my application, memory usage peaked at 800MB, which is acceptable. During the split-application test, memory usage was similar to version 2.2.4.  
Thank you very much for the code fixes on the branch, they are really awesome! I'm looking forward to the new version being quickly merged and released.

**Comment by andydotxyz** [comment] 2023-03-29 11:10
Thanks. There is now a similar PR on release branch for 2.3.4 as well.
Develop will have further text optimisations before we release, so hopefully it keeps getting better :)

**Closed by andydotxyz** 2023-03-29 11:10 UTC
Labels: unverified
