### ISSUE TITLE
can't run ui on windows

### ISSUE THREAD

**Issue by Nothing-no** [fyne-io/fyne#1720] opened 2021-01-05 13:54 UTC
i don't why i can find my program running at the background, but ui can't display and there is no error occurred...

**Comment by Jacalz** [comment] 2021-01-05 14:12
Please always use the issue templates when opening issues. We need more information if we are to be able to help.
We need information such as hardware, operating systems, code examples and so on.

**Comment by Nothing-no** [comment] 2021-01-06 00:28
![lALPBFRyc70ERP7Mg80CmQ_665_131](https://user-images.githubusercontent.com/55579792/103713632-cecd2780-4ff7-11eb-9f7d-4583175e28b8.png)
![lALPBG1Q6j542srNAebNAm8_623_486](https://user-images.githubusercontent.com/55579792/103713634-d12f8180-4ff7-11eb-8920-e35747c1ccce.png)
![lALPBGKoblGW5RTNAZTNAr8_703_404](https://user-images.githubusercontent.com/55579792/103713696-fae8a880-4ff7-11eb-8129-75f68fc8d471.png)
using demo code to run and get the same result.
`func main() {
	myApp := app.New()
	myWin := myApp.NewWindow("demo")
	hb := fyne.NewContainerWithLayout(layout.NewHBoxLayout())
	c1 := canvas.NewText("demo", color.Black)
	hb.Add(c1)
	myWin.SetContent(hb)
	myWin.ShowAndRun()

}`

**Comment by Nothing-no** [comment] 2021-01-06 00:30
> Please always use the issue templates when opening issues. We need more information if we are to be able to help.
> We need information such as hardware, operating systems, code examples and so on.

i have attach more information as mentioned before

**Comment by Jacalz** [comment] 2021-01-06 09:04
Thanks. My best guess is that this issue is a duplicate of https://github.com/fyne-io/fyne/issues/410. While I think you are not running Windows Server, I have seen the Xeon processors not having adequate OpenGL support for their drivers. Can you confirm that you are using the integrated graphics? If that’s the case, can you please try to either install or update your graphics driver?

**Comment by Jacalz** [comment] 2021-01-06 09:07
You could install https://www.geeks3d.com/dl/show/625 and take a screenshot if the GPU tab. That should tell us what GPU you have.

**Comment by Nothing-no** [comment] 2021-01-07 03:46
> You could install https://www.geeks3d.com/dl/show/625 and take a screenshot if the GPU tab. That should tell us what GPU you have.

here is my snapshoot of gpu, I've tried on two PCs(both win10, but with different GPU), one can run and the other cannot, 
![lALPBFuNcRR5EefNA0XNApw_668_837](https://user-images.githubusercontent.com/55579792/103848586-ac153e80-50dd-11eb-9be2-b64781d3a11a.png)
![lALPBGY17QLFBvLNAirNAZI_402_554](https://user-images.githubusercontent.com/55579792/103848590-ae779880-50dd-11eb-8565-23e51df63014.png)

**Comment by Nothing-no** [comment] 2021-01-07 06:27
TX~~, I update the graphic driver and i works perfect~~  thanks a lot

**Comment by Jacalz** [comment] 2021-01-07 08:51
> TX~~, I update the graphic driver and i works perfect~~ thanks a lot

Grate. You are very welcome. I see from the screenshot that it only supported OpenGL 1.1 before, which is unsupported by Fyne. I am going to close this now.

**Closed by Jacalz** 2021-01-07 08:51 UTC
Labels: question
