### ISSUE TITLE
No button can browse windows files

### ISSUE THREAD

**Issue by guijinwei** [fyne-io/fyne#918] opened 2020-04-30 09:13 UTC
it just like you upload a file and you can click a button. Then windows can open a window,you can choose some files.

**Comment by andydotxyz** [comment] 2020-04-30 11:24
I think this is a duplicate of the recently completed work for file dialog. #225

**Comment by andydotxyz** [comment] 2020-04-30 11:24
In 1.3 release you will be able to call `dialog.ShowFileOpen()`

**Closed by andydotxyz** 2020-04-30 11:24 UTC
