### ISSUE TITLE
Auto dismiss notifications after X duration

### ISSUE THREAD

**Issue by Beebeeoii** [fyne-io/fyne#3283] opened 2022-09-26 01:32 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

This is a small feature request and just a QOL feature. Please correct me if I am wrong - Currently, there is no option to enable auto dismissal of notifications. Users would have to manually click the 'X' button to close the notification. This is for macOS and linux. Not too sure about whether this is also missing from windows notifications.

### Is it possible to construct a solution with the existing API?

I would think so as notifications are implemented by using the respective OS's library (darwin, windows etc) and they do support notification duration.

### Describe the solution you'd like to see.

Have a way for users to include duration for notifications.

**Comment by andydotxyz** [comment] 2022-09-27 16:15
This would be a nice feature indeed.
We'd need to code up the specifics for macOS, Windows, Linux, iOS and Android - but I assume the APIs are mostly well documented in how this would be added.

**Comment by Beebeeoii** [comment] 2022-09-28 00:28
let me put together a PR soon (hopefully :p)

**Comment by dweymouth** [comment] 2024-06-13 15:17
Should this be considered a duplicate of #2365?

**Comment by andydotxyz** [comment] 2024-06-14 14:09
Yes good point

**Closed** 2024-06-14 14:12 UTC
Labels: enhancement
