### ISSUE TITLE
Wrong font rendering when overriding theme

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#4937] opened 2024-06-14 08:15 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When one uses a theme for overriding which differs with some font metrics (yet unknown to me) from the main theme, the fonts are rendered wrong.

I discovered this when trying to change the hyperlink theme override test to use `test.Theme()` (default test theme) and `test.newTheme()` (ugly test theme) to remove its dependency from the production theme.

The test fails when doing so and further research revealed that the text was rendered differently.

### How to reproduce

Change the hyperlink theme override test in `widget/hyperlink_test.go` like so:
```diff
func TestHyperlink_ThemeOverride(t *testing.T) {
	_ = test.NewApp()
	defer test.NewApp()
-	test.ApplyTheme(t, internalTest.LightTheme(theme.DefaultTheme()))
+	test.ApplyTheme(t, test.Theme())

	hyperlink := &Hyperlink{Text: "Test"}
	bg := canvas.NewRectangle(color.Gray{Y: 0xc0})
	w.Resize(hyperlink.MinSize())

	light := w.Canvas().Capture()
-	test.ApplyTheme(t, test.Theme())
+	test.ApplyTheme(t, test.NewTheme())
	hyperlink.Refresh()
	ugly := w.Canvas().Capture()
	assertPixelsMatch(t, false, ugly, light)

-	cache.OverrideTheme(hyperlink, internalTest.LightTheme(theme.DefaultTheme()))
+	cache.OverrideTheme(hyperlink, test.Theme())
	hyperlink.Refresh()
	override := w.Canvas().Capture()
	assertPixelsMatch(t, true, override, light)
}
```

The test will then fail. One could use `AssertImageMatches` to get image files of the captured images or write a small test app to have it on screen.

### Example code

-

### Fyne version

develop

### Go compiler version

1.22.1

### Operating system and version

macOS 14.5

**Comment by dweymouth** [comment] 2024-06-14 16:37
This might be caused by the fact that it looks like RichText is still looking up the global theme for text size:

https://github.com/fyne-io/fyne/blob/master/widget/richtext_objects.go#L441

**Comment by dweymouth** [comment] 2024-06-14 16:53
Here is a test snippet that shows that overriding text sizes of labels in ThemeOverrideContainer doesn't work. Not sure it's the same root cause but I think we can track it in this ticket in any case and it should be a blocker. The debug print shows that *ovrTheme.Size is indeed called with the SizeNameText name (more than a dozen times??) but the second label's text size is the same as the first

```go
package main

import (
	"image/color"
	"log"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type ovrTheme struct {
	textSize float32
}

var _ fyne.Theme = (*ovrTheme)(nil)

func (t *ovrTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
	return theme.DefaultTheme().Color(name, variant)
}

func (t *ovrTheme) Size(name fyne.ThemeSizeName) float32 {
	if name == theme.SizeNameText {
		log.Println("ovrTheme.Size returning custom SizeNameText value")
		return t.textSize
	}
	return theme.DefaultTheme().Size(name)
}

func (t *ovrTheme) Font(style fyne.TextStyle) fyne.Resource {
	return theme.DefaultTheme().Font(style)
}

func (t *ovrTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(name)
}

func main() {
	a := app.NewWithID("test")

	w := a.NewWindow("Window")
	content := container.NewVBox(
		widget.NewLabel("hello"),
		container.NewThemeOverride(widget.NewLabel("world"), &ovrTheme{textSize: 30}),
	)
	w.SetContent(content)

	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment] 2024-06-14 18:28
It is less general than it sounds - I use font size overrides through a theme override container currently and it works great. 
Is it fixed by calling "Refresh" on the container? The widget is initialised outside of the theme override.

**Comment by dweymouth** [comment] 2024-06-14 18:31
OK it is fixed by calling `content.Refresh()` - but why is it needed? Any other container or widget can be set up before showing the window, then made visible and it won't need an initial Refresh()

**Comment by andydotxyz** [comment] 2024-06-14 18:33
Well it was a little guess - but the potential reason that this is different is because the initialisation of the Label does not know it will immediately be passed into a container with a different theme.

**Comment by dweymouth** [comment] 2024-06-14 18:35
I think that may need some documentation if that's by design - it is non-obvious to me as a seasoned Fyne API consumer (and core developer) that it would be needed. Or perhaps the NewThemeOverride constructor can ensure the new theme info is automatically passed on to its constituents?

**Comment by andydotxyz** [comment] 2024-06-14 19:43
It's not really "by design" but is understandable given the situation. I would rather we find a non-documentation approach :)

**Comment by andydotxyz** [comment] 2024-06-15 13:40
I have a local fix for this root issue (it's a cache collision) and will open a PR later today.

**Comment by andydotxyz** [comment] 2024-06-17 08:27
This is now fixed on develop, thanks.

**Closed by andydotxyz** 2024-06-17 08:27 UTC
Labels: bug, blocker
