### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by hq-zhonger** [fyne-io/fyne#3519] opened 2022-12-30 11:20 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Can fyne currently display and play videos or render videos to the gui

### Describe the solution you'd like to see.

videos to the gui

**Comment by Jacalz** [comment] 2022-12-30 11:40
This is not currently supported. Closing as duplicate of https://github.com/fyne-io/fyne/issues/449.

**Closed by Jacalz** 2022-12-30 11:40 UTC
