### ISSUE TITLE
The color of the custom icon cannot change with the light and dark of the theme

### ISSUE THREAD

**Issue by junmaqiang** [fyne-io/fyne#4015] opened 2023-07-03 03:22 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

## is demo
<img width="595" alt="截屏2023-07-03 11 18 13" src="https://github.com/fyne-io/fyne/assets/1819457/41b05042-c6f4-47da-8ddf-ab1f368101b7">

## is code
```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("ico.demo")
	//
	svgContent := `<svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 24C4 35.0457 12.9543 44 24 44V44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4" stroke="#333" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M36 24C36 17.3726 30.6274 12 24 12C17.3726 12 12 17.3726 12 24C12 30.6274 17.3726 36 24 36V36" stroke="#333" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`
	svgResource := fyne.NewStaticResource("logo.svg", []byte(svgContent))
	//
	a := widget.NewButtonWithIcon("Btn", svgResource, nil)
	b := widget.NewButtonWithIcon("Btn", theme.DownloadIcon(), nil)
	c := widget.NewButtonWithIcon("Btn", svgResource, nil)
	//
	layouta := container.NewHBox(a, b, c)
	layout := container.NewVBox(layouta)
	myWindow.SetContent(layout)
	myWindow.Resize(fyne.NewSize(600, 400))
	myWindow.ShowAndRun()
}

```

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("ico.demo")
	//
	svgContent := `<svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 24C4 35.0457 12.9543 44 24 44V44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4" stroke="#333" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M36 24C36 17.3726 30.6274 12 24 12C17.3726 12 12 17.3726 12 24C12 30.6274 17.3726 36 24 36V36" stroke="#333" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`
	svgResource := fyne.NewStaticResource("logo.svg", []byte(svgContent))
	//
	a := widget.NewButtonWithIcon("Btn", svgResource, nil)
	b := widget.NewButtonWithIcon("Btn", theme.DownloadIcon(), nil)
	c := widget.NewButtonWithIcon("Btn", svgResource, nil)
	//
	layouta := container.NewHBox(a, b, c)
	layout := container.NewVBox(layouta)
	myWindow.SetContent(layout)
	myWindow.Resize(fyne.NewSize(600, 400))
	myWindow.ShowAndRun()
}
```

### Fyne version

v2.3.5

### Go compiler version

go version go1.20.3 darwin/amd64

### Operating system and version

macOS 13.4.1

### Additional Information

The color of the custom icon cannot change with the light and dark of the theme

**Comment by Jacalz** [comment] 2023-07-03 05:26
Use [NewThemedResource()](https://pkg.go.dev/fyne.io/fyne/v2/theme#NewThemedResource) instead.

**Comment by Jacalz** [comment] 2023-08-19 11:31
Closing as duplicate of #3900.

**Closed by Jacalz** 2023-08-19 11:31 UTC
Labels: unverified
