### ISSUE TITLE
Form submit button remains disabled after pasting text into a MultiLineEntry with custom validation

### ISSUE THREAD

**Issue by agukrapo** [fyne-io/fyne#5028] opened 2024-07-24 23:03 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Pasting text into a MultiLineEntry with custom validation won't enable the submit button

### How to reproduce

1. Run example code
2. Paste text into MultiLineEntry
3. Submit button still disabled

### Example code

```go
package main

import (
	"errors"
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	w := app.New().NewWindow("test")
	w.Resize(fyne.NewSize(500, 100))

	txt := widget.NewMultiLineEntry()
	txt.Validator = func(s string) error {
		if s == "" {
			return errors.New("empty")
		}
		return nil
	}

	form := &widget.Form{
		OnSubmit: func() {
			fmt.Println("OnSubmit")
		},
	}
	form.Append("txt", txt)

	w.SetContent(form)
	w.ShowAndRun()
}


```

### Fyne version

fyne.io/fyne/v2 v2.5.0

### Go compiler version

go1.22.5 darwin/arm64

### Operating system and version

macOS 14.5, windows 10

### Additional Information

I was able to fix it with this workaround:
```go
txt.OnChanged = func(s string) {
_ = txt.Validate()
}
```

**Comment by andydotxyz** [comment] 2024-09-04 10:32
Ah yes, it seems paste is not triggering the change events

**Comment by pierrec** [comment] 2024-09-14 10:15
Duplicate of #5058.

**Closed** 2024-09-14 17:32 UTC
Labels: bug, duplicate
