### ISSUE TITLE
Doesn't support Chinese?

### ISSUE THREAD

**Issue by DoMySon** [fyne-io/fyne#218] opened 2019-04-08 09:06 UTC
![fyne](https://user-images.githubusercontent.com/32303646/55712070-a67a5880-5a20-11e9-9bf1-f2650b488505.png)

**Comment by DoMySon** [comment] 2019-04-08 09:08
The text content is “中文测试”，But it's not displayed correctly.

**Comment by jadr2ddude** [comment] 2019-04-08 12:03
See https://github.com/fyne-io/fyne/issues/63#issuecomment-455850180 until we have a better solution included

**Comment by DoMySon** [comment] 2019-04-09 02:00
@jadr2ddude  Thank you for your efforts.

**Comment by DoMySon** [comment] 2019-04-09 03:52
@jadr2ddude  One more question,When I use 'Lable' to display a long text, the UI will become so wide that it is possible to wrap lines automatically according to the size of' Label' and display a progress bar

**Comment by jadr2ddude** [comment] 2019-04-09 11:05
@DoMySon I am not entirely sure what you mean. Could you send a screenshot and/or some code?

**Comment by DoMySon** [comment] 2019-04-10 08:38
In your 'fyne_demo/main.go:73'
```go
widget.NewButton("Canvas", func() { Canvas(a) }),
//replace to
btn:=widget.widget.NewButton("Canvas", func() { Canvas(a) })
btn.Resize(fyne.NewSize(20, 20))
```
but the Button size doesn't work. it's automatically layout?

and,like my first question. if the Label's content too much, the Label width will be long.(even more than one screen)
```go
widget.NewLabel(Long text) // you can try it
```

**Comment by andydotxyz** [comment] 2019-04-10 16:41
You are right - the demo uses a layout. If there is a layout in the container then the size and position are controlled by the layout. You can build your own layout if you wish to provide specific control over the size and position (see the clock example).

If you set a long text into a label it will be a long label. There is no word wrap implemented, if you want to display on multiple lines you will need to break the text with a newline.

**Comment by andydotxyz** [comment] 2019-04-10 16:43
Closing this as a duplicate of #63 - we need to find a better solution for language support but that will be tracked separately.

**Comment by DoMySon** [comment] 2019-04-10 16:59
tks ，I suggest referring to the layout of unity editor.it’s cool :)

**Comment by andydotxyz** [comment] 2019-04-10 21:57
Out of interest what do you like about the unity editor layout?

**Closed by andydotxyz** 2019-04-10 21:57 UTC
