### ISSUE TITLE
There is no such function

### ISSUE THREAD

**Issue by mei2015** [fyne-io/fyne#3019] opened 2022-06-01 07:13 UTC
![image](https://user-images.githubusercontent.com/10136065/171348106-4ec51dbe-675a-4704-af31-a19746f66343.png)
  
I need a minimize tray feature but there doesn't seem to be an API for that

**Comment by andydotxyz** [comment] 2022-06-01 20:36
This will be released in v2.2.0 later this week. Duplicate of #283

**Closed by andydotxyz** 2022-06-01 20:36 UTC
