### ISSUE TITLE
Big apk size fixed ; upx - -ldflags="-s -w"

### ISSUE THREAD

**Issue by raifpy** [fyne-io/fyne#1673] opened 2020-12-19 10:52 UTC
Whatever, i was create repo for this; https://github.com/raifpy/fynemode

Maybe fyne team can add --upx param for `fyne package...`

Example pic
![image](https://user-images.githubusercontent.com/50047969/102687625-6ca3b280-4201-11eb-8fa4-17fea6066f15.png)

**Comment by Jacalz** [comment] 2020-12-19 11:44
As for the big apk size, that is probably a duplicate of https://github.com/fyne-io/fyne/issues/1097. I guess we probably could add an option to use`-ldflags="-s -w" ` to remove debug and DWARF data. That certainly wouldn’t hurt and would save some space. 

Not so sure about upx though. A user would need to have that installed which makes it a bit less useful and it does not work across all platforms which isn’t really in line with the cross-platform nature of Fyne.

**Comment by stuartmscott** [comment] 2020-12-19 18:00
>  I guess we probably could add an option to use-ldflags="-s -w" to remove debug and DWARF data.

Could be something enabled when packaging in `release` mode

**Comment by andydotxyz** [comment] 2020-12-19 18:40
We already do this for platforms that we build manually (`cmd/fyne/command/build.go`:
```go
		if b.release {
			args = append(args, "-ldflags", "-s -w")
		}
```

However it's possible that we missed adding it to the mobile builder which is located in `cmd/fyne/internal/mobile`.

**Comment by raifpy** [comment] 2020-12-19 20:04
![image](https://user-images.githubusercontent.com/50047969/102698268-31c76c00-424d-11eb-91f2-edf82bb35fa4.png)
`internal/mobile/build.go`

![image](https://user-images.githubusercontent.com/50047969/102698382-e792ba80-424d-11eb-9fd6-22a1db71f95e.png)
`internal/mobile/init.go: 126+`

![image](https://user-images.githubusercontent.com/50047969/102698420-1b6de000-424e-11eb-8097-ce247ae7b853.png)
`internal/mobile/manifest.go`

Maybe you can append this codes regular* for Unix users (`fyne package ... -upx`).  I know upx not safe but can be usefull..
Also my repo isn't safe for other users (can't compile directly)

**Comment by andydotxyz** [comment] 2021-02-23 12:32
I think we have done all we can in this area - as @Jacalz said we are not going to add more external compile dependencies at this time.
With Go 1.16 you should see file size improvements for free.

**Closed by andydotxyz** 2021-02-23 12:32 UTC

**Comment by Jacalz** [comment] 2021-02-23 13:58
Indeed. File sizes with Go 1.16 seems to be around 30% smaller than Go 1.14 🙂
