### ISSUE TITLE
Unable to build/run

### ISSUE THREAD

**Issue by Merith-TK** [fyne-io/fyne#504] opened 2019-10-28 02:32 UTC
**Describe the bug**
Fails to build/Run with the error

**To Reproduce**
function demo
https://fyne.io/develop/
copy/paste into main.go, and `go run`/`go build`

**Screenshots**
```
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from ..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw\c_glfw_windows.go:6:
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function ‘createMonitor’:
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:68:5: warning: implicit declaration of function ‘wcscpy’ [-Wimplicit-function-declaration]
   68 |     wcscpy(monitor->win32.adapterName, adapter->DeviceName);
      |     ^~~~~~
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function ‘_glfwPlatformIsSameMonitor’:
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:228:9: warning: implicit declaration of function ‘wcslen’ [-Wimplicit-function-declaration]
  228 |     if (wcslen(first->win32.displayName))
      |         ^~~~~~
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:229:16: warning: implicit declaration of function ‘wcscmp’ [-Wimplicit-function-declaration]
  229 |         return wcscmp(first->win32.displayName, second->win32.displayName) == 0;
      |                ^~~~~~
# command-line-arguments
C:\msys\usr\local\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1   
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status
````

**Device (please complete the following information):**
 - OS: Windows 10,
 - Version: 1903
 - Go version: `go1.12.7 windows/amd64`
 - Fyne version: litterally just `go get fyne.io/fyne` at around 1920 PST -8 time. 10/27/2019

**Comment by Merith-TK** [comment] 2019-10-28 02:47
same err on `go1.13.1 windows/amd6`
```
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from ..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw\c_glfw_windows.go:6:
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function ‘createMonitor’:
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:68:5: warning: implicit declaration of function ‘wcscpy’ [-Wimplicit-function-declaration]
   68 |     wcscpy(monitor->win32.adapterName, adapter->DeviceName);
      |     ^~~~~~
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function ‘_glfwPlatformIsSameMonitor’:
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:228:9: warning: implicit declaration of function ‘wcslen’ [-Wimplicit-function-declaration]
  228 |     if (wcslen(first->win32.displayName))
      |         ^~~~~~
..\..\..\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:229:16: warning: implicit declaration of function ‘wcscmp’ [-Wimplicit-function-declaration]
  229 |         return wcscmp(first->win32.displayName, second->win32.displayName) == 0;
      |                ^~~~~~
# command-line-arguments
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status```

**Comment by minias** [comment] 2019-10-28 13:02
same err on go1.13.3 windows/x64 
install msys64 in gcc Dir : C:\msys64\usr\bin
My opinion does not seem to support 64 bits.

```
C:\Users\user\go\src\fyne.io\fyne\cmd\fyne_demo>go build
# github.com/go-gl/glfw/v3.2/glfw
In file included from ..\..\..\..\..\pkg\mod\github.com\go-gl\glfw@v0.0.0-20181213070059-819e8ce5125f\v3.2\glfw\c_glfw_windows.go:6:
..\..\..\..\..\pkg\mod\github.com\go-gl\glfw@v0.0.0-20181213070059-819e8ce5125f\v3.2\glfw/glfw/src/win32_monitor.c: In function 'createMonitor':
..\..\..\..\..\pkg\mod\github.com\go-gl\glfw@v0.0.0-20181213070059-819e8ce5125f\v3.2\glfw/glfw/src/win32_monitor.c:68:5: warning: implicit declaration of function 'wcscpy' [-Wimplicit-function-declaration]
   68 |     wcscpy(monitor->win32.adapterName, adapter->DeviceName);
      |     ^~~~~~
..\..\..\..\..\pkg\mod\github.com\go-gl\glfw@v0.0.0-20181213070059-819e8ce5125f\v3.2\glfw/glfw/src/win32_monitor.c: In function '_glfwPlatformIsSameMonitor':
..\..\..\..\..\pkg\mod\github.com\go-gl\glfw@v0.0.0-20181213070059-819e8ce5125f\v3.2\glfw/glfw/src/win32_monitor.c:228:9: warning: implicit declaration of function 'wcslen' [-Wimplicit-function-declaration]
  228 |     if (wcslen(first->win32.displayName))
      |         ^~~~~~
..\..\..\..\..\pkg\mod\github.com\go-gl\glfw@v0.0.0-20181213070059-819e8ce5125f\v3.2\glfw/glfw/src/win32_monitor.c:229:16: warning: implicit declaration of function 'wcscmp' [-Wimplicit-function-declaration]
  229 |         return wcscmp(first->win32.displayName, second->win32.displayName) == 0;
      |                ^~~~~~
# fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

go: failed to remove work dir: GetFileInformationByHandle C:\Users\user\AppData\Local\Temp\go-build940952330\NUL: Incorrect function.
```

**Comment by minias** [comment] 2019-10-28 13:36
C:\Users\user\go\pkg\mod\github.com\go-gl\glfw@v0.0.0-20181213070059-819e8ce5125f\v3.2\glfw\glfw\src

```
#include "internal.h"

#include <stdlib.h>
#include <string.h>
#include <wchar.h> //this in wcspy , wcslen,wcscmp  //added
#include <limits.h>
#include <malloc.h>
```

but same to error :(

**Comment by andydotxyz** [comment] 2019-10-28 15:28
Do you have the mingw-w64 package installed inside msys2?

**Comment by Merith-TK** [comment] 2019-10-28 15:43
yes, I even installed the msys32, msys, and msys64 toolchains
—Merith

**Comment by Merith-TK** [comment] 2019-10-28 15:46
Also, there is no `mingw-w64` package
```
$ pacman -Syu mingw-w64
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
error: target not found: mingw-w64
```

**Comment by andydotxyz** [comment] 2019-10-28 16:43
You may need the name of the platform too? perhaps "mingw-w64-x86_64-gcc"

**Comment by Merith-TK** [comment] 2019-10-28 16:48
That is installed, the package you are referencing is `mingw-w64-x86_65-toolchain`
Which means the information on the site is incorrect as the site states it only needs GO
not gcc or anything else, just GO.

**Comment by andydotxyz** [comment] 2019-10-28 17:40
I'm sorry the documentation wasn't clear, whilst the API is 100% Go we do still need a C compiler under the hood. The page about compiling tries to explain it: https://fyne.io/develop/compiling.html

Can you confirm which docs you were following so we can update them appropriately?

**Comment by andydotxyz** [comment] 2019-10-28 17:43
Getting back to the original error I think that this is caused by a mix of 32 and 64 bit toolchain - probably path or package related issues.

I think it is the same as this other issue which has some helpful hints https://github.com/faiface/pixel/issues/112

**Comment by Merith-TK** [comment] 2019-10-28 18:04
Well i installed all the tool chains (msys has good seperation for this)
now it miracously build properly, but when i run, it has a opengl error
```
$ ./fyne-wallpaper.go.exe
2019/10/28 11:01:28 Fyne error:  failed to initialise OpenGL
2019/10/28 11:01:28   Cause: glBindFramebuffer
2019/10/28 11:01:28   At: C:/Users/merith/go/src/fyne.io/fyne/internal/driver/gl/window.go:1012
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x54 pc=0x5b4ead]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/internal/driver/gl.(*window).SetContent(0x0, 0x971ba0, 0xc000046240)
        C:/Users/merith/go/src/fyne.io/fyne/internal/driver/gl/window.go:362 +0x2d
main.main()
        C:/Users/merith/Documents/Workspace/fyne-wallpaper.go/main.go:12 +0x225
```

**Comment by Merith-TK** [comment] 2019-10-28 18:51
@andydotxyz the docs i was looking at were https://fyne.io/develop/

**Comment by andydotxyz** [comment] 2019-10-28 22:07
We only require 2.0 so it should work fine.
Can you provide any more information about your graphics processor?
Do you by any chance have 2, a low power one and a full one?

**Comment by Merith-TK** [comment] 2019-10-28 22:37
I have a Laptop, Dell Latitude E6400, can't give more specs at the moment,
as I mostly don't know how.

**Comment by MikeCongdon1** [comment] 2019-10-29 01:51
I have a Dell XPS13 with Ubuntu 18.04:
>gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0


>go build .
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from ./glfw/src/internal.h:169:0,
                 from ./glfw/src/context.c:28,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:
./glfw/src/x11_platform.h:39:10: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
 #include <X11/Xcursor/Xcursor.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

>go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mike/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mike/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build725024325=/tmp/go-build -gno-record-gcc-switches"


>go version
go version go1.12.7 linux/amd64

Hope some of this helps!

**Comment by Merith-TK** [comment] 2019-10-29 02:02
So here is another odity
my Latitude (windows 7) can BUILD the program, it just cant run it
my Toshiba (Windows 10) can RUN the program, it just cant build it

Like WTF?!

Is it possible to cross compile? like from linux to windows?

**Comment by lucor** [comment] 2019-10-29 08:42
@MikeCongdon1 on ubuntu you'd need additional packages like `xorg-dev` to compile. List of all prerequisites are available here: https://github.com/fyne-io/fyne#prerequisites

@Merith-TK yes, it is possible to cross compile from linux to windows. Docs available here: https://fyne.io/develop/cross-compiling.html

**Comment by andydotxyz** [comment] 2019-10-29 10:28
Hi @Merith-TK I have researched that laptop and it comes in two varieties that both should (only just) meet our minimum requirements. The model seems to originate to more than 10 years ago and we reference OpenGL spec of 2008 so it's kindof close. (Unless I have the wrong model information - I'm reading mostly this page: https://www.notebookcheck.net/Review-Dell-Latitude-E6400-Notebook.12875.0.html).

Can you please confirm that all of your graphics drivers are up to date? If possible let us know what OpenGL version is reported by your graphics drivers - the hints on this page may help:
https://community.esri.com/groups/technical-support/blog/2012/03/15/what-version-of-opengl-do-i-have-and-do-i-have-the-latest-drivers-for-my-system

**Comment by andydotxyz** [comment] 2019-10-29 10:29
> my Toshiba (Windows 10) can RUN the program, it just cant build it

Is the build error similar to before? I am building on a Windows 10 machine with MSYS2 and MingW-w64 installed and it works just fine. Graphics hardware should not affect the ability to compile.

**Comment by andydotxyz** [comment] 2019-10-29 10:30
At some point in the future (soon?) we should probably create a "fyne_graphics_test" app that can run and diagnose these issues. Distributing a binary so that compile issues are ruled out... but I think we need to focus on the next release first as it's only 4 weeks left!

**Comment by MikeCongdon1** [comment] 2019-10-29 13:45
@lucor  Thanks for the guidance!
However, I am now getting a different error having to do with snprintf %s truncating. It's not something I'm going to pursue for now though - though, I would be happy to provide details if desired

**Comment by Merith-TK** [comment] 2019-10-29 17:05
@andydotxyz i posted the build error from my windows 10 machine, i wish i knew the model number easily so i could give it to you, but it DEFINATELY supports opengl 3+

At this point i have even reinstalled msys2 and installed the exact same toolchains i did on my Latitude, and it is still returning errors akin to that, (i can post them in a few hours as i dont have RDP

@lucor I made a issue showing that despite docker being installed on my archlinux machine, the program `fyne-cross` does not detect the docker binary

**Comment by andydotxyz** [comment] 2019-10-30 08:12
@Merith-TK Apologies, I thought the windows 10 build issue was the one that was resolved. Please do post details once we have them so we can help with the specifics.

**Comment by andydotxyz** [comment] 2019-12-25 18:54
Can you please confirm if this is still and issue and/or provide confirmation of which aspect of the reports are still unresolved?

**Comment by airplayx** [comment] 2020-01-08 05:04
> Can you please confirm if this is still and issue and/or provide confirmation of which aspect of the reports are still unresolved?

can't package in Win10 

![QQ截图20200108125334](https://user-images.githubusercontent.com/8004501/71951600-90e7c880-3216-11ea-9df4-f75c4de893b8.png)

 `fyne@v1.2.1`
 `go version go1.12.3`

**Comment by andydotxyz** [comment] 2020-01-08 08:30
To cross compile you will need to follow the  setup steps in the documentation at https://fyne.io/develop/cross-compiling.html.

Make sure that you have downloaded the appropriate tool chains, or try fyne-cross instead.

**Comment by andydotxyz** [comment] 2020-03-13 13:21
Closing due to no confirmation that this is still an issue

**Closed by andydotxyz** 2020-03-13 13:21 UTC
Labels: OS:Windows, question

**Comment by ryangurn** [comment] 2020-04-13 21:26
This is occuring for me, the aspect that does not work is when attempting to execute `go get fyne.io/fyne/cmd/fyne_demo/`. I get the following output.

```
PS C:\Users\Ryan> go get fyne.io/fyne/cmd/fyne_demo/
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw\c_glfw_windows.go:6:0:
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function 'createMonitor':
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:68:5: warning: implicit declaration of function 'wcscpy'; did you mean 'stpcpy'? [-Wimplicit-function-declaration]
     wcscpy(monitor->win32.adapterName, adapter->DeviceName);
     ^~~~~~
     stpcpy
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function '_glfwPlatformIsSameMonitor':
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:228:9: warning: implicit declaration of function 'wcslen'; did you mean 'scalbn'? [-Wimplicit-function-declaration]
     if (wcslen(first->win32.displayName))
         ^~~~~~
         scalbn
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:229:16: warning: implicit declaration of function 'wcscmp'; did you mean 'wctomb'? [-Wimplicit-function-declaration]
         return wcscmp(first->win32.displayName, second->win32.displayName) == 0;
                ^~~~~~
                wctomb
# fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

go: failed to remove work dir: GetFileInformationByHandle C:\Users\RYANGU~1\AppData\Local\Temp\go-build598511330\NUL: Incorrect function.
PS C:\Users\Ryan>
```

I am unable to run the demo app what so ever. 

Here are my machine specs, please let me know if you need versions for anything else. 

go version go1.14.2 windows/amd64
windows 10 pro 64bit.

**Comment by andydotxyz** [comment] 2020-04-13 21:59
From the output it looks like you have mingW in 32 bit mode but your gcc and go are 64bit.

**Comment by ryangurn** [comment] 2020-04-13 23:00
it seems to still be happening after going to 64 bit mode, any other ideas...

`PS C:\Users\Ryan Gurnick\Documents\Go\src\project-x> go get fyne.io/fyne/cmd/fyne_demo/
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw\c_glfw_windows.go:6:0:
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function 'createMonitor':
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:68:5: warning: implicit declaration of function 'wcscpy'; did you mean 'stpcpy'? [-Wimplicit-function-declaration]
     wcscpy(monitor->win32.adapterName, adapter->DeviceName);
     ^~~~~~
     stpcpy
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function '_glfwPlatformIsSameMonitor':
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:228:9: warning: implicit declaration of function 'wcslen'; did you mean 'scalbn'? [-Wimplicit-function-declaration]
     if (wcslen(first->win32.displayName))
         ^~~~~~
         scalbn
Documents\Go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:229:16: warning: implicit declaration of function 'wcscmp'; did you mean 'wctomb'? [-Wimplicit-function-declaration]
         return wcscmp(first->win32.displayName, second->win32.displayName) == 0;
                ^~~~~~
                wctomb
# fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-cygwin/9.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/9.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

PS C:\Users\Ryan Gurnick\Documents\Go\src\project-x>`

**Comment by andydotxyz** [comment] 2020-04-14 06:27
It looks like 32 but is still being preferred - other projects stumble upon similar if you install 32bit by mistake https://github.com/faiface/pixel/issues/112

**Comment by bapi23** [comment] 2021-04-09 05:36
I have a solution for you guys:
- use TDD-GCC-64
- and set flags before build - for example in power shell it looks like:
` $Env:CGO_CFLAGS = "-g -O2 -DNDEBUG"`

**Comment by andydotxyz** [comment] 2021-04-09 09:06
Thanks @bapi23 I think that the TDD-GCC-64 is the key part (a 64bit compiler), those CGO_FLAGS are just a nice extra.

**Comment by bapi23** [comment] 2021-04-09 09:17
@andydotxyz I was not able to build without these flags

**Comment by andydotxyz** [comment] 2021-04-09 09:18
What was the error without them?

**Comment by bapi23** [comment] 2021-04-09 14:48
The issue was:
"undefined references to `__assert_func' follow..."

**Comment by andydotxyz** [comment] 2021-05-26 08:27
@jankeso is that computer a laptop, and does it have two different graphics chips? (one low power and one that supports OpenGL?)

**Comment by andydotxyz** [comment] 2021-05-26 13:14
Maybe you are hitting this bug in the drivers? https://msfn.org/board/topic/174272-intel-g41etc-video-chipsets-no-opengl-support-fix/

**Comment by jankeso** [comment] 2021-05-27 10:06
It seems to be Windows 10 related, I'm running Win7 with latest drivers.
