### ISSUE TITLE
Web View Widget is necessary for modern app

### ISSUE THREAD

**Issue by sorainnosia** [fyne-io/fyne#1356] opened 2020-10-04 03:41 UTC
### Is your feature request related to a problem? Please describe:
Modern app now mostly have some sort of web interaction and web view is not necessary means writing app purely in web.

For example, the app wanted user to login to a website and get the cookies then use http package to post information. Example is forum app which show list of threads written in Fyne, capable to do posting via Entry widget but requires cookies to post into the forum website. Such cookies are normally gotten from Web widget

### Is it possible to construct a solution with the existing API?
Existing API needs to bridge between native android/ios webview/windows webview and Fyne framework without having to rewrite entire webview component

### Describe the solution you'd like to see:
However I understand the difficulty of implementing web widget, so I suggest Fyne team to include a new activity when packaging as android app, maybe WebViewActivity class that includes an android native WebView and native rendering instead of Fyne rendering. Triggering the activity via a Fyne button and replace whole screen with that native webview then support listening of page changes event and when condition is met then redirect back to Fyne Main activity bringing its html content and html headers such as cookies.

This is implemented in Flutter which also similar to Fyne render directly to graphics, and Fllutter uses above method to bridge the gap of having no webview component.

**Comment by andydotxyz** [comment] 2020-10-04 08:19
Looks like this is a duplicate of #116. 
The login use-case is a good one but most authentication providers have a non-web solution to this problem.

For all the reasons in the original thread we don’t really want to add a complete embedded web UI. That said we could consider a library or component that makes it easier to handle logins etc where the common approach is to throw up a web view.

**Comment by sorainnosia** [comment] 2020-10-07 05:05
When fyne implement Web view and wasm together, it will draw people who loves wasm to compile into native fyne for the particular os because they looks and behave the same

Currently fyne approach is to make a tree with branches where it stops at bottom. Such as for android, ios, windows, Linux, mac. Then stop there. But people is fighting to unify and standardise those OS UI which gives birth to Html. 

If those bottoms can be link up to the top it form a circle.

A successful library is an library that can load itself from its own component which form a circle.

Such as a program can call itself which makes an infinite loop. In this way the app is the start and the end, alpha and omega. Fyne can load Web view which load its app as wasm which can load a browser that load a fyne wasm.

This will turn out to be a breakthrough in UI programming.

**Comment by andydotxyz** [comment] 2020-10-07 11:08
We arre working on WASM - displaying inside a browser is a driver that we can support, but we are very hesitant of embedding HTML content inside native applications. Often this leads to terrible UX - screens that look different from each other in the same application etc. Formatted text will be supported in the future, probably with Markdown instead of HTML.

We are fighting for a unified development method and look for applications across all platforms - but we want to do it using fast, easy to develop and maintain tools, which HTML/JS is not really best in class.

I'm sorry but I don't really undertstand what you mean about forming a circle through HTML. I also don't really know what a library that can load itself means. If an app loaded a browser that loaded a WASM fyne then you would have *very bad* performance. Why is this a desirable use-case?

**Comment by andydotxyz** [comment] 2020-11-17 19:10
Closing as duplicate of #116

**Closed by andydotxyz** 2020-11-17 19:10 UTC
Labels: duplicate
