### ISSUE TITLE
Bumping to glfw 3.3 (introduce more freedom to window object)

### ISSUE THREAD

**Issue by mortzdk** [fyne-io/fyne#1041] opened 2020-05-27 17:37 UTC
The current release uses glfw 3.2 but glfw 3.3 has been released for golang: https://github.com/go-gl/glfw/tree/master/v3.3/glfw.

This version introduce a lot of new stuff, including being able to define attributes on the window after creation: [glfwSetWindowAttrib](https://www.glfw.org/docs/3.3/group__window.html#gace2afda29b4116ec012e410a6819033e)

This will be useful as I want to create a Fyne application that is rendered on top of other applications, and I do not see how I'm able to do that in the current state of this project, since I'm not able to add window Hints or set attributes on the window.

**Comment by andydotxyz** [comment] 2020-05-27 18:47
This change has been under test for a good while in our “develop” branch and should be released next week in 1.3

**Comment by andydotxyz** [comment] 2020-05-27 18:48
Closing as duplicate of #183

**Closed by andydotxyz** 2020-05-27 18:48 UTC
