### ISSUE TITLE
Backspace in text widgets deletes 2 characters

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#2862] opened 2022-03-21 11:31 UTC
### Describe the bug:

On Android, backspace deletes two characters.  On the Android emulator, the cursor also sometimes jumps back (over) a character before deleting the prior character.

I see this with all Text widgets, whether they're in a `Form` or just `Entry` widgets added to a container. I have *not* seen this on Linux, only on an Android phone and on the Android emulator.

I've observed this bug for a couple months, across both Go and Fyne versions. 

### To Reproduce:

1. Create a simple app with a form with text fields
2. Build & run the app on Android; the bug shows on the emulator as well, no device needed.
3. Enter text into the text fields
4. Press the backspace button

Two characters are deleted for every backspace event. On the emulator, other behavior may be seen, with the cursor jumping back over characters.

### Device (please complete the following information):

 - **OS:** Developed on Linux 5.16.14-arch1-1. Bug shows up on Samsung Android 12, and the Android emulator with android-32 ('system-images;android-32;google_apis;x86_64)
 - **Go version:** 1.17 and 1.18
 - **Fyne version:** v2.1.2 through v2.1.4

**Comment by andydotxyz** [comment] 2022-03-30 22:21
I think this is a duplicate of #277.
Please make sure you are using the latest version of the `fyne` command to match the library version (check with "fyne env").

Please feed back more info on the original ticket. Specifically the type of keyboard you are using, as they are all different!

**Closed by andydotxyz** 2022-03-30 22:21 UTC
Labels: unverified

**Comment by xxxserxxx** [comment] 2022-03-31 14:01
Hi -- #277 is about gradients?

**Comment by andydotxyz** [comment] 2022-03-31 16:20
> Hi -- #277 is about gradients?

Sorry typo - fixed, it was #2774.

Ah, it is a bluetooth keyboard? Yes I see this could be an issue - I don't think this has been tested before.
(hardware keyboards on mobile and soft-keyboards on desktop are areas we don't fully support yet due to lack of testing mostly).

**Comment by xxxserxxx** [comment] 2022-03-31 18:38
No, sorry, not just on a bluetooth keyboard. It behaves like this:

1. On a Pixel 5 (phone)
2. On a Samsung Galaxy Z Flip (phone)
3. On a Pixel C with BT keyboard (tablet)
4. *Also* on Android SDK emulator with android-32 (VM)

I'll check the other ticket, thanks.
