### ISSUE TITLE
Compile warnings on Ubuntu 18.04

### ISSUE THREAD

**Issue by aluedtke7** [fyne-io/fyne#620] opened 2020-01-17 08:30 UTC
Hi,

when I run my own fyne program (**go run myprog.go**) or when I execute **go get fyne.io/fyne/cmd/fyne_demo**, I get always warnings from the c compiler. Even though, the program works as expected but it's irritating for a go compilation.

Steps to reproduce the behaviour:
**go get fyne.io/fyne/cmd/fyne_demo**

The result is:
```
$ go get fyne.io/fyne/cmd/fyne_demo
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:24:0:
go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/internal.h:169,
                 from go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_init.c:28,
                 from go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

 - OS: Linux Ubuntu 18.04
 - Go version: 1.13.4
 - Fyne version: 1.2.1
 - GCC version: Ubuntu 7.4.0-1ubuntu1~18.04.1

**Comment by andydotxyz** [comment] 2020-01-17 08:33
Duplicate of #182 - this is fixed on develop branch and will be released as 1.3 later this year.

**Closed by andydotxyz** 2020-01-17 08:33 UTC
