### ISSUE TITLE
MacOS Code Sign Missing

### ISSUE THREAD

**Issue by Stoyvo** [fyne-io/fyne#1547] opened 2020-11-15 12:06 UTC
### Describe the bug:
Using `fyne release`, and providing all parameters to sign an app on MacOS, no codesign activity happens. Please review:
https://github.com/fyne-io/fyne/blob/master/cmd/fyne/commands/release.go#L69

There is no codesign for darwin.

### To Reproduce:
Steps to reproduce the behaviour:
1. fyne package -release -os darwin -appID "ABCD1234.com.example.myapp" -appVersion "1.2.3" -appBuild 2020111401 -certificate "developerID_application.cer" -profile "MyProfile" -icon "assets/icon.png"
2. Verify code sign: `codesign -dv --verbose=4 myapp.app`

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.12
 - Go version: 1.15
 - Fyne version: 1.14

**Comment by Stoyvo** [comment] 2020-11-15 12:07
Workaround is to manually code-sign:
`codesign --force --sign "Developer ID Application: <my name>" myapp.app`

**Comment by andydotxyz** [comment] 2020-11-15 12:33
I think this is a duplicate of the issue stating that we have not completed the macOS packaging (if you mean "fyne release" not "fyne package -release").
Dupe of #1443

**Closed by andydotxyz** 2020-11-15 12:33 UTC
