### ISSUE TITLE
running gcc failed: exit status 1

### ISSUE THREAD

**Issue by zhanghuizong** [fyne-io/fyne#2396] opened 2021-08-23 10:30 UTC
### Describe the bug:
D:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

### version
1. 'go version go1.15.2 windows/amd64
2. window10

**Comment by andydotxyz** [comment] 2021-08-23 11:56
Did you follow the suggested setup steps at https://developer.fyne.io/started/?
Which terminal / C compiler combination are you using?

**Comment by zhanghuizong** [comment] 2021-08-23 12:02
> 您是否按照[https://developer.fyne.io/started/ 上](https://developer.fyne.io/started/)的建议设置步骤操作？
> 您使用的是哪种终端/C 编译器组合？

yes

I installed cygwin64 in windows

## gcc
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/11/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-11.2.0/configure --srcdir=/mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-11.2.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --with-gcc-major-version-only --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --disable-bootstrap --enable-languages=c,c++,fortran,lto,objc,obj-c++,jit --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (GCC)
```

**Comment by andydotxyz** [comment] 2021-08-23 12:10
I don't think that cygwin installs the mingw64 libraries automatically, can you check that they have been installed as well?
(see the illustration below the options that show how you would do that if it was MSYS2 - you will need to adapt accordingly for cygwin)

**Comment by zhanghuizong** [comment] 2021-08-23 14:16
> I don't think that cygwin installs the mingw64 libraries automatically, can you check that they have been installed as well?
> (see the illustration below the options that show how you would do that if it was MSYS2 - you will need to adapt accordingly for cygwin)


Hi,
I have installed msys2 now. Recompile or report an error

```
# tools
D:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ZHANGH~1\AppData\Local\Temp\go-link-033036851\000002.o: in function `glfwSetCursor':
C:\Users\zhanghuizong\.go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw/src/input.c:820: undefined reference to `__assert_func'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ZHANGH~1\AppData\Local\Temp\go-link-033036851\000002.o: in function `glfwSwapBuffers':
C:\Users\zhanghuizong\.go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw/src/context.c:646: undefined reference to `__assert_func'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ZHANGH~1\AppData\Local\Temp\go-link-033036851\000002.o: in function `glfwExtensionSupported':
C:\Users\zhanghuizong\.go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw/src/context.c:680: undefined reference to `__assert_func'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ZHANGH~1\AppData\Local\Temp\go-link-033036851\000002.o: in function `glfwGetProcAddress':
C:\Users\zhanghuizong\.go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw/src/context.c:746: undefined reference to `__assert_func'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ZHANGH~1\AppData\Local\Temp\go-link-033036851\000002.o: in function `glfwGetInputMode':
C:\Users\zhanghuizong\.go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw/src/input.c:476: undefined reference to `__assert_func'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ZHANGH~1\AppData\Local\Temp\go-link-033036851\000002.o:C:\Users\zhanghuizong\.go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw/src/input.c:501: more undefined references to `__assert_func' follow
collect2.exe: error: ld returned 1 exit status
```
# version

## gcc

```
C:\Users\zhanghuizong>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev5, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.0 (Rev5, Built by MSYS2 project)
```

**Comment by andydotxyz** [comment] 2021-08-23 15:06
This is looking like a duplicate of #861 - somehow there is still a mismatch with 32 and 64bit.
Perhaps it is the Go cache from when you were building before? Try resetting all the caches and trying again?

**Comment by zhanghuizong** [comment] 2021-08-24 02:15
> 这看起来像是#861的副本- 不知何故，32 位和 64 位仍然不匹配。
> 也许这是您之前构建时的 Go 缓存？尝试重置所有缓存并重试？

Thank you. 

Problem Solved.

**Closed** 2021-08-24 08:14 UTC
Labels: question
