### ISSUE TITLE
package name flag not work

### ISSUE THREAD

**Issue by Virgil-N** [fyne-io/fyne#2507] opened 2021-09-27 11:43 UTC
Run command: `fyne package -os windows -name client -icon ./resources/images/icon/appIcon.jpg`.
At last, the name of executable file is not "client.exe", it's my project dir name.

env:
window 10
go 1.17
fyne 2.1.0

**Comment by Jacalz** [comment] 2021-09-27 12:17
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

**Comment by andydotxyz** [comment] 2021-09-27 13:03
Looks like a duplicate of #2395 ?

**Comment by Virgil-N** [comment] 2021-09-27 14:07
> Looks like a duplicate of #2395 ?

yep.

**Comment by andydotxyz** [comment] 2021-09-27 14:19
OK, thanks. Closing as dupe, should get this resolved soon

**Closed by andydotxyz** 2021-09-27 14:19 UTC
Labels: duplicate
