### ISSUE TITLE
[Feature Request, but actually also a question or suggestion at the same time] Cross-platform introspection and cross-language use

### ISSUE THREAD

**Issue by rubyFeedback** [fyne-io/fyne#2413] opened 2021-08-29 23:22 UTC
I found fyne recently after having used libui and ruby-libui (bindings, via FFI) for some time.

libui is nice, neat, small - it works on windows by default. All great. There is one problem
though in that andlabs does not have a whole lot of time; most work came from 2016 to
2018 and since then things became less active. Which is fine - time is a finite resource.

fyne on the other hand seems to have quite some momentum, but of course the use case(s)
are different. But it is cross-platform so that is one shared goal.

Are there plans or possibilities to see something like fyne be usable from other languages
too? A bit like gobject-introspection for GTK (but getting gtk to work on windows is soooo
annoying ... I failed to compile it on windows, for instance. Works on linux).

Please feel free to close this as it is probably just a lot of work and perhaps it is not a
good use case for fyne. If however had anyone has too much time, I think it would be
great, and might make fyne even more popular. (I guess that it is popular - you already
have ~86 contributors. Even excluding casuals that's quite a lot. Many other projects
never reach that number... and there are lots of screenshots so I assume fyne is in a
good, "healthy" state.)

**Comment by MatejMagat305** [comment] 2021-08-30 09:16
I'm not developer of this but you should try msys2 on windows, and I think this library will only for golang, but if you realy want golang can be like shared library...

**Comment by Jacalz** [comment] 2021-08-30 10:52
While not directly a duplicate of this issue, I think some of the answers to these questions can be seen in the following thread: https://github.com/fyne-io/fyne/issues/777

**Comment by andydotxyz** [comment] 2021-08-30 10:57
Fyne was created using Go to benefit from the advantages of modern programming languages.
Binding Fyne back to C or out to interpreted languages removes those benefits.
Therefore (as commented in #777) we have decided not to support binding in the main project.

**Closed by andydotxyz** 2021-08-30 10:57 UTC

**Comment by Jacalz** [comment] 2021-08-30 10:58
I think it’s theoretically possible to export the Go code as a shared library that can be used from any language that can link to C-style shared libraries. It is not something that I think anyone has tried because it really doesn’t make much sense and would require adding comments to export all the functions which would become a burden over time. https://github.com/vladimirvivien/go-cshared-examples

With that being said, don’t do it. There’s really no point and there are no guarantees that it is going to work at all.
