### ISSUE TITLE
Suggestions of widget : listbox

### ISSUE THREAD

**Issue by Dynamith** [fyne-io/fyne#1131] opened 2020-06-25 13:20 UTC
There seems to be no listbox in widget, hope to add.

**Comment by Dynamith** [comment] 2020-06-25 13:43
Such as this ![image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAdcAAAC4CAYAAACxUab6AAAeJElEQVR4nO3dTWxc193f8e//3Es5saPYz9MHCSo8KVB5RgJYLQqh4GJUFNnIBikEcBYUEPRFXFhDC31gTuGoBQEvBWjBBBgKaGXSG3orFbCSp5qBxbW44JNqkRAErBkTRYs6LerEdBQnkc25p4t7h/PC4cydF2os6fcBBhJn7pxz7rn3njPn3vNiwS9+580M7z1mRp33vvF/I/ks/tz2P0r+4+zAd5rDGkS370cWYWaYGd6AyLd8fvC7rv7NOJ09kpY+7dGA30u+3bS5WRCH59KHUT9m5uO4fX0/LTqwTTfdPk/z/V7q398/ShbhsL72NV0cUc/tWrm2czbe1+b3mkV2MK9S543r/Ha3a8bMDpzb7fbz1nvMXJzHdvA79fMEup3/zfnn4rz449fYbkTtsSfw0f451pxPzjzeIKqBdwEW1eJ42o6v67Ar7WWOmbVdFwcTa8mOtB+nRl503sHDj1XUuk8uaAu7ni+Ng9h8vpmvpyXJm6ApTuKyKvJ+/4IP6mVXUxwO29+vxnvt6QefxBVvn5TNHpwZUVIOWHKl1eN1OMxHTedARIh1zI89mtPUyJMIR83FcUdm1PzB7Zqu8EaafVxrBBh7eHzbdvWyC+J9gPg8cXhCjAhPRFNZ5zwBjTRhEc437d9+XnkiPHi3H3aAp4bHeyPE41w99XEY9fMu8p7AN58vEVYLcJ/XsL+Ad43rpPmQxelOvmMRFv79Zx2vXn9YadCUIfWTo+UC6VAADSJqCaK10HS+7cIdQSHdPc1Rim3a09xPnG7/wooYrjKrX0BxIZGuUj3sh9Vh6Tjs/U6FXVzYN+VfcrIb4O1gZZiuEmhPS7+Val3rj67e29Xj9B0r2sP4tkq7/r0OdWCHqHtXsM1hemu6wOvxJ/HuX5tR+7lxsPII8ezhkzQ6cEaNGuGfwP9+Dx6Dp4YR7J8/3nvMJYVeU7gO8MnF0emHfLu4cmycM4287nycms/jtOo/zlvjbWtQ+NZzsJ6vh52XjUo2SZMzLElz0FSZ7W/TXLHU/8bXq8b9iqVe0HuLc8DM9k8el9TZ3seJDYEJi/PfOyOKGvl4rPmHnG/8SKnvjsfhjZaKM0wO5WNgzzfyLqjnRXMGuLjyqp9H8TYR3tt+pW20VkJG6/ELMAIDl/woqSWZHfgIl5QntSRNobckl1xckSbHyDWVpXvE+RbWw6ZxTOoVav18DL3HmWFBHOrXtSjeF+cx7/AWYXsO/3mN4C/wAvEPy/p50mjsRFjgCPcz24xLd/4TIiIi0r+tf7mM88aEGaER38PwSW3+/vvvjzNtMgKPHj3i5z//Oe+88w7Hjx8fd3JkCJ9++iknTpwYdzJEnirjuG4uX75M6IwasAc4b/HtuVHcypXxe/ToEfPz85w4cYJ33nmHR48ejTtJIiLPBe88ocX/7j9k6ed5hXwz1SvWn/zkJ+TzeX7605+qghUReULsrx2EERPmcPUekpEd3oFJvvmaK9Yf/ehHAJw6dUoVrIjIEzLxgmPie8ewvybu0BR37VbL9WmXz+f54Q9/2PJevYL97W9/q+evIiJHKO6EH+G+ZYTxMJAUQxmqVcqVCmSnmc40v12mUsmSnc6QOfzbcsSOHz9+oGKtO3Xq1BNOjTwZVcrlyiGfdbgmq1XKFXStihyReHhT3H8pjJ+1pujMVFliZmYVckUq9xf2L87K0gwzq3lKfkUXrMiTVL3LtZkCGx0/7HBNVpaYmUHXqsgRsSgel52Mvk0GiqcYqA7ARoGl8pGmT0TSyCxw33u89/hSHshRrCR/+xWm27fPTpLPT5IdQ1JFngc1F88ZEboAl8yRgfXRoWn1jmpXkadOZoGVlQW1WkWOiMPH06hGyVAcn/z6TSOfz8PqNZar3berVsuUy2XKB7arUk3+LZfLVJPPq+Uy5WqHQA8NR0T61ekS0zUpMhreGzUPNWpdJhA+zBtXKeY2KBx2b7i6zPw5I5udYWZmhpmsYefmqW9dns+SnZ9n3rLMzMyQzc4zP29kZ2aYyWY5t19rl5k/Z1h2hmvXDoYjIn0qz5PNHryGdE2KjE4QxbMrJ5Wrp9OKBp1luHAxB6t3Ol5U5aUCqxt5SvVnQZUS+Y1VrjU3dVe3mKzUnxOtsjVZwfsKxVx9gyrL52ZYpUjFe+7fb4QzM69LWWTkdE2KDC3EEzgwgrhDExF9LSySWXiXPG0VZmJ6pbUzRbXykK32jfLvsrD/4CfHxQttT4Gqd7m1AbkzUCknt6AqQA7YeojuRomMmK5JkaEZAc47HNZYFac/01wt5sgWlriTb/uoWmZ56Rq3VjfiIQK5HLkOIXRV2Y6/u3qLay01c44c21RAnTJEniRdkyI9ee+pWRQvcxcvjtf/epiZCxfJFQqsrja/W2Y+O8Nqrkip8gHTmQzx7aQst/oJPDtJDjhTus/KgfEEIvLE6ZoU6am+rq4DnP828IKLX/3ILPDugVZrfAs4/+5CUrGyfzupv7BPcYaDQ37K84adW9YtKJEnTdekSE/feiF+HXsBQleLV1EfxPTVIrnVphli6hfgtXPw8CJs32J1Nf60v1vD06yU8qzOzHBuK8/Fi5Ns37rF6gbkSxqnJ/Lk6ZoU6aWW1KXmwHnv49mZes3QlJ0kn88z2Ty9S+YC7xbzTbO+TLNSKVE8A1u3brHFRUqVCqVinjNUqALZyTz5eiDZSfL5i9Rnvj11Mc/F+h/TK/hKiYtntrh16xZbZ+KwdEtKpIO2a+nwbQ7O0KRrUmREvMeAsAYW/vJzX69Y5/7bf+T9998fb+JEZN+nn37KiRMnxp0MkafKOK6by5cv89ml/4I3MIMw9ZzCIiIicqiaj8CDc0bovEs99aGIiIh0ZknFit9fck5ERESGcQzbH9ka+lq8RI6IiIgMzqJ4rGtkEFqkilVERGRoSW9h5yGMLG7DqvUq8s1z7OV/PO4kiDx1xnXdeMDwODNCC+I3VbeKiIgMzh0zzOLGakgQT3uou8MiIiJDCA1vHvOeEGeYGapbRUREBhdYfGMYSxZL98nC5ulUKZer+xN1V6tlyt1m7a6WWZ7XxN4iR6Zapbw8z/z8PPPLZaodL7Yq1fIy8/PzLDddv0cSTrpEpw+nWmZ5fp7lgddk7zPNw5RZafIwVT6niqyxX8vlnsd0uWtBnTLG8jwdlvHutOFzWe6beYIQghAIf/mFr7/efPNN31Ol6HO5oq/Ef/hiDp8vHbqxL+bwkPeHbiIih/p/f4y6b1DK+1zcj8LncjkPeMj5YqVlI5/PtW3TftGOKpxU+gunlMezX+YcbVxDlVlp8jBVPqfcr+S7+XwuCbM1nEqxEX4uyQNyQ5TFpbyHbuX9fsxjL/d7XjdH4M033/Q/+dVj/69/9Rf/b/77Y0/w4ec+vLPrwzu76SrXUr7pRC/5fJcTo3FwVbmKDKJ7IZEUsPlSU8XTeG//nXxyDdY3qhR9rqWQHFU46fQVTuoCfQRx+WHKrDR5mC6fU8V24AdHWzjJfuZaa9u4Eh4gMytNPwp6ff2bUO6Pq3K99A9f+bl/eOz/7a8ee+e8wyKj93jXKtVqlfLDLThzCqrVptsZHW61VJe5VNggn29f9FVERqL6EHJ5SivTTUu+TfNGHth6mFyTZe6sQq54len6RslazKvXktt2owonlX7CKTM/swr50oAr7/SZ5mHKrDR5mCqf0+3XQ/IUP1g4NJzq3VtskOfdhabFAOtrcPcVF1CeJzuzxcVKiZ4587yX+1bDW0QYRfGSc94bvseiruX5LNlslpnCBqzOkM1myWZnWGWDQjbLpZYb8VWWLxXYyJdYeeNo90XkuZVZYOX+Cq31TpWHW8CZU3HBW31I/GfriqvZyRxsbFMZZThp9BFOeX6GVeLKaCB9pXnIMitNHqbZpuWjMuVyp2ep0yysrLDQ8oXWcCrbG5A7uLwg0Pl4HRoXkL1KqXK/Lb5OVO47PA7DnCeM34p6fml6pULlKty9lGX7YoWrF4DKEtlrk5Q+uEA208j56vIlCht5SvenoXzniHZDRA4oL1HYgPy7SRFe2WaDHBfbStnMqTNHEE61a+ecTCaTPj3leWZWAVaZsdX4vVye0gcrSSt0hHHRq8xKEVcn7XnY5zbVu9eYKUCxMt21YquWl1m6Vmj5IZKdzMFqXIk2lcxxBZx/g/bYusaVyRzYvmM6VO5jPgQiLAgJ08/MlCGTSc6wUxkyGaje3YIzbzDdfHKV58kWNsiX7qc6ICIyKlWWr3W6jXqGUz1bHcOHU57PJhViZ/mSZyVVepL4yVEsfcDCdAaqZeYvzTCThZJfgZHFRc8yK9V+HfjiYXmYfpvMwgdULsBhdXc97ZdmVtkguf1d/+6Fi+QKBWbm36CyMk2GKuX57KEVeaq4ulG5D8BEEA/FicwT9jd5RIXtjRyTTb8Ec81/JM9IcsXKgM9IRGRQceGZtBzGEM70isev9Ao8RUDVu9zagFwxqVgBMtOsfFBkK1vgTnmFlVHFlaLMSrVf7aGmyMPe22R6V3bTK9z3K1TLy1yayXKOCvcXMpBZ4IPSNpdmZsg2/zDIFbnaMboUcR1K5X5dZPG8wgGGMzPMfPxOF+V5w6z+jDWeeCJb2GCjkMXMOLdcjZ+R5PK8ewGq1bgDVKPP0zBj4kSkm+ryOeK+P+3P9AC2eJjy4htVON31CKd+O/dCW2mfOcUZYKuvRHSP6yjKrO55mH6bfmSm485KG7fu7qc5M73Cfe/xlQqVYg6A/LsLB5/tDknlfoNz8RjXwHkIfrHrw19+4Sd+0X2ca6VS8qVi3pPL+2Kp5Eulos/n8LliyZdKJV+q1Mc2dXkN2p9e5DmVakhBMlwl13FMXDxEo/2zjmNHRxVO98T2DqdS9LmOQ/w6f3fwuI6gzOqah31s002l5Iv54oFhLvEQmE7DXwYb7nNQHE5rMN/Mcn9cQ3H+7tdf+b/79Vf+3//mKx9Xrnd2e1au3vv4pGgZs5Vi8HMpr3GuIgNKO4lErtckDC3XYIdKZ1ThpNA7nM6VQVx59DfhwkBpHrTMSpGHqbbpHVGHfUgquQ7hDpJv3eJNlfQxl/vjqlwLv/nKL/z6sS/85isfmk+/3Fz14RbQ3Me6344SIjI68bOuDXLkucP8fHMPzUmursS3AKevFsmtFpg5t0X+zBm2VlfZIE9pv1voqMJJp3c401wt5lgtzGBbeYoX34DtaxRWN8jlSymGhPQT16ikycN0+VxXXT5HtgDFA8Ng4vzJFrLYrTz5M7C1tcrGRo7iB+03mcssFTbIFSvdexwfGpf0Y4J4ofSgPrdwemcovpF0YKrCZP6QcVTNspPk02wnIv2pwmQ+Tz7fY1hNZoH7lRLFM7C1tQX5EhXf9KxvVOGklSKczMJ9KpUSxTNb3Lp1jVtbZyiWKtzvt8fMIGkepMxKk4dp87nu1EXy+Yuc6vBRc/5sbW1x5mKJSoeKsbp8ja1csXUyiT7jasgymc+3dGg9fNPns9x3DiYCIzCwiV98sd+T6dLfv8P7778/zrSJSJPPvvT8zUtas0qkH+O4bi5fvsz33vnPQHw3uM+Wq4iIiHTiXLxYOnjCXtMeioiISG+BeeqLo4fOxwNfRUREZHCWTCABEHofTzQsIiIiQ7J4rv79uYXrrdcvvvhiXEkSkTYTgC5Jkf5MAPDyE4/3BTO8xX2EQ+/j/1j32Q9FRESki9BB/aGr897HFWuk2lVERGRQjfmYjJDIE+FTz9IkIiIindXr0tCieIUbBmm47qxz80aV14tXODna9IlIWjs7rH90g7sfA6cv8Pbr5zl54ILcYWf9I27c/ZjTF97m9fMnD16zowonXaLTh7Ozzs0bd+FCkSvnjziu/fgGLNfS5GGqfO433sPSPKLj1TPNO+ysf8In7d979Tznn6PKwYiIuwhHuHhh10GG4+xw861ZFtc+PpihIvJkrBd47exZZhfX2N7eZm1xlrNnX+PmTstGFF47y9nZRba3t1mcPcvZwvrRhJMu0X2Fs35jlsXt07w+UMXab5qHKNfS5GGqfO7XYWke0fFKk+adj3hrdpbZttfSR0Pt2FPHzHDmk3+PGS6MX/3YufkWi5tHlEIRSWGdwuwam3O3ebC7y71799jdvc0cmyzeaBSi64VZ1jbnuP0g2ebBdabWZmmUs6MKJ2Wq+wlnvcDsGsxdHezuWL9pHrxcS5OH6fK5X4eleTTHK2WaP/mYTea4vbvLbtPr3pXnqNkKvGSelwLjRQfOe8N7T73XcCo7N3lrcZO5ubmjS6WIdLdThak5bhfPN1U857kwB2xXidsM69xdg6nrbzduz528wtU5WFu6GW8zqnBS6SecuGBn7jbFAVutfaV5mHItTR6myud+4z0szSM6XinTvH53DeYuMNBheobUzKh5j3f7q+I40i+Qs8PNtxbZnLtN8cJRJVFEejp5heK9YluBtkN1G5jMxIXhTpX4z9YWxKunp2AzuY04qnDS6COc9cIsa8QF+0D6SvOQ5VqaPEyzTctH66yvr3epCLukud/jdVhcqdIc/z11GtbX43DWn6+7wQ2vOPxxB2aE/X43vgUxx+1752H97lEkT0QGtX6DxU2Yu5oUh598zCZT/PjV1s1OZiaPIJwddroUqidPnkyfnuR2MKwx+8pa/N7UHLffKyYtsRHGRa9yLUVcnbTnYZ/b7Hy0xOwiXH9wnk53V7umuc/j3iuu7mn+hI83YXNzllmmmJraZHMTmLrOg3vPWWdX73AO+E4UD8VJbb3A2cVN5m7fe+6b/yLfPDvcXOp0G3WSTF8l3GDhrBfOJhViZ3O3dymmSk8SP1Ncv/0eV86fhJ11Cm/NMnsWbu8WYWRx0bNcS7VfB754WB6m3+bklfd48DqdexKnKovTH/eucfVK806V7akprr93r1Ex79zktbOLvHXz9efuuau3CPMQWpR2jGv8/GPq+oMBn3+IyFFaL5xttGTGEM754i67xV6Bpwho5yM+3ISp60nFCnDyPMX3rrN9dpG760WKo4orRbmWar/aQ02Rh723OXlIZXcUZfFhcbXF3CnNJ69w796VtuCucHVukdkPP2LnyvPVevWRUTNw3kMURURR1PUL64VZ1qbmuPo67OzsxK/6h83/F5Enbufma3Gv2tvtz8cAtqmmvEBHFU53PcKp39J8va1IPplhEtjuKxHd4zqKcq17HqbfZvg0j+p4JUH3mea+n8c/A4woHobjwRF5iIhfXVS3gc01Zs+e5Wz9NbsGJO8NNN5NRIaW3CLs2JI5f4E5Nvmwbbzh+t01mDpNyyO5UYXTTZpwXj3NVNrwhoprZ/TlWrc87GebQ6VM86iOV4o076zfpNBhoO4nH28OFtdTzohw5nGuZtRf3Vy51zp+aXd3l93bc1Af26R7xSJP3nqB12bXmJq7fcizrXjYxObijaa7pMkwjR+/3rhdN6pwekoRzskMkx3Gfu7cXGKtU4t24LhOjrZc65mHKbfpKm2aR3W8UqS5+iFrLfEAOzdZWqNzL+hnmMP2X6F3mlNY5OmUDPBnijnuUig09xg9zdvJVHjn377O1Nois69tMzc5yfbaWjzgf7+gHFU46fQO5zxvX59ibXGWV7bnuP7jC/DxEotrm0zN3e7dm7WvuEYlTR6my+e6nZuvcXYRrj+419c+1/Wz74fHlSLNV64y9+Ess69sMzc3CWyzvbYZx/WcNbrMrLGea/+DcZq8epq5OZ67Zr/IN8IOnJ6bo+eUByevcO9Bhps3lvhwexvmbvOgeVKAUYWTVopwTl65x4PX1/noxhIffrgNTDZ6Do84rgMGKdfS5GHafK7L/Ji5Ocik2bZTmvvZ98PiSpXm8xTvPeDCzRssfbgNwOT127x3ZYBz4ykXmKc+H5NN/Nc/+Hpv4X9X/g/87Gc/G2PSREREhvfyy092sfTLly/zr372HhC3YEPn0s7MJCIiIoepT9oPntDrkauIiMjQmueMULNVRERkRPYXS+9r+kMRERHpyCLDzPAYofO0LDf3pB8Ci8jhPvvS8zcv6dmNSD8++3K8jUYHhPV6ta/1XEVERKSFmSeiflsYT2Rg6jUsIiIysMAcQfL/0MziP9RwFRERGdiE99RH4AwzP5OIiIgkQgfmAfOEkYFTq1VERGQoziB+5GpxyzVSZ0QREZGhBPvPV138zDX+v2pYERGRQRk0pj80M7wl94lFRERkIM3TH+7PLaw5hkVERAZnPtr/f6gWq4iIyCg4gqRSDQG8RV03FxERke7MDLxhHsIIj2lxHBERkaE4D1iEt2SGJs0rLCIiMhxzHks6MDmieOV0PXsVEREZXHM9Gk9/qDVdRUREhuY8uPoMTbotLCIiMhwX1TAm8EQ4iyDAtQx+FRERkf4cwzFh8YquIXi89wSaRUJERGRgX1s8+sYswlkyJgfdGhYRERlY6A0jAhyhT7o3qWoVEREZToBhLiJkQuNcRUREhhU4AA8eQiLD0PNWERGRYTjfWBknVKtVRERkeJEBxBMzhc01rYiIiAxmvz71xDP2e++THk4iIiIyiNbF0pPbwl7jXEVERIZmZoT1Gfz15FVERGRwlqzeat4TatJ+ERGR4Xnvccnom9Ai3Q4WEREZlnnwyX3g0Du1XEVERIbl8CR3hgktUMtVRERkWBMG9b7BoQWOyDQMR0REZBhBy1Ac5zGs5U0RERHpT9yZKW6shri4Uq352hiTJCIi8rSLK1ZnFg/FcUBQH6AjIiIifXPNt4UtWRVHT11FRESG572Ppz+sWU2T94uIiAwpHt1qOHNeFauIiMiQgmR2JjMjrA/DcV7PXEVERAZleMzADEIjABoDX0VERKR/QTIUJ8ITjjsxIiIizwrzjhAj1PNWERGR4QUWT9xvBiEWobn7RUREhldvsIZGQKShOCIiIkOJJ5FIpj/01MAMNV5FRESGEWFmOA8h1hiXIyIiIoMJMOot1dCsPvmh2q4iIiKDMpqeuQJNa6eLiIjIIJrvAIdooXQREZGhBXgic8kzVxERERkBR+AjPBASqSOTiIjIsFxyJ9hIWq4WaWUcERGRYbV0aCJw6issIiIyBNc+FEdERESG0zyVsDo0iYiIjIA5j/dxDRtaFP/hUAtWRERkUObBkro0jP75i3A8ohYa/HLMKRMREXlKBU2N1NB/2xN8DVFNLVcREZFBNdeiofs0wr8IvKSZmkREREbBRf8owH4HfkItVxERkVEI3R9r2EsBwfa4kyIiIvL0MmuMxQmP/yGAV2rYS2q5ioiIDMo3VaPhP30lwr4I4Duao0lERGRQ1jyJxIndCH8MvFfLVUREZFDeGhVs+IOXQ6Iv9wj+DF+MN10iIiJPrbhidQCEX/1+Dztu1Fww1kSJiIg83dz+/8L/8Yqx9ziAr2v87RiTJCIi8nSLGkvO/Z/PPd5/Te2vJlS5ioiIDKh5lbnwf343xHvg86/5F+NLk4iIyDMj/PJPNZwD+76euYqIiAwqnkQifu7qXvg+fPuYMfHb2nhTJSIi8tSLgIjw9Mc1oowRHte66SIiIoNr6i38g382ge14wu+p5SoiIjIK4Q92PbVXwXYdj8adGhERkadWY+nW8FgILnS4KFLlKiIiMrCm28KPXvS4/x3hv6uJ+0VERAbX1HL97HFAdDyCKOC7Y0ySiIjIsyL81Dz+L47wRa/KVUREZGBNt4X9S4b9ICL6k+vyBREREUkrPPFX4COD4+NOioiIyLMh/CcOoi+N6H959RYWEREZgfBvf/01wZ6nFhq/GXdqREREngHh9495bAJcDVWuIiIiIxD+eQ+cc0Sh9d5aREREegp398A5aB78KiIiIoMLvzbDmccitVxFRERGwQUkFWtNLVcREZFRCI87h68BQTDutIiIiDwTwhd9DQLDVLmKiIiMRPhnAlwE1PbGnRYREZFnQvj7ryMsNCwIx50WERGRZ0L4BxfAV55AQ3FERERGIvyyFmHe4SJVriIiIqMQ1szhiQiclpwTEREZhXAviiAwIo1zFRERGQnnALe3R2BquYqIiIxC+KIBxwK8GX8ed2pERESeAeG3XISLwHzE7rhTIyIi8gwIXc2omRHokauIiMhIhJ9F4JyhJ64iIiKjEf4uckR7EQ7jO+NOjYiIyDMg/MNjz55zmKHKVUREZATCL/YivPeEGoojIiIyEuHvnVFzhvfGqXGnRkRE5BkQ/t8JtVhFRERGKdxzYJEfdzpERESeGc72IiDCTBWsiIjIKIS8EOJr8VAcERERGV5oexE4T4RariIiIqPgfAjeeyxQxyYREZFRCIM9Axfi99RyFRERGYUwiiLAQD2GRURERuL/A3fZnKPwegmLAAAAAElFTkSuQmCC)

**Comment by andydotxyz** [comment] 2020-06-25 13:49
Is this a duplicate of #157?

**Comment by Dynamith** [comment] 2020-06-25 14:17
It's a bit simplistic, but I want listbox with options etc. And it can be bound to variables.

**Comment by andydotxyz** [comment] 2020-06-25 14:18
That sounds like what we are planning for data binding and the list/table widgets in 2.0

**Comment by Dynamith** [comment] 2020-06-25 14:27
Good, I'm looking forward to it.

**Comment by andydotxyz** [comment] 2020-06-26 19:23
I think this duplicates either #156 or #157, either way it's in hand

**Closed by andydotxyz** 2020-06-26 19:23 UTC
