### ISSUE TITLE
Memory leak in unused cached images

### ISSUE THREAD

**Issue by lewisthoma5** [fyne-io/fyne#348] opened 2019-06-29 10:32 UTC
Just a video of me going through the fyne demo with task manager on the side , it seems to go well until the graphics tab as thats where memory usage makes massive spikes and is then never freed. 

https://youtu.be/b4Yh9dGj9e4?t=70

go1.12.4 windows/amd64

**Comment by andydotxyz** [comment] 2019-06-29 11:41
Thanks for the report. I think this is similar to #210 which is due to a raster cache growing. We are working on a smarter way to keep the cache pruning (currently it’s just on a timer) and the fix is due in 1.2.

We are not proposing a hotfix as this is a big change and does not affect many real life application scenarios.

**Comment by andydotxyz** [comment] 2019-11-20 11:56
This is still an issue in 1.2 - we did not yet work on a way to stop this from happening.
It is due to the fact that we cache rasterised graphics after they are sent to the graphics card.
We could turn that off but then things get slower in general.
Perhaps there are enough optimisations in place we don't need it any more?...

**Comment by Michael-F-Ellis** [comment] 2020-05-03 23:13
After a couple of hours, my application running on a Raspberry Pi shows the following heap report from pprof.

```
pi@pi2TEST1:/tmp $ go tool pprof heap.pprof
File: legacy
Build ID: 0d57f22e0fb4ca928a7814b61aa4eec26b494bd0
Type: inuse_space
Time: May 3, 2020 at 6:45pm (EDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20
Showing nodes accounting for 108.94MB, 99.09% of 109.94MB total
Dropped 11 nodes (cum <= 0.55MB)
Showing top 20 nodes out of 42
      flat  flat%   sum%        cum   cum%
   98.48MB 89.57% 89.57%    98.48MB 89.57%  image.NewAlpha
   10.46MB  9.52% 99.09%    10.46MB  9.52%  bytes.makeSlice
         0     0% 99.09%    10.46MB  9.52%  bytes.(*Buffer).Grow
         0     0% 99.09%    10.46MB  9.52%  bytes.(*Buffer).grow
         0     0% 99.09%    10.46MB  9.52%  fyne.io/fyne.LoadResourceFromPath
         0     0% 99.09%    98.48MB 89.57%  fyne.io/fyne/canvas.(*Text).MinSize
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver.WalkVisibleObjectTree
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver.walkObjectTree
         0     0% 99.09%    98.48MB 89.57%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).RenderedTextSize
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow.func1
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL
         0     0% 99.09%     0.86MB  0.78%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).SetContent
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).ensureMinSize
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).ensureMinSize.func1
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree.func2
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTrees
         0     0% 99.09%    97.62MB 88.79%  fyne.io/fyne/internal/driver/glfw.(*window).RunWithContext
(pprof)
```
The app has a about 20 screens, most of them having a few data items displayed with a 1 second update.  One of the screens (see attached screen shot) shows a PNG file created once per minute by an external app. 

The code that fetches the graphs looks like this:
```
// getGraph returns a canvas image of a graph
func getGraph(fpath string) (img *canvas.Image, err error) {
	graphResource, err := fyne.LoadResourceFromPath(fpath)
	if err != nil {
		err = fmt.Errorf("Failed to load graph: %v", err)
		return
	}
	img = canvas.NewImageFromResource(graphResource)
	img.SetMinSize(fyne.NewSize(800, 320)) // force fit to width and 1/4 height of Pi touchscreen
	return
}
```

The graph is loaded into a pre-existing container with this code:
```
func refreshGraph() (err error) {
	newgraph, err := getGraph(graphWidgets.graphFilePath)
	if err != nil {
		info(err.Error())
		return
	}
	graphWidgets.container.Objects[0] = newgraph
	info("refreshing graph ...")
	graphWidgets.container.Refresh()
	graphWidgets.graphBox.Refresh()
	return
}
```

The graphs are about 40Kb on disk. I'm not (intentionally) keeping the old ones around in memory and -- to be honest -- I don't know for sure that the graphs are the problem.  Looking at the heap report I see that that 89% of the memory in use appears to be allocated by `fyne.io/fyne/canvas.(*Text).MinSize`

I can supply more code excerpts and/or pprof output if needed.

Advice appreciated. Thanks!

**Comment by andydotxyz** [comment] 2020-05-04 16:37
Using an intermediate `fyne.Resource` is loading the bytes from disk, storing them in memory and then converting it to an image.
Do you see the same memory leaks if you use `canvas.NewImageFromFile`?

**Comment by Michael-F-Ellis** [comment] 2020-05-04 17:15
I'll give it a try. Thanks!
Cheers,
Mike

*“I want you to act as if the house was on fire. Because it is.” — Greta
Thunberg*

**Comment by Michael-F-Ellis** [comment] 2020-05-04 20:46
I change to using canvas.NewImageFromFile.  No change in behavior.

The 100Mb I reported earlier appears to be a constant allocation shortly after startup.  The report from pprof is essentially identical after hours of running.   That's the good news. 

The bad news is that it looks like Fyne's cgo is leaking.  

The memory usage report from top starts out at about 10% (consistent with the 100Mb early allocation since the Pi has 1 Gb RAM). Over the course of 2 hours, it's steadily grown to 50% (500Mb). Fyne is the only cgo package in my app.  I'm aware that the reports from top are hard to interpret because of Go's lazy GC. However, I've also observed the program running out of memory and crashing.  

In particular, I can tail my log file as the memory reserved approaches 60% and see "can't allocate memory" reported by calls to vcgen (for monitoring CPU temperature and throttling). When those messages start appearing the end is nigh.

**Comment by andydotxyz** [comment] 2020-05-04 21:48
Yes it does sound like the CGo is peaking somewhere - is there any more information you are able to gather?

**Comment by Michael-F-Ellis** [comment] 2020-05-04 23:23
I'm not quite ready to take a deep dive into the techniques described in this article:

https://kirshatrov.com/2019/11/04/finding-memory-leak-in-cgo/

What I may do is create a stripped down version of my app that does nothing but repeatedly load  and show an image. That might confirm or disprove the hypothesis that the leak is related to image handling.

**Comment by Michael-F-Ellis** [comment] 2020-05-05 01:07
Here's a minimal main.go that reproduces the problem on OS X and Raspbian Linux.   It  does nothing but repeatedly load the same image at 5 second intervals.  It also serves pprof on port 6060.  
 
https://gist.github.com/Michael-F-Ellis/4df32251b0d4210c581ab34844a1eb6d

I've also attached a png file I used in the tests -- but you can specify any valid image file at the command line, e.g.

```
memleak four-hour-plot.png
```

On both platforms, each reload  claims ~1.7Mb of memory, yet pprof only shows a constant allocation of a few Mb, e.g

```
File: memleak
Build ID: 32c2de3f0f79f7696a4d5364b5389ebf7912f43f
Type: inuse_space
Time: May 4, 2020 at 8:53pm (EDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20
Showing nodes accounting for 3.59MB, 100% of 3.59MB total
Showing top 20 nodes out of 29
      flat  flat%   sum%        cum   cum%
    3.59MB   100%   100%     3.59MB   100%  image.NewRGBA
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver.WalkVisibleObjectTree
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver.walkObjectTree
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow.func1
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint.func1
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree.func1
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTrees
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*window).RunWithContext
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/driver/glfw.(*window).ShowAndRun
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/painter.PaintImage
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/painter/gl.(*glPainter).Paint
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/painter/gl.(*glPainter).drawImage
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/painter/gl.(*glPainter).drawObject
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/painter/gl.(*glPainter).drawTextureWithDetails
         0     0%   100%     3.59MB   100%  fyne.io/fyne/internal/painter/gl.(*glPainter).newGlImageTexture
(pprof)
![four-hour-plot](https://user-images.githubusercontent.com/6699301/81026954-eee58f00-8e49-11ea-82af-991fe69061cd.png)

```

**Comment by andydotxyz** [comment] 2020-05-05 07:07
Excellent thanks, we will see if this can be addressed for the next release

**Comment by Michael-F-Ellis** [comment] 2020-05-05 12:25
Glad to have helped a little.  In the meantime, is there any workaround for periodically freeing the CGo allocations?  My client's  app needs to run reliably for months at a time.

**Comment by andydotxyz** [comment] 2020-05-06 16:15
Not that I am aware of - there is no GC in the C bridge.

**Comment by steveoc64** [comment] 2020-05-08 15:26
Proposal - add a function / property to the Fyne app to give hints on preferred memory usage.

The cleanup threads can then look at these values to make smarter decisions about what to reap, etc.

**Comment by steveoc64** [comment] 2020-05-08 15:31
Raises another idea out of left field .... I need to have a play with the TinyGo compiler again, and see how close we are to being able to build Fyne apps with TinyGo.  It may give better control over memory for building embedded apps.

**Comment by jcbritobr** [comment] 2020-11-07 22:13
This happens not only with images, but resizing a windows. I could get 856 Mb ram in demo just resizing the application.

**Comment by andydotxyz** [comment] 2020-11-09 14:52
Did the application that you resized have SVG images in it though @jcbritobr?
For great looks we have to draw lots of different images as it resizes and currently they are not removed until a timer lapses.
If you run the application for a long time you should not see the memory increase further as it will continue to free up memory and re-use it (apps don't ever "give back" mamory as far as I can tell).

**Comment by jcbritobr** [comment] 2020-11-09 15:55
> 
> 
> Did the application that you resized have SVG images in it though @jcbritobr?
> For great looks we have to draw lots of different images as it resizes and currently they are not removed until a timer lapses.
> If you run the application for a long time you should not see the memory increase further as it will continue to free up memory and re-use it (apps don't ever "give back" mamory as far as I can tell).

I had test this in the official demo. Its is a lot of memory, even for java applications.

**Comment by jcbritobr** [comment] 2020-11-09 15:59
Hope this help
![image](https://user-images.githubusercontent.com/6579862/98564703-6f6ac980-228b-11eb-8a49-8792e7a777cb.png)

**Comment by andydotxyz** [comment] 2020-11-12 11:17
This is not good, indeed, but I think it is still the rendered icon cache doing it - the graphics tutorial tab has a large icon that, when resized, will eat into memory. Perhaps we should more agressively remove the cache upon object resize so we only keep one cached size per object?

**Comment by jcbritobr** [comment] 2020-11-12 18:47
> 
> 
> This is not good, indeed, but I think it is still the rendered icon cache doing it - the graphics tutorial tab has a large icon that, when resized, will eat into memory. Perhaps we should more agressively remove the cache upon object resize so we only keep one cached size per object?

Hello @andydotxyz  I will build a simple window without an image and test with it. I'll update this thread soon.

**Comment by andydotxyz** [comment] 2020-11-12 19:51
Good plan, thanks @jcbritobr

**Comment by jcbritobr** [comment] 2020-11-13 00:50
Hello. It happens with a simple hello world. To reproduce you only need to resize the window. Is a huge leak.

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("simple Sample")
	hello := widget.NewLabel("hello sample")
	w.SetContent(widget.NewVBox(
		hello,
		widget.NewButton("Hi", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

Console output:
```
2020/11/12 21:45:36 PlatformError: WGL: Failed to make context current: Não há suporte para a operação de transformação solicitada.
2020/11/12 21:45:45 PlatformError: WGL: Failed to make context current: Não há suporte para a operação de transformação solicitada.
```

![image](https://user-images.githubusercontent.com/6579862/99014085-c04f1c00-2530-11eb-858e-88bc33d69863.png)

**Comment by fpabl0** [comment] 2021-07-27 21:26
@lewisthoma5 @jcbritobr this seems to be fixed on `develop` branch, could you confirm if the issue disappeared?

**Comment by jcbritobr** [comment] 2021-07-28 13:26
> 
> 
> @lewisthoma5 @jcbritobr this seems to be fixed on `develop` branch, could you confirm if the issue disappeared?

I'll download to test. On master it was broken last time I tested.

**Comment by changkun** [comment] 2021-10-31 15:31
I tested the fyne_demo and https://github.com/fyne-io/fyne/issues/348#issuecomment-726433285 on Ubuntu 20.04, and I have seen the scavenger releases memory to OS after a while, hence the problem should be fixed. Close.

**Closed by changkun** 2021-10-31 15:31 UTC
Labels: bug

**Comment by Jacalz** [comment] 2021-10-31 16:10
Is that one develop? If so, we should change the milestone to make sure that it is in the release notes.

**Comment by changkun** [comment] 2021-10-31 16:11
Yes, it is on develop.

**Comment by Jacalz** [comment] 2021-10-31 16:13
Thanks. I changed the milestone.
