### ISSUE TITLE
windows server 2016 error!

### ISSUE THREAD

**Issue by Xuzan9396** [fyne-io/fyne#1306] opened 2020-09-12 03:30 UTC
2020/09/12 10:31:58 log.go:12: Fyne error:  window creation error
2020/09/12 10:31:58 log.go:14:   Cause: APIUnavailable: WGL: The driver does not appear to support OpenGL
2020/09/12 10:31:58 log.go:19:   At: C:/go/src/gui_wechat/src/fyne.io/fyne/internal/driver/glfw/window.go:1164

**Comment by Jacalz** [comment] 2020-09-12 08:24
When opening issues, could you please fill out the issue template that is provided. It makes sure that we get most of the information that we might need and thus helps us help you :)

As far as the issue goes, it looks to me like you are running into the same issue as #664 . If that is the case, I highly recommend that you try and install a graphics driver for your system. Fyne requires this to be able to show the graphical interface. What system are you using?

**Comment by wenerme** [comment] 2020-10-13 09:26
@Jacalz cross build from linux, start failed on new installed windows server 2012 r2

![image](https://user-images.githubusercontent.com/1777211/95842436-1d608200-0d79-11eb-9771-37dab9545547.png)

![image](https://user-images.githubusercontent.com/1777211/95842491-2c473480-0d79-11eb-8094-6bbec128806b.png)

**Comment by Jacalz** [comment] 2020-10-13 09:49
@wenerme. It looks like you are encountering the same issue with a graphics driver not being installed.

**Comment by wenerme** [comment] 2020-10-13 09:54
@Jacalz Thanks,I'll try to install the driver, but not very good at windows.

**Comment by markgician** [comment] 2020-11-06 04:46
@Jacalz I meet the same issue on azure vm. (Standard D2s v3) the default display adapter is "microsoft hyper-v video driver", is there way to get around this? 

I can probably get around it if I upgrade to an N-series vm with GPU supported but that's expensive and I think there should be an easy way to have graphic driver in cloud vm.

**Comment by andydotxyz** [comment] 2020-11-17 13:08
Closing as duplicate of #410 which is the original report of VM and Server for Windows not having a compatible graphics driver

**Closed by andydotxyz** 2020-11-17 13:08 UTC
Labels: OS:Windows
