### ISSUE TITLE
Entry Line break

### ISSUE THREAD

**Issue by devcomcool** [fyne-io/fyne#408] opened 2019-08-18 11:33 UTC
I'm using Entry command and it keeps extending automatically when it runs out of space. How do I make it automatically extend to the next line?

[Image File](https://bot.onionbot.me/K-017.png)

**Comment by andydotxyz** [comment] 2019-08-18 12:28
Word wrap is not yet supported, this is a duplicate of #332

**Closed by andydotxyz** 2019-08-18 12:28 UTC
