### ISSUE TITLE
Apps built for Android don't run properly

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#661] opened 2020-02-07 15:59 UTC
### Describe the bug:

Fyne applications don't work on Android.

### To Reproduce:
Build and install an APK, and then run the application.

1. Create a new directory `fynetest`; `cd` there
2. Copy the source code in this ticket to a file called `main.go`
3. `go mod init ser1.net.fynetest`
4. Find a 382x512px image to use as an icon
5. Package the application for Android using fyne; `fyne package -os android -appID ser1.net.fynetest -name FyneTest -icon 382x512.png`
6. Copy the resulting APK to an Android device (e.g. with ADB, or with some other file sharing)
7. Install the APK on the Android device
8. Run the installed application

Behaviors vary. 

0. Usually, the app comes up as a white screen and never renders any widgets.  It stays a white screen.
1. Very, very rarely the UI will render and work correctly.  Out of two dozen times that I've tried, this has happened twice.
2. Sometimes, if the screen is tapped early after starting, the UI will partially render; widgets will not work, and are overlapping in random ways.  It feels like tapping interrupts the layout and what's shown is where it was interrupted.  Again, the UI doesn't function in this state.

### Example code:
This is a minimal Fyne program; however, I've seen this behavior on the two apps I've built and deployed.  The application runs fine on the desktop.

```Go
package main

import (
        "fyne.io/fyne/app"
        "fyne.io/fyne/widget"
)

func main() {
        a := app.New()
        w := a.NewWindow("test")
        defer w.ShowAndRun()
        w.SetContent(
                widget.NewVBox(
                        widget.NewLabel("Hello Fyne!"),
                        widget.NewButton("Quit", func() { a.Quit() }),
                ),
        )
}
```

### Device (please complete the following information):
 - OS: Android
 - Version: 10
 - Go version: go1.13.7
 - Fyne version: development branch, 97a6e6c0ff8e

**Comment by andydotxyz** [comment] 2020-02-07 18:12
This is very worrying - such results should never happen! Given the challenges with modules in other tickets can you provide steps that don’t require “go mod” commands?

Also we have a mobile “test UI” mode, perhaps you can confirm that the following works as expected:
“Go run -tags mobile .”?

**Comment by andydotxyz** [comment] 2020-02-07 18:16
One other interesting question, if you override the light theme (default on mobile) to dark, does the white screen become a dark grey screen on the times it does not render correctly?

`a.Settings().SetTheme(theme.DarkTheme())`

**Comment by andydotxyz** [comment] 2020-02-07 18:29
Is it possible to capture some screenshots? I'm not sure where to start with the debugging as apps have worked thus-far so it might help to see exactly what you are seeing.

**Comment by xxxserxxx** [comment] 2020-02-07 19:05
`go run -tags mobile .` produces a white screen too!  When I set the dark theme, it produces a blank dark screen.  Very strange, but it's great that the behavior is the same on the desktop as on the phone.  Can you reproduce it?

Here's the sample code; all I did was add a flag for setting the theme.  You can throw it in a file and compile it without modules.

```
package main

import (
	"flag"

	"fyne.io/fyne/app"
	"fyne.io/fyne/theme"
	"fyne.io/fyne/widget"
)

func main() {
	t := flag.Bool("t", false, "Dark theme")
	flag.Parse()
	a := app.New()
	if *t {
		a.Settings().SetTheme(theme.DarkTheme())
	} else {
		a.Settings().SetTheme(theme.LightTheme())
	}
	w := a.NewWindow("test")
	defer w.ShowAndRun()
	w.SetContent(
		widget.NewVBox(
			widget.NewLabel("Hello Fyne!"),
			widget.NewButton("Quit", func() { a.Quit() }),
		),
	)
}
```
Here are the runs:

`go run .`
![2020-02-07-125710_527x287_scrot](https://user-images.githubusercontent.com/60757196/74057683-11cae900-49aa-11ea-86d7-e24c4121af7a.png)

`go run . -t`
![2020-02-07-125726_474x268_scrot](https://user-images.githubusercontent.com/60757196/74057568-d3cdc500-49a9-11ea-82fe-532e395be037.png)

`go run -tags mobile .`
![2020-02-07-125747_689x851_scrot](https://user-images.githubusercontent.com/60757196/74057724-24ddb900-49aa-11ea-9e3a-80ca0d8c4e0d.png)

`go run -tags mobile . -t`
![2020-02-07-125801_710x861_scrot](https://user-images.githubusercontent.com/60757196/74057736-2ad39a00-49aa-11ea-8b4f-b128b97e81b6.png)

In all cases, the `mobile` tag produces an unresponsive, blank canvas.  This matches the behavior on the mobile device, although I haven't tried the dark theme on it yet.

Do you get different results?  What version of Go are you using?

**Comment by xxxserxxx** [comment] 2020-02-07 19:10
You know what's funny?  Why is it doing this?

```
➜  fyne git:(develop) ✗ go run ./cmd/fyne_demo 
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20191125211704-12ad95a8df72
go: extracting github.com/go-gl/glfw/v3.3/glfw v0.0.0-20191125211704-12ad95a8df72
go: finding github.com/go-gl/glfw/v3.3/glfw v0.0.0-20191125211704-12ad95a8df72
➜  fyne git:(develop) ✗ pwd
/home/ser/go/src/fyne.io/fyne
```

Fyne vendors this package; it's right there in the `vendor` directory... so why is go downloading it?

**Comment by xxxserxxx** [comment] 2020-02-07 19:39
I'm stuck.  I copied the better part of the `fyne_demo` main func into my `fynetest` -- all of the bits that didn't require calling out to other functions to create containers -- and it still hangs.  I even moved the class into `fyne/cmd/fynetest` and ran it from there.  In all cases, running with `-tags mobile` causes it to hang.  I am unable to see the difference that is causing the issue.

**Comment by andydotxyz** [comment] 2020-02-07 20:00
Thanks for all this helpful info. I will try to reproduce the behaviour as well.
FYI: vendor is ignored in modules mode unless you pass -mod=vendor - maybe that makes a difference? I’m beginning to suspect a bad updated dependency but will look harder now

**Comment by xxxserxxx** [comment] 2020-02-07 20:15
See if you can replicate it first; it could still be something with my set-up.

**Comment by andydotxyz** [comment] 2020-02-07 21:24
I have tried but cannot replicate this. The cmd/hello binary works as expected with modules on and off and using `-mod=vendor` as well, I don't know what is going on with your setup.
Go 1.13.6 on one machine and 1.12.5 on another are both working.
If it is hanging perhaps you are able to deduce where?

**Comment by andydotxyz** [comment] 2020-02-07 21:31
Also tested Fyne 1.2.2 and develop branches, same result

**Comment by xxxserxxx** [comment] 2020-02-07 23:39
I thought it might only be my computer, but I get exactly the same behavior when I install the APK on my Pixel 2.  I'll try some other machines.

**Comment by xxxserxxx** [comment] 2020-02-08 14:08
I installed everything on a VPS, `ssh -X`ed into it, and ran my app with `go run -tags mobile ./cmd/diary`.  It came up on my local desktop partially rendered; when I resized it, the window went blank.  When I full-screened the window, it stayed blank.  I ran it again and got the same incomplete rendering; without resizing, I tried clicking some of the UI elements and got no response from the UI.

It's acting like it is hung.

I'm going to try it next by running a VNC session on the remote machine and see if I get any different behavior, and eliminate that there's something strange about my desktop configuration.  It still doesn't explain why the app doesn't run on my mobile device.  Do you have an Android phone you'd be willing to install an APK for if I provide one?  Or can you download my project, build the APK yourself and try it?

Is there a third person we can ask to try testing mobile?  It'd be great to have a third data point.

This is really baffling.

**Comment by andydotxyz** [comment] 2020-02-08 14:38
Yes baffling! It seems like the build is somehow not correct - explaining why installing the APK on other devices makes no difference. As for “third person” we have many developers using this successfully so I know it’s not only the core developers that have it working. 

Currently I think we should focus on why the mobile simulation build (-tags mobile) does not work, as this is quicker and has much more in common with the desktop code. If there is a deadlock would you be able to use a debugger to find where it is? That does seem like the most logical cause.

**Comment by xxxserxxx** [comment] 2020-02-08 15:21
I installed go cleanly on a VM (hosted on a third-party VPS provider); copied my repository there; installed Fyne (fresh) with `go get`; installed (fresh) all of the X dependencies needed to build Fyne apps; installed a VNC server and xfce4; connected to the VNC session; and ran my app with `go run -tags mobile`.  I still see freezing-like behavior.  I've [made a video of the VNC session](https://gofile.io/?c=6RwvyC):

**Comment by xxxserxxx** [comment] 2020-02-09 00:42
Theoretically, any app built with [fyne-cross](https://github.com/lucor/fyne-cross) should eliminate any issue with my environment?  Apps built with fyne-cross should either work, or demonstrate a true bug, correct?

**Comment by andydotxyz** [comment] 2020-02-09 10:10
Yes I guess that is true. At this stage the deadlock backtrack would be much more helpful though.

**Comment by xxxserxxx** [comment] 2020-02-09 14:58
Ok, I'll try to pull that, but I'm seeing different behaviors now.  It's quite erratic.  

I discovered that the fyne-cross project doesn't actually build an APK, and after spending a couple of hours learning that packaging apps for Android has gotten significantly more involved in the past ten years, and that I really have no interest in going down that rabbit hole or taking up even more of my hard drive space with the Android toolset (Studio -- I'm at, what, 10GB now and it wants more? Madness!), I'm taking a different approach.

I'm in the process of provisioning a new VPS so that I can install **everything** cleanly (again), but also include the entire, stupidly large, Android build chain so that I can build an APK and test that on my phone.  This, too, should eliminate environmental issues, or at least find out whether it works or not with an entirely virgin toolkit installation.

**Comment by xxxserxxx** [comment] 2020-02-09 16:01
I''m attaching a backtrace, from pprof.  That's (obviously) responding to requests, but the UI is not updating (refreshing, redrawing, responding to resize requests).  Maybe I'll go in and add hooks on redraw events to see if I can see if those are even getting triggered.

This trace is from the VPS I set up yesterday and VNC'd into; it has a freshly installed go1.13.7, and I removed the GOPATH directory before I ran the app, so all of the dependencies were freshly downloaded.

![2020-02-09-095944_497x753_scrot](https://user-images.githubusercontent.com/60757196/74105400-f9320e80-4b22-11ea-8e2e-dfa7207400ac.png)

[fyne.dump.txt](https://github.com/fyne-io/fyne/files/4177128/fyne.dump.txt)

**Comment by andydotxyz** [comment] 2020-02-10 11:50
Thanks, that is really helpful.
I have just thought of something - can you try adding the following line to the bottom of your go.mod please?

replace golang.org/x/mobile => github.com/fyne-io/mobile v0.0.0-20191204153723-f14fb9562406

We have some bug fixes on top of standard gomobile which may impact this..?

**Comment by xxxserxxx** [comment] 2020-02-10 17:32
Progress!

Ok, so I made that change for the version (is that the `develop` branch?).  Now, with `-tags mobile`:

- The initial window is partially drawn, but as if the (x,y) origin coordinates are incorrect.  **However** I wrapped my VBox in a ScrollContainer and now it comes up correctly!
- If I interact with the user interface, it redraws the UI correctly.
- I can interact with the widgets, and they behave correctly, except text inputs.  
- I can select an input, and the cursor appears and blinks, but when I type nothing is put into the field.
- I've noticed that if I cover the window, when it's exposed it doesn't redraw.  This includes switching to a different desktop and back.  However, if I interact with any widget, including the scroll bar, it redraws and we're all happy again.

This is on my desktop.  On the mobile device, the app comes up with a blank screen, but if I tap around on it, eventually the UI renders and I can interact with it.  On the phone, the text fields also accept input.

I provisioned a VPS and installed everything from scratch.  The APK I'm testing is being built on that, but I'm also going to test APKs built on my desktop again, too.

##### P.S.
Every once in a while, when quitting I get one of these:
```
➜  healthdiary go run -tags mobile ./cmd/diary/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x6a7c7e]

goroutine 180 [running]:
fyne.io/fyne/widget.(*selectRenderer).Destroy(0xc0000d2800)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/widget/select.go:92 +0x8e
fyne.io/fyne/internal/cache.DestroyRenderer(0x8a6a20, 0xc00015e360)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/cache/widget.go:42 +0x49
fyne.io/fyne/internal/driver/gomobile.(*window).Close.func1(0x8a5ea0, 0xc00015e360, 0x8a56c0, 0xc0000be190)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/gomobile/window.go:147 +0x6f
fyne.io/fyne/internal/driver.walkObjectTree(0x8a5ea0, 0xc00015e360, 0x8a56c0, 0xc0000be190, 0x4, 0xffffffffffffffd7, 0x4, 0x4, 0x124, 0x188, ...)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/util.go:89 +0x27f
fyne.io/fyne/internal/driver.walkObjectTree(0x8a56c0, 0xc0000be190, 0x8a5c60, 0xc000156150, 0x4, 0xffffffffffffffd7, 0x4, 0x4, 0x124, 0x188, ...)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/util.go:82 +0x1f6
fyne.io/fyne/internal/driver.walkObjectTree(0x8a5c60, 0xc000156150, 0x8a5b40, 0xc000435880, 0x4, 0xffffffffffffffd7, 0x4, 0x4, 0x124, 0x188, ...)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/util.go:82 +0x1f6
fyne.io/fyne/internal/driver.walkObjectTree(0x8a5b40, 0xc000435880, 0x8a5e40, 0xc0000bd260, 0x4, 0x4, 0x4, 0x4, 0x124, 0x188, ...)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/util.go:82 +0x1f6
fyne.io/fyne/internal/driver.walkObjectTree(0x8a5e40, 0xc0000bd260, 0x0, 0x0, 0x0, 0x0, 0x4, 0x4, 0x124, 0x188, ...)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/util.go:82 +0x1f6
fyne.io/fyne/internal/driver.WalkVisibleObjectTree(0x8a5e40, 0xc0000bd260, 0x0, 0x83b2c0, 0x10)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/util.go:26 +0x82
fyne.io/fyne/internal/driver/gomobile.(*mobileCanvas).walkTree(0xc000158000, 0x0, 0x83b2c0)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/gomobile/canvas.go:171 +0x4f
fyne.io/fyne/internal/driver/gomobile.(*window).Close(0xc0000bc3c0)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/gomobile/window.go:144 +0x1c1
fyne.io/fyne/app.(*fyneApp).Quit(0xc0000bc300)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/app/app.go:62 +0x79
main.main.func12()
        /home/ser/workspace/healthdiary/cmd/diary/main.go:189 +0x2f
fyne.io/fyne/widget.(*Button).Tapped(0xc00015e5a0, 0xc0009800e0)
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/widget/button.go:169 +0x3d
created by fyne.io/fyne/internal/driver/gomobile.(*mobileDriver).tapUpCanvas.func1
        /home/ser/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/driver/gomobile/driver.go:238 +0x4d
exit status 2
```

Of note is that it appears to still be using v1.2.2, despite [having added the replace to go.mod and having modules enabled](https://asciinema.org/connect/0dee3af0-4ac6-4914-95e1-94f7f68e4a6d).  Is that just something strange go modules is doing?

**Comment by andydotxyz** [comment] 2020-02-10 17:54
Thanks for the detail, I'm glad the patch helped. It's annoying and I'm trying to figure a way round it.
We have lots of mobile patches to push upstream to gomobile but that will take some time - in the meantime leave this change in. (notice that is replacing our mobile library not the main fyne lib)

The keyboard not working with "-tags mobile" is a known issue, on the device it should correctly bring up the virtual keyboard. https://github.com/fyne-io/fyne/issues/591

Let me know how the desktop APK build goes. If the mobile tags simulation looks right the APK should look the same. If they are different that's a bug to dig into.

**Comment by cerisara** [comment] 2020-02-10 19:48
Might be related, but when I compile the examples as an apk and install on my phone, then I got just a blank screen, nothing else. I tried with the "replace" option, but no luck.
However, in my case, when I run on the linux desktop with the -tags mobile flag, it works perfectly.

So the problem is just on my phone: it may be related to a lack of memory ? (it's a low-end phone Android 7.0 )
I've not seen any bad error message in the logcat (but I may have missed one)

Note: I've already compiled before other simple apps with gomobile (no fyne), and they worked on my phone.

**Comment by andydotxyz** [comment] 2020-02-10 20:16
Fyne apps should not require much memory - we did a benchmark and they were favourable. If it was a memory error then logcat should report it. Perhaps there is an error in booting the app? You should be able to grep the log for “GoLog” with the current version to see anything.

**Comment by cerisara** [comment] 2020-02-11 08:37
Thank you: you're right, the issue is not related at all to deploying on phone: it also occurs when running the very basic fyne hello world code (see below) with:
```
go run -tags mobile .
```
Then, the window displays correctly (I'm running ubuntu 18.04), but as soon as I try to make the window larger, then the display gets all wrong, not refreshing.

Here is some info:
```
xtof@lully:~/go/src/xtof.fr/fapp1$ go version
go version go1.13.7 linux/amd64
xtof@lully:~/go/src/xtof.fr/fapp1$ gomobile version
gomobile version +0df4eb2 Wed Feb 5 17:02:28 2020 +0000 (android); androidSDK=/home/xtof/softs/android-sdk-linux/platforms/android-23
```

```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()

	w := a.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			a.Quit()
		}),
	))

	w.ShowAndRun()
}
```

**Comment by xxxserxxx** [comment] 2020-02-11 12:08
I can replicate this, sort of; my window starts out blank, but if I click around and hit a widget it redraws.  If I resize the window, it never redraws.

This fixes both of those issues:
```
...
		widget.NewButton("Quit", func() {
			fmt.Println("QUIT")
			b.Refresh()
		}),
	)
	w.SetContent(b)
	go func() {
		time.Sleep(1 * time.Second)
		b.Refresh()
	}()
	w.ShowAndRun()
}
```
The `go func()` goroutine causes the window to draw correctly about a second after it shows.  Resizing still doesn't refresh the window, but if I click on the button (note that it doesn't exit any more), it refreshes the window.

@andydotxyz, somehow the resize events are not cascading and triggering a refresh.  Manually calling `Refresh()` in a widget and then interacting it does cause the UI to re-layout.  If I remove the `Refresh()`, interacting with the button does not redraw (although it does run the `Println()`).

@cerisara, can you try this button code for me and see if you see the same thing?

**Comment by andydotxyz** [comment] 2020-02-11 16:51
Thanks. I think the resize events (though should be fixed) are a distraction as the phone cannot be resized as a workaround ;).
Can you both (@xxxserxxx, @cerisara) please confirm what development OS and desktop environment? I am struggling a little again.

**Comment by cerisara** [comment] 2020-02-11 17:52
Yes, but it's related: I've deployed the following minimal app on my phone, and now it works !
This is because it does a refresh every second, which makes the button visible on my phone now.
So the issue is really about the refreshing loop I think.

```
package main

import (
    "fmt"
    "time"
        "fyne.io/fyne/app"
        "fyne.io/fyne/widget"
)

func hdl() {
  fmt.Println("uuyypass here")
}

func main() {
        app := app.New()

        w := app.NewWindow("Hello")
        b := widget.NewButton("Hello Fyne!",hdl)
        w.SetContent(b)
        fmt.Println("zzyypass4")

        go func() {
            for ;; {
                fmt.Println("zzyypass5")
                b.Refresh()
                time.Sleep(time.Second)
            }
        }()

        w.ShowAndRun()
}
```

**Comment by xxxserxxx** [comment] 2020-02-11 22:15
```console
$  uname -a
Linux glamdring 5.5.2-arch1-1 #1 SMP PREEMPT Tue, 04 Feb 2020 18:56:18 +0000 x86_64 GNU/Linux
$ fyne lib-version
v1.2.2
$ cd ~/go/src/fyne.io/fyne && git --no-pager log -1 | head -n 1 && cd -
commit b4a7630aa4d89b6d38940685b1c197a6e6c0ff8e
```

and here's the project go.mod, renamed to .txt to appease github ಠ_ಠ

[go.mod.txt](https://github.com/fyne-io/fyne/files/4188726/go.mod.txt)

**Comment by cerisara** [comment] 2020-02-12 07:58
```
cd ~/go/src/fyne.io/fyne && git --no-pager log -1 | head -n 1
commit eba8bb2e8629ad0cbe2d4b07a051043a9759e4f3
uname -a
Linux lully 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by andydotxyz** [comment] 2020-02-12 12:12
Do you know what window manager you are using @cerisara?
Can you please show your full go.mod file with the replace directive added?

Another question would be, when running on the phone, does rotating it refresh the screen?

**Comment by cerisara** [comment] 2020-02-13 10:48
OK, I've reinstalled everything, and tested with the minimal code at the end of this post.
I tried both without any go.mod, and with a go.mod that contains the single "replace..." line: it does not change anything.
I compile with
```
fyne package -appID fr.xtof54.fapp -icon olkible.png -name fapp -os android
```
and install on my phone.

Observations:
- without the refresh loop, just get a blank screen; rotating the device makes it black, but nothing more
- with the refresh loop, the app works properly (congratulation for the Entry widget: it's great !); but as soon as I rotate the screen, the black screen of death appears, and there is no way to get the app working any more.

Any idea ? please ?

Thank you !

code:
```
package main

import (
    "fmt"
    "time"
    "fyne.io/fyne/app"
    "fyne.io/fyne/widget"
)

func hdl() {
    fmt.Println("uuyypass here")
}

func main() {
    app := app.New()

    w := app.NewWindow("Hello")
    b := widget.NewButton("Hello Fyne!",hdl)
    t := widget.NewEntry()
    t.OnCursorChanged = func() {
        fmt.Println("ttyypass")
    }
    glob := widget.NewHBox(b,t)
    w.SetContent(glob)
    fmt.Println("zzyypass4")

    // THE refresh loop:
    go func() {
        for ;; {
            fmt.Println("zzyypass5")
            b.Refresh()
            t.Refresh()
            time.Sleep(time.Second)
        }
    }()

    w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment] 2020-02-13 12:40
Apologies to ask more questions, but can you also confirm the path to directory you are compiling in and the value of GO111MODULE environment variable?

One other command that could be worth testing is this:
`GO111MODULE=off go run -tags mobile .`
Does that operate the same or have some more useful GUI displayed?

**Comment by cerisara** [comment] 2020-02-13 18:42
GO111MODULE is unset
when I define it off, it does not change anything: still refresh problem with go run -tags mobile .
here is the absolute path where my app.go is:
```
/home/xtof/go/src/xtoftest/fapp
```
and the go.mod:
```
module xtoftest/fapp
go 1.13
require fyne.io/fyne v1.2.2
replace golang.org/x/mobile => github.com/fyne-io/mobile v0.0.0-20191204153723-f14fb9562406
```
I compile this time with:
```
fyne package -icon ble.png -os android -appID xtoftest.fapp
```
but still no luck on the phone as well

**Comment by cerisara** [comment] 2020-02-14 14:32
I've tried to trace down the bug on my phone within fyne.io, and maybe found a way to prevent the initial blank screen from happening:

in internal/driver/gomobile/driver.go
the problem occurs when a size.Event with size 0x0 arrives: I don't know where it comes from, but this sometimes happens. Then, in case paint.Event (around line 135), I've added a safeguard:
```
if currentSize.WidthPx<10 {
                                    fmt.Printf("detson0g BUGSIZE %v\n",currentSize)
                                    continue
                                }
```

But this is not enough, and I've also added just before, in case size.Event:
```
time.Sleep(time.Millisecond * 10)
a.Send(paint.Event{})
```
So that a new paint event is triggerred  when size changes.

With these modifications of fyne.io, I've not seen so far the blank screen again, and the app is working... as long as we do not rotate nor put the app in the background: in both cases, the black
screen always appear when waking up the app, and I've also sometimes observed a cross to lifecycle.stageDead. So I think this is another issue.

**Comment by andydotxyz** [comment] 2020-02-14 16:42
This is a big step forward thank you!
The black screen on rotate and background is something I have seen before, though I cannot replicate now, so I agree it's probably a different issue.

Would it be possible for you to open a PR with the changes above? It would be good to know the exact change is working for you rather than me patching it in and waiting for next release?

**Comment by cerisara** [comment] 2020-02-14 17:26
You're right: I've made the test == 0 instead of < 10
I've tested again on my phone: it's working for background/foreground (that's the second fix in the PR: but CI fails, not sure it's because of the PR).
But there are still 2 different issues:

- when rotating => black screen and crash
- when pressing the "back" button and foreground again => black screen and crash

**Comment by andydotxyz** [comment] 2020-02-24 22:37
Thanks to @cerisara a lot of work has gone in to this and I think it's in a good place now.
It's all on release/v1.2.3 branch for pre-release testing.
If possible @xxxserxxx could you take a look as well? It is working for me on a range of devices but I'd love to get more input!

**Comment by andydotxyz** [comment] 2020-02-24 22:37
If fixed I think we could close this similarly to #677

**Comment by xxxserxxx** [comment] 2020-02-25 17:33
@andydotxyz I'll test this afternoon.  Thanks for working so diligently on this.

**Comment by andydotxyz** [comment] 2020-03-02 17:32
That’s v1.2.3 out, I think we can close this now.

**Closed by andydotxyz** 2020-03-02 17:32 UTC
