### ISSUE TITLE
IOS black screen on APP switcher

### ISSUE THREAD

**Issue by freedreamer82** [fyne-io/fyne#3028] opened 2022-06-02 12:55 UTC
Hi all,

I tried to build my own app for IOS device (iphone 8 with ios 15.5)...everything it works except when I slide up to the app switcher... the app snapshot becomes  all black and when I switch back to the app sometimes it works and sometimes I need to go it in the background and reopen to get it working.

I tried the last stable release and the develop branch as well ..but with both I have the same issue.

Any advice ?

PS
build with:
`fyne package -os ios -appID com.mqtt.shell  -icon ../../assets/mqtt-shell.png -name mqtt-shell
`
on MacOs Apple M1

fyne version develop : v2.1.4-0.20220602113944-20fbb51896f7
fyne versione stable v2.1.4

Thanks

Marco

![IMG_A5A3C64C4800-1](https://user-images.githubusercontent.com/5691521/171632254-2db1fc5d-37c5-4292-8c17-bc6c597c5ab2.jpeg)

**Comment by Jacalz** [comment] 2022-06-02 13:00
Please use the issue templates when opening a new issue. It makes sure that we get all the information that we need to be able to help out and triage bugs.

What version of Fyne are you using? From what I can tell, this should have been fixed, according to https://github.com/fyne-io/fyne/issues/1610, in Fyne 2.0 and later. I wonder if the issue has popped up again or if you are using an older version.

**Comment by freedreamer82** [comment] 2022-06-02 13:39
edit with the version I tried.
more info: 
I build another app (https://github.com/fynelabs/mqttweather) and i have the same issue.. so i guess it's not related to the app but to the way I build or the framework.

**Comment by Jacalz** [comment] 2022-06-02 13:41
Thanks. I think it most likely is an issue on our end. Seems like something has made it appear again.

**Comment by changkun** [comment] 2022-06-02 15:49
> Thanks. I think it most likely is an issue on our end. Seems like something has made it appear again.

It sounds like this was an old issue that had been fixed before but somehow occurred again. Am I correct?

As far as I understood the phenomenon, this is due to the mobile driver (including gomobile) does not yet handle GL context recovering at application switch, which has been a long-standing knowing problem (at least in gomobile).

**Comment by andydotxyz** [comment] 2022-06-02 17:16
The previous fixes are around this issue and it was marked resolved 15 months ago: https://github.com/fyne-io/fyne/issues/1610

**Comment by andydotxyz** [comment] 2022-06-02 20:38
Aaaah, the old iPhone with almost square corners really confused me as their task switcher takes the shape of the surrounding device!

**Comment by freedreamer82** [comment] 2022-06-02 20:41
> Aaaah, the old iPhone with almost square corners really confused me as their task switcher takes the shape of the surrounding device!

ahahha "old"... :(  if you want to gift me a new iphone , no problem :)

**Comment by freedreamer82** [comment] 2022-06-02 21:25
> > ahahha "old"... :( if you want to gift me a new iphone , no problem :)
> 
> It's not young - nearly 5 years old. Apple will stop supporting it next year. Of course we will still support it... We go back to the `iPhone 5s` - but your screenshot caught me by surprise. So it could relate to the graphical memory or the age of the GPU...

I hope apple will support it for one year more... my wife has an iphone 11 ..I can try on it...

**Comment by freedreamer82** [comment] 2022-06-07 07:56
in order to help your  debug I noticed that when there a screen with infinity bar running the black issues disappears... when the bar is closed the issues comes back again..no i don't thing could be a GPU problem.

Marco

**Comment by andydotxyz** [comment] 2022-06-07 10:58
I'm sorry can you clarify what an infinity bar is? How can we replicate this case where it works and then stops working?

**Comment by freedreamer82** [comment] 2022-06-07 11:55
> I'm sorry can you clarify what an infinity bar is? How can we replicate this case where it works and then stops working?
![IMG_4792](https://user-images.githubusercontent.com/5691521/172372798-d133d804-b3d4-484f-92de-e13ac5089c61.PNG)

to replicate this you have to build my app for ios:
https://github.com/freedreamer82/mqtt-shell/tree/feature-gui

**Comment by freedreamer82** [comment] 2022-06-10 10:36
v2.2.0

same issue.. here a videoclip.

https://user-images.githubusercontent.com/5691521/173047571-fd09c086-b8fc-498e-9739-ed1bce0c293c.mov

**Comment by andydotxyz** [comment] 2022-11-21 23:27
I don't seem to have this issue any more with iOS16.
Not sure what that means...

**Comment by inchworks** [comment] 2023-05-27 17:00
I have the same issue with my own app. The demo calculator app installed from the app store doesn't show the problem. However building https://github.com/fyne-io/calculator myself does reproduce the issue. This is with fyne v2.3.4, iOS 16.4.1(a), iPhone 14 Pro. Also with Xcode simulator for iPhone 14 Pro Max, except that the screen is bright magenta instead of black. (I don't suspect the iPhone model but I haven't tried a different one with calculator.)

**Comment by freedreamer82** [comment] 2023-05-28 07:03
HI ,

I changed my phone from iphone 8 to iphone 12 mini and....it happens some way. I can confirm that it's not an iphone ram issue. It's something else, at least IMHO.

Marco

**Comment by andydotxyz** [comment] 2023-05-28 08:59
Thanks for this extra info.
Can you confirm if the Fyne apps downloaded from store work ok on your new device?

**Comment by freedreamer82** [comment] 2023-05-28 11:16
Yes i confirm. the apps downloaded From the store are ok.
M.

**Comment by freedreamer82** [comment] 2024-05-24 15:42
Hi, I resume this thread since with the last  version the error is here...I also tried an example fyne app (calculator) but it does the same.
I noticed on my app when the keyboard is on foreground the app is NOT black in the switcher ! maybe can be  a clue for you.

Thanks


M.

**Comment by andydotxyz** [comment] 2024-05-24 16:08
Thanks for the tip. I had thought it was a timing issue of some sort but perhaps that's not right after all.

**Comment by freedreamer82** [comment] 2024-05-24 18:13
![IMG_1439](https://github.com/fyne-io/fyne/assets/5691521/0134d43b-ddc0-43ce-b62c-92525e4e0183)

here the example with keyboard foreground

**Comment by freedreamer82** [comment] 2024-06-15 11:03
Any news?

**Comment by andydotxyz** [comment] 2024-06-15 13:47
> Any news?

No. Updates to the issue will be posted or linked here.

**Comment by freedreamer82** [comment] 2024-07-18 22:05
hi,

good news. compiled with fyne 2.5 and problem seems not here anymore.

M.

**Comment by andydotxyz** [comment] 2024-07-18 22:26
Excellent. It turns out that Go had changed how it handled the iOS GOOS and so a few seemingly unrelated issues were resolved in the last release cycle.

**Closed by andydotxyz** 2024-07-18 22:26 UTC
Labels: unverified
