### ISSUE TITLE
Issues exported to Android (or mobile)

### ISSUE THREAD

**Issue by MoLuoPro** [fyne-io/fyne#1117] opened 2020-06-20 03:12 UTC
### Describe the bug:
There is no problem exporting the official simple case to Windows platform, but when exporting to Android platform, the Quit button on the interface loses its function and cannot be clicked.

### To Reproduce:
Steps to reproduce the behaviour:
1. export to Android platform
2. Click on 'Quit' button, and there is no response

### Example code:
func main() {
    app := app.New()
    w := app.NewWindow("Hello")
    w.SetContent(widget.NewVBox(
        widget.NewLabel("Hello Fyne!"),
        widget.NewButton("Quit", func() {
            app.Quit()
        }),
    ))

 w.ShowAndRun()
}

### Device (please complete the following information):
 - OS: Android
 - Version: IQOO Neo 855 Edition, Android 9
 - Go version: latest1.14
 - Fyne version: latest

**Comment by Jacalz** [comment] 2020-06-20 07:27
Hello @MoLuoPro. This is the intended behaviour. If you read the documentation on the quit function, you will see it is handled by the operating system and thus doesn’t work on mobile:

```go
// Calling Quit on the application will cause the application to exit
	// cleanly, closing all open windows.
	// This function does no thing on a mobile device as the application lifecycle is
	// managed by the operating system.
	Quit()
```

Lastly I just want to give you some tips for opening issues in the future. We all did this in the future, no worries, just giving some friendly advice :)

Please don’t use “latest” for versioning because latest will change when a new version comes out and it thus becomes irrelevant in the future. Also please label issues after the issue like  “quit function does not work in mobile” because then it can more easily be found in the future.

**Comment by MoLuoPro** [comment] 2020-06-20 07:44
Thank you for your friendly suggestions. This is my first issue. Your suggestions will allow me to integrate into the community faster. Thanks again. In addition, I hope that the API of this cross-platform application framework can be as consistent as possible on different platforms. Especially the code used in the official demo, as a place to show our strong cross-platform capabilities to new friends who do not adequately understand our project, should have platform consistency.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jacob&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月20日(星期六) 下午3:27
收件人:&nbsp;&quot;fyne-io/fyne&quot;<fyne@noreply.github.com&gt;;
抄送:&nbsp;&quot;MoLuo&quot;<2056673609@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [fyne-io/fyne] Issues exported to Android (or mobile) (#1117)

**Comment by andydotxyz** [comment] 2020-06-20 08:14
I completely agree thanks @MoLuoPro - I have started transitioning from “Quit” button to “fyne.io” hyperlink. I guess some of the docs have not been updated yet.

**Comment by andydotxyz** [comment] 2020-06-20 21:06
Closing as not an issue

**Closed by andydotxyz** 2020-06-20 21:06 UTC
Labels: not an issue
