### ISSUE TITLE
Cannot run the demo on macOS 10.14

### ISSUE THREAD

**Issue by mdzidic** [fyne-io/fyne#901] opened 2020-04-24 13:26 UTC
### Describe the bug:

Hello,
I'm just trying to run fyne_demo and after running `go get fyne.io/fyne/cmd/fyne_demo/` I get:

```
# fyne.io/fyne/internal/driver/glfw
go/src/fyne.io/fyne/internal/driver/glfw/gl_darwinfix.go:10:5: warning: 'NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:202:12: note: 'NSOpenGLContext' has been explicitly marked deprecated here
```

### To Reproduce:
go get fyne.io/fyne
go get fyne.io/fyne/cmd/fyne_demo/

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.14.6
 - Go version: 1.14.2
 - Fyne version: 1.2.4

**Comment by andydotxyz** [comment] 2020-04-24 13:47
These are just warnings and should not impact the application build or runtime.
They go away in release 1.3 which is coming in May.

After your `go get` commands above the `fyne_demo` should be in `$GOPATH/bin/` as expected.

**Comment by andydotxyz** [comment] 2020-04-24 13:48
Duplicate of #310

**Closed** 2020-04-24 13:48 UTC
Labels: duplicate
