### ISSUE TITLE
widget.Entry can not render Chineses properly

### ISSUE THREAD

**Issue by cokeBeer** [fyne-io/fyne#3302] opened 2022-10-03 09:00 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

widget.Entry can not render Chineses properly

### How to reproduce

code:
```go
respEntry := widget.NewMultiLineEntry()
respEntry.SetText("你好")
```

run the code
then we can see ?? in text, not Chinese

### Screenshots

<img width="404" alt="image" src="https://user-images.githubusercontent.com/70683161/193538722-3cacf636-2bc7-4ff0-a13f-584632c483d6.png">

### Example code

code:
```go
respEntry := widget.NewMultiLineEntry()
respEntry.SetText("你好")
```

### Fyne version

v2.2.3

### Go compiler version

go version go1.19.1 darwin/amd64

### Operating system

macOS

### Operating system version

macos catalina 10.15.4

**Comment by Jacalz** [comment] 2022-10-03 11:21
This is a duplicate of various other issues regarding Chineese support. The built in font does not support those characters and need to be specified. See https://github.com/fyne-io/fyne/issues/2660#issuecomment-1223452508 for more information.

**Closed by Jacalz** 2022-10-03 11:21 UTC
Labels: unverified
