### ISSUE TITLE
Slider input do not implement Disableable

### ISSUE THREAD

**Issue by chran554** [fyne-io/fyne#4664] opened 2024-02-22 15:02 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Slider input can not be disabled (only hidden or shown).
Slider should implement fyne.Disableable interface.

A form with a slider should not have to hide the slider when it's not applicable for the moment but rather show it as disabled/read only.

### How to reproduce

Not really applicable.

Create a slider. There are no Enable or Disable functions to call.

### Example code

Not applicable.

### Fyne version

2.4.4

### Go compiler version

1.21.3

### Operating system and version

macOS Sonoma 14.2.1

**Comment by Jacalz** [comment] 2024-02-22 15:15
This has already been solved on the `develop` branch for the upcoming v2.5.0 release. See  https://github.com/fyne-io/fyne/pull/4482.

**Comment by Jacalz** [comment] 2024-02-22 15:16
Duplicate of https://github.com/fyne-io/fyne/issues/3551.

**Closed by Jacalz** 2024-02-22 15:16 UTC
Labels: unverified

**Comment by chran554** [comment] 2024-02-22 16:40
> Also, FYI: That a widget doesn’t support being disabled is not a bug. A feature request would be more appropriate.

Yes, I agree and I gave some thought before submitting. But you might argue that all(?) **input** widgets should be able to be disabled.

**Comment by Jacalz** [comment] 2024-02-22 16:57
> But you might argue that all(?) input widgets should be able to be disabled.

Yeah perhaps, but I wouldn't personally block a new input widget because it doesn't support being disabled. Being disableable is more of an extension than a core principle, I'd say :)
