### ISSUE TITLE
app is getting quit when used the .Close() it use to not happen previously.

### ISSUE THREAD

**Issue by rajkumarks7** [fyne-io/fyne#1192] opened 2020-07-17 10:23 UTC
hey i am facing a issue of closing the window i have two screens one for login and another for selection of project. so on first screen after logging in the first screen should be closed so that i am using the w.Close() and e.Close() for the second window but the problem i am facing in the latest version is the whole program is getting closed after logging in. but previously it use to not happen  it happening in both the windows and ubuntu also so can you please suggest me with a solution. 
for first screen i am using w.showandrun() for second screen i am using e.show()

**Comment by andydotxyz** [comment] 2020-07-17 11:15
Apologies for this, an app is designed to exit if all it's windows are closed.
Previously what you described worked by mistake.

This can be fixed by using `Window.Hide()` (so that it can be re-used later).
Closing this as a duplicate of #1080

**Closed by andydotxyz** 2020-07-17 11:15 UTC

**Comment by rajkumarks7** [comment] 2020-07-17 11:18
Thank you shall I use w.hide() ?

**Comment by andydotxyz** [comment] 2020-07-17 11:20
Because when you close windows it will quit the app.
Using Hide is a workaround as you are saying "Don't display this window any more, but don't dispose of it" so the app does not think it can close.

**Comment by rajkumarks7** [comment] 2020-07-17 11:31
Thank you
