### ISSUE TITLE
Widget shortcut prevents window shortcut

### ISSUE THREAD

**Issue by pekim** [fyne-io/fyne#2938] opened 2022-04-24 09:45 UTC
### Describe the bug:
* a window with a registered shortcut
* a widget with a registered shortcut
* when the widget is focused and receives the shortcut the window does not receive the shortcut

### To Reproduce:

1. Run the example application below.
1. Ensure the widget has focus. ("focus" in stdout)
1. Press `ctrl+2`. The message `widget shortcut` is sent to stdout.
1. Press `ctrl+1`. The message `window shortcut` should be sent to stdout, but is not.

If `testWidget`'s `TypedShortcut` method is commented out, then the window shortcut works.

### Example code:
```go
package main

import (
	"fmt"
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()

	w := a.NewWindow("Shortcut bug")
	widget := newTestWidget()
	w.SetContent(widget)

	w.Canvas().AddShortcut(&desktop.CustomShortcut{
		KeyName:  fyne.Key1,
		Modifier: desktop.ControlModifier,
	}, func(shortcut fyne.Shortcut) {
		fmt.Println("window shortcut")
	})

	a.Lifecycle().SetOnEnteredForeground(func() {
		fyne.CurrentApp().Driver().CanvasForObject(widget).Focus(widget)
	})

	w.ShowAndRun()
}

type testWidget struct {
	widget.BaseWidget
	shortcuts fyne.ShortcutHandler
}

func newTestWidget() *testWidget {
	w := &testWidget{}
	w.ExtendBaseWidget(w)

	w.shortcuts.AddShortcut(
		&desktop.CustomShortcut{
			KeyName:  fyne.Key2,
			Modifier: desktop.ControlModifier,
		},
		func(se fyne.Shortcut) {
			fmt.Println("widget shortcut")
		},
	)

	return w
}

func (w *testWidget) CreateRenderer() fyne.WidgetRenderer {
	return &renderer{}
}

func (w *testWidget) FocusGained() {
	fmt.Println("focused")
}

func (w *testWidget) FocusLost() {
	fmt.Println("blur")
}

func (w *testWidget) TypedRune(r rune) {}

func (w *testWidget) TypedKey(ev *fyne.KeyEvent) {}

func (w *testWidget) TypedShortcut(shortcut fyne.Shortcut) {
	w.shortcuts.TypedShortcut(shortcut)
}

type renderer struct{}

func (*renderer) Layout(size fyne.Size) {}

func (*renderer) MinSize() fyne.Size {
	return fyne.NewSize(100, 100)
}

func (*renderer) Refresh() {}

func (r *renderer) Objects() []fyne.CanvasObject {
	rect := canvas.NewRectangle(color.RGBA{255, 0, 0, 255})
	rect.Resize(fyne.NewSize(100, 100))
	return []fyne.CanvasObject{rect}
}

func (*renderer) Destroy() {}
```

### Device:
 - **OS:** Linux
 - **Version:** Ubuntu 20.04, kernel 5.13.0-39
 - **Go version:** go1.18.1 linux/amd64
 - **Fyne version:** v2.1.4

**Comment by dweymouth** [comment] 2023-10-22 16:20
Closing as duplicate of #2627

**Closed by dweymouth** 2023-10-22 16:20 UTC
Labels: duplicate, unverified
