### ISSUE TITLE
Is there a way to play a video in container?

### ISSUE THREAD

**Issue by JackySmith** [fyne-io/fyne#1272] opened 2020-08-28 05:25 UTC
video from local or  url like youtube , 
thanks

**Comment by andydotxyz** [comment] 2020-08-28 09:05
This is not yet supported. We would like to do it in the future, but there are many issues to overcome.
Tentatively positioned for a [3.0 release](https://github.com/fyne-io/fyne/milestone/9) next year.

**Comment by andydotxyz** [comment] 2020-08-28 09:06
Closing as duplicate of #449

**Closed by andydotxyz** 2020-08-28 09:06 UTC
