### ISSUE TITLE
Android MainMenu overwrites label

### ISSUE THREAD

**Issue by DaleEMoore** [fyne-io/fyne#3560] opened 2023-01-12 15:16 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The Menu "hamburger" overwrites the label in the "Example code" on Android. Linux does not experience this issue.

### How to reproduce

Run the example code in the "Example code" section of this issue.

### Example code

// fyneMenu3.go - simple example of fyne Menu.
// DaleEMoore@gMail.Com
//From https://blogvali.com/main-menu-items-submenu-fyne-gui-golang-tutorial-36/

package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	//New app
	app2 := app.NewWithID("com.anydom.com")
	win2 := app2.NewWindow("Main menu items")
	win2.Resize(fyne.NewSize(400, 400)) //400x400windowsize
	// TODO, it appears that actuating File New, File Edit, or File Run causes Quit to have to be
	//		actuated more than once to occur! Or maybe not?
	//Menuitems
	menuItem1 := fyne.NewMenuItem("New", func() { fmt.Println("Menu New->Other->Mail") })
	menuItem2 := fyne.NewMenuItem("Edit", func() { fmt.Println("Menu Edit->Other->Mail") })
	menuItem3 := fyne.NewMenuItem("Run", func() { fmt.Println("Menu Run->Other->Mail") })
	newMenu1 := fyne.NewMenu("File", menuItem1, menuItem2, menuItem3) //NewMenu
	//more new menus
	newMenu2 := fyne.NewMenu("Other", menuItem1, menuItem2, menuItem3)
	newMenu3 := fyne.NewMenu("Help", menuItem1, menuItem2, menuItem3)
	menu := fyne.NewMainMenu(newMenu1, newMenu2, newMenu3) //New mainmenu
	win2.SetMainMenu(menu)                                 //set upmainmenu
	hello := widget.NewLabel("MainMenu learning project!")
	win2.SetContent(hello)
	win2.ShowAndRun()
}

### Fyne version

2.3.0

### Go compiler version

go version go1.19.2 linux/amd64

### Operating system

Android

### Operating system version

13

**Comment by andydotxyz** [comment] 2023-01-13 20:38
I think this is a duplicate of the earlier note that it covers a tab-bar item if that is at the top of the app too... #2141

**Closed by andydotxyz** 2023-01-13 20:38 UTC
Labels: unverified

**Comment by DaleEMoore** [comment] 2023-01-13 23:21
> I think this is a duplicate of the earlier note that it covers a tab-bar item if that is at the top of the app too... #2141

As always Andy, you are right. [#2141](https://github.com/fyne-io/fyne/issues/2141) seems like the same underlying issue. I wonder how iOS handles it? Perhaps the same way.

I'll work around it.

Thanks Andy! 
Dale

**Comment by andydotxyz** [comment] 2023-01-14 21:01
Mostly they make an "app level layout" that makes a blank space for a title bar under the venue button component. Kinda like the AppSkeleton we proposed.
