### ISSUE TITLE
Enable strikethrough text

### ISSUE THREAD

**Issue by GaetanBaert** [fyne-io/fyne#4297] opened 2023-10-03 08:30 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I want to display ~~strikethrough text~~ in `widget.Label` or in `widget.RichText`.

### Is it possible to construct a solution with the existing API?

It seems it's currently not possible. (maybe we can cheat by adding a `canvas.Line` over the text, but it will probably be very ugly...)

### Describe the solution you'd like to see.

I see 2 different ways to do that : 
- modify `fyne.TextStyle` by adding a `Strikethrough  bool` in the `struct`
- add strikethrough support in the markdown parser of `widget.RichText`

**Comment by andydotxyz** [comment] 2023-10-09 10:50
However it is exposed (and the `TextStyle` seems the right place for it) we will need font strikethrough support into the rendering at go-text I am pretty sure.

**Comment by mgazza** [comment] 2023-10-09 11:51
Adding https://github.com/fyne-io/fyne/pull/4244 as related. Underlining is implemented as @GaetanBaert suggests with a line.

**Comment by dweymouth** [comment] 2024-01-08 19:33
Duplicate of #1084

**Closed by dweymouth** 2024-01-08 19:33 UTC
