### ISSUE TITLE
Menu: functional change between Fyne 2.5.0 and Fyne 2.5.2

### ISSUE THREAD

**Issue by Klaus-Tockloth** [fyne-io/fyne#5242] opened 2024-11-06 11:11 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

With Fyne 2.5.0 I see this correct menu (only 'Quit'):
<img width="62" alt="Bildschirmfoto 2024-11-06 um 11 59 46" src="https://github.com/user-attachments/assets/532255f1-f73c-4e3a-b642-1cf9a822a29c">

With Fyne 2.5.2 I see a menu with an additional, unwanted and undefined menu entry "Beenden":
<img width="94" alt="Bildschirmfoto 2024-11-06 um 12 00 23" src="https://github.com/user-attachments/assets/7f7dcd83-46fb-4917-8702-565cc800dbd8">

Questions:

- Was there a functional change between Fyne v2.5.0 and Fyne v2.5.2?
- Is there a workaround to avoid the above behavior?  

BTW: "Beenden" is the german translation for "Quit". 

### How to reproduce

Code snippet:

	// menu items for 'File' menu entry
	fileQuit := fyne.NewMenuItem("Quit",
		func() {
			logger.Println(Format(TRANSACTION, INFO, MESSAGE, "user action: activate 'File -> Quit'"))
			if isApplicationClosable {
				application.Quit()
			}
		})
	fileMenu := fyne.NewMenu("File", fileQuit)

### Example code

See above.

### Fyne version

v2.5.0 versus v2.5.2

### Go compiler version

v1.23.2

### Operating system and version

Windows

**Comment by Klaus-Tockloth** [comment] 2024-11-06 11:56
Maybe related to https://github.com/fyne-io/fyne/issues/5158

**Comment by andydotxyz** [comment] 2024-11-06 17:00
It will be because we added the German translation. This should be fixed if you update your code so that 

```go
fileQuit := fyne.NewMenuItem("Quit",
```

becomes

```go
fileQuit := fyne.NewMenuItem(land.L("Quit"),
```

That way your Quit is going to match the system (translated) one.

**Comment by Klaus-Tockloth** [comment] 2024-11-07 07:46
```
	// menu items for 'File' menu entry
	fileQuit := fyne.NewMenuItem(lang.L("Quit"),
		func() {
			slog.Info("user action: activate 'File -> Quit'")
			if isApplicationClosable {
				application.Quit()
			}
		})
	fileMenu := fyne.NewMenu("File", fileQuit)
```

With the above correction I get to this:

<img width="93" alt="Bildschirmfoto 2024-11-07 um 08 37 41" src="https://github.com/user-attachments/assets/d7968d78-f5a5-4da3-bfb1-9ca5bf294ab6">

This is better (only one menu entry) but not what I want. My international application is "english only" and should not have translated parts (in this case "Beenden"). How to achieve this?

**Comment by andydotxyz** [comment] 2024-11-15 22:07
Oh I realise now that this was a duplicate of #5158

**Closed by andydotxyz** 2024-11-15 22:07 UTC
Labels: unverified

**Comment by Klaus-Tockloth** [comment] 2024-11-16 08:10
Concerning the question "Windows menu: How to avoid /disable any translation?" I opened this separate issue: https://github.com/fyne-io/fyne/issues/5269
