### ISSUE TITLE
Hide() not working properly in the mac 

### ISSUE THREAD

**Issue by rajkumarks7** [fyne-io/fyne#2242] opened 2021-05-14 13:35 UTC
### Describe the bug:

like if we use the hide() for a window it is not working properly it is hidden for some time after that it is getting back t normal again it is showing the window.
 
first on clicking the first button the first screen will hide and on clicking the second button the second window will hide after that when you click on third button the third window will hide and after calling another function inside the third button the last window will start appearing and if we close then second window will appear and if we close the second window then first window will appear.
please can you give me a solution so that the windows won't show. 

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to run the below code
2. Click on 

### Example code:

```go
func main(){
       a := app.New()
	w := a.NewWindow("Hello")
	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(widget.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			w.Hide()
                        b:=a.NewWindow("Welome")
                     	b.Resize(fyne.NewSize(350, 200))
			b.CenterOnScreen()
			b.SetFixedSize(true)
                        hello2 := widget.NewLabel("How are you")
                        b.SetContent(widget.NewVBox(
                               hello2,
                               widget.NewButton("Hi!", func() {
                                       b.Hide()
                                       "here i will be calling another function "
                                })  
                        ))
                       b.Show()
		})
	  ))

         w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:**  Mac OS
 - **Version:** 10.15.5 
 - **Go version:**  1.14.4
 - **Fyne version:**  1.4.3

**Comment by Jacalz** [comment] 2021-05-14 14:15
Hi there. Can you please create an example code that is easier to read? I corrected the source highlighting, but there is a lot of code and the indentation is all over the place. I would appreciate a shorter and simpler code example.

It would also be good if you could try with the latest version of Fyne instead of 1.4.3 which is several releases behind at this point.

**Comment by rajkumarks7** [comment] 2021-05-14 14:17
yes sir it is i will be updating it.

**Comment by Jacalz** [comment] 2021-05-14 14:28
Thanks. The code is much easier to read now. This could have been fixed in a later version. Please see if the issue reproduces with Fyne 2.0.3 before we start digging deeper in to this.

**Comment by rajkumarks7** [comment] 2021-05-14 14:29
okay sir

**Comment by andydotxyz** [comment] 2021-05-17 09:02
I think the cause of the issue is in code that you have not included.
Although the code you write does not currently compile I fixed it locally but cannot replicate the problem with 2.0.3.
From the description I think that `"here i will be calling another function "` is hiding the problem area.

**Comment by Jacalz** [comment] 2021-07-27 20:06
Ping @rajkumarks7 per the previous comment.

**Comment by rajkumarks7** [comment] 2021-07-30 03:17
sir can i get your slack channel url and i have one doubt can we implement the google api call like html meta tag and the button which will open a new chrome or any browsing windows and show us the signin option with google.

**Comment by Jacalz** [comment] 2021-07-30 06:20
> sir can i get your slack channel url and i have one doubt can we implement the google api call like html meta tag and the button which will open a new chrome or any browsing windows and show us the signin option with google.
> 
> 

If that is what you are doing, I cannot help you. Let's instead focus on the reported Fyne issue here. If you remove that code from within the function above, does the Hide() call work?

**Comment by rajkumarks7** [comment] 2021-07-30 08:12
i mean using of the google api call with the fyne is it possible?

**Comment by rajkumarks7** [comment] 2021-07-30 08:12
hide() error did not look into it again.

**Comment by andydotxyz** [comment] 2021-07-30 09:16
You can find the contact details for all of our support channels at https://fyne.io/#contact.
Most APIs can be used with Fyne. There is an example of using GMail APIs in my first book on Go GUIs https://www.packtpub.com/product/hands-on-gui-application-development-in-go/9781789138412.

> hide() error did not look into it again.

Without your assistance we can't progress this ticket as we are not able to replicate in standard apps, so I am closing this issue.
Please re-open if you are able to replicate the error with code you can share.

**Closed by andydotxyz** 2021-07-30 09:16 UTC
Labels: unverified
