### ISSUE TITLE
The dialog. newCustomConfirm callback occasionally has no response

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2094] opened 2021-03-17 09:26 UTC
### Describe the bug:

I can't make this happen again, it only happens occasionally, when I click the confirm or cancel button at the bottom of the dialog, the dialog will disappear, the whole app will freeze, I can only click the close button, and then re-run the exe file and it will work again.

### Example code:
```
func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	dlg := container.NewVBox(
		hello,
		widget.NewEntry(),
	)
	dialog.NewCustomConfirm("test win", "yes", "no", dlg, func(b bool) {

	}, w)
	w.Resize(fyne.NewSize(300,300))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** :win10 home
 - **Go version:** go1.16
 - **Fyne version:** 1.4.3

**Comment by andydotxyz** [comment] 2021-03-17 12:35
You talked about the callback not responding - but there is no code in the callback.
Is there something missing from the example code, or should the title be updated to refer to the app being unresponsive after closing dialog instead of about the callback?

I wonder if it is possible that some code in your callback could have triggered a UI freeze somehow?

**Comment by smp12345** [comment] 2021-03-17 13:01
My example code does not have callback content, my original project content is more, there is a callback, it is not easy to copy separately.When the OK button is clicked, the dialog disappears immediately and the entire window is unresponsive, except for the button above the title bar.Because this doesn't happen to me every time, just occasionally, my business code is the one place where there is no blocking, and I feel like the framework itself is not stable enough.Since my problem cannot be repeated, I guess it will be very difficult to solve it. I just hope you can give me some ideas to reduce the possibility of this happening

**Comment by Jacalz** [comment] 2021-03-17 13:17
I don't think it is possible for us to reproduce this without the code inside the callback. My best guess would be that there is a bug  callback code that leads to it sometimes blocking, and thus stalling the event thread.

**Comment by smp12345** [comment] 2021-03-17 13:24
Well, thanks for your help. I'm just checking for occasional blockages

**Comment by Jacalz** [comment] 2021-11-21 16:10
Any news on this @smp12345? Can we close this?

**Comment by andydotxyz** [comment] 2023-01-03 09:59
Closing due to lack of activity

**Closed by andydotxyz** 2023-01-03 09:59 UTC
Labels: bug, information-needed
