### ISSUE TITLE
Kannada characters not rendering correctly

### ISSUE THREAD

**Issue by ravihara** [fyne-io/fyne#2654] opened 2021-11-21 12:22 UTC
### Describe the bug:

I was following the example given at https://developer.fyne.io/tour/binding/twoway. I changed my keyboard layout to Kannada-itrans. I'm using Ubuntu 20.04 LTS 64 bit system and have install ibus-m17n and fonts-indic packages. While running the application via `go run main.go`, after typing couple of characters, the application crashed with the following error.

```
panic: runtime error: slice bounds out of range [15:14]

goroutine 9 [running]:
fyne.io/fyne/v2/widget.(*RichText).insertAt(0xc000618000, 0xf, {0xc000353f30, 0x3})
	/home/ravihara/.asdf/installs/golang/1.17.3/packages/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/richtext.go:222 +0x2b8
fyne.io/fyne/v2/widget.(*Entry).TypedRune(0xc0001a4000, 0xccd)
	/home/ravihara/.asdf/installs/golang/1.17.3/packages/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/entry.go:743 +0x11b
fyne.io/fyne/v2/internal/driver/glfw.(*window).charInput.func1()
	/home/ravihara/.asdf/installs/golang/1.17.3/packages/pkg/mod/fyne.io/fyne/v2@v2.1.1/internal/driver/glfw/window.go:1226 +0x25
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0xc00045c200)
	/home/ravihara/.asdf/installs/golang/1.17.3/packages/pkg/mod/fyne.io/fyne/v2@v2.1.1/internal/driver/common/window.go:58 +0x56
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/home/ravihara/.asdf/installs/golang/1.17.3/packages/pkg/mod/fyne.io/fyne/v2@v2.1.1/internal/driver/glfw/window.go:1395 +0x15b
exit status 2
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to 'https://developer.fyne.io/tour/binding/twoway' and create a sample project as per the guide. In my case, the sample code was in main.go in main package.
2. Export the required font file so as to get the Kannada font to render properly in the InputEntry box
    `export FYNE_FONT=/usr/share/fonts/truetype/Gubbi/Gubbi.ttf`
3. Run the fyne application using `go run main.go`

### Device (please complete the following information):
 - **OS:**  Ubuntu Linux 20.04 LTS 64-Bit (x86-64)
 - **Version:**  20.04 LTS
 - **Go version:**  1.17.3
 - **Fyne version:**  2.1.1

**Comment by andydotxyz** [comment] 2021-11-21 15:35
> * Run the fyne application using `go run main.go`
> * See error

I think this is missing some steps - didn't you have to type something into one of the fields? It would be helpful to get the characters so we can replicate correctly.

**Comment by ravihara** [comment] 2021-12-03 16:19
> > * Run the fyne application using `go run main.go`
> > * See error
> 
> I think this is missing some steps - didn't you have to type something into one of the fields? It would be helpful to get the characters so we can replicate correctly.
Yes. The issue happens once you start typing couple of Kannada (IN_Kn) characters. I use ibus-m17n engine with itrans keyboard layout for Kannada, in order to type the characters. An Example string in Kannada could be - ಕನ್ನಡ ಒಂದು ಸುಂದರ ಭಾಷೆ

**Comment by andydotxyz** [comment] 2021-12-06 02:03
Is the font you are using this one: https://github.com/aravindavk/Gubbi?

**Comment by ravihara** [comment] 2021-12-07 06:32
> Is the font you are using this one: https://github.com/aravindavk/Gubbi?

Yes.. Do you see an issue in the font?

**Comment by andydotxyz** [comment] 2021-12-08 01:29
It would be good if you could outline the specific steps required to replicate the crash - that way I can know if we have fixed the problem,

**Comment by ravihara** [comment] 2021-12-13 07:03
> It would be good if you could outline the specific steps required to replicate the crash - that way I can know if we have fixed the problem,

- `mkdir check-fyne`
- `cd check-fyne`
- `go mod init github.com/ravihara/check-fyne`
- `go get fyne.io/fyne/v2`
- Create the file main.go with the code sample as given in https://developer.fyne.io/tour/binding/twoway
- `go mod tidy`
- `export FYNE_FONT=/usr/share/fonts/truetype/Gubbi/Gubbi.ttf`
- `go run main.go`
- Clear the type in the text box
- Switch to Kannada (IN_kn) keyboard layout and start typing random characters. If you need a proper string type ಕನ್ನಡ ಒಂದು ಸುಂದರ ಭಾಷೆ

**Comment by ravihara** [comment] 2021-12-13 07:06
Today I retried again and the app hung instead of crashing. When I tried running again, it went fine. In all the cases, the font rendering is not proper too.

**Comment by andydotxyz** [comment] 2021-12-30 02:31
I think we need more details replication steps for:

> Switch to Kannada (IN_kn) keyboard layout and start typing random characters. If you need a proper string type ಕನ್ನಡ ಒಂದು ಸುಂದರ ಭಾಷೆ

Because I tried and it seemed to work OK, so I am clearly missing something.
![cap](https://user-images.githubusercontent.com/294436/147716997-35fc9488-bbdb-404b-94b0-acf04af4133b.png)

**Comment by andydotxyz** [comment] 2022-01-04 17:17
Just for posterity this was the code that created the screenshot above:
```go
// Package main loads a very basic Hello World graphical application.
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	str := binding.NewString()
	str.Set("ಕನ್ನಡ ಒಂದು ಸುಂದರ ಭಾಷೆ")

	e := widget.NewEntryWithData(str)
	w.SetContent(container.NewVBox(
		widget.NewLabelWithData(str),
		e,
	))

	w.Resize(fyne.NewSize(180, 20))
	w.ShowAndRun()
}
```

**Comment by ravihara** [comment] 2022-01-07 06:21
> Just for posterity this was the code that created the screenshot above:
> 
> ```go
> package main
> 
> import (
> 	"fyne.io/fyne/v2"
> 	"fyne.io/fyne/v2/app"
> 	"fyne.io/fyne/v2/container"
> 	"fyne.io/fyne/v2/data/binding"
> 	"fyne.io/fyne/v2/widget"
> )
> 
> func main() {
> 	a := app.New()
> 	w := a.NewWindow("Hello")
> 
> 	str := binding.NewString()
> 	str.Set("ಕನ್ನಡ ಒಂದು ಸುಂದರ ಭಾಷೆ")
> 
> 	e := widget.NewEntryWithData(str)
> 	w.SetContent(container.NewVBox(
> 		widget.NewLabelWithData(str),
> 		e,
> 	))
> 
> 	w.Resize(fyne.NewSize(180, 20))
> 	w.ShowAndRun()
> }
> ```

Hi, thanks for trying it out. As I mentioned in my last comment, I couldn't reproduce the crash error due to slice size, again. Now, the only issue that remains is the font rendering. You can easily compare the rendered output in the fyne app and how it renders in the github in the code snippet that you posted. I mean, the value of str.set(...) method. We may close this issue, if font-rendering is a separate problem space.

**Comment by andydotxyz** [comment] 2022-01-13 01:21
> You can easily compare the rendered output in the fyne app and how it renders in the github in the code snippet that you posted.

It is not as easy as you think - the string rendered in GitHub is system dependent, I do not normally have "Gubbi" font running, so I just see squares. If you want to compare rendering output please post screenshots so we can see exactly what you expect.

**Comment by ravihara** [comment] 2022-01-13 12:22
> > You can easily compare the rendered output in the fyne app and how it renders in the github in the code snippet that you posted.
> 
> It is not as easy as you think - the string rendered in GitHub is system dependent, I do not normally have "Gubbi" font running, so I just see squares. If you want to compare rendering output please post screenshots so we can see exactly what you expect.

Sorry about that! i missed the point. I'll share you the screenshot soon.

**Comment by andydotxyz** [comment] 2022-01-13 15:34
Ah, thank you. I now understand that this is a shaping issue.
We are working on this with the [go-text](/go-text) project with the Gio toolkit and other font experts :).

**Comment by andydotxyz** [comment] 2022-01-13 16:52
Oh the fix needs to be in Fyne, but the problem is a large one and we are collaborating on the solution :).
We can leave this open and track the implementation.

**Comment by andydotxyz** [comment] 2022-01-18 03:05
The go-text team are awesome and I'm excited to share this latest version.
It is a long way from a Fyne PR, but this shows it should be possible in our next release...

![shaped](https://user-images.githubusercontent.com/294436/149863904-8a170a4c-6840-4371-9e19-3016d9f6004d.png)

**Comment by ravihara** [comment] 2022-01-30 14:07
> The go-text team are awesome and I'm excited to share this latest version. It is a long way from a Fyne PR, but this shows it should be possible in our next release...
> 
> ![shaped](https://user-images.githubusercontent.com/294436/149863904-8a170a4c-6840-4371-9e19-3016d9f6004d.png)

Cool! Thanks. Waiting for that to happen 👍🏽

**Comment by andydotxyz** [comment] 2023-01-03 09:53
This was fixed in v2.3.0 :)

**Comment by andydotxyz** [comment] 2023-01-04 21:50
Actually this may not yet be sorted - the rendering is in, but we have to set the region for shaping to work well - making it part of a wider localisation work in future release :(

**Comment by ravihara** [comment] 2023-01-05 06:59
> Actually this may not yet be sorted - the rendering is in, but we have to set the region for shaping to work well - making it part of a wider localisation work in future release :(

Thanks for taking it up @andydotxyz

**Comment by andydotxyz** [comment] 2023-07-11 15:58
Please do test our `develop` branch - it uses a new test renderer @ravihara .
The region issue may still exist, but testing so far indicates that it is working quite well without additional hints.

**Comment by ravihara** [comment] 2023-07-12 06:09
Sure @andydotxyz . I'll verify once and get back to you soon. Thanks for the update btw.

**Comment by andydotxyz** [comment] 2023-07-22 22:08
OK, sorry about that. We will have to get the region hinting in then as part of the internationalisation work, which didn't make it into v2.4.0

**Comment by andydotxyz** [comment] 2024-07-04 09:49
This is now working on develop branch. Using the string `"ಕನ್ನಡ ಒಂದು Hello 🖥️"` in the code above I get the following render:

![kannada](https://github.com/fyne-io/fyne/assets/294436/cfdab4a3-7588-491c-b04c-fec57338cda1)

**Closed by andydotxyz** 2024-07-04 09:49 UTC
Labels: bug, blocker

**Comment by ravihara** [comment] 2024-07-07 08:16
> This is now working on develop branch. Using the string `"ಕನ್ನಡ ಒಂದು Hello 🖥️"` in the code above I get the following render:
> 
> ![kannada](https://private-user-images.githubusercontent.com/294436/345782504-cfdab4a3-7588-491c-b04c-fec57338cda1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDA0MjAsIm5iZiI6MTcyMDM0MDEyMCwicGF0aCI6Ii8yOTQ0MzYvMzQ1NzgyNTA0LWNmZGFiNGEzLTc1ODgtNDkxYy1iMDRjLWZlYzU3MzM4Y2RhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwODE1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDZlNDIyYzkwNGYyMDI4NjA5YjcxYTUxNWViY2E4YzE2NmViYTcyMWUzNGUzZjU0NDNmY2U0Y2E2OWY3ZTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._hTu665Fh6P1MSVtEBhI_lT6t9atSPP5V7geHY2tK5Y)
> 
> Also worth noting, this did not require FYNE_FONT or a custom theme, as the system fonts are looked up now so this just worked :)

Thanks @andydotxyz. Let me verify it in my local system.

**Comment by ravihara** [comment] 2024-07-07 08:25
![image](https://github.com/fyne-io/fyne/assets/383541/000091a1-cc84-4d04-abbb-8a017533085f)
It's working fine with "develop" branch. Thanks @andydotxyz for the help.

**Comment by andydotxyz** [comment] 2024-07-07 13:34
Thanks for confirming :)
