### ISSUE TITLE
how to let fyne app run on a lower osx  version ?

### ISSUE THREAD

**Issue by JackySmith** [fyne-io/fyne#1327] opened 2020-09-20 23:43 UTC
Hi,I have a problem that delay my work for a few days
when i package app on 10.15, it can not run on 10.11
when i package app on 10.11, it can run on 10.11+ include 10.15
but i cannot run it on osx lower than 10.11
it there a resolution let app run on 10.7?

**Comment by Jacalz** [comment] 2020-09-21 05:24
This might partly be dependent on the Go version that you are using. I know for example that Go 1.15 dropped support for El Capitan. Are you using different Go versions?

**Comment by JackySmith** [comment] 2020-09-21 06:19
on osx10.11, I use go1.13.15 ,that's ok
but if I use go1.12.17,   it can not run after go build on osx10.11
well, osx10.7 only support go1.11 
so I cannot find a solution

**Comment by andydotxyz** [comment] 2020-09-21 08:36
This seems like it could be a duplicate of #886, you may need to specify some macos parameters when packaging for older systems, particularly:

```
export CGO_CFLAGS=-mmacosx-version-min=10.11
export CGO_LDFLAGS=-mmacosx-version-min=10.11
```

**Comment by andydotxyz** [comment] 2020-11-17 17:48
We will get this addressed in 1.4.2 following the duplicate #886 issue

**Closed by andydotxyz** 2020-11-17 17:48 UTC

**Comment by andydotxyz** [comment] 2020-11-27 11:01
Fix is in PR #1612, should be merged for 1.4.2 release next week

**Comment by andydotxyz** [comment] 2020-11-27 11:05
> it there a resolution let app run on 10.7?

Unfortunately Apple stopped supporting this platform 6 years ago, so it is unlikely you can build new apps for it.
We support back to 10.11 which most computers sold in the last 12 years should be able to run.

Can you update your old OSX Lion computer to a newer version of OS X to get support?

**Comment by Jacalz** [comment] 2020-11-27 11:17
I don’t think it would be possible to make them run on OSX 10.7. Go 1.12 (the currently oldest version for compiling fyne) supports only OSX 10.10 and Go 1.15 (latest stable release of Go) dropped supports only OSX 10.12 and later.
