### ISSUE TITLE
not support chinese

### ISSUE THREAD

**Issue by xingliuhua** [fyne-io/fyne#604] opened 2020-01-08 07:21 UTC
not support chinese

**Comment by beoran** [comment] 2020-01-08 11:34
This is a duplicate of #598. 

But, you can use Chinese if you change the fyne font to a Chinese TTF font.

**Comment by andydotxyz** [comment] 2020-01-08 11:38
Closing as duplicate of initial issue #63. Let's aim to solve this properly in 2.0 release.

**Closed by andydotxyz** 2020-01-08 11:38 UTC
