### ISSUE TITLE
Entering long text in entry will cause OpenGL issue

### ISSUE THREAD

**Issue by kinwang94** [fyne-io/fyne#4616] opened 2024-02-06 23:30 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Input more than 1022 to 1032 characters in the Entry widget, the following error message will appear, and the text will also turn black as shown in the screenshot.

```text
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
```

### How to reproduce

1. Enter more than 1022 to 1032 characters in any Entry widget

### Screenshots

<img width="612" alt="fyne-GLD_TEXTURE_INDEX_2D" src="https://github.com/fyne-io/fyne/assets/23193126/e8041ad2-4780-4507-a310-314ed0c1726f">

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")
	w.Resize(fyne.NewSize(500, 200))

	w.SetContent(makeEntryTab(w))
	w.ShowAndRun()
}

func makeEntryTab(_ fyne.Window) fyne.CanvasObject {
	entry := widget.NewEntry()
	entry.SetPlaceHolder("Entry")

	entryPassword := widget.NewPasswordEntry()
	entryPassword.SetPlaceHolder("Password")

	entryMultiLine := widget.NewMultiLineEntry()
	entryMultiLine.SetPlaceHolder("MultiLine Entry")
	entryMultiLine.SetMinRowsVisible(4)

	return container.NewVBox(
		entry,
		entryPassword,
		entryMultiLine,
	)
}
```

### Fyne version

v2.4.3

### Go compiler version

1.21.6

### Operating system and version

Apple M2 Pro macOS Sonoma 14.2.1

### Additional Information

https://onlinetexttools.com/generate-text-of-certain-length

The above issue occurs when testing with the following options:
(Text Length / Text Composition)
- 1024 / Uppercase Letters (A-Z)
- 1024 / Mixed Case Letters (a-zA-Z)
- 1024 / Numbers (0-9)
- 1024 / Uppercase Letters and Numbers
- 1024 / All Letters and Numbers

The above issue **does not** occur when testing with the following options:
- 1024 / Lowercase Letters (a-z)
- 1024 / Lowercase Letters and Numbers

**Comment by andydotxyz** [comment] 2024-02-07 09:53
This is a duplicate of #678

**Closed by andydotxyz** 2024-02-07 09:53 UTC
Labels: unverified
