### ISSUE TITLE
NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit

### ISSUE THREAD

**Issue by mimicode** [fyne-io/fyne#382] opened 2019-08-04 06:26 UTC
# fyne.io/fyne/internal/driver/gl
../../pkg/mod/fyne.io/fyne@v1.1.0/internal/driver/gl/gl_darwinfix.go:10:5: warning: 'NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:202:12: note: 'NSOpenGLContext' has been explicitly marked deprecated here

**Comment by andydotxyz** [comment] 2019-08-04 18:40
Closing as duplicate of #61 - this is just a deprecation warning and it will be resolved when newer version is available upstream.

**Closed** 2019-08-04 18:41 UTC
Labels: duplicate
