### ISSUE TITLE
Add rich text features to Entry

### ISSUE THREAD

**Issue by 0x414a** [fyne-io/fyne#4428] opened 2023-11-29 00:53 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

"Add rich text capabilities to Entry, such as the ability to change font color, font background color, font size, and more. Alternatively, add an editor that allows user editing and includes rich text features."Additionally, I'd like to mention again the previously discussed issue that Entry does not handle large texts well, and every time it focuses or new content is added, it re-renders the entire text.

### Describe the solution you'd like to see.

"Add rich text capabilities to Entry, such as the ability to change font color, font background color, font size, and more. Alternatively, add an editor that allows user editing and includes rich text features."Additionally, I'd like to mention again the previously discussed issue that Entry does not handle large texts well, and every time it focuses or new content is added, it re-renders the entire text.

**Comment by Jacalz** [comment] 2023-11-30 07:01
Please remember to search for open issues before opening a new one. This is a duplicate of https://github.com/fyne-io/fyne/issues/21 (with a very similar title). Will close in favour of that one.

**Closed by Jacalz** 2023-11-30 07:01 UTC
