### ISSUE TITLE
widget.Select lacks scrolling

### ISSUE THREAD

**Issue by prifre** [fyne-io/fyne#1005] opened 2020-05-19 00:41 UTC
Not really sure if the is to be considered a bug or a request for feature... BUT:
The problem is obvious if a larg number of select-items exist. In HTML there is automatic scrolling when items >available windows space. In Fyne, you get stuck.

My code to show the problem:

```go
package main

import (
	"strconv"

	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func makeslicelist(range1 int, range2 int) []string {
	s := []string{}
	for i := range1; i < range2; i++ {
		s = append(s, strconv.Itoa(i))
	}
	return s
}
func main() {
	a := app.NewWithID("")
	w := a.NewWindow("")
	s2 := makeslicelist(0, 100)
	wi := widget.NewSelect(s2, func(s string) {})
	w.SetContent(wi)
	w.ShowAndRun()
}
```

### Describe the solution you'd like to see:

The best would be if the widget automatically checked for what is visible and did scrollig when necessary. Compare with HTML...

**Comment by andydotxyz** [comment] 2020-05-19 10:54
I am pretty sure this is a duplicate of #675 which is being resolved right now for the 1.3 release.

**Closed by andydotxyz** 2020-05-19 10:54 UTC
