### ISSUE TITLE
size hint of all the layouts

### ISSUE THREAD

**Issue by hussam132** [fyne-io/fyne#701] opened 2020-02-24 08:34 UTC
Hi I'm a new in a fine and go a start with A Tour of Fyne and I learned how to make layout 
but it's possible to use size hint and position hint with all the layout on Fyne ?
also with the widgets ??

**Comment by andydotxyz** [comment] 2020-02-24 09:09
I’m not sure what the question is here - can you try to explain what you are trying to achieve?

**Comment by hussam132** [comment] 2020-02-24 10:39
> I’m not sure what the question is here - can you try to explain what you are trying to achieve?

I mean to a layout for example it takes 75% of the Hight and 30% of the width 
and the position will be at 35% from the right side of the screen and 40% above the top side of the screen and all the percentage value is relative to full screen size I mean I don't want to make the size and the position in any unit

**Comment by andydotxyz** [comment] 2020-02-24 22:41
I see. We don't currently have a builtin layout that does this. The FixedGrid is fixed to DPs, as you say - GridLayout is the closest, but it equally spaces all columns.

Perhaps this is a duplicate of #47 or #4?
You can always add your own layout algorithm to do this and pass it to the Container. They are pretty trivial :)

**Comment by hussam132** [comment] 2020-02-25 06:28
but the size hint and the position hint is effective when you change the size of the screen I really hope this property added to fyne in the next version

**Comment by andydotxyz** [comment] 2020-02-25 09:18
All layouts respond to changes in screen size - that is why they exist as algorithms (see the `layout` package). The only layout that may seem "fixed" is the FixedGrid - this aims to keep contents a consistent size so when the layout grows it can have more items in each row (think of icon view in a file manager?).

If this doesn't make sense I would recommend running fyne_demo and going to the "Windows" tab - on the right hand side you can see how some of the builtin layouts work.

**Comment by hussam132** [comment] 2020-02-26 09:07
but what about the position for example I want to a Boxlayout to take the top10% of the screen 
and anthers boxlayout to take the 20% button side of the screen and a gridlayout to take the rest area in the screen ??
@andydotxyz

**Comment by andydotxyz** [comment] 2020-02-26 09:42
Indeed we do not have percentage based layouts in the core library, but that does not mean that what exists is all static (maybe I misread your message).

For me the questions is what is the percentage based layout aiming to acheive? Mostly we pack widgets and layout the UI based on the required space. I'm not against the idea, I just would like to learn more as getting these APIs right is complex :)

**Comment by hussam132** [comment] 2020-02-26 10:04
can you please give me a simple example for a screen that contain to gridlayout with two different size 
this example may answer some of my question ??
@andydotxyz

**Comment by andydotxyz** [comment] 2020-02-26 12:19
I cannot provide such an example because our GridLayout is designed specifically to provide an even grid.

Combining multiple containers with different layouts can provide advanced results, BorderLayout is popular to keep supporting content minimised to sides whilst the centre expands, for example.

There is nothing to stop anyone using a custom layout too, if your app has specific requirements (like our Solitaire example).

**Comment by hussam132** [comment] 2020-02-26 19:59
1)the idea for border layout is very good but what If I want to make layout that's contain a different size of buttons and labels what should I do ?
2)I'm developing GUI apps using python and kivy and the size hint and the position hint property is very effective and faster and can decrease the code length I hope see this property in fyne soon in the future

**Comment by andydotxyz** [comment] 2020-02-26 20:46
I appreciate your point, and agree that what you describe cannot currently be done.
What I am trying to ask is for the bigger picture of what you are trying to build and so how such a layout feature would be useful.
The reason for this request is that Fyne does not add features based on what other toolkits do, but based on the use-case and enabling the desired outcome. The more information you can provide the more likely we are to understand the requirements and therefore consider adding the appropriate functionality.

**Comment by hussam132** [comment] 2020-03-06 16:41
after a lot of thinking about the layout of the fyne I can say that any design with fyne layout will give a uniform arrangement of the widget but what if some one want to design nonuniform and that's why I think the size hint and the position hint it's very important in case you want to get the same design in different size of screens  specially with the GUI Kit that design to make apps for mobiles and desktops I hopes my idea is clear now

**Comment by andydotxyz** [comment] 2020-03-07 14:28
Can you expand what “nonuniform” means, or how the available layouts don’t work on mobile? If you look at fyne_demo and how it runs on desktop and on mobile you should see how our containers adapt.

I don’t quite understand what functionality you think we are missing. Also if you want a custom layout you can provide your own (but if we are missing an important feature obviously we should address it)

**Comment by andydotxyz** [comment] 2020-03-13 13:01
> the idea for border layout is very good but what If I want to make layout that's contain a different size of buttons and labels what should I do ?

I just re-read this and I think there is a simpler answer.
Fyne layouts are all based on packing in widgets at their min-size or larger, depending on the type of layout.
Therefore if you want to have larger buttons or labels then simply make them larger - the layout will adapt.

What we have no support for yet is a layout that props widgets up to % of screen size.
I'm going to close this as a duplicate of #47 as that layout would satisfy this request rather than adding hints to widgets that all layouts must support.

**Closed by andydotxyz** 2020-03-13 13:01 UTC
Labels: question
