### ISSUE TITLE
demo.fyne.io has performence issure

### ISSUE THREAD

**Issue by Bmixo** [fyne-io/fyne#4641] opened 2024-02-15 18:19 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

demo.fyne.io has performence issure

### Describe the solution you'd like to see.

improve the wasm performence

**Comment by dweymouth** [comment] 2024-02-15 18:34
Possible duplicate of https://github.com/fyne-io/fyne/issues/2803

**Closed** 2024-02-15 18:36 UTC
