### ISSUE TITLE
how tu change button color in text

### ISSUE THREAD

**Issue by junmaqiang** [fyne-io/fyne#2822] opened 2022-03-05 12:48 UTC
btn := widget.NewButton("立即安装", func() {}
btn.Importance = widget.HighImportance

![WX20220305-203926](https://user-images.githubusercontent.com/1819457/156883724-b0e4a4f5-cddd-454f-b3fd-c06e01cd4106.png)

 i want to change  this color White

**Comment by junmaqiang** [comment] 2022-03-05 12:52
![WX20220305-203926](https://user-images.githubusercontent.com/1819457/156883896-0a0bb232-7202-427a-82bf-cd75fe81fcf5.png)

**Comment by andydotxyz** [comment] 2022-03-06 14:18
This is a duplicate of #2469

**Closed by andydotxyz** 2022-03-06 14:18 UTC
