### ISSUE TITLE
customize the Label of the Quit option of MainMenu?

### ISSUE THREAD

**Issue by medivh-jay** [fyne-io/fyne#1871] opened 2021-01-27 03:17 UTC
Hello, because my mother tongue is not English, but the default in the code when there is no Quit option in MainMenu will automatically add Quit option, but Label can only be English, can you customize the text of this Label to other languages?
Thank you very much!

**Comment by andydotxyz** [comment] 2021-01-27 10:14
The correct solution this is for us to support internationalisation (planned for 3.0 at the moment).
This is a duplicate of #602 and there is a workaround in there that might help.

**Closed by andydotxyz** 2021-01-27 10:14 UTC
