### ISSUE TITLE
Check menu render chaos

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2797] opened 2022-02-20 13:11 UTC
### Describe the bug:
I use the check menu in my application, but if I set the menu.Checked to false, when I click it, the menu will display a chaotic state, and if I set it to true, it will be normal. However, in my scenario, the initialization of this menu option is likely to be false, so the state of this menu will always be chaotic

### Screenshots:
Sorry. I can't upload screenshots due to network reasons, 

### To Reproduce:
My sample code is as follows. Did I use it incorrectly? Thank you for your attention
```go
func main() {
	a := app.New()
	w := a.NewWindow("Hello")
	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	fullItem := fyne.NewMenuItem("CheckedMenu", nil)
	// must set true. otherwise it will be chaos
	fullItem.Checked = false
	fullItem.Action = func() {
		if fullItem.Checked {
			fullItem.Checked = false
		} else {
			fullItem.Checked = true
		}
	}
	w.SetMainMenu(fyne.NewMainMenu(
		fyne.NewMenu("Option",
			fullItem,
		),
	))

	w.Resize(fyne.NewSize(800, 600))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **Windows 10** 
 - **19044** 
 - **Go version: 1.17.5** 
 - **Fyne version: 2.1.2**

**Comment by blackfox1983** [comment] 2022-02-20 13:13
This is an example of the chaos one mentioned in this case
![微信图片_20220220210808](https://user-images.githubusercontent.com/6658943/154844260-57d19ba1-fee3-4b72-8f57-f9941bbd710b.png)

And this is the normal one
![微信图片_20220220210812](https://user-images.githubusercontent.com/6658943/154844300-517a5273-9651-456d-8037-b440732ea205.png)

**Comment by andydotxyz** [comment] 2022-02-21 20:58
As with normal widgets you need to call `Refresh()` after setting a property.
We don't currently have a refresh on menu, to apply the changes call `App.SetMainMenu(menu)` again to force the refresh.
I think this is basically a duplicate of #2147.

**Closed** 2022-02-21 20:59 UTC
Labels: duplicate
