### ISSUE TITLE
Failed to decode image for window icon

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#783] opened 2020-03-29 20:36 UTC
### Describe the bug:
Flakey test in Fyne test suite:
```
2020/03/29 13:33:08 Fyne error:  Failed to decode image for window icon
2020/03/29 13:33:08   Cause: image: unknown format
2020/03/29 13:33:08   At: /Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:215
--- FAIL: TestWindow_Focus (0.13s)
    window_test.go:726: 
        	Error Trace:	window_test.go:726
        	Error:      	Not equal: 
        	            	expected: "abcd"
        	            	actual  : "bcd"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-abcd
        	            	+bcd
        	Test:       	TestWindow_Focus
FAIL
FAIL	fyne.io/fyne/internal/driver/glfw	5.338s
```

### To Reproduce:
Steps to reproduce the behaviour:
1. go test -count=1 fyne.io/fyne/... (may need to run tests multiple times)

### Screenshots:
N/A

### Example code:
N/A

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.15.4 (Catalina)
 - Go version: go1.13.8 darwin/amd64
 - Fyne version: develop/a85639c2c5ffba3cbaf962a156b5961b3f3349d4

**Comment by andydotxyz** [comment] 2020-04-06 15:14
I think this is actually 2 separate test failures in one report... both need fixed

**Comment by jkvatne** [comment] 2020-05-25 09:09
The second failure can be fixed by inserting the following line at windwo_test.go:753
```
	w.waitForEvents()
```
The problem is that the w.charInput() call just queues the characters, but w.keyPressed() handles the tab imediately. The result depends on how many characters are queued before they are processed. For some reason, on windows, the 'a' is processed first, then the Tab (which clears the buffer) and then the 'bcd' giving an entry content of 'bcd' instead of 'abcd'.

**Comment by andydotxyz** [comment] 2020-05-25 10:25
Thanks @jkvatne that is a fair point. However I worry that it would be hiding an underlying issue.
I don't think we should alter a test to pass like this - we are simulating key presses so if the event handling is incorrect that probably needs corrected in the main code to avoid it happening when a user actually types those keys?

**Comment by jkvatne** [comment] 2020-05-26 07:01
I agree. But what is realy frustrating is that yesterday the test failed every time, and today it never fails. The only change I know about is that I installed Windows Subsystem for Linux with Ubuntu on my Windows machine and ran fyne under linux. Suprisingly the graphics worked fine!

**Comment by jkvatne** [comment] 2020-05-26 07:51
The underlying problem is that the call to keyPressed() will mostly call w.queueEvent(), but not for Tabs. They call FocusNext/FocusPrevious directly, bypassing the event queue. This makes it possible for the tabs to be handled before the characters. This behaviour is also possible on a physical keyboard, if the operating system is queueing up a lot of keystrokes.

Passing the FocusNext/Previous calls via w.queueEvent() will solve this problem.

In addition we need to modify charInput so it uses the focused widget at the time of event execution, and not at the time of adding it to the queue. This function seems to be used only by the test program but is located in glfw/window.go. The following modifications works ok (All in internal/driver/glfw/window.go):
```
line 874 :  w.queueEvent(func() {w.canvas.focusMgr.FocusNext(w.canvas.focused)})
line 879 :   w.queueEvent(func() {w.canvas.focusMgr.FocusPrevious(w.canvas.focused)})

ca line 993:
func (w *window) charInput(viewport *glfw.Window, char rune) {
	if w.canvas.Focused() == nil && w.canvas.onTypedRune == nil {
		return
	}
	w.queueEvent(func() {
		focused := w.canvas.Focused()
		if focused != nil {
			focused.TypedRune(char)
		} else if w.canvas.onTypedRune != nil {
			w.canvas.onTypedRune(char)
		}
	})
}
```

**Comment by andydotxyz** [comment] 2020-05-26 08:56
Moving tab handling into the eventQueue has other challenges unfortunately. The code you indicate that would have to change (that saves which was focused input when key is pressed) is designed so that they key presses do go to the correct entry despite tabs being immediate rather than in an event queue.
I suspect there is a subtle bug in there rather than a design flaw.

**Comment by andydotxyz** [comment] 2020-05-29 11:11
@jkvatne I can no longer replicate the focus issue on the 'develop' branch.
Can you please test this and let me know if it is still an issue at your end?

**Comment by andydotxyz** [comment] 2020-06-01 11:41
Not heard back, Travis is not replicating any more, going to close this as fixed.
Please re-open if you see it again on develop or after the 1.3 release.

**Closed by andydotxyz** 2020-06-01 11:41 UTC
Labels: bug, question
