### ISSUE TITLE
When will ttc fonts be supported?

### ISSUE THREAD

**Issue by sh1luo** [fyne-io/fyne#3799] opened 2023-04-08 16:16 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I noticed the previous issues, someone mentioned this problem, and some developers said that they will fix it in the next minor version, but I found that it will still panic directly in version v233

### How to reproduce

```golang
var (
	HmTTf []byte
	//go:embed msyh.ttc
	backup []byte
)

func init() {
	fontPaths, err := findfont.Find("msyh.ttc")
	if err != nil {
		HmTTf = backup
		return
	}

	HmTTf, err = os.ReadFile(fontPaths)
	if err != nil {
		log.Logger.Println(err)
	}
}

```

```golang
func (*CustomerTheme) Font(s fyne.TextStyle) fyne.Resource {
	return fyne.NewStaticResource("font", fonts.HmTTf)
}
```

### Screenshots

2023/04/09 08:17:27 Fyne error: font load error
2023/04/09 08:17:27 Cause: unsupported font format
2023/04/09 08:17:27 At: C:/Users/zhonger/go/pkg/mod/fyne.io/fyne/v2@v2.3.3/internal/painter/font.go:150
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x4ec pc=0x7ff7fd7549e0]

goroutine 1 [running, locked to thread]:
github.com/benoitkugler/textlayout/fonts/truetype.(*Font).Upem(0x1?)
C:/Users/zhonger/go/pkg/mod/github.com/benoitkugler/textlayout@v0.3.0/fonts/truetype/metrics.go:34
github.com/benoitkugler/textlayout/harfbuzz.NewFont({0x7ff7fdf2b078?, 0x0})

### Example code

```golang
var (
	HmTTf []byte
	//go:embed msyh.ttc
	backup []byte
)

func init() {
	fontPaths, err := findfont.Find("msyh.ttc")
	if err != nil {
		HmTTf = backup
		return
	}

	HmTTf, err = os.ReadFile(fontPaths)
	if err != nil {
		log.Logger.Println(err)
	}
}

```

```golang
func (*CustomerTheme) Font(s fyne.TextStyle) fyne.Resource {
	return fyne.NewStaticResource("font", fonts.HmTTf)
}
```

### Fyne version

223

### Go compiler version

1.19+

### Operating system and version

win10

**Comment by Jacalz** [comment] 2023-04-08 19:24
There is likely a better answer (I have not quite read into how the fonts are handled) but I think https://github.com/fyne-io/fyne/issues/3245 will have to be closed before then. It is not currently supported in v2.3.3 as far as I know.

FYI: We appreciate that you opened this issue but I just want to say that we prefer to use discussions for questions and would prefer if you use that next time. The issue tracker is intended for bug reports and feature requests. I think the bug part of might be a duplicate of the issue mentioned above.

**Comment by andydotxyz** [comment] 2023-04-08 22:54
> I noticed the previous issues, someone mentioned this problem, and some developers said that they will fix it in the next minor version

It would be better to follow up on the ticket you found. Which I suspect is the one @Jacalz linked. Opening a new issue to ask about an open one doesn't help us get it done.

**Comment by sh1luo** [comment] 2023-04-09 03:15
i know, thx

**Closed** 2023-04-09 06:59 UTC
Labels: unverified
