### ISSUE TITLE
Extending widgets breaks them in various ways

### ISSUE THREAD

**Issue by scottmayo** [fyne-io/fyne#615] opened 2020-01-14 02:43 UTC
### Describe the bug:

Material for this bug is taken directly from 
https://stackoverflow.com/questions/59691001/failing-at-extending-fynes-widgets

Extending widgets causes them to change behaviour in unexpected ways. The author recently corrected a crash bug in Select, but fixes, maybe similar ones, are needed for other widgets. IN all cases I'm extending the widget to catch TappedSecondary() and making no other changes. 

Symptoms:
- [x] 1: Extending button: Basic widget.Button changes color when the mouse enters the area. The extended version does not. Neither form changes the appearance of the button when clicked (which I'd expect in general from any GUI; this seems to be a significant bug all by itself.)

- [x] 2: Extending Select no longer crashes on left click, but if something from the dropdown is selected, it instead displays (Select one), scrunched into the space the actual selection would have taken. 

- [x] 3: Extending Entry: Left click (to move the cursor) doesn't redraw the cursor in the new location, but the internal cursor position does change (backspace will remove the character at the new position, and then redraw everything correctly). This doesn't seem to happen every time?

- [x] 4: Extending Check: Left-clicking causes OnChanged to be called (and the boolean passed properly alternates each time) but the check mark is never drawn.

Summary: extending a widget seems to cruftify how it is redrawn when there should be no affect on redrawing at all.

Correct behaviour: other than the fact that trapping TappedSecondary takes away the dropdown meny from Entry, nothing visible should change in the behaviour of any widget simply because it was extended. And left clicking a non-extended button should certainly change at least the color of the button between mouse down and mouse up.

### To Reproduce:
Steps to reproduce the behaviour:
Try the attached code and click on the various widgets.

### Example code:

```go
type About struct {
    name string
    value string
}

type HasAbout interface {
    GetAbout() *About
}

//loses reaction to mouse movement
type myButton struct {
    widget.Button
    about *About
}

func (m *myButton) TappedSecondary(*fyne.PointEvent) {
    log.Println("Right Click") //works
}

func (m *myButton) GetAbout() *About {
    return m.about
}

func newMyButton(label string, tapped func()) *myButton {
    ret := &myButton{}
    ret.ExtendBaseWidget(ret)
    ret.Text = label
    ret.OnTapped = tapped

    return ret
}

//panic on left click
type mySelect struct {
    widget.Select
    about *About
}

func (m *mySelect) TappedSecondary(at *fyne.PointEvent) {
    log.Println("Right Click", m.about.name, *at) //works
}

func (m *mySelect) GetAbout() *About {
    return m.about
}

func newMySelect(about *About) *mySelect {
    ret := &mySelect{}

    ret.ExtendBaseWidget(ret)
    ret.about = about
    //widget.Renderer(ret).Layout(ret.MinSize()) //from NewSelect, but did not fix panic
    return ret
}

//must override Tapped, and then all seems well
type myLabel struct {
    widget.Label
    about *About
}

func (m *myLabel) TappedSecondary(at *fyne.PointEvent) {
    log.Println("Right Click Label", m.GetAbout().name, *at)
}
//must also implement this or we don't get TappedSecondary
func (m *myLabel) Tapped(at *fyne.PointEvent) {
}

func (m *myLabel) GetAbout() *About {
    return m.about
}

func newMyLabel(about *About) *myLabel {
    ret := &myLabel{}

    ret.ExtendBaseWidget(ret)
    ret.about = about
    ret.Text = about.value
    return ret
}

//lose the ability to see cursor changes on left click.
//correctly, lose the usual dropdown menu on right click
type myEntry struct {
    widget.Entry
    about *About
}

func (m *myEntry) TappedSecondary(at *fyne.PointEvent) {
    log.Println("Right Click Entry", m.Text, *at)
}

func (m *myEntry) GetAbout() *About {
    return m.about
}

func newMyEntry(about *About) *myEntry {
    ret := &myEntry{}

    ret.ExtendBaseWidget(ret)
    ret.about = about
    return ret
}


//lose the ability to see check changes you made with left click.
type myCheck struct {
    widget.Check
    about *About
}

func (m *myCheck) TappedSecondary(at *fyne.PointEvent) {
    log.Println("Right Click myCheck", m.Text, *at) //works
}


func (m *myCheck) GetAbout() *About {
    return m.about
}

func newMyCheck(about *About) *myCheck {
    ret := &myCheck{}

    ret.ExtendBaseWidget(ret)
    ret.about = about
    ret.Text = about.value
    ret.OnChanged = func(v bool) {fmt.Println("Check is ", v)} //works
    return ret
}

//driver, from original answer, given new tests
func main() {
    about := About{}
    about.name = "hi"
    about.value = "Whee"

    a := app.New()

    w := a.NewWindow("Hello")
    w.SetContent(widget.NewVBox(
            newMyButton("Right tap me", func() {
                    log.Println("Normal callback")
            }),
            newMySelect(&about),
            newMyLabel(&about),
            newMyEntry(&about),
            newMyCheck(&about),
            widget.NewButton("X", func(){}) , //to compare against
        ),
)

    w.ShowAndRun()
}
```
-->

### Device (please complete the following information):
 - Linux Mint 19.1 Cinnamon
 - Cinnamon 4.0.10
 - go version go1.13.5 linux/amd64
 - Fyne version - go get -u fyne.io/fyne as of 13-Jan-2020

**Comment by andydotxyz** [comment] 2020-01-14 22:39
Thanks for this, edited the info a little so we can keep track - numbered the items for reference.

Number 1 should now be fixed on develop.
Number 2 I think is a duplicate of #583 but it is good that this select is easier to reproduce, we can probably fix it more easily now.

3 and 4 probably need the same fix as 1 but it will need to wait for another day.
If you could test and confirm 1 on develop @scottmayo then I can patch it back into master.

**Comment by scottmayo** [comment] 2020-01-14 23:12
Willing to help, but the only way I know how to update fyne is "go get -u fyne.io/fyne". I'm not a git user; brief instructions on how to fetch the the specific branch?

**Comment by andydotxyz** [comment] 2020-01-15 07:47
Thanks very much @scottmayo - you can use `git checkout develop` like so:

    cd $GOROOT/src/fyne.io/fyne
    git checkout develop

Running your application again (assuming you are not using go modules for the test case) and it will use the latest version.

To revert once you're done use `git checkout master`.

**Comment by andydotxyz** [comment] 2020-01-15 18:20
OK, Select, button and check all fixed.
Entry is another beast altogether and will require more investigation.

**Comment by scottmayo** [comment] 2020-01-16 02:54
Additional information: extended Entry doesn't display highlight when a mouse is dragged over text; arrow keys don't show cursor movement, and this might be intentional, but ^A doesn't implement a "select all text" operation.

Also, "git checkout develop" ran silently and I rebuilt my app and reran. Mousing into a button doesn't change color. Select didn't crash but you'd already fixed that on master. git says I'm up to date on branch develop... I feel like I missed something.

Also, how do a get a widget to tell me what text if any is currently selected (highlighted)? I need to find out during my overriden TappedSecondary.

**Comment by andydotxyz** [comment] 2020-01-16 08:42
Thanks for the added info. The selection issue and missing command keys (notice ctrl-x etc don't work either) all seem to be part of the same bug.

It is strange that updating didn't fix your issue. Is this the same small code snippet you pasted above?
I had assumed you were not using modules - if you are (go.mod etc) then you will need different instructions. If so then update the version number in your go.mod file to "5c9027b" (the commit SHA of the last fix) and re-run your build process.

**Comment by andydotxyz** [comment] 2020-01-16 15:37
Oh, also develop has a "SelectedText()" function on Entry.
It was added recently so you will know that you have the right version of Fyne if that function can be found :)

**Comment by scottmayo** [comment] 2020-01-16 22:09
So this is interesting. In ~/go/src/fyne.io/fyne I do git checkout develop
 and I get told 
Already on 'develop'
Your branch is up to date with 'origin/develop'.
I also notice that an annoying compile time warning about some internal misuse of sprintf is gone.
But now I get
w.SelectedText undefined (type *widget.Entry has no field or method SelectedText)
which aligns with the belief that I don't have the right stuff.

**Comment by andydotxyz** [comment] 2020-01-16 23:38
Then I guess either you are using go modules or have a vendor folder?

**Comment by scottmayo** [comment] 2020-01-16 23:41
Since I don’t know what those are, I doubt it. But as this is my first Go project I could believe something is wrong.

**Comment by andydotxyz** [comment] 2020-01-17 00:07
Is there any way you could share your code or a directory listing? It’s a bit difficult to figure out what might be going on otherwise.

**Comment by andydotxyz** [comment] 2020-01-17 08:09
In ~/go/src/fyne.io/fyne please type `git checkout develop` again (just in case) and then `git pull` to ensure it's the latest version of develop.
Then let us know how it goes.
It would be better if you test with the code you posted above first - as I know that works here.
Trying to eliminate a few variables :).

**Comment by scottmayo** [comment] 2020-01-17 17:08
"git pull" did the trick. Was I supposed to know that before?

Buttons now properly change color when mousing in.

Checkboxes don't change when clicked "on", until the mouse is moved 
again, however slightly (ie, no need to move the pointer entirely out of 
the box). On the other hand, clicking them "off" repaints immediately, 
with no need to move the mouse. That sort of inconsistency makes me less 
confident in the fix.

Select no longer scrunches the newly selected text into the width of the 
former text.


I'm likely to abandon this effort. The more I use Go the more annoyed I 
get by the little inconsistencies in the language, as well as the lack 
of real OO. And while I think Fyne has promise, it's clearly immature 
and shaky, and the fact that backgrounds won't ever be controllable is a 
dealbreaker. I paid for these pixels and I get to decide what color they 
are.

You're to be commended for promising that Fyne will someday be fully 
thread safe; my number one beef with GUI coding is that so many 
libraries demand you funnel everything into a single thread, which makes 
network-responsive applications a pain to develop. That promise is what 
originally sold me on Fyne and hence Go.  I once wrote a thread-safe GUI 
library (not a portable one) and I have some idea how carefully the 
coding has to be done. I think you have a long haul to get there - the 
moment I saw SetText had no lock and there wasn't even a GetText to do 
the necessary matching lock, I knew thread safety wasn't the primary 
design goal, and it's a hard thing to add after the fact. But if you 
manage it I think you'll get flocks of GUI developers looking at Fyne. 
Many of them won't be as demanding as I am.

**Comment by andydotxyz** [comment] 2020-01-17 18:28
Sorry I didn't think that `git pull` was needed but it clearly was, oops.
I cannot replicate the checkbox for some reason, but it may because I have a change locally which I need  to finish working through first.
Entry is now extending properly thankfully - it was some strange legacy code that was managing to load a secondary renderer in memory that didn't get displayed. Glad to have got to the bottom of it, thanks for the help.

**Comment by andydotxyz** [comment] 2020-01-17 22:20
This is all fixed on develop now, If you can confirm that would be great. 
I'll get this backported to the next 1.2.x point release.

**Closed by andydotxyz** 2020-01-17 22:20 UTC
