### ISSUE TITLE
MenuEncoding Error

### ISSUE THREAD

**Issue by rffanlab** [fyne-io/fyne#368] opened 2019-07-25 08:03 UTC
Code Below 
```golang
hugeLogViewer := app.New()
	w := hugeLogViewer.NewWindow("大文件日志打开器")
	w.SetMainMenu(
		fyne.NewMainMenu(
			fyne.NewMenu("文件",fyne.NewMenuItem("打开", func() {
				fmt.Println("点击了打开文件")
			})),
			))
	w.ShowAndRun()
```
the title show currectly.
But menu shows wrong encodeing.

**Comment by andydotxyz** [comment] 2019-07-25 10:30
Can you confirm which operating system you are using and possibly add a screenshot? The menus are one of the few operating system specific parts of the toolkit.

**Comment by rffanlab** [comment] 2019-07-25 10:33
@andydotxyz 
Microsoft Windows 10.0.17763 Build 17763
go version go1.12.6 windows/amd64

**Comment by andydotxyz** [comment] 2019-07-25 14:36
I’m pretty sure this is a duplicate of #63. Does setting FYNE_FONT to a Chinese ttf file fix things for you?

We need to find a better solution but this should work in the meantime

**Comment by rffanlab** [comment] 2019-07-26 08:42
Not work for me .I've set FYNE_FONT system var to my msyh.ttc ,and rebuild it error still exist.

**Comment by rffanlab** [comment] 2019-07-26 08:48
@andydotxyz should I set it in my golang code? not system var?

**Comment by rffanlab** [comment] 2019-07-26 08:49
besides could I develop encoding?

**Comment by andydotxyz** [comment] 2019-07-26 14:08
The font is loaded at runtime not during compile. Did you set it to the full path? If the file could not be loaded then the app should log an error to the command line. I am pretty sure it’s not an encoding issue but a problem with not bundling all languages in our font. If you know of a good font set that is free and combines all languages we could consider it - but file size may be an issue.

I was considering adding language selection to the upcoming fyne_settings tool that could download additional language packs, maybe that would work?

**Comment by rffanlab** [comment] 2019-07-26 14:15
File is set full path.No error show during compiling and running. 
Here is free chinese Font.
[FreeChineseFont](http://archive.cdn.fonts.net.cn/font-37732-190726065720.zip?response-content-disposition=attachment%3Bfilename%3D%22Taipei-Sans-TC-Beta-Light.zip%22&auth_key=1564150910-5d3b0a26098ef6x00320568-0-4362563df94e5a401382e6deed40c543).

**Comment by andydotxyz** [comment] 2019-07-26 14:19
Perhaps I am misunderstanding - can you provide a screenshot please?

**Comment by rffanlab** [comment] 2019-07-26 14:23
![screenshot](https://www.rffan.com/img.png) 
above is screenshot

**Comment by rffanlab** [comment] 2019-07-26 14:24
github eat my pic,just open the link.

**Comment by andydotxyz** [comment] 2019-07-26 14:33
That is what I had thought... and can you share the full environment variable you set please?

**Comment by rffanlab** [comment] 2019-07-26 14:37
[var](https://www.rffan.com/img2.png)
all var shows in img

**Comment by andydotxyz** [comment] 2019-07-26 14:41
Did you re-open your compiler (command line / IDE) after setting the variable?

**Comment by rffanlab** [comment] 2019-07-26 14:42
Tried reboot.

**Comment by rffanlab** [comment] 2019-07-26 14:44
I tried use cmd to compile ,it worked.... goland does not reload the env.......

**Comment by rffanlab** [comment] 2019-07-26 14:45
when could i haven't to add this env var?

**Comment by andydotxyz** [comment] 2019-07-29 21:09
Sorry I don't understand this last question.
GoLand has it's own build environment variables you can select "Edit Configurations" from the run dropdown.

Does your response mean that this issue is resolved?

**Comment by andydotxyz** [comment] 2019-08-07 08:39
Closing as this seems to be resolved except the GoLand configuration question.

**Closed by andydotxyz** 2019-08-07 08:39 UTC
