### ISSUE TITLE
Ability to add an "Action button" on an Accordion title

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3852] opened 2023-05-01 12:44 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I came accross a situation when I want to do some action (Button Tap) related to the content of an Accordion Item without expanding the Accordion Item.

It would be nice to have some Button or Toolbar on the trailing side of the Accordion header.

### Is it possible to construct a solution with the existing API?

Not really.

### Describe the solution you'd like to see.

```go
type AccordionItem struct {
	Title  string
	ActionItem fyne.CanvasObject
	Detail fyne.CanvasObject
	Open   bool
}
```

**Comment by andydotxyz** [comment] 2023-05-01 18:24
This looks like a duplicate of #3363, would that be right?

**Comment by matwachich** [comment] 2023-05-01 18:39
Yes totally!

Seems like my search skills are lacking... Sorry

Le lun. 1 mai 2023 à 19:24, Andy Williams ***@***.***> a
écrit :

**Closed** 2023-05-01 19:46 UTC
