### ISSUE TITLE
Fix ImageFromReader(), doesn't render text in from file.svg

### ISSUE THREAD

**Issue by DarkReduX** [fyne-io/fyne#2606] opened 2021-11-02 08:29 UTC
### Describe the bug:
canvas.NewImageFromReader(f, f.Name()) using svg file, doesn't render text

### To Reproduce:
Steps to reproduce the behaviour:
`	golang
width := 500
	height := 500

	f, _ := os.Create("p.svg")
	s := svg.New(f)
	s.Start(width, height)
	s.Circle(width/2, height/2, 100)
	s.Text(width/2, height/2, "Hello, SVGS", "text-anchor:middle;font-size:30px;fill:red")
	s.End()

	f, _= os.Open("p.svg")
	img := canvas.NewImageFromReader(f, f.Name())

	return container.NewMax(img)`

### Screenshots:
![image](https://user-images.githubusercontent.com/57458347/139811549-1f0cf3d3-037f-4b25-9ee2-4bcf1bd155a4.png)
![image](https://user-images.githubusercontent.com/57458347/139811612-125ced08-13e8-4e4b-aaab-122d2f820f66.png)

### Device (please complete the following information):
 - **OS:** Linux, MacOS or iOS]
 - **Version:**20.04
 - **Go version:** v1.17.2
 -  **Fyne version:** v2.1.1

**Comment by Jacalz** [comment] 2021-11-02 10:33
This is not a bug with `.NewImageFromReader()`, it is a bug with the SVG implementation. I'll close this as a duplicate of https://github.com/fyne-io/fyne/issues/685.

**Closed by Jacalz** 2021-11-02 10:33 UTC
Labels: unverified
