### ISSUE TITLE
Unreliable Behaviour when `app.New()` is run twice

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1595] opened 2020-11-22 02:17 UTC
### Describe the bug:

Pressing `MainMenu -> menu[0] -> Quit` does nothing.

### To Reproduce:

1) Make a fyne app with a MainMenu (Quit item automatically added)
1) Update to the latest verison
1) Quit no longer works

### Example code:

```go
	w := a.NewWindow("Window w/ Menu")
	w.SetMainMenu(fyne.NewMainMenu(
		fyne.NewMenu("File",
			fyne.NewMenuItem("Check for Updates", func() { fmt.Println("Check for Updates") }),
			fyne.NewMenuItem("Settings", func() { fmt.Println("Settings") }),
		),
	))

	w.Resize(fyne.NewSize(420, 360))
	w.CenterOnScreen()
	w.Show()
```

### Device:

- OS: Fedora Linux
- Version: 33
- Go version: 1.15.2
- Fyne version: 1.4.1

**Comment by AlbinoGeek** [comment] 2020-11-22 02:48
Okay, I am not able to reproduce this issue in `cmd/fyne_demo` -- so now I'm rather confused as to what I broke :/

**Comment by AlbinoGeek** [comment] 2020-11-22 02:58
Alright, narrowed this down to some auto-complete code that ran `app.New()` a second time.

**Comment by andydotxyz** [comment] 2020-11-22 09:57
Aha, so no Quit issues either? phew :).
Yes we only support 1 running Fyne app at a time, it is a restriction of the current architecture.
`fyne.CurrentApp()` would not be possible without this.

There is, however, an issue that it could be tidied - marking duplicate of #639

**Closed by andydotxyz** 2020-11-22 09:57 UTC
