### ISSUE TITLE
the input method cannot follow with the cursor.

### ISSUE THREAD

**Issue by 93Alliance** [fyne-io/fyne#3884] opened 2023-05-11 11:49 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When you type characters in an entry widget, the input method cannot follow with the cursor.

### How to reproduce

1. use Entry widget
2. input chinese

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/33192459/d3b734c1-6f20-4cb8-9acd-eaf3128f667d)

### Example code

```go
entry := widget.NewMultiLineEntry()
```

### Fyne version

2.3.4

### Go compiler version

1.18

### Operating system and version

windows 11

**Comment by andydotxyz** [comment] 2023-05-12 21:56
This looks like a duplicate of #618

**Closed by andydotxyz** 2023-05-12 21:56 UTC
Labels: unverified
