### ISSUE TITLE
Warnings when building on Ubuntu

### ISSUE THREAD

**Issue by tegk** [fyne-io/fyne#365] opened 2019-07-18 14:34 UTC
System: Ubuntu 19.04 

```# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:24:
../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:867,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by andydotxyz** [comment] 2019-07-18 22:00
Can you confirm if this is the latest version of Fyne?
Additionally can you please confirm that the build fails? From this output it looks like it could be just warnings..?

**Comment by tegk** [comment] 2019-07-19 12:14
using v1.1 and building the example with go build

**Comment by andydotxyz** [comment] 2019-07-22 10:12
Thanks for confirming - I am glad they're just warnings. This should be fixed when we upgrade the GLFW library which does not currently have a release schedule.
Pretty sure this is a duplicate of #221 now.

**Closed by andydotxyz** 2019-07-22 10:12 UTC
