### ISSUE TITLE
If I want to make one, does the widget.richtext support the function of dragging and dropping selected text with the mouse?

### ISSUE THREAD

**Issue by wonderfulLand** [fyne-io/fyne#5091] opened 2024-08-25 01:09 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

no

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see.

The text content in widget.richtext supports mouse selection and copying

**Comment by andydotxyz** [comment] 2024-08-28 18:50
Fyne has interactive text (which can be selected, copied etc) and static text widgets.

Entry is interactive but Label and RichText are not interactive widgets.

**Comment by andydotxyz** [comment] 2024-09-04 10:27
I think this question was answered, closing as duplicate of #21

**Closed by andydotxyz** 2024-09-04 10:27 UTC
