### ISSUE TITLE
Resizing window sometimes leads to segmentation violation on darwin/arm64

### ISSUE THREAD

**Issue by justmax437** [fyne-io/fyne#2295] opened 2021-06-21 21:20 UTC
### Describe the bug:
On Apple Silicon running macOS 11.4 any change in at least master window dimensions randomly leads to this:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x182e5b240]
```

Full stack trace is [here](https://pastebin.com/kBY1LryE)

### To Reproduce:
Create a window like this:
```go
MainWindow = App.NewWindow("AppName")
	MainWindow.SetFixedSize(false)
	MainWindow.SetMaster()
	MainWindow.SetPadded(true)
	MainWindow.Resize(fyne.Size{
		Width:  500,
		Height: 0,
	})
	MainWindow.CenterOnScreen()
```
Add some widgets to it and interact with them. (not sure if this nessesary, but i was able to reproduce it faster after clicking a button that has empty OnClick). Then double-click window header or resize it manually, program will panic at seemingly random moment when you do so.

### Example code:
Window contents if this helps
```go
widget.NewForm(
		&widget.FormItem{
			Text:     "Logins",
			Widget:   widget.NewButtonWithIcon("Select", theme.FileTextIcon(), func() {
				d := dialog.NewFileOpen(func(reader fyne.URIReadCloser, err error) {
					if reader == nil {
						return
					}
					defer reader.Close()
					if usersFile, err := io.ReadAll(reader); err == nil {
						splits := bytes.Split(usersFile, []byte(","))
						Usernames = make([]string, len(splits))
						for i := range splits {
							Usernames[i] = string(splits[i])
						}
					}
				}, MainWindow)
				d.Show()
			}),
	
		},
		&widget.FormItem{
			Text:     "Target",
			Widget:   widget.NewEntryWithData(Target),
		},
		&widget.FormItem{
			Text:     "Latency",
			Widget:   widget.NewEntryWithData(Latency),
		},
		&widget.FormItem{
			Text:     "Test",
			Widget:   widget.NewButton("Test", func() {
				
			}),
		},
	)

	form.SubmitText = "Submit"
	form.OnSubmit = func() {
		go worker()
	}
```
-->

### Device (please complete the following information):
M1 Macbook Air
 - **OS:** macOS
 - **Version:** 11.4 Big Sur
 - **Go version:** 1.16.5
 - **Fyne version:** 2.0.3

**Comment by andydotxyz** [comment] 2021-06-22 14:34
I think this may be a duplicate of #2188

**Comment by justmax437** [comment] 2021-06-22 14:45
Looks pretty similar, yes. Shall I close this issue and move to 2188?

**Comment by andydotxyz** [comment] 2021-06-22 14:46
Thanks, I think that would be best

**Closed** 2021-06-22 14:53 UTC
Labels: unverified
