### ISSUE TITLE
build error on mac<>

### ISSUE THREAD

**Issue by qshuai** [fyne-io/fyne#867] opened 2020-04-15 13:33 UTC
### Describe the bug:

cd $GOPATH/fyne.io/fyne/cmd/fyne_demo
go build error

the error detail is the following:
In file included from ../../../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/c_glfw_darwin.go:8:
../../../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/glfw/src/cocoa_window.m:989:9: warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionViewCompositionalLayout.h:601:19: note: using
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:312:1: note: also found
# fyne.io/fyne/internal/driver/glfw
../../internal/driver/glfw/gl_darwinfix.go:10:5: warning: 'NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:184:12: note: 'NSOpenGLContext' has been explicitly marked deprecated here

### To Reproduce:
Steps to reproduce the behaviour:

### Device (please complete the following information):
 - OS: [e.g. Linux, MacOS or iOS]
      Model Name: MacBook Pro
      Model Identifier: MacBookPro14,1
      Processor Name: Dual-Core Intel Core i5
      Processor Speed: 2.3 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Hyper-Threading Technology: Enabled
      Memory: 8 GB
      Boot ROM Version: 205.0.0.0.0
      SMC Version (system): 2.43f7
      Serial Number (system): FVFYP296HV22
      Hardware UUID: 05B94C31-3C41-58BD-9587-414558CA052A

 - Version: [e.g. 22]
 - Go version: [e.g. 1.12.3]
go version go1.13.5 darwin/amd64
 - Fyne version: [e.g. 1.2.0 or git SHA]
latest

**Comment by andydotxyz** [comment] 2020-04-15 16:52
These are not errors, they are warnings.
They have been resolved internally and will go away with 1.3 release.

Duplicate of #310

**Closed** 2020-04-15 16:53 UTC
Labels: duplicate
