### ISSUE TITLE
Keyboard is often too sensitive (press event trigger twice) on Android release

### ISSUE THREAD

**Issue by sorainnosia** [fyne-io/fyne#1357] opened 2020-10-04 03:50 UTC
### Describe the bug:
This happen on Android release. Below is the apk
https://github.com/sorainnosia/4DPredictorGo/releases/tag/1.2

Extract 4D_Analysis.apk.zip install it on Huawei devices (P30 Pro)

### To Reproduce:
Then go to DataSet tab
1. Click on DataSet Name Entry
2. type "top3" and the 3 will be triggered twice and turn to become "top33"

### Screenshots:
No screenshot, but can find my source code in https://github.com/sorainnosia/4DPredictorGo/tree/main/src

### Example code:
No code example, it happens on UI and keyboard

### Device (please complete the following information):
 - OS: Android
 - Version: 10 
 - Go version: 1.13
 - Fyne version: 1.2

**Comment by andydotxyz** [comment] 2020-10-04 08:24
Are you using the google keyboard? It sounds like a duplicate of #1256

**Comment by andydotxyz** [comment] 2020-11-17 19:11
Closing as duplicate

**Closed by andydotxyz** 2020-11-17 19:11 UTC
Labels: duplicate, question
