### ISSUE TITLE
lifecycle.Event functions

### ISSUE THREAD

**Issue by MatejMagat305** [fyne-io/fyne#2380] opened 2021-08-15 21:25 UTC
I'm sorry if it already exist, but I do'nt found it...
I was interasting in your implementation and I was found that
`(mobileDriver).onStart()` and `(mobileDriver).onStop()` <br>in `fyne/internal/driver/gomobile/driver.go` are empty and I do'nt know why, because it is simple to do it with current API(I think wihout effect to pefformance or simplicity):
I sugest <br>`struct{
Onstart: func()
OnQuit: func()
}` <br>and two small functions: <br>`SetOnStart(fn func())` and `SetOnQuit(fn func())` <br> 
because mainly in Android it is usefull for save data or load.... in case you allow me I will be able do this change in my fork

**Comment by andydotxyz** [comment] 2021-08-16 12:12
There is a lifecycle API in the not-yet-released v2.1, you can find it on the `develop` branch.
https://github.com/fyne-io/fyne/blob/5304bfac74439bc5ee8ed2fc61922c167270bc34/app.go#L90

It is accessed from `App.Lifecycle()`

**Comment by andydotxyz** [comment] 2021-08-16 12:12
Closing as duplicate of #2236

**Closed by andydotxyz** 2021-08-16 12:12 UTC
