### ISSUE TITLE
Possible to get a native file chooser

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#458] opened 2019-09-22 16:42 UTC
I am sorry if this feature already exists, but I couldn’t find it when looking through the godoc reference. Using gtk with Gotk3 there is a widget for a FileChooserButton that lets the user choose a file, folder and such. This is really useful and powerful when needing simple file handling, would it be possible to have that support here?

My use case in gotk3 is that I have the button set for choosing a file and then I use a method for the created variable to get the whole path for that file to then pass in to a os.Open call.

**Comment by celer** [comment] 2019-09-22 16:58
You might want to check out: https://github.com/sqweek/dialog

**Comment by Jacalz** [comment] 2019-09-22 17:05
Thanks @celer that seems like it might do the trick for me until there is proper support in fyne 🙂

**Comment by okratitan** [comment] 2019-09-23 13:35
This is a feature that is coming.  We have plans to finish a data API soon and that will come with widgets such as lists that are cached for performance.  We also have plans to have file mimetype support and icons.  With that - we will easily be able to provide a file chooser dialog.

**Comment by andydotxyz** [comment] 2019-09-24 03:31
Yes, I think this is a duplicate of #225

**Closed by andydotxyz** 2019-09-24 03:31 UTC

**Comment by Julien2313** [comment] 2020-04-28 10:35
I think that this is a different thing. I'd like to choose a directory, to get the path, so I can open multiple files in this directory. My only solution is to ask the user to pick 1 file in the directory, so I can pick all the others
