### ISSUE TITLE
Can you implement a port that can display same ui by remote webbrowser

### ISSUE THREAD

**Issue by runsys** [fyne-io/fyne#2342] opened 2021-07-28 11:38 UTC
Can you implement a port that can display same ui by remote webbrowser

**Comment by andydotxyz** [comment] 2021-07-28 11:54
Is this a duplicate of the request for a driver to display a Fyne app? #1646

**Comment by Jacalz** [comment] 2021-08-04 15:20
This looks very much like a duplicate issue requesting html/css support for showing websites inside the ui. It is also an invalid feature request as it doesn't use the issue templates.

**Comment by andydotxyz** [comment] 2021-08-04 15:47
Not convinced they want to show a website inside the UI - I think they want the UI inside a website...

**Comment by andydotxyz** [comment] 2021-10-30 22:33
It’s a duplicate of one or the other :) and no update so closing

**Closed by andydotxyz** 2021-10-30 22:33 UTC
