### ISSUE TITLE
我想把日志滚动输出到屏幕上，有什么好的方法吗

### ISSUE THREAD

**Issue by xbc563771383** [fyne-io/fyne#2009] opened 2021-02-23 06:49 UTC

**Comment by andydotxyz** [comment] 2021-02-23 09:12
Google translate: 

I want to scroll the log output to the screen, is there any good way

**Comment by andydotxyz** [comment] 2021-02-23 09:13
We don't have an "auto scroll" widget - but you can use a `VBox` of `Label` widgets, inside a `container.Scroll` and when you add new elements you can call `Scroll.ScrollToBottom()`.

**Comment by andydotxyz** [comment] 2021-02-23 11:49
Closing as duplicate of the English version #2010

**Closed by andydotxyz** 2021-02-23 11:49 UTC
Labels: bug
