### ISSUE TITLE
a customizable window title bar

### ISSUE THREAD

**Issue by jerryan1** [fyne-io/fyne#5246] opened 2024-11-08 12:14 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Hello, could you consider providing a customizable window title bar? When creating windows, it should be possible to display and hide it, as well as make it full-screen or minimize it  Both the minimized and maximized states can be hidden 

### Describe the solution you'd like to see.

The title bar of the project I'm currently working on looks ugly and cannot be customized in terms of style. The minimize and maximize buttons are only grayed out, which greatly affects the overall UI style

**Comment by jerryan1** [comment] 2024-11-11 05:44
Thank you very much for your reply, but the current version 2.5.2 does not have the 'decorate' property set when creating a window in the windows.go file, nor does it provide a method to hide the title bar

**Comment by andydotxyz** [comment] 2024-11-11 07:01
It's a Splash window and it's been in for a few years.

The feature is desktop only so appears on a different interface:

```go

if drv, ok := fyne.CurrentApp().Driver().(desktop.Driver); ok {
        w := drv.CreateSplashWindow()
        w.SetContent(widget.NewLabel("Hello World"))
        w.Show()
    }
```

Closing now as dupe of #2175

**Closed** 2024-11-11 07:02 UTC
