### ISSUE TITLE
TextGrid makes the application extremely slow

### ISSUE THREAD

**Issue by wenhsinhsieh** [fyne-io/fyne#1486] opened 2020-10-29 06:41 UTC
### Describe the bug:
A TextGrid with multiple lines of string in it makes the application extremely slow. No matter put in the text with NewTextGridFromString initially or use SetText to set the content later, once the text is set, the application takes seconds to response. Adding more line makes it worse.

### To Reproduce:
Steps to reproduce the behaviour:
In the Fyne_demo project, makeTextGrid() function in widget.go, add more line to the parameter of widget.NewTextGridFromString() (maybe 10 lines or more). Compile and run. 

### Screenshots:
For example, it takes more than a second to maximize the window, which allows me to capture a screenshot like this:
![slow](https://user-images.githubusercontent.com/3656867/97533929-192c9980-19f4-11eb-9917-d572219f9cbd.png)

### Example code:
in widget.go:
`func makeTextGrid() *widget.TextGrid {
	grid := widget.NewTextGridFromString("TextGrid\n  Content\nZebra\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\nbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\ncccccccccccccccccccccccccccccccccccccccccccc\ndddddddddddddddddddddddddddddddddddddddd\neeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\nffffffffffffffffffffffffffffffffffff\nggggggggggggggggggggggggggggggggggggggggggg\n")
......`

### Device (please complete the following information):
 - OS: Windows
 - Version: 10
 - Go version: 1.14.6
 - Fyne version: 1.3.3

**Comment by andydotxyz** [comment] 2020-10-29 17:18
There were some big improvements in TextGrid in the pending 1.4 release, hopefully this should be resolved.
Closing as duplicate of a previous issue #1142

**Closed by andydotxyz** 2020-10-29 17:18 UTC
