### ISSUE TITLE
FileDialog: select multiple files

### ISSUE THREAD

**Issue by noerw** [fyne-io/fyne#1239] opened 2020-08-08 17:05 UTC
### Is your feature request related to a problem? Please describe:
I have a common task to select multiple files within  a single context using a file dialog.

### Is it possible to construct a solution with the existing API?
I worked around this by building a `MultiFileChooser` widget, where users incrementally add files to a list using a `FileDialog`, but this has really bad UX.

### Describe the solution you'd like to see:

It should be possible to select multiple files. The FileDialog callback should return with a slice of `Reader`s.

@jesseduffield has [implemented this in their fork](https://github.com/jesseduffield/fyne/commit/ebd24f2ef36f49c8cddfe5c9f2e708b74314d850) already.

**Comment by andydotxyz** [comment] 2020-08-08 18:50
Pretty sure this is a duplicate of #1082

**Closed by andydotxyz** 2020-08-08 18:50 UTC
