### ISSUE TITLE
Why does Fyne close application if no Windows are shown?

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1080] opened 2020-06-05 16:35 UTC
I would like to have an app event loop running while I open and close windows without exiting with a last window? What's behind this design decision and how can I overpass this behaviour? Thanks in advance.

**Comment by andydotxyz** [comment] 2020-06-05 16:43
In most desktop operating systems closing the last window closes the app.
Can I assume you are a macOS user? That is the only one that I know has some apps stay open after last window closes.
More information about your platform would help us to consider this issue.
However I think that we will always have to compromise between cross platform consistency and matching OS expectations. on Mobile apps we don't quit when the window hides, so this is certainly a place we can explore more.

**Comment by ababo** [comment] 2020-06-05 16:49
Can I hide the main window instead of closing it?

**Comment by andydotxyz** [comment] 2020-06-05 22:35
There is an ongoing discussion in this area - but unless the user can tell the difference I’m not sure that it seems like a good idea. What is the difference between closed and hidden for a user, how can they bring them back?

As I said before the more we can know about your platform and why this is important the more it can inform the discussion.

**Comment by andydotxyz** [comment] 2020-07-16 11:25
I am going to close this as a duplicate of #467 - if you intercept the close and call Hide() instead the behaviour you desire will be possible.
How the window becomes un-hidden is of course another question, but I suspect you have designed the workflow already.

**Closed by andydotxyz** 2020-07-16 11:25 UTC

**Comment by guillermo** [comment] 2020-08-10 14:12
I leave this to document a use case:

The app manages a dev environment where:
* A API server is started and can be started stoped in different modes through the fyne window
* A web server is started and can be started, stoped in different modes through the fyne window.
* Several clients are started. Also started and stoped through the fyne window.

Once launched the application, the app shows a try icon. On press of the tray icon, it shows the fyne window. Upon close, the trayicon is show again.


The app flows as this:
1. AppManager init. (where all the servers are started).
2. fyne is setup and called with Run().
3. Trayicon is called and the go program waits until closed.
4. Call to win.Show().

Then the app exists... and don't know how to restart the UI within the same process.

**Comment by andydotxyz** [comment] 2020-08-10 14:50
the call to `App.Run()` will return when all windows are closed.
Either:

*) Use `Window.Hide()` (and with #467 you could do the same wind user closes the window)
*) Use `Window.ShowAndRun()` and put it in a loop until you truly want to quit.

**Comment by zsr228** [comment] 2021-06-08 07:59
@andydotxyz  I have the same query as @ababo 
I run two windows, one is Window.Hide(), the other is Window.Show(), when I close the showed window, the main app is quit. I don't know whether it's expected。

**Comment by andydotxyz** [comment] 2021-06-08 12:25
That is expected. As listed above you can use `Window.Hide()` instead of `Window.Close()` to keep the app alive.
If you want to deal with user closing the window and still staying open then `Window.SetCloseIntercept()` will allow you to intercept and call `Hide` in place of `Close` in the callback.

**Comment by zsr228** [comment] 2021-06-09 03:11
> That is expected. As listed above you can use `Window.Hide()` instead of `Window.Close()` to keep the app alive.
> If you want to deal with user closing the window and still staying open then `Window.SetCloseIntercept()` will allow you to intercept and call `Hide` in place of `Close` in the callback.

Okay, It means fyne doesn't support new a window in hidden status，but can be hidden by the user's click. Thanks a lot.

**Comment by andydotxyz** [comment] 2021-06-09 05:32
I don’t understand why you think this means a window can’t be created hidden? This is absolutely possible - just don’t call `Show` when you create the window.

**Comment by zsr228** [comment] 2021-06-09 06:00
I'm not express clear, I want a master window created in hidden default, other windows can be closed.
The following code, If close all showed window app is quit, where the hidden window is?
```
var appTest fyne.App

func gen(isHide bool) {
	w := appTest.NewWindow("Hello")

	if isHide {
		w.SetContent(widget.NewLabel("Hello Hide Fyne!"))
		w.SetMaster()
		//w.Show()
	} else {
		w.SetContent(widget.NewLabel("Hello Show Fyne!"))
		w.Show()
	}
}
func main() {
	appTest = app.New()
	gen(true)
	go func() {
		for {
			time.Sleep(10 * time.Second)
			gen(false) 
		}
	}()
}
```

**Comment by andydotxyz** [comment] 2021-06-09 11:03
That code has forgotten to call `Run`, which you need to do at the end of your `main`.
