### ISSUE TITLE
Quit menu item appearing in menus of sub windows of fyne system tray app

### ISSUE THREAD

**Issue by brucealthompson** [fyne-io/fyne#4671] opened 2024-02-23 18:11 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have a fyne system tray app. A couple of the system tray menu items open separate UI windows for performing different tasks. Each of these windows has its own main menu created with: fyne.NewMainMenu() and w.SetMainMenu(). This menu has a separate "Quit" menu entry separate from the "Quit" menu entry in the system tray.
I do not want users to have the ability to exit the application from these task related windows. It is not look like there is any way for me to disable this.

### How to reproduce

1. Create a system tray app.
2. Have one of the system tray menu items create a window.
3. Add a main menu to the created with with:  fyne.NewMainMenu() and w.SetMainMenu()
4. The "Quit" menu item will appear in the first drop down of the main menu.

### Example code

main() {
 // Create desktop app
// Add submenu item to open window
// Add menu menu to opened window
}

### Fyne version

2.4.4

### Go compiler version

1.22.0

### Operating system and version

Windows 11

**Comment by andydotxyz** [comment] 2024-02-23 19:54
The quit items cannot be removed - some OS insist that they exist.

I am curious though, what is the difference in quitting from the system tray vs quitting from a window - it's the same action...

**Comment by brucealthompson** [comment] 2024-02-24 02:22
I am curious though, what is the difference in quitting from the system tray vs quitting from a window - it's the same action...
________________________________

**Comment by brucealthompson** [comment] 2024-02-24 02:30
I am curious though, what is the difference in quitting from the system tray vs quitting from a window - it's the same action...

Real applications consist of more than just a single window. I have designed my application as a system tray application where different UI based activities are launched via menu items from the system tray app.

Why would I want to quit the entire application from a UI activity window launched from the system tray? Seems like a pretty common use case to me.

If you want download and try the application I created go here: https://homecld.com/downloads/

Unfortunately, the only up to date version of the application is the Windows version at the moment. I will update the Mac and Linux versions shortly.
[https://homecld.com/wp-content/uploads/2023/01/HomecloudLogo-Header.jpg]<https://homecld.com/downloads/>
Downloads<https://homecld.com/downloads/>
Homecloud Monitor for Windows Homecloud Monitor for MacOS Homecloud Monitor for Linux (x86)
homecld.com

________________________________

**Comment by andydotxyz** [comment] 2024-02-24 21:08
> Real applications consist of more than just a single window.

Indeed they can, but quitting an app is a single action no matter where it comes from. Some people even want buttons in their UI.

I guess that's why Apple enforces every App menu includes Quit no matter what window is focused. We follow this model.

I'm not sure why this consistent user flow is a problem for your app.

**Comment by brucealthompson** [comment] 2024-02-25 15:52
Indeed they can, but quitting an app is a single action no matter where it comes from. Some people even want buttons in their UI.

I guess that's why Apple enforces every App menu includes Quit no matter what window is focused. We follow this model.

OK. No point in arguing about the Apple induced forced behavior on all platforms. I will take that as a given. Beauty is in the eye of the beholder.

However, there is a basic problem with the current platform induced Quit() menu item that I am not able to work around. Please refer to this page: https://docs.fyne.io/explore/systray.html.
The page says:
By default a Fyne app will exit when you close all windows and this may not be what you want with a system tray app. To override the behaviour you can use the Window.SetCloseIntercept feature to override what happens when a window is closed.

I have already implemented the Window.SetCloseIntercept function as there is behavior I need when a window is closed. So now, the same hook is overloaded for these 2 functions:
1. The Window Close operation (E.G. someone hits the "X" at the top right of a Window)
2. The forced Quit() operation (someone selects the "Quit" menu item enforced by the fyne toolkit.

The 2 actions outlined above are different and (at least in my application) require different behavior. After all, one item is closing a window while the other is quitting the entire application.

So, the minimum thing I need is an indication to Window.SetCloseIntercept function as to whether the selected action is closing a window or exiting the entire application.

Hope this makes sense to you. It certainly does to me.

      Bruce T
System Tray Menu<https://docs.fyne.io/explore/systray.html>
Developer documentation for the Fyne toolkit
docs.fyne.io

________________________________

**Comment by andydotxyz** [comment] 2024-02-25 16:26
Apologies, that documentation is out of date. An app that has a system tray icon will not quite when the windows close anymore.
If you close a window where "SetMaster(true)" was called then it will quit. I will make sure that is up to date.

However I don't think this makes things different... asking a Fyne app to quit should always fire the "OnCloseIntercept" of every visible window that is set on. So I still don't understand what this ticket is requiring.

**Comment by andydotxyz** [comment] 2024-02-25 21:10
I mis-typed apologies, I mean that the documentation is out of date and closing a window will no longer quit a systray app.

> That being said, the quit action does terminate the app.Run() loop so I am able to catch it with code after the App.Run() loop.


I guess this ended up being a resolved as duplicate of #4670 then?

**Comment by brucealthompson** [comment] 2024-02-25 23:44
I guess this ended up being a resolved as duplicate of #4670 then?

That's fine.

FYI. I think the fyne toolkit is pretty cool. Not sure if you looked at my app but it's fairly sophisticated.
https://homecld.com/downloads/

Linux and Windows versions are now up to date. My Mac died so Mac version is out of date.

      Bruce T
________________________________

**Comment by andydotxyz** [comment] 2024-02-26 09:51
It's a great app well done.
Just FYI you don't have to have a macOS computer to compile for macOS (only if you want to compile for iOS).

Or you could use the FyneLabs platform that would manage all the different platforms with one build: https://fynelabs.com/geoffrey

**Closed by andydotxyz** 2024-02-26 09:51 UTC
Labels: unverified

**Comment by andydotxyz** [comment] 2024-02-26 10:03
Apologies, I meant also to link to the docs page that covers cross compiling and Fyne-cross https://docs.fyne.io/started/cross-compiling

**Comment by brucealthompson** [comment] 2024-02-26 23:35
It's a great app well done.

Did you let it run through the network scan? It scans the local network for http apps. I have an engine + plugin interface the specifically recognizes the popular http apps (wordpress, etc). I am actually working on IP camera support right now. Getting really cool.

Just FYI you don't have to have a macOS computer to compile for macOS (only if you want to compile for iOS).

Not sure that is true if you want to create fully signed dmg file. I was not able to get the fyne app to create the dmg file correctly. I ended up plagiarizing a script on github to create the fully signed dmg file. I have attached it. You may want to look at this as it does fully work with all the Apple sign, seal, deliver craziness.

      Bruce T
________________________________

**Comment by andydotxyz** [comment] 2024-02-28 12:01
> I was not able to get the fyne app to create the dmg file correctly.

This sounds like it should be a bug report against the project rather than a comment that it's not possible.
If you have time perhaps you can open a new issue describing the challenge and how you worked around it so we can fix this?
