### ISSUE TITLE
The program panic while input Chinese at some time by v2.2.1

### ISSUE THREAD

**Issue by tycjlee** [fyne-io/fyne#3067] opened 2022-06-13 08:04 UTC
The program panic while input Chinese at some time

### Describe the bug:
typing chinese panic

```
panic: runtime error: slice bounds out of range [12:11]

goroutine 27 [running]:
fyne.io/fyne/v2/widget.(*RichText).insertAt(0xc0003f2000, 0xc, {0xc0018d7f30, 0x3})
        C:/Users/Victor/go/pkg/mod/fyne.io/fyne/v2@v2.2.1/widget/richtext.go:222 +0x2b0
fyne.io/fyne/v2/widget.(*Entry).TypedRune(0xc0000003c0, 0x5566)
        C:/Users/Victor/go/pkg/mod/fyne.io/fyne/v2@v2.2.1/widget/entry.go:738 +0x11b
fyne.io/fyne/v2/internal/driver/glfw.(*window).processCharInput.func1()
        C:/Users/Victor/go/pkg/mod/fyne.io/fyne/v2@v2.2.1/internal/driver/glfw/window.go:782 +0x25 
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        C:/Users/Victor/go/pkg/mod/fyne.io/fyne/v2@v2.2.1/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Users/Victor/go/pkg/mod/fyne.io/fyne/v2@v2.2.1/internal/driver/glfw/window.go:942 +0x136
```

### To Reproduce:
https://user-images.githubusercontent.com/32116849/173307706-dac1044e-a808-455a-b65a-5d3ff8cb9513.mp4

### Screenshots:
![fyne_bug](https://user-images.githubusercontent.com/32116849/173307820-50296acb-c7ad-4427-b777-859e930b1b47.png)

### Example code:

```
package main

import (
	"os"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	os.Setenv("FYNE_FONT", "./font/msyh.ttf")
	myApp := app.New()
	w := myApp.NewWindow("Demo")

	str := binding.NewString()
	str.Set("你好!")

	w.SetContent(container.NewVBox(
		widget.NewLabelWithData(str),
		widget.NewEntryWithData(str),
	))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10
 - **GCC:** gcc version 12.1.0 (Rev2, Built by MSYS2 project)
 - **Go version:**  1.18.3
 - **Fyne version:** v2.2.1

**Comment by andydotxyz** [comment] 2022-06-13 09:39
I think this is a duplicate of #2730

**Closed as completed** 2022-06-13 11:20 UTC
Labels: duplicate
