### ISSUE TITLE
Spinner Widget 

### ISSUE THREAD

**Issue by DerThorsten** [fyne-io/fyne#704] opened 2020-02-24 17:04 UTC
Hi I was playing around with your library and tried to implement a  Spinner widget since it was not yet available (and I want to implemented this as custom type which implements the widget interface, st I can define whatever method I want on  the spinner instance, but it should still be a fyne.widget )
This spinner is in particular nice to use in conjunction with the form widget:
![Untitled](https://user-images.githubusercontent.com/904752/75173389-15db6280-572f-11ea-93d6-ef02f5343fa4.png)

While the widget is looking fyne(ish), I am not yet happy with the code.
I ended up writing a custom widget (`Spinner`) which extends the fyne container.
The custom renderer (`spinnerRenderer`) then mostly calls functions from the container. 
Is there an easier way to have a custom widget struct which basically just composes existing widgets with a  (border) layout?

Greetings

```golang
package widget

import (
	"fmt"
	"image/color"
	"math"
	"strconv"

	"fyne.io/fyne"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/theme"
	"fyne.io/fyne/widget"
)

func sgn(a float64) float64 {
	switch {
	case a < 0:
		return -1
	case a > 0:
		return +1
	}
	return 0
}

// extend entry to detect enter
type customEntry struct {
	widget.Entry
	onEnter    func()
	onScrolled func(s *fyne.ScrollEvent)
}

func newCustomEntry() *customEntry {
	cutomEntry := &customEntry{}
	cutomEntry.ExtendBaseWidget(cutomEntry)
	return cutomEntry
}

// KeyDown handler for keypress events - used to store shift modifier state for text selection
func (e *customEntry) KeyDown(key *fyne.KeyEvent) {

	if key.Name == fyne.KeyReturn {
		if e.onEnter != nil {
			e.onEnter()
		}
	} else {
		e.Entry.KeyDown(key)
	}
}

func (e *customEntry) Scrolled(s *fyne.ScrollEvent) {
	if e.onScrolled != nil {
		e.onScrolled(s)
	}
}

type Spinner struct {
	fyne.Container
	value    float64
	Min      float64
	Max      float64
	Step     float64
	startVal float64

	buttonUp   *widget.Button
	buttonDown *widget.Button
	entry      *customEntry
	integer    bool
}

func NewSpinner(min, max, step float64) *Spinner {
	return newSpinnerImpl(min, max, step, false)
}

func NewIntegralSpinner(min, max, step int) *Spinner {
	return newSpinnerImpl(float64(min), float64(max), float64(step), true)
}

func newSpinnerImpl(min, max, step float64, integer bool) *Spinner {

	buttonUp := widget.NewButtonWithIcon("", theme.MoveUpIcon(), func() {})
	buttonDown := widget.NewButtonWithIcon("", theme.MoveDownIcon(), func() {})

	updown := widget.NewHBox(buttonUp, buttonDown)
	entry := newCustomEntry()
	nip := &Spinner{
		buttonUp:   buttonUp,
		buttonDown: buttonDown,
		entry:      entry,
		Min:        min,
		Max:        max,
		value:      math.Min(math.Max(min, 1), max),
		startVal:   math.Min(math.Max(min, 1), max),
		Step:       1,
		integer:    integer,
	}
	buttonDown.OnTapped = nip.onDown
	buttonUp.OnTapped = nip.onUp
	entry.onEnter = nip.onEnter
	entry.onScrolled = nip.onScrolled
	nip.Layout = layout.NewBorderLayout(nil, nil, nil, updown)
	nip.AddObject(updown)
	nip.AddObject(entry)
	nip.updateVal()
	return nip
}

func (spinner *Spinner) GetValue() float64 {
	spinner.updateVal()
	return spinner.value
}

func (spinner *Spinner) SetValue(value float64) {
	spinner.value = value
	spinner.updateVal()
}

func (spinner *Spinner) onEnter() {
	if f, err := strconv.ParseFloat(spinner.entry.Text, 64); err != nil {
		spinner.value = spinner.startVal
	} else {
		spinner.value = math.Min(math.Max(spinner.Min, f), spinner.Max)
	}
	spinner.updateVal()
}

func (spinner *Spinner) onScrolled(e *fyne.ScrollEvent) {
	if e.DeltaY != 0 {
		spinner.value += spinner.Step * sgn(float64(e.DeltaY))
		spinner.updateVal()
	}
}
func (spinner *Spinner) onUp() {
	spinner.value += spinner.Step
	spinner.updateVal()
}
func (spinner *Spinner) onDown() {
	spinner.value -= spinner.Step
	spinner.updateVal()
}
func (spinner *Spinner) updateVal() {
	spinner.value = math.Min(math.Max(spinner.Min, spinner.value), spinner.Max)
	if spinner.integer {
		spinner.value = math.Round(spinner.value)
		spinner.entry.SetText(fmt.Sprintf("%d", int(spinner.value)))
	} else {
		spinner.entry.SetText(fmt.Sprintf("%.4f", spinner.value))
	}
	if spinner.value <= spinner.Min {
		spinner.buttonDown.Disable()
	} else {
		spinner.buttonDown.Enable()
	}
	if spinner.value >= spinner.Max {
		spinner.buttonUp.Disable()
	} else {
		spinner.buttonUp.Enable()
	}

}

func (spinner *Spinner) CreateRenderer() fyne.WidgetRenderer {
	return &spinnerRenderer{
		spinner: spinner,
	}
}

type spinnerRenderer struct {
	spinner *Spinner
}

func (renderer *spinnerRenderer) Layout(size fyne.Size) {
	renderer.spinner.Layout.Layout(renderer.spinner.Objects, size)
}
func (renderer *spinnerRenderer) MinSize() fyne.Size {
	return renderer.spinner.MinSize()
}

func (renderer *spinnerRenderer) Refresh() {
	renderer.spinner.Refresh()
}

func (renderer *spinnerRenderer) BackgroundColor() color.Color {
	return theme.BackgroundColor()
}

func (renderer *spinnerRenderer) Objects() []fyne.CanvasObject {
	return renderer.spinner.Objects
}

func (renderer *spinnerRenderer) Destroy() {
}
```

**Comment by andydotxyz** [comment] 2020-02-24 23:01
Thanks for working on this.
Spinners are a challenge, partly because on mobile they have completely different UI. That I think we can skip for a while as our mobile keyboard work is super limited at the moment.

If you'd like to develop this further then could you take the route of a pull request instead? we can't really accept code in the form of pasted into issues.

In terms of quick feedback I would think that extending Entry might make it neater, that way the key handling code is internal and it could be more easily extended by others. I'm not sure that "Enter" being pressed is normal for changing the value, you could use Entry.OnChanged instead?
Lastly if you could get the buttons one upon the other it would be cool - and using different arrows (such as MenuDropDown and MenuDropUp) makes it look less like you are re-ordering list items.

Really this is a duplicate of #667, but maybe we could close that one as there is more in here?

**Comment by DerThorsten** [comment] 2020-02-25 10:45
Hi, of  route of a pull request instead when  working on this properly.
But this issue was more for the question on how to write a custom widget when all it does is but some pre-existing widgets in a layout. 
Do I really have to implement a custom renderer for this? 
Iff you want to I can set up a PR and we can discuss the things there.

**Comment by DerThorsten** [comment] 2020-02-25 15:58
see #711

**Comment by Kvaz1r** [comment] 2020-02-25 17:11
Looks good for me, I definitely will use it until fyne won't get own implementation.

**Comment by AlbinoGeek** [comment] 2020-12-26 21:40
Currently working on this for https://github.com/fyne-io/fyne-x
Will update this thread when it's been put into a PR.

---

@DerThorsten I would like your go-ahead on using your code as the basis, for LICENSE/copyright-sake

**Comment by AlbinoGeek** [comment] 2020-12-28 21:54
@DerThorsten This is now a PR to the `fyne-x` repository: https://github.com/fyne-io/fyne-x/pull/6

**Comment by andydotxyz** [comment] 2021-02-23 12:28
Closed in preference to the PR linked above.

**Closed by andydotxyz** 2021-02-23 12:28 UTC
Labels: enhancement
