### ISSUE TITLE
fyne running error under windows11

### ISSUE THREAD

**Issue by zehuamama** [fyne-io/fyne#2975] opened 2022-05-14 10:35 UTC
### Describe the bug:
```shell
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c: In function 'glfwGetInputMode':
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c:476:1: error: converting to execution character set: Illegal byte sequence
     assert(window != NULL);
 ^   ~~~~~~~~~~~~~~~~~~~~~~~                                                                                                
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c: In function 'glfwSetInputMode':
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c:501:1: error: converting to execution character set: Illegal byte sequence
     assert(window != NULL);
 ^   ~~~~~~~~~~~~~~~~~~~~~~~                                                                                                
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c: In function 'glfwGetKey':
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c:632:1: error: converting to execution character set: Illegal byte sequence
     assert(window != NULL);
 ^   ~~~~~~~~~~~~~~~~~~~~~~~                                                                                                
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c: In function 'glfwGetMouseButton':
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c:655:1: error: converting to execution character set: Illegal byte sequence
     assert(window != NULL);
 ^   ~~~~~~~~~~~~~~~~~~~~~~~                                                                                                
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c: In function 'glfwGetCursorPos':
C:\Users\����\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20211024062804-40e447a793be/glfw/src/input.c:678:1: error: converting to execution character set: Illegal byte sequence
     assert(window != NULL);

```

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 11
 - **Go version:** 1.17.1
 - **Fyne version:** 2.1.4

**Comment by andydotxyz** [comment] 2022-05-14 12:05
This looks like a duplicate of #1257 - The GLFW (and possibly other CGo?) cannot handle some unicode characters in the directory path.
You can see the corruption in the output pasted. Try moving the project / GOPATH to another location to eliminate this possible problem.

**Closed by andydotxyz** 2022-05-14 12:05 UTC
Labels: unverified

**Comment by zehuamama** [comment] 2022-05-15 03:47
thx
