### ISSUE TITLE
Question: Is there away to define rich text widget?

### ISSUE THREAD

**Issue by Aukstkalnis** [fyne-io/fyne#169] opened 2019-03-22 14:54 UTC
Hi.

I want to create serial port terminal and I want to use rich text widget but currently it is not yet developed. So my question is what alternatives do we have to print text to window? Use label as text output?

**Comment by andydotxyz** [comment] 2019-03-22 15:29
A label would be the easiest approach if you want to do it with widgets.
If you want more control you could use the lower level canvas API and the text object - but you would have to handle the layout yourself.

Perhaps see my BeebUI project for inspiration? https://github.com/andydotxyz/beebui

**Comment by andydotxyz** [comment] 2019-03-23 21:40
Pretty sure this is a duplicate of #21

**Closed by andydotxyz** 2019-03-23 21:40 UTC
