### ISSUE TITLE
Memory usage surge when selecting/appending MultilineEntry text

### ISSUE THREAD

**Issue by aztack** [fyne-io/fyne#3426] opened 2022-11-24 07:35 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

My fyne App is just a node.exe launcher. It launcher node.exe and capture its output and write to a text entry.
Memory usage surge when selecting/appending MultilineEntry text as the following gif shows.
Memory usage keeps growing when the output of the node script is captured to the text entry. After about an hour of running, the memory usage peak at an astonishing 12G.

### How to reproduce

1. Create a multiline entry with a lot text content
2. Keep Selecting text in the entry and monitor the memory usage of the app

### Screenshots

![20221124151652_rec_](https://user-images.githubusercontent.com/782871/203718483-51876e85-ace3-4a2b-81bf-dd9f891904de.gif)

![image](https://user-images.githubusercontent.com/782871/203719543-43684dcd-2b72-4b11-85fe-d1a571aa4212.png)

### Example code

```go
	text := widget.NewMultiLineEntry()
	text.SetText("Press button 'Run' to Start")
	text.SetMinRowsVisible(16)

       var c *cmd.Cmd = cmd.NewCmdOptions(cmdOptions,  'node', newArgs...)
```

```go
		go func() {
			complete := c.Status().Complete
			for !complete && c.Stdout != nil || c.Stderr != nil {
				complete = c.Status().Complete
				if !complete {
					if !runButton.Disabled() {
						runButton.Disable()
					}
					if stopButton.Disabled() {
						stopButton.Enable()
					}
				}
				select {
				case line, open := <-c.Stdout:
					// OK
					if !open {
						c.Stdout = nil
						continue
					}
					log.Println(line)
					text.SetText(text.Text + "\n" + line)
				case line, open := <-c.Stderr:
					// Error
					if !open {
						c.Stderr = nil
						continue
					}
					fmt.Fprintln(os.Stderr, line)
					text.SetText(text.Text + "\n" + line)
				}
			}
			stopButton.Disable()
			runButton.Enable()
		}()
		c.Start()
		a.Lifecycle().SetOnStopped(func() {
			log.Println("Stopped")
			c.Stop()
		})
```

### Fyne version

2.2.3

### Go compiler version

1.17

### Operating system

macOS

### Operating system version

12.5.1

**Comment by aztack** [comment] 2022-11-24 08:30
maybe related: https://github.com/fyne-io/fyne/issues/2969 https://github.com/fyne-io/fyne/issues/3413

**Comment by andydotxyz** [comment] 2022-11-24 11:04
Thanks for this. It is very strange that selecting should do this, as everything should be a cache hit regarding the text rendering.
May not be duplicate of the issues you listed, so good to track this separately.

**Comment by andydotxyz** [comment] 2022-11-26 22:37
I can replicate this quite easily. The moving of selection is triggering refresh, which we should avoid as we don't have to refresh the whole widget.

This is probably separate to the linked issues which are really the source for the huge growth as the text rendering is clearly not clearing out old textures

**Comment by aztack** [comment] 2022-11-28 04:56
Nice work guys！
Is there any way I can use the fix in my project right away or in foreseeable future?

**Comment by andydotxyz** [comment] 2022-11-28 12:51
It has been landed on develop now, so you can test before release by running `go get fyne.io/fyne/v2@develop`

**Closed by andydotxyz** 2022-11-28 12:51 UTC
Labels: bug

**Comment by aztack** [comment] 2022-11-30 10:43
@andydotxyz I tried `fyne.io/fyne/v2@develop`.  Selecting text no longer causes memory surge. This is great.
But a long text in a multiline entry still causes HUGE memory usage. Is there any suggestion to mitigate this issue?

**Comment by andydotxyz** [comment] 2022-12-01 22:23
Indeed, sorry for this. There is a separate issue that we are working on - texture cache hits with text are basically not firing so we keep rendering new content when anything changes
