### ISSUE TITLE
Maximizing FixedGridLayout and VScrollContainer causes items to display in a vertical row.

### ISSUE THREAD

**Issue by mondy** [fyne-io/fyne#1250] opened 2020-08-14 12:01 UTC
### Describe the bug:
When FixedGridLayout and VScrollContainer are combined, items are displayed in a vertical row.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the following code.
2. Maximize the window.
3. The items in the FixedGridLayout will be displayed in a single vertical column.
4. Mouse over the scroll bar on the far right to view it correctly.

### Screenshots:

![ss2](https://user-images.githubusercontent.com/3961824/90246665-0f24e100-de70-11ea-92db-e9eafa4fe6d5.png)

### Example code:

```go
package main

import (
	"strconv"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/theme"
	"fyne.io/fyne/widget"
)

func main() {
	application := app.New()

	window := application.NewWindow("")

	files := files()

	grid := fyne.NewContainerWithLayout(
		layout.NewFixedGridLayout(fyne.NewSize(200, 200)),
		files...,
	)
	window.SetContent(widget.NewVScrollContainer(grid))

	window.ShowAndRun()

}

func files() []fyne.CanvasObject {
	objects := make([]fyne.CanvasObject, 100)
	for i := range objects {
		text := widget.NewLabel(strconv.Itoa(i))
		text.Wrapping = fyne.TextTruncate
		text.Alignment = fyne.TextAlignCenter

		objects[i] = fyne.NewContainerWithLayout(
			layout.NewBorderLayout(nil, text, nil, nil),
			text,
			widget.NewIcon(theme.FileImageIcon()),
		)

	}

	return objects
}

```

### Device :
 - OS: Ubuntu 20.04
 - Go version: go1.15 linux/amd64
 - Fyne version: v1.3.3

**Comment by andydotxyz** [comment] 2020-08-14 13:44
This looks like a duplicate of #1245

**Closed by andydotxyz** 2020-08-14 13:44 UTC
