### ISSUE TITLE
Scroll with check boxes quickly freeze

### ISSUE THREAD

**Issue by FredSoftwares** [fyne-io/fyne#2424] opened 2021-09-01 08:39 UTC
### Describe the bug:
When many check boxes are included in a scroll container, after few second playing with the scroll, the window freeze.

PS : In a more complex window containing buttons, labels, and lists, the last checkbox is not displayed when the scroll is down. I did not reproduce this yet in a toy example. It is unclear if it is related to my code or a bug. I include a screenshot to show the problem just in case.

### To Reproduce:
Steps to reproduce the behaviour:
1. compile the code bellow with fyne 
2. Scroll up and down 10-20 sec to display the checboxes
3. See error

### Screenshots:
2 frozen windows obtained with the code bellow + 1  screenshot showing that the scroll does not go down enough to show last item

### Example code:
```
package main

import (
	"log"
	"strconv"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("test")
	w := a.NewWindow("test check boxes")

	data := buildData()

	content := container.New(layout.NewGridLayoutWithColumns(2),
		widget.NewLabel("select"),
		listColums(data),
	)
	w.Resize(fyne.Size{100, 200})
	w.SetContent(content)
	w.ShowAndRun()
}

// list data slice items with check boxes
func listColums(data []string) fyne.CanvasObject {
	strings := binding.BindStringList(&data)
	l := widget.NewListWithData(strings,
		func() fyne.CanvasObject {
			return widget.NewCheck("text", func(val bool) {
				log.Println(val)
			})

		},
		func(item binding.DataItem, obj fyne.CanvasObject) {
			lbl := item.(binding.String)
			label, _ := lbl.Get()
			chk := obj.(*widget.Check)
			chk.Text = label
			chk.Refresh()

		})

	return l
}

func buildData() []string {
	var data []string
	for i := 0; i < 100; i++ {

		data = append(data, strconv.Itoa(i))
	}
	return data
}

```
-->

### Device (please complete the following information):
 - **OS:** linux manjaro
 - **Version:** up to date
 - **Go version:** 1.17
 - **Fyne version:** fyne.io/fyne/v2 v2.0.5-0.20210825130215-83ca35d98be7
![scroll_cut_last_item_2021-09-01](https://user-images.githubusercontent.com/26299514/131639917-082fe5f0-e2a8-4280-b319-53540adbae1c.png)
![scroll_hang_2021-09-01_b](https://user-images.githubusercontent.com/26299514/131639921-8ce4e9c8-3173-42bf-a4d0-e1c04c48e596.png)
![scroll_hang_2021-09-01](https://user-images.githubusercontent.com/26299514/131639923-c453109e-b237-44b6-a5d3-f90ac6487101.png)

**Comment by andydotxyz** [comment] 2021-09-01 08:58
This may be a duplicate of #2408 - perhaps you can test the fix in that issue?

**Comment by FredSoftwares** [comment] 2021-09-01 09:34
Hi @andydotxyz,
If I remove the refresh, suggested [here](https://github.com/fyne-io/fyne/pull/2421) like this 
```
func(item binding.DataItem, obj fyne.CanvasObject) {
			lbl := item.(binding.String)
			label, _ := lbl.Get()
			chk := obj.(*widget.Check)
			chk.Text = label
			//chk.Refresh()

		})
```
the stability is improved, but the display is bad (see screenshots) . My `update()` function is minimalist I do not know what else can be removed : )
![scroll_noresfresh_2021-09-01_c](https://user-images.githubusercontent.com/26299514/131648155-d22aad65-b1db-406b-8204-8d0d9fd7e4f3.png)
![scroll_noresfresh_2021-09-01](https://user-images.githubusercontent.com/26299514/131648161-4cd7769c-6b0d-4647-9d71-8f6d6f222b21.png)
![scroll_noresfresh_2021-09-01_b](https://user-images.githubusercontent.com/26299514/131648162-981d4f10-d8a2-4ed7-bfb1-eee17248942c.png)

**Comment by andydotxyz** [comment] 2021-09-01 13:05
That’s not what I meant - in your case the Refresh is required. What I meant is can you try the PR diff that fixed the linked issue?

**Comment by FredSoftwares** [comment] 2021-09-01 13:21
Sorry @andydotxyz , I am not familiar with Fyne PR and where I can find the SHA.
So I took the last commit fyne.io/fyne/v2 v2.0.5-0.20210901094005-4a0baea457bf
And I tested again, and, unfortunately the scroll freeze very quickly.

**Comment by Jacalz** [comment] 2021-09-01 14:37
Closing as a duplicate of the issue mentioned above.

**Closed by Jacalz** 2021-09-01 14:37 UTC
Labels: duplicate

**Comment by andydotxyz** [comment] 2021-09-01 16:25
Thanks for confirming @FredSoftwares
