### ISSUE TITLE
Do you consider supporting the display of statistical charts?

### ISSUE THREAD

**Issue by wangshenghao1** [fyne-io/fyne#3862] opened 2023-05-04 11:10 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

If it can support the display of statistical charts, it can achieve functions related to performance statistics.

### Describe the solution you'd like to see.

Provide X-axis and Y-axis coordinates, display statistical charts, and dynamically update them.

**Comment by Bluebugs** [comment] 2023-05-04 16:21
This is something to be considered for https://github.com/fyne-io/fyne-x project. I think a few people have worked on it, but no PR has been proposed yet. As an example: https://github.com/metal3d/fyne-x/tree/propose-graph-widget2/widget/charts .

**Comment by Jacalz** [comment] 2023-05-06 09:53
Duplicate of https://github.com/fyne-io/fyne/issues/2228?

**Comment by andydotxyz** [comment] 2023-05-06 14:07
Agreed

**Comment by andydotxyz** [comment] 2023-05-06 14:08
It should of course be mentioned that such things can be built using the API - just because we don't have the widget ready to go does not mean apps cannot include such features by coding them up ;).

**Closed by andydotxyz** 2023-05-06 14:07 UTC
