### ISSUE TITLE
go get fyne v2 also downloads fyne 1.4.3

### ISSUE THREAD

**Issue by lazyhacker** [fyne-io/fyne#2150] opened 2021-04-08 22:29 UTC
### Describe the bug:
When downloading Fyne v2 with `go get` (e.g. go get fyne.io/fyne/v2), both Fyne v2 and v1 are getting downloaded.  I wouldn't expect to v1 to get downloaded.

When using `go build` to build a project that imports fyne v2 then only v2 is downloaded which is what I'd expect.

### To Reproduce:

`go get fyne.io/fyne/v2`

or 

`go get fyne.io/fyne/v2/cmd/fyne`

Result:

go: downloading fyne.io/fyne/v2 v2.0.2
**go: downloading fyne.io/fyne v1.4.3**
go: downloading github.com/lucor/goinfo v0.0.0-20200401173949-526b5363a13a
go: downloading github.com/Kodeworks/golang-image-ico v0.0.0-20141118225523-73f0f4cfade9
go: downloading github.com/jackmordaunt/icns v0.0.0-20181231085925-4f16af745526
go: downloading github.com/josephspurrier/goversioninfo v0.0.0-20200309025242-14b0ab84c6ca
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/mod v0.2.0
go: downloading golang.org/x/tools v0.0.0-20200328031815-3db5fc6bac03
go: downloading github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
go: downloading github.com/akavel/rsrc v0.8.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Fedora 32
 - **Go version:** 1.16.3
 - **Fyne version:** 2.0.2

**Comment by andydotxyz** [comment] 2021-04-09 09:21
Hmm, yes this is strange. I don't know if we have done something wrong or if there is a bug/feature/complication of the "go get" process.
Is it causing problems?

**Comment by lazyhacker** [comment] 2021-04-09 17:49
This doesn't cause any problems.  It is just surprising and causes extra downloads.  Initially, I wasn't sure if there was some reference to v1 that I missed.

**Comment by Jacalz** [comment] 2021-07-27 20:11
I think this might be more of a thing about how the Go modules work. While I’m not certain, I think I have seen similar things without other projects. I’m not sure that we can do anything about it because as far as I know, we don’t import any of the old versions locally.

**Comment by andydotxyz** [comment] 2021-07-27 20:13
I'd say you're right about that @Jacalz

**Comment by Jacalz** [comment] 2021-07-28 12:55
I asked in the #modules-help channel on the Gophers slack and got it confirmed that Go does this to be able to check if v2 is a module or a subdirectory. Closing this as won't fix/not an issue.

**Closed** 2021-07-28 12:55 UTC
Labels: not an issue, wontfix
