### ISSUE TITLE
Problem with new version of github.com/go-text/typesetting. 

### ISSUE THREAD

**Issue by angelogeminiani** [fyne-io/fyne#5170] opened 2024-09-28 14:25 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I cannot compile any more due a change in a dependency.

I got following error:
github.com/go-text/typesetting/opentype/api/metadata: module github.com/go-text/typesetting@latest found (v0.2.0), but does not contain package github.com/go-text/typesetting/opentype/api/metadata

Can you please try to update and adjust the code for new version of github.com/go-text/typesetting module?

### How to reproduce

go get -u

### Example code

no code

### Fyne version

2.5.1

### Go compiler version

1.23

### Operating system and version

macOS Sierra

**Comment by andydotxyz** [comment] 2024-09-30 17:09
That happens because you are updating your app to use an incompatible version of go-text - blindly upgrading all dependencies is a somewhat dangerous thing to do.

That said we do have a fix in the works, it will land in the next release #5169

**Comment by andydotxyz** [comment] 2024-09-30 19:49
Fixed on develop and picked into the 2.5.x release branch

**Closed by andydotxyz** 2024-09-30 19:49 UTC
Labels: unverified

**Comment by malcolmradelet** [comment] 2024-10-11 07:42
> That happens because you are updating your app to use an incompatible version of go-text - blindly upgrading all dependencies is a somewhat dangerous thing to do.
> 
> That said we do have a fix in the works, it will land in the next release #5169

Why would you blame the user for this? I went to use Fyne for the first time (ever) today and did nothing other than copy and paste your own guide and got this exact error.

I started a blank project and added these imports:

```
fyne.io/fyne/v2
fyne.io/fyne/v2/app
fyne.io/fyne/v2/container
fyne.io/fyne/v2/widget
```

And it fails.

Fyne Docs say to run this command, so I tried that as well and get the same error:

`go get fyne.io/fyne/v2@latest`

Thanks for saying its our fault! I don't care about the latest, I just want it to work, but it won't.

Even if I remove the "@latest" I still get an automatic upgrade:

`go get fyne.io/fyne/v2`

```
go: downloading fyne.io/fyne/v2 v2.5.1
go: downloading fyne.io/fyne v1.4.3
go: upgraded github.com/go-text/typesetting v0.1.0 => v0.2.0
font.go:16:2: no required module provides package github.com/go-text/typesetting/opentype/api/metadata; to add it:
        go get github.com/go-text/typesetting/opentype/api/metadata
```

A frustrating experience I've never had before with Go modules.

**Comment by andydotxyz** [comment] 2024-10-11 08:20
Hmm, that is very strange, it should certainly not happen if you get fyne at the latest version. There may be some strange version resolving bug hiding in here.

The OP reported that `go get -u` caused the issue - this does make sense because they are requesting a version upgrade of everything to latest, which is not the same as installing Fyne @latest.

However (and I have just confirmed for me) `go get fyne.io/fyne/v2@latest` does /not/ pull the incompatible go-text code - as our dependency version marks what is working.

To clarify, the steps to get started that I executed are:

```
mkdir test
cd test
go mod init test
go get fyne.io/fyne/v2@latest
(put some code into main.go)
go mod tidy
go run .
```

These steps correctly import go-text v0.1.0 and the code compiles and runs.

Can you please execute those commands and verify the output. Maybe the go compiler version lookup is changing and / or dependant on cache state.

Also note the v2.5.2 which resolves this for all usages is in rc1 testing and will be out next week.

**Comment by ikouchiha47** [comment] 2024-10-13 18:26
```go.mod
replace github.com/go-text/typesetting v0.2.0 => github.com/go-text/typesetting v0.1.0
```

Only for this version. In case someone came looking
