### ISSUE TITLE
Entry widget data binding doesn't work together with OnChanged event

### ISSUE THREAD

**Issue by lukamicoder** [fyne-io/fyne#3081] opened 2022-06-19 20:46 UTC
### Describe the bug:
Entry widget data binding doesn't work together with OnChanged event

### To Reproduce:
See example code

### Screenshots:
See example code

### Example code:
```
	a := app.New()
	w := a.NewWindow("Test")
	w.Resize(fyne.NewSize(500, 220))

	val := ""
	dataVal := binding.BindString(&val)
	entry := widget.NewEntryWithData(dataVal)
	labelVal := widget.NewLabelWithData(binding.String(dataVal))

	//binding only works if this line is disabled:
	entry.OnChanged = func(v string) { fmt.Println(v) }

	w.SetContent(
		container.NewVBox(entry, labelVal,),
	)
	w.ShowAndRun()
```

### Device (please complete the following information):
 - **OS:** Linux Mint
 - **Version:** 20.3
 - **Go version:** 1.18.3
 - **Fyne version:** v2.2.1

**Comment by Jacalz** [comment] 2022-06-20 05:05
Thanks for opening this issue. I will however have to close this as a duplicate of https://github.com/fyne-io/fyne/issues/2542 and https://github.com/fyne-io/fyne/issues/2883. You’ll find most of the information in the attached issues.

**Closed by Jacalz** 2022-06-20 05:05 UTC
Labels: unverified
