### ISSUE TITLE
Selectable Text in label

### ISSUE THREAD

**Issue by Kazkans** [fyne-io/fyne#2330] opened 2021-07-19 14:57 UTC
### Is your feature request related to a problem? Please describe:
It should be possible to select text of label and for example copy it.
### Is it possible to construct a solution with the existing API?
You can do it now  by using Entry and disabling it.
### Describe the solution you'd like to see:
I would like label to be selectable or other widget that offers this functionality.

**Comment by andydotxyz** [comment] 2021-07-19 16:40
Label is not an interactive text widget, the Entry is.
Having all text in an application selectable is only standard on web-pages.
If your user flow includes copying text out of a UI you could also consider a "copy text" button which is far more discoverable.

This is kind of a duplicate of #2113

**Closed by andydotxyz** 2021-07-19 16:40 UTC

**Comment by hkparker** [comment] 2021-07-20 23:01
I'm interested in this for a chat bubble that users can select text from.  I could build a "copy" button, but it's a common UX to drag specific text from a message and copy it, so I'd like to support that.  A disabled entry looks like, well, a disabled entry, which wouldn't look correct in a chat bubble.  Entries also come with other things I don't need for this, and since it's never intended to use as an entry it's not really the right widget.

I agree the the use of Label in user interface design / structure doesn't need to be copyable, but there's applications that will want to display text that's not supposed to be edited/submitted, but isn't _from_ the application itself and should be copyable.  An example aside from chat apps may be something printing log lines in the user interface.

Since this is a wontfix, what's the suggested way to present selectable/copyable text that looks just like standard text?  Would it possible to create a custom widget based on Label that adds this behavior?

**Comment by andydotxyz** [comment] 2021-07-21 12:17
>  but it's a common UX to drag specific text from a message and copy it

Hmm, I think this is platform specific. Most chat UI that works on mobile uses context menu (right click) rather than presenting text bubbles as interactive text. As we target cross-platform solutions it's hard to know how much complexity to push into standard components.

After we move to full RichText underpinning all text objects it may be easier to enable this for more niche use-cases.

**Comment by hkparker** [comment] 2021-07-22 05:06
Yeah, it's platform specific in that it's something you'll want on desktop and probably won't want on mobile.  On mobile the UX I'm used to is long pressing to get additional options (like copy all, forward, delete, etc).  There are times I'd actually prefer to be able to select specific text via a long press and drag on mobile chat like you can on mobile web, but I get why it's uncommon (usually more than just "copy" appears in that menu).

I can't think of an example of a desktop chat app that _doesn't_ let you copy text via click 'n' drag (slack, telegram, and signal come to mind).  Maybe this shouldn't be called a "label" and is more of a "text area" or something, but I'm sure this is going to continue to come up.  Looking through the apps on my machine, virtually all of them have some text that's selectable or at least "right click > copy"-able, so I wouldn't call it niche.

I get the annoyance though, now a Fyne user would have to switch off which environment they are in and adjust some things to make a great user experience on either one.  I at least would love exposure to more complexity like this as it's going to let me build much more intuitive interactions, and I'm happy to increase the complexity of my app to make that happen the best way I can in each environment.

Very excited for rich text, being able to format size and color of text will allow for lots of new stuff.  For example, take this telegram screenshot I just got off google:

![image](https://www.nairaland.com/attachments/5013927_screenshot20170317092352_jpegf310abcdf6a74e4f4b0b925bcb1b499c)

Being able to add timestamps at a different font size and color in the same widget, like in the above example, will be very nice.

I'd love to see text selectability as an option as part of that migration as well!

**Comment by andydotxyz** [comment] 2021-07-22 08:24
> Being able to add timestamps at a different font size and colour in the same widget, like in the above example, will be very nice.

You can do that already. Canvas.Text allows complete control of size/colour etc. It is only not yet possible to do inside 1 flow of text. Having multiple different types of text in one widget has always been possible (of course it would be a custom widget).
An illustration of a chat app with coloured bubbles is available in the Fyne book.

**Comment by hkparker** [comment] 2021-07-24 23:09
Cool, I gave this a try today and made a [custom chat bubble widget](https://gist.github.com/hkparker/3b8c44685119d1704e33cb5d3f2cba6e).  It's not perfect but I'm pretty happy with the progress so far.  It looks like this:

![fyne_message_bubbles](https://user-images.githubusercontent.com/2918615/126882407-22448c62-a466-4164-8f51-c616fb51194e.png)

There were several difficulties though, some of which I have yet to solve.  First of all, in order to get text wrapping I used a `widget.Label` internally, so my goal of selectable text was not going to happen from the start.  I would have used a `canvas.Text` but the line wrapping code ([this](https://github.com/fyne-io/fyne/blob/master/widget/text.go#L427) and friends) isn't exported, and I wasn't up to the task of copy-pasting that all in and figuring out how to use it just yet.  Hopefully there's something I missed and you're going to tell me there's an easy way to word wrap a `canvas.Text`. :crossed_fingers: 

`canvas.Text` isn't selectable either btw so I still have more work to do to figure that out.  I'm guessing the mouse/select interactions are widget level and the canvas is all about display, so I'd need to build selection into the custom widget?

One of the features I wanted to build was clicking the profile picture of the user in a group to result in being taken to their profile.  You'll see I got a button to render nicely in there but for some reason it isn't clickable.  I'd imagine that my custom widget doesn't support mouse events so I can't "pass it through" to the button or whatever.

Another issue with those buttons is that when you're rendering them and you get a lot of chat messages going, resizing the window gets pretty slow.  It's fast without it so it's either some call I'm making to position them (which isn't much), or something internal to `widget.Button`.  I guess the "correct" thing to do would probably be to not use a button and instead make this whole thing clickable and internally detect where the click happened and if it was over where I put the icon.  Maybe `widget.List` will help with performance too, idk.

This is my first custom renderer so I ran into a few [other questions](https://gist.github.com/hkparker/3b8c44685119d1704e33cb5d3f2cba6e#file-main-go-L344) that aren't clear to me yet.  Layout math can fry your brain if you don't approach it right, so I'm still learning good habits there.

Looking forward to [rounded corners](https://github.com/fyne-io/fyne/issues/1090)!

**Comment by andydotxyz** [comment] 2021-07-26 08:39
> I gave this a try today and made a [custom chat bubble widget](https://gist.github.com/hkparker/3b8c44685119d1704e33cb5d3f2cba6e)

Looks great, well done.

> I would have used a canvas.Text but the line wrapping code (this and friends) isn't exported

Wrapping and line parsing is not supported in `canvas.Text` - that is simply a canvas primitive for displaying text to screen. The items in `canvas` package are taken and drawn optimally to GPU, there is no fancy logic in this package.
The internal code you found in `widget/text.go` has been refactored on `develop` branch to `RichText` which does indeed export much more functionality.

> You'll see I got a button to render nicely in there but for some reason it isn't clickable

If a button isn't tapping then it's because you have positioned it underneath something else. Make sure the order of `Objects` returns button above (that is, after) any background elements that could be covering it.

> resizing the window gets pretty slow

Slow resize is normally down to lots of text calculations - measuring a string draw size is very slow. This will improve in v2.1 as well, but if your custom widget is delegating a lot to Text.MinSize you may need to do clever things to cache values. I don't think that the `widget.Button` is the source of slowness, merely causing it elsewhere.

**Comment by andydotxyz** [comment] 2021-07-26 08:39
P.S. For questions please use our Slack channel so others can join in and/or find answers. If you encounter an issue please open a new ticket as this one is closed.

**Comment by hkparker** [comment] 2021-07-28 04:43
Awesome, I'll be switching to `develop` and giving rich text a try in my next pass at this.  It doesn't appear as if there's a tag associated with the develop branch so I can't explore it on pkg.go.dev, is that right?  I can just run a local godoc, it's fine, but perhaps I missed something and it's actually on there somewhere.

I assumed github was better as it's indexed by google so new users can find things easier, but I'll keep these threads on slack from now on if that's preferred.  Thanks!

**Comment by andydotxyz** [comment] 2021-07-28 08:30
There are no tags on develop, we use them for release versions so they are all on master.

We use GitHub to track development of the Fyne project, so support questions don't really belong here.
You can see that when adding an issue as getting support takes you to a different page (our contacts info).
