### ISSUE TITLE
Carriage Return (\r) is rendered as space

### ISSUE THREAD

**Issue by TUSF** [fyne-io/fyne#2456] opened 2021-09-11 15:11 UTC
### Describe the bug:
I've only tested the entry and label widgets so far, but it appears that when Fyne comes across `\r`, it is rendered as a space. Ideally, the application would NOT render it at all, while still potentially having the option to use `\r\n` for linebreaks, for compatibility with other Windows applications.

### To Reproduce:
In my case, I merely edited the textedit example, and inserted this line into the `Show()` function:

```Go
editor.entry.SetText("A test\nwith\rcarriage return,\r\nAnd if it understands?")
```

I also added a `\n\r` into the "Cursor Row" label (which is backwards from how Windows apps normally handle it, but still demonstrates how Fyne labels handle the carriage return)

### Screenshots:
![image](https://user-images.githubusercontent.com/8594356/132952370-ac4b648d-47eb-483e-8ba6-5ef3c6116cc6.png)

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10
 - **Go version:** 1.17
 - **Fyne version:** 2.0.4

**Comment by julieta-311** [comment] 2022-02-05 18:16
I'm having issues with carriage return as well when executing a command in the background and writing the logs into a text grid. These logs contain a progress bar with carriage return at the beginning of each line. It prints out unexpected characters that are not printed out when writing to Stdout (prints out the outcome of `fmt.Println("\u001b[1A")`).
 
![carriage_return](https://user-images.githubusercontent.com/60350242/152653037-5bbd0f2f-9614-4968-9d0e-a4543b25c715.png)

Here is minimal code to visualise it and compare to the output :

```
package main

import (
	"fmt"
	"io"
	"os"
	"time"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	t := widget.NewTextGrid()
	b := widget.NewButton("read", func() {
		pipeToTextGrid(t)
	})

	w.SetContent(container.NewVBox(t, b))
	w.ShowAndRun()
}

func pipeToTextGrid(t *widget.TextGrid) {
	r, w := io.Pipe()
	go doRead(r, t)

	// Carriage return: \u001b[1A
	w.Write([]byte("Foo:\n"))
	for {
		w.Write([]byte("\u001b[1A Bar 1"))
		time.Sleep(time.Second)
		w.Write([]byte("\u001b[1A Bar 12"))
		time.Sleep(time.Second)
		w.Write([]byte("\u001b[1A Bar 123"))
		time.Sleep(time.Second)
		w.Write([]byte("\u001b[1A Bar 1234"))
		time.Sleep(time.Second)
		w.Write([]byte("\u001b[1A Bar 12345"))
		time.Sleep(time.Second)
		w.Write([]byte("\u001b[1A Bar 123456"))
		time.Sleep(time.Second)
		w.Write([]byte("\u001b[1A Bar 1234567\n"))
	}
}

func doRead(r *io.PipeReader, t *widget.TextGrid) {
	for {
		buf := make([]byte, 50)
		n, _ := r.Read(buf)
		line := string(buf[:n])
		t.SetText(line)
		fmt.Fprintf(os.Stdout, "\n%v", line)
	}
}
```

Device:
OS: Manjaro Linux.
Version: `DISTRIB_RELEASE=21.2.2`.
Go version: 1.17.6 linux/amd64
Fyne version:  v2.1.2

**Comment by andydotxyz** [comment] 2022-02-07 18:56
Your terminal interprets these control characters @julieta-311, but a text renderer does not.
You should either tell the software you are logging not to include colour code/style information or you will have to filter it in your own code. This is not a bug of our text rendering - you are asking it to print the "escape" character - which the font does not contain.

**Comment by andydotxyz** [comment] 2022-02-07 18:57
This fix was landed for Bowmore

**Closed by andydotxyz** 2022-02-07 18:57 UTC
Labels: bug, Hacktoberfest

**Comment by julieta-311** [comment] 2022-02-07 19:04
> Your terminal interprets these control characters @julieta-311, but a text renderer does not.
> You should either tell the software you are logging not to include colour code/style information or you will have to filter it in your own code. This is not a bug of our text rendering - you are asking it to print the "escape" character - which the font does not contain.

Thanks for the quick response! I'm filtering it out in my code at the moment, will try your other suggestion as well.
