### ISSUE TITLE
Feature Request: How to register system global key event

### ISSUE THREAD

**Issue by netrip** [fyne-io/fyne#2861] opened 2022-03-21 10:48 UTC
### Is your feature request related to a problem? Please describe:

When the app is running in the backend(main window is at the minimize status or at the system tray),  press some key combination(CTL + F). the application respond to the key event and shows as normal status. it behaviors like Alfred（Press Option + Space to show the search input box) in the Mac OS

### Is it possible to construct a solution with the existing API?

can not find such API

**Comment by Jacalz** [comment] 2022-03-21 14:06
I think this might be a duplicate of https://github.com/fyne-io/fyne/issues/2304.

**Closed** 2022-03-21 14:07 UTC
Labels: duplicate
