### ISSUE TITLE
(Double)Tappable list items

### ISSUE THREAD

**Issue by BillBuilt** [fyne-io/fyne#4530] opened 2024-01-07 21:20 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When a list item satisfies TappedSecondary or DoubleTapped (and possibly others) the parent list's OnSelected method is ignored.

### How to reproduce

See example code. If you comment the TappedSecondary and DoubleTapped methods, the list's OnSelected method starts working, otherwise it never executes.

### Example code

package main

import (
	"fmt"
	"log"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Clickable list items")
	myWindow.Resize(fyne.Size{
		Width:  300,
		Height: 300,
	})

	listData := binding.NewStringList()
	listData.Set([]string {"Item 1", "Item 2", "Item 3"})

	list := widget.NewListWithData(listData,
		func() fyne.CanvasObject {
			l := NewMyListItem("item name")
			return l
		},
		func(item binding.DataItem, object fyne.CanvasObject) {
			i, _ := item.(binding.String).Get()
			lbl := object.(*MyListItem)
			lbl.SetText(i)
		},
	)

	list.OnSelected = func(id widget.ListItemID) {
		log.Println(fmt.Sprintf("list item %d selected", id))
	}

	myWindow.SetContent(list)
	myWindow.ShowAndRun()
}

type MyListItem struct {
	widget.Label
}

func NewMyListItem(text string) *MyListItem {
	item := &MyListItem{}
	item.ExtendBaseWidget(item)
	item.SetText(text)
	return item
}

func (e *MyListItem) TappedSecondary(pe *fyne.PointEvent) {
	newItem := fyne.NewMenuItem("New", func(){log.Println("New clicked")})
	editItem := fyne.NewMenuItem("Edit",  func(){log.Println("Edit clicked")})
	deleteItem := fyne.NewMenuItem("Delete",  func(){log.Println("Delete clicked")})
	div := fyne.NewMenuItemSeparator()

	entryPos := fyne.CurrentApp().Driver().AbsolutePositionForObject(e)
	popUpPos := entryPos.Add(fyne.NewPos(pe.Position.X, pe.Position.Y))
	c := fyne.CurrentApp().Driver().CanvasForObject(e)

	menu := fyne.NewMenu("", newItem, div, editItem, deleteItem)

	popUp := widget.NewPopUpMenu(menu, c)
	popUp.ShowAtPosition(popUpPos)
}

func (e *MyListItem) DoubleTapped(pe *fyne.PointEvent) {
	log.Println("Double clicked")
}

### Fyne version

v2.4.3

### Go compiler version

 1.21.5

### Operating system and version

macOS Sonoma 14.2.1

**Comment by BillBuilt** [comment] 2024-01-07 21:22
I would like to be able to have a "right-click" menu on the list item, but also to be able to select the list item and apply logic when the user presses the DELETE key. Is this possible?

**Comment by andydotxyz** [comment] 2024-01-08 13:28
I think this is a duplicate of https://github.com/fyne-io/fyne/issues/2551.
We need to re-work the tap handling in the desktop/GLFW driver code to resolve this issue.

**Closed** 2024-01-08 14:24 UTC
Labels: duplicate

**Comment by Jacalz** [comment] 2024-01-08 14:25
I agree. Looks like a duplicate. Let’s close this in favour of the other issue.

**Comment by dweymouth** [comment] 2024-01-08 21:01
> I would like to be able to have a "right-click" menu on the list item, but also to be able to select the list item and apply logic when the user presses the DELETE key. Is this possible?

This is possible, if you have your list item implement Tappable and SecondaryTappable. In your Tapped handler, you can just call list.Select(itemID). In your TappedSecondary handler, you show the menu. For the delete key logic, you probably want to extend the List widget itself to provide a replacement for the TypedKey handler that handles DELETE specially, but delegates all other keys to the base List's TypedKey handler.

**Comment by BillBuilt** [comment] 2024-01-10 00:34
#2551 mentions assigning a reference to the list and the item ID to the list item in the updateItem() func. That would work for a regular list but I'm using an untyped list and the updateItem() func for that does not pass the ListItemID, but rather the binding.DataItem. Is there no way to reference the ListItemID in this function?

**Comment by BillBuilt** [comment] 2024-01-10 01:31
So close. I supplied a TypedKey handler to the custom list in order to grab the DELETE keypress as suggested, but it seems that selecting a list item does not also set focus to the list so the event is never captured unless I also tab into the list, even after making a selection.

**Comment by dweymouth** [comment] 2024-01-10 01:45
For that last one you can focus it yourself after you call Select, using `fyne.CurrentApp().Driver().CanvasForObject(t).Focus(theList)`

**Comment by andydotxyz** [comment] 2024-01-10 07:42
This seems more like a discussion, you should consider joining one of our support channels or using GitHub discussions instead of a bug report.
