### ISSUE TITLE
关于字符的支持

### ISSUE THREAD

**Issue by kelvins-io** [fyne-io/fyne#2100] opened 2021-03-19 09:16 UTC
### Is your feature request related to a problem? Please describe:
在程序生成的界面中输入中文显示不出来哦，需要特别设置吗

**Comment by Jacalz** [comment] 2021-03-19 09:21
Can we please keep discussions in English? No one in our team speaks Chinese. Google translate indicates that it is about Chinese character support, so I’ll close this as a duplicate of https://github.com/fyne-io/fyne/issues/598. You need to specify as font that supports it, using FYNE_FONT= environment variable.

**Closed by Jacalz** 2021-03-19 09:21 UTC
