### ISSUE TITLE
Failed to set dark mode

### ISSUE THREAD

**Issue by lorypelli** [fyne-io/fyne#5105] opened 2024-09-02 11:09 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

![image](https://github.com/user-attachments/assets/97f5acd0-b1eb-46ce-9ec6-39c2107ebefd)
`Operazione completata` = `Completed Successfully`
wtf?

### How to reproduce

idk, I'm on windows 11 with dark mode enabled

### Example code

```go
a := app.New()
login := a.NewWindow("Login")
program := a.NewWindow("http_requests") <-- the one that had the issue
bot := a.NewWindow("bot_info")
msg_list := a.NewWindow("msg_list")
```

### Fyne version

2.5.1

### Go compiler version

1.23.0

### Operating system and version

Windows 11

### Additional Information

it didn't crash the app, just the titlebar was in light mode, the second time I tried it worked perfectly

**Comment by lorypelli** [comment] 2024-09-02 11:27
it seems to work until 2.4.5

**Comment by andydotxyz** [comment] 2024-09-03 08:30
This is a duplicate of #4758

**Closed** 2024-09-03 08:30 UTC
Labels: duplicate
