### ISSUE TITLE
a.Preferences().RemoveValue  function has no effect

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2022] opened 2021-02-24 13:33 UTC
### Describe the bug:
 In version v1.4.3, removeValue does not remove the key in the preferences.json file
 In version v1.4.4,The preferences.json file was not generated (the Develop branch)
The v1.4.3 dialog box cannot be resized, switch to the development branch, the window can be resized, but after the window to minimize,when I reactivate, the window is restored to the minimum size

### Example code:

Write your code here.
```
a := app.NewWithID("com.example.tutorial.preferences")
	a.Preferences().SetString("test", "aaa")
	a.Preferences().SetString("test", "")
	a.Preferences().RemoveValue("test")
```

### Device (please complete the following information):
 - **OS:** win10 home
 - **Go version:** v1.16
 - **Fyne version:** v1.4.3 and v1.4.4

**Comment by andydotxyz** [comment] 2021-02-24 13:34
Can you please test against latest release, `v2.0.0`?

**Comment by smp12345** [comment] 2021-02-24 13:36
The V2.0.0 dialog box cannot be resized

**Comment by andydotxyz** [comment] 2021-02-24 13:39
I was meaning with regards to this issue title "a.Preferences().RemoveValue function has no effect".

If you have another bug to report, please open a new issue.

**Comment by smp12345** [comment] 2021-02-24 13:48
V2.0.0 cannot generate a preferences.json file

**Comment by madaxemad** [comment] 2021-02-24 13:52
> V2.0.0 cannot generate a preferences.json file

no it do
you can see on fyne_demo 
it's reactive too

**Comment by Jacalz** [comment] 2023-01-08 10:22
This has been fixed a while ago. Closing as duplicate of https://github.com/fyne-io/fyne/issues/3229.

**Closed by Jacalz** 2023-01-08 10:22 UTC
Labels: bug
