### ISSUE TITLE
Emphasis in Markdown gives erroneous output in RichText

### ISSUE THREAD

**Issue by jfjensen** [fyne-io/fyne#2974] opened 2022-05-14 09:32 UTC
### Describe the bug:
If I run the example code from [#2589](https://github.com/fyne-io/fyne/issues/2589#issue-1035769991) and type in `**hello**` then no emphasis is added. The emphasis only appears when I add another `*`, which is obviously incorrect behavior.

The bug must be somewhere in the Markdown Renderer where the emphasis is handled.

### To Reproduce:
Steps to reproduce the behaviour:
1. Type in `**hello**` into the editor panel on the left. No emphasis is added.
2. Then add another `*`.

### Screenshots:
![Screen Shot 05-13-22 at 10 40 PM](https://user-images.githubusercontent.com/2771076/168419917-559c0f1f-eda1-4b4d-bb34-52b134920115.PNG)

### Device (please complete the following information):
 - **OS:** Windows 11Pro
 - **Version:** 10.0.22000
 - **Go version:** 1.17
 - **Fyne version:** v2.1.4

**Comment by andydotxyz** [comment] 2022-05-14 12:09
Thanks for opening this, Apologies I did not notice it before commenting on the other thread where you mentioned this

**Comment by andydotxyz** [comment] 2022-05-15 21:15
Confirmed, thanks for reporting

**Comment by d4x1** [comment] 2022-06-10 04:20
@jfjensen 
This is caused by codes [here](https://github.com/fyne-io/fyne/blob/master/widget/markdown.go#L172).
I try to fix it  like [this](https://github.com/d4x1/fyne/commit/e89a160d02e29af0f2194611805b24ad79654ee9),  it works but breaks some test cases.  

I cannot come up with an elegant way,  I think `markdownRenderer.Render` must be implemented in a better way just like 
html render in github.com/yuin/goldmark.

**Comment by d4x1** [comment] 2022-06-10 04:30
Or I can rewrite markdown render. Is this welcomed?

**Comment by jfjensen** [comment] 2022-06-10 07:26
@d4x1 Thanks for looking into this! Perhaps a total rewrite is indeed necessary?

**Comment by d4x1** [comment] 2022-06-10 07:45
> 
At least, you can refer to my modification, it  makes emphasis's behavior normal. :)

**Comment by d4x1** [comment] 2022-06-10 07:45
> @d4x1 Thanks for looking into this! Perhaps a total rewrite is indeed necessary?

At least you can refer to my modification, it makes emphasis' behavior normal. :)

**Comment by andydotxyz** [comment] 2022-06-21 13:51
> I cannot come up with an elegant way, I think `markdownRenderer.Render` must be implemented in a better way just like html render in github.com/yuin/goldmark.
> 
> @andydotxyz do you have any advice?

No specific thoughts. We always prefer smallest change possible - but some times the implementation was going down a blind alley. As long as there is no change to the `RichText` API we don't need to worry.

It's a naive stack implementation, but could certainly be better.
I think the main confusion is around paragraph vs block level text, so it is possible that a smaller fix may be OK

**Comment by andydotxyz** [comment] 2022-06-21 14:26
Maybe #3086 makes you a little happy? :)

**Comment by andydotxyz** [comment] 2022-06-27 18:28
Merged for v2.22

**Closed by andydotxyz** 2022-06-27 18:28 UTC
Labels: bug
