### ISSUE TITLE
TextGrid performence issue

### ISSUE THREAD

**Issue by my4381918** [fyne-io/fyne#2276] opened 2021-06-02 12:25 UTC
### Describe the bug:
i want to make a file diff tool just use fyne GUI, and i found that if line is 100 lines or more, program will be stoped and broken, seems it just satisfied little file with few content.

### code
code is like this :
```
	a := app.NewWithID("fyne.demo")
	w := a.NewWindow("Demo")
	msg, err := ioutil.ReadFile("./log.txt")
	con := string(msg)
	if err != nil {
		fmt.Println(err)
		return
	} else {
		fmt.Println(con)
	}

	grid := widget.NewTextGridFromString(con)
	grid.SetRowStyle(1, &widget.CustomTextGridStyle{BGColor: &color.NRGBA{R: 64, G: 192, B: 64, A: 128}})
	grid.ShowWhitespace = true
	grid.ShowLineNumbers = true
	content := container.NewMax(container.NewScroll(container.NewHSplit(grid, grid1)))

	w.SetContent(content)
	w.Resize(fyne.NewSize(1200, 800))
	w.ShowAndRun()
```

### To Reproduce:
Steps to reproduce the behaviour:
1. add 200 lines to log.txt
2. run program
3. my computer will not response as this program stoped

### Device (please complete the following information):
 - MacOS big sur 11.4 intel core i5 mem:16G
 - **Go version:go1.16.3
 - **Fyne version: v1.4.3

**Comment by Jacalz** [comment] 2021-06-02 13:04
The performance of TextGrid has improved a lot in the latest releases (v2.0.0 and onwards). I would recommend you to try with the latest versions instead of 1.4.3 which is a few months old. I am going to close this as a duplicate of https://github.com/fyne-io/fyne/issues/1142.

**Closed by Jacalz** 2021-06-02 13:04 UTC
Labels: unverified
