### ISSUE TITLE
Entry's popupmenu can support other language

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2831] opened 2022-03-09 16:50 UTC
### Is your feature request related to a problem? Please describe:
The language of my program is non English, but i found the popupmenu of entry is English and cannot be set other language.  Unless I extend Entry. 
![图片](https://user-images.githubusercontent.com/6658943/157487042-4f7e0e4d-aebc-4ea2-89d5-669fcbe88005.png)

### Is it possible to construct a solution with the existing API?
Of cause, i can extend Entry. But I just want to modify the text of the menu. Most of the code is completely copied. I don't think this implementation is reasonable.

### Describe the solution you'd like to see:
I am not sure whether the following interfaces are reasonable. :) Looking forward to more elegant design
```go
func (*Entry) SetPopUpMenuText(cutMenuText, pasteMenuText, copyMenuText, selAllMenuText string) {..}
```

**Comment by Jacalz** [comment] 2022-03-09 18:14
I think that this most likely is a duplicate of https://github.com/fyne-io/fyne/issues/605. Internationalisation is a big and pretty complicated topic.

**Comment by andydotxyz** [comment] 2022-03-09 19:10
... Something we need to fix right and probably aiming to do at 3.0 (currently working on 2.2)

**Comment by BabySid** [comment] 2022-03-10 03:00
> ... Something we need to fix right and probably aiming to do at 3.0 (currently working on 2.2)

I'm looking forward to version 3.0. Fyne is my favorite GUI framework at present. Look forward to seeing killer applications soon. come on!

**Comment by andydotxyz** [comment] 2022-03-10 12:31
Thanks :).

At the moment you can extend the `Entry` widget to intercept `TappedSecondary` if you would like to provide your own menu.

**Comment by bon-ami** [comment] 2022-05-23 09:42
I want to extend menu items, only to add a "clear all". But I do not know how to.
```
type EntryLog struct {
	*widget.Entry
}

func (e *EntryLog) TappedSecondary(pe *fyne.PointEvent) {
```
I paste this function from Entry. But all its inner members like requestFocus() and popUp cannot be accessed.
Thank you.

**Comment by andydotxyz** [comment] 2022-05-23 10:04
@bon-ami if you want to customise you will need to add your own popup instead of re-using the one internally.
It should be possible, you should not need to access internal items to make this possible.

**Comment by bon-ami** [comment] 2022-05-23 23:16
> @bon-ami if you want to customise you will need to add your own popup instead of re-using the one internally. It should be possible, you should not need to access internal items to make this possible.

Yeah, I can add my own popup, though I'll have to rewrite Hide(), (while I cannot rewrite TypedRune() either, which also uses popup). The key issue here is the use of super() to implement requestFocus() and use clipboard. IMHO, I'll have to rewrite everything from the scratch.

**Comment by andydotxyz** [comment] 2022-05-24 17:30
Instead of `super.(fyne.Shortcutable).TypedShortcut(...)` just do `m.Entry.TypedShortcut(...)` - super is an internal detail about how we support widget extension.
The call to `requestFocus` may be less easy to call into, but I think it can just be replaced with `fyne.CurrentApp().Driver().CanvasForObject(m).Focus(m)`

**Comment by bon-ami** [comment] 2022-05-25 00:39
Since I'm not focused on this part now, I skipped TypedRune(), which hides popup, but I need to handle e.propertyLock.
Thanks to your code, the only issue remain is selectAll(). It makes me wonder how to select some text by code, or maybe it is not regarded as necessary?

**Comment by andydotxyz** [comment] 2022-05-25 10:26
> the only issue remain is its size does not change when I resize the window.

Did you forget to call `ExtendBaseWidget` - I think I forgot it in my example, but you can see at https://developer.fyne.io/extend/extending-widgets.

With regards to text selection I think we have not exposed those APIs but we should. I think the hesitance was we did not know how to publicly index the characters, I guess the same way as `CursorCol` perhaps?

**Comment by bon-ami** [comment] 2022-05-26 01:54
Andy, you are right. I used `ExtendBaseWidget` wrong. Thank you again for your patience.

**Closed** 2024-07-14 17:45 UTC
