### ISSUE TITLE
The package chain does not support modules when cross-compiling for mobile

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#660] opened 2020-02-07 14:55 UTC
### Describe the bug:

If the import path has a major version number in it, `fyne package` can't find the dependencies.  Interestingly:

0. `go build` works
1. Native packaging works (no `-os` argument)
2. Packaging for android doesn't work
3. Manually running the command that fyne says failed, works
4. Removing the version information from the import works
5. Packaging for darwin *appears* to work, except the cross-compiling failes on glfw with the missing `Carbon.h` headers, the same as trying to cross-compile without the versioned dependency.

### To Reproduce:

The "Sample Code" section below contains a minimum program that demonstrates the problem.  

#### Steps

1. Make a directory, "fynetest"
2. Copy this code to `main.go`
3. Set up go modules  (e.g., `go mod init foo.bar/fynetest`)
4. Execute commands to demonstrate behavior
5. Remove the version information
6. Re-run the commands to see everything succeed

Another note: while `go build` will accept a package name that differs from the current directory, fyne will fail if they do not match.  Fyne is using absolute directories; it (probably) should not.

#### Behavior Commands

0. `go build .` -- **succeeds**
1. `fyne package -appID fynetest -name "FyneTest" -icon /usr/local/share/icons/hicolor/16x16/mimetypes/gnome-mime-application-lrf.png` -- **succeeds**
2. `fyne package -os android -appID fynetest -name "FyneTest" -icon /usr/local/share/icons/hicolor/16x16/mimetypes/gnome-mime-application-lrf.png` -- **fails**
3. Capture the `go` command that the previous step failed; copy and paste it into the command line.  E.g. `/usr/lib/go/bin/go build -buildmode=c-shared -o /tmp/gomobile-work-325956592/lib/armeabi-v7a/libgo_.so` (the go path and /tmp file name will differ) -- **succeeds**
4. Remove the version part of the import path: `sed -i 's^/v3"^"^' main.go` and run the first three commands -- **succeeds**
5. On Linux, use the `-os darwin` argument -- **fails**, but because the glfw dependency can't be cross-compiled for darwin on Linux.

### Screenshots:
The first three behaviors are [demonstrated in a video](https://asciinema.org/a/GprAxK0zTOWCm6IBHopF7R5BA).  The fourth is demonstrated in [this video](https://asciinema.org/a/5pb4PBC0zzLaEoIKqnvn8dA7Z). The last is demonstrated in [this video](https://asciinema.org/a/kTVs4zokcqqH5pAC2ogKgFID3).

### Example code:
```Go
package main
import (
        diskv "github.com/peterbourgon/diskv/v3"
        "fyne.io/fyne/app"
)
func main() {
        a := app.New()
        w := a.NewWindow("test")
        defer w.ShowAndRun()
        s := diskv.New(diskv.Options{BasePath:"ft"})
        s.Write("a", []byte("abc"))
}
```

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.4.15-arch1-1
 - Go version: go1.13.7
 - Fyne version: 43a9759e4f3

**Comment by andydotxyz** [comment] 2020-02-07 17:53
I think this is a duplicate of #655 - if you look the dep "github.com/peterbourgon/diskv" exists, but "github.com/peterbourgon/diskv/v3" des not - that is a virtual package only available as a module.
And so this requires modules to function as expected... 
Thoughts?

**Comment by andydotxyz** [comment] 2020-02-07 18:18
A quick note about compiling for macOS on Linux - you will need to install the full set of headers or toolchain to enable this (see https://fyne.io/develop/cross-compiling.html). If that is hassle we have the fyne-cross project that tries to avoid the complications using containers (https://github.com/lucor/fyne-cross).

**Comment by andydotxyz** [comment] 2020-03-05 09:43
This requires pulling in commits from upstream that will need lots of testing, so probably will get it into 1.3 rather than a patch on 1.2.x

**Comment by andydotxyz** [comment] 2020-03-05 14:50
On develop now for testing. Worked on some of my apps but would like more folk to confirm!

**Closed by andydotxyz** 2020-03-05 14:50 UTC
Labels: enhancement

**Comment by xxxserxxx** [comment] 2020-03-05 15:58
Confirmed fixed.  Thank you!

Pixel 2, Android 10.  Go 1.14.

**Comment by yougg** [comment] 2020-03-08 03:04
after upgrade to latest develop branch, also not work for me

```bash
$ go get fyne-io/fyne@develop
go: fyne.io/fyne develop => v1.2.1-0.20200307215026-3663d890ef95


$ cat go.mod
module hello

go 1.14

require fyne.io/fyne v1.2.1-0.20200307215026-3663d890ef95


$ fyne package -os android -appID com.example.hello -icon /home/me/Pictures/gopher.jpg
/usr/local/go/bin/go build -buildmode=c-shared -o /tmp/gomobile-work-114416668/lib/armeabi-v7a/libhello.so . failed: exit status 1
hello.go:8:2: cannot find package "fyne.io/fyne" in any of:
        /usr/local/go/src/fyne.io/fyne (from $GOROOT)
        /home/me/go/src/fyne.io/fyne (from $GOPATH)
hello.go:9:2: cannot find package "fyne.io/fyne/app" in any of:
        /usr/local/go/src/fyne.io/fyne/app (from $GOROOT)
        /home/me/go/src/fyne.io/fyne/app (from $GOPATH)
hello.go:10:2: cannot find package "fyne.io/fyne/canvas" in any of:
        /usr/local/go/src/fyne.io/fyne/canvas (from $GOROOT)
        /home/me/go/src/fyne.io/fyne/canvas (from $GOPATH)
hello.go:11:2: cannot find package "fyne.io/fyne/layout" in any of:
        /usr/local/go/src/fyne.io/fyne/layout (from $GOROOT)
        /home/me/go/src/fyne.io/fyne/layout (from $GOPATH)
hello.go:12:2: cannot find package "fyne.io/fyne/widget" in any of:
        /usr/local/go/src/fyne.io/fyne/widget (from $GOROOT)
        /home/me/go/src/fyne.io/fyne/widget (from $GOPATH)

# copy and run the command is OK
$ go build -buildmode=c-shared -o libhello.so .
$ file libhello.so
libhello.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=fc258e9f6fd9b5a8fc83c9cb96e2f538e6b5a4fe, not stripped
```

this is my env
```
OS: Ubuntu 19.10 x86_64

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/me/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/me/go/Code/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build706328073=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by andydotxyz** [comment] 2020-03-08 08:02
Did you re-install the fyne command from develop? It does not look like it’s using the new module code.

**Comment by yougg** [comment] 2020-03-08 08:50
package succeed after reinstall the fyne command, thanks.
