### ISSUE TITLE
Button vertical alignment looks wrong next to select widget

### ISSUE THREAD

**Issue by alexrudd** [fyne-io/fyne#2080] opened 2021-03-11 12:12 UTC
### Describe the bug:

When placing a button alongside a select widget, the shadow around the button and the underline below the select cause the button's alignment to look wrong. Specifically that it's slightly higher up than the select.

When you look closely you can see the the body of the button is actually aligned with the select, but the shadow combined with the select's underline cause this to look "off".

This might apply to other widgets too but this is the one I noticed

### Screenshots:

![image](https://user-images.githubusercontent.com/3588652/110785244-a1546280-8262-11eb-9911-dc7037a3ec3e.png)

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()
	// window
	w := app.NewWindow("Alignment demo")
	w.Resize(fyne.NewSize(300, 100))
	w.SetFixedSize(true)

	w.SetContent(
		container.NewCenter(
			container.NewHBox(
				widget.NewSelect([]string{"example"}, func(s string) {}),
				widget.NewButton("example", func() {}),
			),
		),
	)

	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10
 - **Go version:** 1.15.2
 - **Fyne version:** 2.0.1

**Comment by andydotxyz** [comment] 2021-03-12 12:22
This is an artefact of trying to keep the text in entry centered.
The problem is probably the "half padding" gap at the top of entry which I am not completely certain about.
We can remove this gap so the entry looks taller, will fix alignment with button - but the text inside entry then looks a litttle off-center vertically.

You can see the gap more clearly at https://developer.fyne.io/architecture/widgets.
Keen to get your thoughts.

**Comment by andydotxyz** [comment] 2021-03-15 19:08
The changed version would look like this (from fyne_demo theme icons tab):

<img width="316" alt="Screenshot 2021-03-15 at 19 07 31" src="https://user-images.githubusercontent.com/294436/111207610-bf52f780-85c1-11eb-8a17-b21a797c686b.png">

I'm not certain if it's better or not.

**Comment by alexrudd** [comment] 2021-03-20 16:37
I see what you mean! The only other thing I could think of would be to reduce the height on the entry so that the top alignment stays the same but the bottom of the underline is aligned with the bottom of the button. I imagine this will cause numerous other problems though.

Feel free to close this issue and thank you for the explanation :)

**Comment by andydotxyz** [comment] 2021-03-22 17:47
I don't know if I am ready to close this - because I am not sure what the right answer is ;)

**Closed** 2023-01-03 10:03 UTC
Labels: bug, information-needed
