### ISSUE TITLE
ready for windows commercial use ? windows 10 memory huge

### ISSUE THREAD

**Issue by 678uhb** [fyne-io/fyne#1541] opened 2020-11-15 06:00 UTC
![屏幕截图 2020-11-15 135711](https://user-images.githubusercontent.com/6631439/99178072-ab4dd500-274a-11eb-9359-542b2136ce47.png)

i drag and resize windows, memory increase and never release, even add 
![image](https://user-images.githubusercontent.com/6631439/99178084-cb7d9400-274a-11eb-8914-1645fe68f909.png)

but not work

is fyne ready for windows ?

**Comment by 678uhb** [comment] 2020-11-15 06:08
![image](https://user-images.githubusercontent.com/6631439/99178247-10ee9100-274c-11eb-9959-318b438631f1.png)
 f'yne_demo same

**Comment by andydotxyz** [comment] 2020-11-15 10:21
This is not a memory "leak" which is why calling `debug.FreeOSMemory()` does not clear it.
It seems that on Windows the texture cache is not currectly resetting and so the cached image textures are not being freed.
We are tracking it in #348 - on some operating systems this is working OK but Windows has this issue more than others.

There are no reports of this causing instability or issues, but it will be fixed as soon as we can find the cause.
Closing as duplicate

**Closed by andydotxyz** 2020-11-15 10:21 UTC
