### ISSUE TITLE
Sometimes infinite progress bars are not shown when requested

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1529] opened 2020-11-13 13:38 UTC
In my codebase there're several forms with infinite progress bars that indicate progress of processing when submitted. After porting my code from Fyne 1.3.0 into 1.4.0 it turned out that the hidden progress bars are not shown when requested anymore. After switching some widgets and returning back to the forms above suddenly the progress bars begin to appear and from that moment always work as expected. 

I doubt I can share with you some minimal code example unfortunately.

**Comment by andydotxyz** [comment] 2020-11-13 14:17
Just to check, do you mean that a ProgressBarInfinite that has had Hide() called does not reappear when Show() is called?

This may relate to the container that it is in - can you share what container or layout it is inside? The container may accidentally be forcing the hidden item to 0, 0 size and not updating correctly until it is refreshed.

**Comment by ababo** [comment] 2020-11-13 15:23
> Just to check, do you mean that a ProgressBarInfinite that has had Hide() called does not reappear when Show() is called?

yes.

> can you share what container or layout it is inside?

```go
func createSSOLoginPageContent(cg *util.CancelGroup,
	data *pageData, finished chan<- *pageError) fyne.Widget {

	progress := widget.NewProgressBarInfinite()
	progress.Hide()

	var guard int32
	var auth *fynex.Button
	auth = fynex.NewButton("Authenticate", func() {
		if !atomic.CompareAndSwapInt32(&guard, 0, 1) {
			return
		}

		auth.Disable()

		go performSSOLogin(cg, data, finished, progress)
	})
	auth.EnabledCursor = desktop.PointerCursor
	data.container.Canvas().Focus(auth)

	progressSize := fyne.NewSize(
		auth.MinSize().Width, loginPageProgressHeight)

	return widget.NewVBox(
		newPageTitle(loginTitle),
		newRichText(loginText),
		fynex.NewVerticalMargin(loginPageFormMargin),
		widget.NewHBox(
			auth,
			layout.NewSpacer(),
		),
		fyne.NewContainerWithLayout(
			layout.NewFixedGridLayout(progressSize),
			progress,
		),
	)
}
```
The returned widget is embedded as a page inside a widget.Box that is a window content.

**Comment by ababo** [comment] 2020-11-13 15:27
BTW the container is not a pure Window, but rather a `struct` with `fyne.Window` anonymously embedded:

```go
type container struct {
	fyne.Window
	box    *widget.Box
	header *header
	footer *footer
}
```

**Comment by ababo** [comment] 2020-11-13 15:28
> and not updating correctly until it is refreshed.

Calling `Refresh()` explicitly doesn't help.

**Comment by stuartmscott** [comment] 2020-11-13 15:36
I can see `progress.Hide()`, but I can't see `progress.Show()`

**Comment by ababo** [comment] 2020-11-13 15:44
```go
func performSSOLogin(cg *util.CancelGroup, data *pageData,
	finished chan<- *pageError, progress *widget.ProgressBarInfinite) {
	ssoToken := newSSOToken()

	if err := launch.LoginWithSSO(data.conf, cg, ssoToken); err != nil {
		finished <- &pageError{
			title: "...",
			text: "...",
			metricsError: metrics.ErrorProcessFailed,
		}
		return
	}

	cg.Wait()

	progress.Show()
	data.container.RequestFocus()

	finished <- login(data, backend.NewSSOCreds(ssoToken))
}
```

**Comment by stuartmscott** [comment] 2020-11-13 20:32
Shouldn't the progress bar be shown at the start of the function, before the work begins?

**Comment by ababo** [comment] 2020-11-13 20:35
Nope, here is a specific case, when we I to show an SSO login popup window, and then, when it's closes, but before logging in I need to visualise a progress.

**Comment by stuartmscott** [comment] 2020-11-13 21:58
I think the issue is that `NewFixedGridLayout` (which returns a GridWrapLayout) doesn't layout objects if they are hidden and it is never told to re-layout its objects when the progress bar become visible, so the progress bar's size is always 0x0.

There are a couple of fixes, the simplest one would probably be:
```go
progressSize := fyne.NewSize(
		auth.MinSize().Width, loginPageProgressHeight)
progress.Resize(progressSize)
```

**Comment by ababo** [comment] 2020-11-13 22:13
I have logged the `progress` size and confirm that you're right, though the suggested fix doesn't work. Doesn't it look like a Fyne bug?

**Comment by stuartmscott** [comment] 2020-11-13 22:16
Okay then you need to call `Refresh()` on the container holding the progress bar

**Comment by andydotxyz** [comment] 2020-11-14 10:18
I wonder if the NewFixedGridLayout is even needed? its' a container that is containing a single element that is sized manually - what if you just append the progress bar to the vbox container?

**Comment by ababo** [comment] 2020-11-14 18:54
How can I specify a fixed size for the progress widget otherwise?

**Comment by andydotxyz** [comment] 2020-11-14 19:52
Fair enough. It just seemed a little strange to have some fixed sized element at the bottom of a full-width box

**Comment by ababo** [comment] 2020-11-14 19:56
Don't you think that this behaviour is buggy / counter-intuitive? I didn't experience this problem in v1.3.0.

**Comment by andydotxyz** [comment] 2020-11-15 00:24
I don't think you replied to say whether calling `Refresh()` on the parent fixes the issue like @stuartmscott suggested.

Right now I don't understand the situation fully so I can't say whether you have found a bug in the toolkit.
It sounds like there might be one, but it's tough to confirm with so many variables.

**Comment by ababo** [comment] 2020-11-15 12:43
> I don't think you replied to say whether calling Refresh() on the parent fixes the issue like @stuartmscott suggested.

`progress.Refresh()` didn't help, but `container.Canvas().Refresh(progress)` did. Though the simplest working solution is to hide the container and show it when needed.

**Comment by andydotxyz** [comment] 2020-11-15 13:38
I think Stuart was suggesting theContainer.Refresh(), to signal it that the content required different layout

**Comment by ababo** [comment] 2020-11-15 13:41
This is exactly what I wrote. Please re-read my post, maybe you read pre-edited version.

**Comment by andydotxyz** [comment] 2020-11-15 13:42
In which message?

**Comment by andydotxyz** [comment] 2020-11-17 19:28
Just for clarity, `container.Canvas().Refresh(progress)` is different to `container.Refresh()`, the former asks it to be redrawn by the canvas, whereas the latter checks that all of the layout is correct before redrawing what has changed.
Using `xxx.Refresh()` is almost always the right thing to do, it is designed to do what is required to apply changes.

**Comment by ababo** [comment] 2020-11-17 19:34
Anyway I think showing back a hidden widget in a fixed grid layout shouldn't zero it's size.

**Comment by andydotxyz** [comment] 2020-11-17 19:47
At no point have we disagreed with that.
But thus far we have not been able to replicate the issue -  the questions we have asked will help us to track down the problem.

**Comment by Jacalz** [comment] 2021-11-21 16:04
The solution has been proposed above and there has been no further activity here. Feel free to reopen if I'm wrong, but I will go ahead and close this is not an issue.

**Closed by Jacalz** 2021-11-21 16:04 UTC
Labels: not an issue
