### ISSUE TITLE
Certain Windows settings cause distortion, blurry text.

### ISSUE THREAD

**Issue by stormon-force** [fyne-io/fyne#1440] opened 2020-10-21 21:04 UTC
### Describe the bug:

Hi,

I've been having bit of challenge finding info on this and was wondering if anyone had some advice. Running the demo program or the the ```fyne_settings``` program I see a distortion and scaling issue. I've tested on other Windows machines and the program appears fine, so this doesn't seem to be a issue with fyne or the example programs.

### Screenshots:

![image](https://user-images.githubusercontent.com/22061813/96781312-db9b9100-13a1-11eb-9e0f-d6c7f89a7a25.png)
![image](https://user-images.githubusercontent.com/22061813/96786725-86617e80-13a5-11eb-93ef-288c8631f359.png)

What I've tried.
- Fiddling with Windows display settings such as resolution, scale and layout, etc. (nothing very specific)
- Setting the environment variable ```FYNE_SCALE``` to various values (1.00, 0.5, 1.25, etc.)
- Running an elevated privileges mode (do not have access to administrator)

Can anyone think of some settings on Windows that would cause this problem?

Code sample
```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
	"os"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	os.Setenv("FYNE_SCALE","1")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(widget.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: Windows 10 Enterprise 10.0.17134
 - Go version: go1.15.3 windows/amd64
 - Fyne version: v1.3.3

**Comment by andydotxyz** [comment] 2020-10-21 21:07
This is a problem we have not been able to replicate yet - originally reported as #1041 .
Any information you can provide would be greatly appreciated as it's a very strange issue.

Anything special about graphics drivers, screens, fonts?

**Comment by stormon-force** [comment] 2020-10-21 21:19
No sorry, I'm not aware of anything in particular. I did not setup this company laptop.

From System Information -> Display
- Name: Intel(R) HD Graphics 520
- Driver Version: 21.20.16.4664

**Comment by andydotxyz** [comment] 2020-10-22 13:08
Looking carefully at those images it seems like the canvas is being drawn at the size of the border instead of the content size. No idea if that is a clue or just coincidence ...

**Comment by andydotxyz** [comment] 2020-11-17 19:21
I just realised this is a duplicate of #1043, hopefully we can find a resolution over there

**Closed by andydotxyz** 2020-11-17 19:21 UTC
