### ISSUE TITLE
RichText word wraps hyperlinks wrongly

### ISSUE THREAD

**Issue by pjanx** [fyne-io/fyne#5262] opened 2024-11-13 08:00 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

RichText word wraps HyperlinkSegments wrongly, and then the following letters are exploded one per line within the negative horizontal space.

### How to reproduce

* Run the application
* Toy around with window size

### Screenshots

![wrap-fail](https://github.com/user-attachments/assets/f9c31a5a-7dd9-4c09-9c92-b24b399051cf)

### Example code

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Bugs")
	w.Resize(fyne.NewSize(480, 360))
	rt := widget.NewRichText()
	rt.Wrapping = fyne.TextWrapWord
	rt.ParseMarkdown(`
This is a very, very, very long line with a hyperlink at the end like this:
[https://example.com](https://example.com) which word wraps wrongly.
`)
	w.SetContent(rt)
	w.ShowAndRun()
}
```

### Fyne version

2.5.2

### Go compiler version

1.23.2

### Operating system and version

Linux

**Comment by dweymouth** [comment] 2024-11-13 22:53
Duplicate of #3393

**Closed by dweymouth** 2024-11-13 22:53 UTC
Labels: unverified
