### ISSUE TITLE
How to solve Chinese garbled characters?

### ISSUE THREAD

**Issue by xlango** [fyne-io/fyne#4762] opened 2024-04-02 09:57 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The screen directly enters Chinese characters. After startup, the Chinese characters are garbled

### How to reproduce

go1.22.1

### Example code

package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
	"github.com/flopp/go-findfont"
	"math/rand"
	"os"
	"strings"
	"time"
)

func init() {
	//设置中文字体:解决中文乱码问题
	fontPaths := findfont.List()
	for _, path := range fontPaths {
		if strings.Contains(path, "msyh.ttf") || strings.Contains(path, "simhei.ttf") || strings.Contains(path, "simsun.ttc") || strings.Contains(path, "simkai.ttf") {
			os.Setenv("FYNE_FONT", path)
			break
		}
	}
}

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("TOPESS UI")
	myWindow.Resize(fyne.NewSize(1000,1000))

	grid := showAttackMatrix()

	tabs := container.NewAppTabs(
		container.NewTabItem("列表1",grid),
		container.NewTabItem("列表2", widget.NewLabel("World!")),
		container.NewTabItem("列表3", widget.NewLabel("World!")),
	)

	//tabs.Append(container.NewTabItemWithIcon("Home", theme.HomeIcon(), widget.NewLabel("Home tab")))

	tabs.SetTabLocation(container.TabLocationBottom)

	myWindow.SetContent(tabs)

	myWindow.ShowAndRun()
}

### Fyne version

2.4.4

### Go compiler version

1.22.1

### Operating system and version

Ubuntu 22.04 Linux xyl-virtual-machine 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andydotxyz** [comment] 2024-04-02 12:23
Can you show an image of the garbled result? This may be a duplicate of #218, as the embedded font does not support Chinese rendering.
If so, this is resolved for the v2.5.0 release

**Closed** 2024-04-03 03:01 UTC
Labels: unverified
