### ISSUE TITLE
After table creation, if set data to empty, call table.Refresh() will not actually refreshed, still use old data

### ISSUE THREAD

**Issue by lazywhite** [fyne-io/fyne#3903] opened 2023-05-22 09:59 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

after init a table, if change the data used to empty like [][]string,  can call table.Refresh(),  table still use old data

### How to reproduce

please check my Example Code below

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"time"
)

func main() {
	a := app.NewWithID("com.example.demo")
	w := a.NewWindow("Clock")

	Table(w)

	w.Resize(fyne.NewSize(500, 400))
	w.ShowAndRun()
}

func Table(w fyne.Window) {
	var data = [][]string{[]string{"top left", "top right"},
		[]string{"bottom left", "bottom right"}}
	table := widget.NewTable(
		func() (int, int) {
			return len(data), 2
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i widget.TableCellID, o fyne.CanvasObject) {
			l := o.(*widget.Label)
			l.SetText(data[i.Row][i.Col])
		})
	table.Resize(fyne.NewSize(300, 300))

	go func() {
		time.Sleep(1 * time.Second)
		data = [][]string{}
		table.Refresh()
	}()
	w.SetContent(table)
}

```

### Fyne version

2.3.4

### Go compiler version

1.20

### Operating system and version

ubuntu 22.10

**Comment by Jacalz** [comment] 2023-05-22 11:01
Closing as duplicate of https://github.com/fyne-io/fyne/issues/3736.

**Closed by Jacalz** 2023-05-22 11:01 UTC
Labels: unverified
