### ISSUE TITLE
widget not have Date Picker

### ISSUE THREAD

**Issue by AncestorDragon** [fyne-io/fyne#4817] opened 2024-04-30 06:40 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

widget not have Date Picker,
please implement this function
thanks!

### Describe the solution you'd like to see.

I need Date Picker,I hope widget  implement this function

**Comment by Jacalz** [comment] 2024-04-30 10:14
Closing as duplicate of https://github.com/fyne-io/fyne/issues/888.

**Closed as not planned by Jacalz** 2024-04-30 10:14 UTC
Labels: duplicate

**Comment by andydotxyz** [comment] 2024-05-02 14:19
Note that there is one in the fyne-x repo (Calendar) https://github.com/fyne-io/fyne-x/blob/master/widget/calendar.go
