### ISSUE TITLE
Submit form in popup modal when enter pressed

### ISSUE THREAD

**Issue by hismailbulut** [fyne-io/fyne#3023] opened 2022-06-01 17:20 UTC
I don't know if I can do this myself but I guess there is no such feature. If not, that would be really nice to have. If you already have it, it would be greatly appreciated if you could tell me how to do it.

**Comment by Jacalz** [comment] 2022-06-01 19:30
Please use the issue templates when opening issues. It makes it a lot simpler and more clear for us what the users are requesting.

I’m not sure I quite understand what the issue is about as I only have the title to go by. Are you intending to submit the form when you press enter in one of the Entry widgets inside of it? You should be able create something like that yourself using the `widget.OnSubmitted` field and then have some logic that calls `form.OnSubmit`.

**Comment by hismailbulut** [comment] 2022-06-04 11:07
> Please use the issue templates when opening issues. It makes it a lot simpler and more clear for us what the users are requesting.

Okay sorry for this

My users are greeted with a password screen when they start the program. I don't want them to use the mouse to enter the password on this screen. In order for them to enter quickly, the entry must be focused at startup, and when they press enter after entering the password, the form must be as if the submit button was pressed. How can I achieve this?

**Comment by Jacalz** [comment] 2022-06-06 10:55
You don't need to create your own entry for it. I don't usually put together code examples as it often is better and less time consuming to try and explain things. However, this was quite simple to do so I created a small example either way.
```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Form submit and focus")

	password := widget.NewPasswordEntry()
	form := widget.NewForm(widget.NewFormItem("Password", password))
	form.OnSubmit = func() {
		fmt.Println("The user entered a password")
	}
	password.OnSubmitted = func(_ string) {
		form.OnSubmit()
	}

	w.SetContent(form)
	w.Canvas().Focus(password)
	w.ShowAndRun()
}
```

Feel free to close this if you feel that the answer is satisfactory. We usually prefer to keep this issue tracker to bugs and feature requests. Questions get the most attention over on our other support options: https://fyne.io/support/.

**Closed** 2022-06-06 17:39 UTC
Labels: question
