### ISSUE TITLE
Can't compile demo app on Windows 10

### ISSUE THREAD

**Issue by gitspeaks** [fyne-io/fyne#1848] opened 2021-01-21 16:42 UTC
PS C:\Users\jumbo> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jumbo\AppData\Local\go-build
set GOENV=C:\Users\jumbo\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\jumbo\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\jumbo\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\jumbo\AppData\Local\Temp\go-build797217538=/tmp/go-build -gno-record-gcc-switches

PS C:\Users\jumbo> go version
go version go1.15.6 windows/amd64

PS C:\Users\jumbo> gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev6, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Rev6, Built by MSYS2 project)

PS C:\Users\jumbo> go get fyne.io/fyne/cmd/fyne_demo
# fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\jumbo\AppData\Local\Temp\go-link-735776751\000004.o: in function `glfwSetCursor':
C:\Users\jumbo\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.3\glfw/glfw/src/input.c:820: undefined reference to `__assert_func'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\jumbo\AppData\Local\Temp\go-link-735776751\000004.o: in function `glfwSwapBuffers':
C:\Users\jumbo\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.3\glfw/glfw/src/context.c:646: undefined reference to `__assert_func'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\jumbo\AppData\Local\Temp\go-link-735776751\000004.o: in function `glfwExtensionSupported':
C:\Users\jumbo\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.3\glfw/glfw/src/context.c:680: undefined reference to `__assert_func'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\jumbo\AppData\Local\Temp\go-link-735776751\000004.o: in function `glfwGetProcAddress':
C:\Users\jumbo\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.3\glfw/glfw/src/context.c:746: undefined reference to `__assert_func'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\jumbo\AppData\Local\Temp\go-link-735776751\000004.o: in function `glfwGetInputMode':
C:\Users\jumbo\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.3\glfw/glfw/src/input.c:476: undefined reference to `__assert_func'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\jumbo\AppData\Local\Temp\go-link-735776751\000004.o:C:\Users\jumbo\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.3\glfw/glfw/src/input.c:501: more undefined references to `__assert_func' follow
collect2.exe: error: ld returned 1 exit status

PS C:\Users\jumbo> go get -u github.com/go-gl/glfw/v3.3/glfw

Returns without error

**Comment by andydotxyz** [comment] 2021-01-21 17:28
It looks like your C libraries are 32bit with 64bit go. Duplicate of #174

**Closed by andydotxyz** 2021-01-21 17:28 UTC
Labels: bug

**Comment by gitspeaks** [comment] 2021-01-21 17:38
> It looks like your C libraries are 32bit with 64bit go. Duplicate of #174

Where do you see an indication for this ? I made sure to install x86_64-w64-mingw32 and run in 64 bit terminal.
