### ISSUE TITLE
Need for a Markup language

### ISSUE THREAD

**Issue by Srijan-Sengupta** [fyne-io/fyne#1482] opened 2020-10-28 10:44 UTC
### Description:
I am new to fyne an very happy exploring it. But I feel we need a markup language to to increase productivity. I have used some of the modern UI before and found the use of Markup languages. So, If there would be a Support for the markup languages, the it would help us explore this API and also increase productivity and it is good to separate UI designing from code (It helps in generating better code.)  
### Is it possible to construct a solution with the existing API?
Yes There Is...
### Describe the solution you'd like to see:
I would request you to make a package which would read from the a specified JSON file and would place the widgets accordingly and return a window or something like that..

**Comment by andydotxyz** [comment] 2020-10-28 11:00
I agree that in many toolkits this is absolutely required, but I'm not sure how a markup language makes the API easier to explore? Perhaps you can expand more on how you find the markup easier to work with than the code so we can understand the requirement better?

The Fyne API has worked hard to separate rendering details from the main code, so there is less "design specific code" in any application. We will be working on a GUI builder app in the future, so I don't know how a different text-based representation will help new developers? But like I said please feel free to tell us more!

**Comment by Srijan-Sengupta** [comment] 2020-10-28 11:59
You are correct that Markup languages may not help us to "Explore" and I am also glad on hearing that  you you have interest  on building a GUI builder. I proposed this because the next proposal would be to build a GUI builder. But would discard the proposal of a Markup language if you would give me a simple outline how can you can build it with out a markup language. 

I previously used Java in which there was a framework called JavaFX. It uses FXML as a markup language and SceneBuilder as the GUI Builder.
I mentioned it because I have used it and found it very easy for development and wanted Fyne to make something like this.

**Comment by andydotxyz** [comment] 2020-11-09 15:09
We will probably (not decided) use JSON or XML files to save state of the GUI builder.
Given that the reason for such state seemes to be based on GUI builder I will close this as duplicate of #227

**Closed by andydotxyz** 2020-11-09 15:09 UTC
Labels: question

**Comment by Srijan-Sengupta** [comment] 2020-11-09 15:23
Yes I agree! Sorry for disturbing.
