### ISSUE TITLE
SelectEntry chinese garbled 

### ISSUE THREAD

**Issue by kingangelAOA** [fyne-io/fyne#1079] opened 2020-06-05 10:44 UTC
### To Reproduce:
Steps to reproduce the behaviour:

### Screenshots:

![test](https://user-images.githubusercontent.com/15135537/83867771-86e1db80-a75c-11ea-9c3f-c03a50dbbe8a.png)

### Device (please complete the following information):
 - OS: Linux
 - Version: 18.04
 - Go version: 1.14
 - Fyne version: 1.2.4

**Comment by andydotxyz** [comment] 2020-06-05 13:20
Is this just selectEntry or does it apply to normal entry as well?
Perhaps it is a dupicate of #218

**Comment by kingangelAOA** [comment] 2020-06-05 13:23
Cannot enter Chinese after  

os.Setenv("FYNE_FONT", "xxxxxxxxxxxxx/FangZhengFangSongJianTi-1.ttf")

**Comment by andydotxyz** [comment] 2020-06-05 13:29
Have you tried setting it in your environment instead of SeteEnv?

**Comment by kingangelAOA** [comment] 2020-06-05 14:05
![test2](https://user-images.githubusercontent.com/15135537/83885264-b0106500-a778-11ea-9386-ef29bbca7d17.png)
 but Cannot enter Chinese

**Comment by andydotxyz** [comment] 2020-06-05 14:37
Thank you this makes sense.
Can you please confirm that, if set using SetText() the SelectEntry does display the characters?
I just want to confirm this is limited to the input isssue #73 :)

**Comment by kingangelAOA** [comment] 2020-06-06 03:52
![test3](https://user-images.githubusercontent.com/15135537/83935437-27cba780-a7ec-11ea-81c0-e2b95a4e627b.png)
![test4](https://user-images.githubusercontent.com/15135537/83935438-2dc18880-a7ec-11ea-8f2c-a5dbfd5fc3fe.png)

**Comment by andydotxyz** [comment] 2020-06-06 09:52
Thank you, but the original report is against SelectEntry, does that behave the same?

**Comment by andydotxyz** [comment] 2020-06-06 09:54
Another way to load fonts is using the theme API as recently discussed in #1055 - but if this issue relates to input rather than display then it will not help, as it’s the same result as using environment variables.

**Comment by kingangelAOA** [comment] 2020-06-08 02:56
![test111](https://user-images.githubusercontent.com/15135537/83988718-afddb880-a976-11ea-9b31-ece49b11e2a3.png)

**Comment by andydotxyz** [comment] 2020-06-08 09:06
Great, thanks for confirming. This seems like it is input-method related then.
Are you using a Chinese keyboard, or other software-based input device on your system?
I guess this relates to an upstream issue in GLFW? glfw/glfw#41

**Comment by andydotxyz** [comment] 2020-11-17 17:58
Closing as duplicate of #73

**Closed by andydotxyz** 2020-11-17 17:58 UTC
