### ISSUE TITLE
Support file deletion on Android

### ISSUE THREAD

**Issue by bon-ami** [fyne-io/fyne#3358] opened 2022-10-28 07:55 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

currently, I don't seem to be able to delete a file on Android.
```
(m *mobileFileRepo) Delete(u fyne.URI) error {
	// TODO: implement this
```
fyne 2.2.3

### Describe the solution you'd like to see.

I intended to use app.Storage().Remove(), since I cannot get URI of any files under app's Document/. I think implemention Delete() will fix this, too.

**Comment by andydotxyz** [comment] 2023-08-30 11:24
I just realised that this is a duplicate of #2120

**Closed by andydotxyz** 2023-08-30 11:24 UTC
Labels: OS:Android
