### ISSUE TITLE
Very long Label does not display text

### ISSUE THREAD

**Issue by XanderCheung** [fyne-io/fyne#4059] opened 2023-07-13 10:19 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When the text of the label is a long string, although a scroll bar appears, the text cannot be displayed

### How to reproduce

1. Assign a long string to the text of the label

### Screenshots

![20230713181749](https://github.com/fyne-io/fyne/assets/28296509/ae162ce6-f532-47d6-bc09-c4c035a76998)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Label Widget")

	s := ""
	for i := 0; i < 100; i++ {
		s += "this is long text "
	}

	myWindow.SetContent(
		container.NewScroll(
			widget.NewLabel(s),
		),
	)
	myWindow.Resize(fyne.NewSize(500, 300))
	myWindow.ShowAndRun()
}

```

### Fyne version

v2.3.5

### Go compiler version

1.19.2

### Operating system and version

macOS Monterey

**Comment by andydotxyz** [comment] 2023-07-13 11:23
I think this is a duplicate of #678

**Comment by Jacalz** [comment] 2023-08-18 20:07
Closing as duplicate

**Closed by Jacalz** 2023-08-18 20:07 UTC
Labels: duplicate
