### ISSUE TITLE
Non-English text & compose key

### ISSUE THREAD

**Issue by jadr2ddude** [fyne-io/fyne#38] opened 2018-12-09 21:24 UTC
While investigating something else, I attempted to enter bidirectional text into the form input. When pasting Hebrew text into the form demo, I was shown a broken Unicode symbol. Additionally, when attempting to enter `æ`, Fyne intercepted my compose key and caused the system to instead enter `ae`.

So the main parts of this are:
1. Add support for rendering non-English text (adjust fonts, etc.) (done - 7d2d312)
2. Test support for Unicode Bidirectional Text
3. Fix support for compose key on Linux

Possible test inputs:
`שרה` - Hebrew text, right to left
`قرأ Wikipedia™‎ طوال اليوم.‎` - combination of Arabic and English text (RTL and LTR, respectively), with a Unicode character with weak directionality (`™`)
`שרה is Sarah in Hebrew` - combination of Hebrew and English text (RTL and LTR, respectively)

If you are confused, consider editing these text samples in a graphical editor or consulting these references:
https://en.wikipedia.org/wiki/Bi-directional_text
https://unicode.org/reports/tr9/

**Comment by andydotxyz** [comment] 2018-12-09 23:01
I think the first issue you see is because copy-paste is not handled correctly, we need to look into that.

Unicode should be supported but bidirectional probably not - this will need work also. The unicode support should be correct in the default driver - but perhaps not with the new GL based one. 

I need to look more into the compose key - I am not sure if it's an input or a display issue yet.
Thanks!

**Comment by andydotxyz** [comment] 2019-01-09 09:56
OK, I see now there is a lot to handle here.
Firstly, æ and ™ should now be working - they render correctly. Possibly there is still an issue with the compose key? If so can you please provide a test case or reproduction steps for someone with an English keyboard?

The non-english text issue is perhaps going to be complicated. I wonder if we can ship a better default font? Or is switching fonts the only "right" way to do this?

(the hebrew and arabic are not working with the replacement text handling)

**Comment by andydotxyz** [comment] 2019-01-18 18:02
I have a local patch that allows setting fonts, which is a thing we should do... but it brought more questions for me. When using a Hebrew font, for example, it does not contain the English text - which breaks the English display...

Does anyone know how we can "multiplex" these - to see if a font has a glyph and fallback (to builtin) if it does not?

**Comment by andydotxyz** [comment] 2019-01-20 20:59
With the updated font handling I think we are getting closer.
Compose key is working on my Arch Linux system (Shift + Alt-Gr -> ~ -> a -> ã).
If it is not working for your system can you open a new issue with the details please?

I reckon that the contents of this are now either resolved or created in more specific issues.
I'm closing this so we can track the remaining work separately.

**Closed by andydotxyz** 2019-01-20 20:59 UTC
Labels: help wanted

**Comment by dtrehas** [comment] 2021-02-16 03:22
Ubuntu 20.10
Accented greek characters (greek keyboard,semi-colon+vowel) do not appear at all.
Thank you for your wonderful work.

**Comment by andydotxyz** [comment] 2021-02-21 20:36
It's possible the letters are not in our font, can you confirm which were not appearing.
If you paste them in instead of typing them does it work?

**Comment by thebenwaters** [comment] 2021-04-05 14:12
I was able to get Hebrew to work

https://github.com/thebenwaters/ynaboosh-desktop/blob/b9f8f81c1806e631dca17df62a1d41acb188dee7/pkg/internal/ynaboosh/institutions/cal.go#L33

Currently I load a custom font (Noto Hebrew) and then detect Hebrew with regex, and reverse runes, but if it's mixed with english, I haven't separated it out
