### ISSUE TITLE
Input Method Box Stuck in Top-Left Corner When Typing Chinese

### ISSUE THREAD

**Issue by terry2010** [fyne-io/fyne#4546] opened 2024-01-17 04:10 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When inputting Chinese characters, the input method's candidate box fails to acquire input focus coordinates, resulting in it consistently staying in the top-left corner of the screen

### How to reproduce

1.run latest fyne_demo
2.click widgets->form
3.Input Chinese characters

ps : could use microsoft input or [qq pinyin ](https://qq.pinyin.cn/)

### Screenshots

The area enclosed by the red box in this screenshot shows that, when users input Chinese characters in a browser's textarea, the input method candidate box correctly obtains the input focus coordinates and appears in the correct position.
![图片](https://github.com/fyne-io/fyne/assets/1849037/f9752acc-5ed5-4b10-9974-3b3ef63320ed)

The area enclosed by the red box in this screenshot illustrates that, when users input Chinese characters in the fyne_demo form, the input method candidate box fails to obtain the input focus coordinates and appears in the incorrect position at the top-left corner of the screen
qq pinyin:
![图片](https://github.com/fyne-io/fyne/assets/1849037/51152180-2fe7-478c-a80d-607615e9456a)
microsoft chinese pinyin:
![图片](https://github.com/fyne-io/fyne/assets/1849037/e3e4ed82-9329-4ab5-81b2-1a51a4bf4d0e)

### Example code

just use latest demo

### Fyne version

latest

### Go compiler version

1.20

### Operating system and version

windows 10

**Comment by andydotxyz** [comment] 2024-01-17 09:42
I think this is a duplicate of #618

**Closed** 2024-01-24 18:02 UTC
Labels: duplicate
