### ISSUE TITLE
Use CPU time even nothing heavy 

### ISSUE THREAD

**Issue by sunshine69** [fyne-io/fyne#3295] opened 2022-09-29 00:56 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Hi there,

I am not sure if it is intended normal operations but to me it is not acceptable behavior so I log it as a bug. If not then please close it.

So I am exited to try and just run the code sample from the project page to show a tiny windows with a button click `hello` things. However I noticed the program takes around 2% of CPU time idling there sometimes jump up to 3% *constantly*.

I understand just rendering the tiny window no no processing consuming that much of CPU time? 

Compare with my desktop golang note application which uses the gtk3 binding, which has full features of notes/processing etc.. it never use any CPU when it is idle and even when it is do searching notes/save or text processing, it uses less than 1% cpu time on my desktop for a short time and then idle again.

So in my opinion it is not economical at all. I can not use it if it is like that and can not be fixed, or sort of it is the way it is.

It is running on Ubuntu 22.04.1 desktop. Yes 3D graphic accelerations supported. 

I hope this is something in my hardware/computer caused it then I tried to run it on another laptop same OS but different hardware and the 3D graphics driver is known to be fully supported. Still the same result - it even uses more 4% CPU due to the laptop has lower CPU specs.

Is it known - not a problems or a  problem that your guys still work on?

Thank you for listening.

### How to reproduce

create a test go mod and copy paste the example code below and run

### Example code

code is in the example page

```
cat fyne-gui/main.go 
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}

```

### Fyne version

 fyne.io/fyne/v2 v2.2.3

### Go compiler version

go version go version go1.19.1 linux/amd64

### Operating system

Linux

### Operating system version

Ubuntu 22.04.1

**Comment by Jacalz** [comment] 2022-09-29 09:48
Likely duplicate of https://github.com/fyne-io/fyne/issues/2506.

**Comment by sunshine69** [comment] 2022-09-30 11:04
because it is duplicated

**Closed** 2022-09-30 11:04 UTC
Labels: unverified

**Comment by Bluebugs** [comment] 2022-10-01 18:55
Not sure it is a duplicate actually as the problem on the other issue is mostly related to watching file on macos, while here it seems to be a more general issue due to how we schedule rendering.

**Comment by andydotxyz** [comment] 2022-10-04 05:14
When nothing is changing in the window no renders should be scheduled, it is just sitting waiting for events
