### ISSUE TITLE
bluetooth as far futures feature 

### ISSUE THREAD

**Issue by MatejMagat305** [fyne-io/fyne#2457] opened 2021-09-11 17:26 UTC
maybe it is silly request(idea), but I put there because it is sometime anoying tzo search to right library........... 
### Is your feature request related to a problem? Please describe:
No

### Is it possible to construct a solution with the existing API?
So It is real for https://github.com/therecipe/qt, but I m not sure wheter exist simplier library.........., which would be simple enought to integrate to this projekt

### Describe the solution you'd like to see:
So I m trying apply this: https://stackoverflow.com/questions/28991228/getting-android-bluetooth-adapter-name-from-jni-c
and (momentaly) this:  https://github.com/MarinX/goble, but I had tried until now two library and nothing.........., I also trying: https://github.com/paypal/gatt (with change manifest according https://pkg.go.dev/gioui.org/app/permission/bluetooth), but it "print" to label "permission denied"

**Comment by andydotxyz** [comment] 2021-09-11 21:37
To access bluetooth on Android you currently need to enable that in your manifest.
If you have an `AndroidManifest.xml` in your project root then it will be used instead of the automatically-generated one. 
I think this is a duplicate of #2382

**Comment by andydotxyz** [comment] 2021-09-11 21:38
Close as dupe

**Closed by andydotxyz** 2021-09-11 21:38 UTC
Labels: duplicate
