### ISSUE TITLE
Tables do not render fully on develop

### ISSUE THREAD

**Issue by rkmpa** [fyne-io/fyne#3443] opened 2022-11-30 21:57 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

A simple table does not render fully on latest [develop](https://github.com/fyne-io/fyne/commit/dbdb9fc26091aa11aa05fb2ff7067589f63bfedd). After clicking a cell, the previously missing cells render correctly. Unlike in v2.2.4, resizing the window to cover all available screen space does not trigger the cells to render. 

### How to reproduce

1. Setup Ubuntu 22.04.01 LTS
2. Download Go v1.18.1
3. Run code below after setting up Fyne

### Screenshots

![Bildschirmfoto vom 2022-11-30 22-47-53](https://user-images.githubusercontent.com/107888696/204915793-6ae9ed98-9e4e-4254-84bf-b824fb52f13f.png)

:point_up_2: before clicking cell

![Bildschirmfoto vom 2022-11-30 22-48-11](https://user-images.githubusercontent.com/107888696/204915804-90f67e21-327d-46d1-ba7c-9ff3d018bd42.png)

:point_up_2: after clicking cell

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {

	fyneApp := app.New()
	window := fyneApp.NewWindow("Playground")

	tableData := [][]string{
		{"Col 1", "Col 2", "Col3"},
		{"1", "2", "3"},
		{"4", "5", "6"}}

	table := widget.NewTable(func() (int, int) {
		return 3, 3
	},
		func() fyne.CanvasObject {
			return widget.NewLabel("")
		},
		func(tci widget.TableCellID, co fyne.CanvasObject) {
			co.(*widget.Label).SetText(tableData[tci.Col][tci.Row])
		})

	table.SetColumnWidth(0, 40)
	table.SetColumnWidth(1, 40)
	table.SetColumnWidth(2, 40)

	window.Resize(fyne.Size{1000, 1000})
	window.SetContent(table)
	window.ShowAndRun()

}
```

### Fyne version

v2.2.5-0.20221129230658-dbdb9fc26091

### Go compiler version

v1.18.1

### Operating system

Linux

### Operating system version

Ubuntu 22.04.1 LTS

**Comment by andydotxyz** [comment] 2022-12-01 22:11
Adding blocker as this is a regression

**Comment by ddkwork** [comment] 2022-12-01 23:23
> This seems to be only an issue when the table is larger than its content.
> Not sure how this slipped by!

i have the same problem.

**Comment by eliranwong** [comment] 2022-12-03 18:59
I encounter the same issue, the only workaround I found, so far, is to scroll to the bottom when it is loaded.

> table.ScrollToBottom()

Obviously, it is not a good solution, please kindly let me know if there is a better one.

**Comment by andydotxyz** [comment] 2022-12-03 22:18
I'm not much for recommending workarounds. But I can say this will be fixed in the upcoming release v2.3.0 that we are testing.

**Comment by andydotxyz** [comment] 2022-12-04 18:28
After a false start looks like that is resolved (in the PR)

**Comment by andydotxyz** [comment] 2022-12-06 20:39
Fixed on develop ready for v2.3.0

**Closed** 2022-12-06 20:39 UTC
Labels: bug, blocker

**Comment by junmaqiang** [comment] 2023-01-07 05:50
![WX20230107-134942](https://user-images.githubusercontent.com/1819457/211133378-51db9901-2e0f-41b8-9e6d-c35e10337b13.png)

**Comment by Jacalz** [comment] 2023-01-07 07:15
@junmaqiang If you have questions, please direct them on slack or through discussions. This is a solved issue and not the right place to ask unrelated questions. Thanks for understanding.
