### ISSUE TITLE
Remove "Folder" from FolderDialog -> makeUI() and set same as f.file.confirmText

### ISSUE THREAD

**Issue by Cheeches** [fyne-io/fyne#3373] opened 2022-11-03 10:13 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The problem is that the FolderDialog title contains "Folder". Better set the title the same as the confirmText or add a function to set the dialog title.

### Is it possible to construct a solution with the existing API?

-

### Describe the solution you'd like to see.

Dialog is editable or the label Part "Folder" is removed

**Comment by andydotxyz** [comment] 2022-11-03 20:00
> The problem is that the FolderDialog title contains "Folder". 

I don't understand this sorry - can you expand on why the standard title is not OK?

**Comment by Cheeches** [comment] 2022-11-03 20:25
Because if you set the ConfirmText in german the dialog title contains still the english word "Folder" and that can't be changed see screenshot. [https://iili.io/mBSpe9.png](url)

**Comment by andydotxyz** [comment] 2022-11-04 18:08
Ah yes thank you. So the request is really for localisation support. This impacts a lot more than just one dialog title - there are lots of standard text in dialog and menus, they all need to be fixed as part of the work for better language support.

**Comment by Jacalz** [comment] 2022-11-12 20:21
I agree with @andydotxyz. It is better to solve all of the internationalisation in one coherent measure rather than adding half-baked solutions in just some places. Will close this as, more or less, a duplicate of #605.

**Closed by Jacalz** 2022-11-12 20:21 UTC
