### ISSUE TITLE
Single click in file dialog enters two directories

### ISSUE THREAD

**Issue by codesoap** [fyne-io/fyne#5053] opened 2024-08-05 08:44 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When clicking a directory in a file dialog, the dialog will go two directories deeper instead of one, whenever possible.

This has been reported to me by a @vaibhav-kaushal: https://github.com/codesoap/spind/issues/1

### How to reproduce

1. Run `go run fyne.io/fyne/v2/cmd/fyne_demo@v2.5.0`.
2. Go to the "Dialogs" tab.
3. Click "Folder Open".
4. Now click a directory which also contains a directory "at the same position"; this means if the first directory is, e.g., the third entry, this directory should also contain another directory as its third entry.

In case I didn't explain 4. well enough, here is an example: Create `mkdir -p /tmp/foo/bar/baz`, then go to `/tmp/foo` with the file dialog and click "bar". Instead of just changing directory to "bar", fyne will directly go to "bar/baz".

### Example code

`go run fyne.io/fyne/v2/cmd/fyne_demo@v2.5.0`

### Fyne version

54b25af3ce9ed44005867999a7fc8ee69da42cc1

### Go compiler version

go version go1.22.1 openbsd/amd64

### Operating system and version

OpenBSD 7.5

### Additional Information

`git bisect` shows me that 54b25af3ce9ed44005867999a7fc8ee69da42cc1 introduced the bug.

**Comment by hfmrow** [comment] 2024-08-12 02:09
Hi,
I can confirm this issue. I'm using W10, Fyne v2.5, Go 1.22.6 and I've had to create my own file explorer to work around this issue. I've also tested it on Android and, since the file explorer uses the native Android version, the problem doesn't occur there.

**Comment by andydotxyz** [comment] 2024-08-12 16:57
Yes I have started to see this as well. Let's try and get it fixed ASAP

**Comment by andydotxyz** [comment] 2024-08-12 17:25
I have a fix ready, just want to get some tests in and I'll open a PR. We will get this fixed in 2.5.1.

**Comment by andydotxyz** [comment] 2024-08-12 17:25
Adding blocker as this is a pretty bad regression.

**Comment by hfmrow** [comment] 2024-08-13 01:00
@andydotxyz Thank you.

**Comment by andydotxyz** [comment] 2024-08-14 17:10
Fixed  landed ready for v2.5.1

**Closed by andydotxyz** 2024-08-14 17:10 UTC
Labels: bug, blocker, FileDialog

**Comment by codesoap** [comment] 2024-08-14 20:00
Thanks!
