### ISSUE TITLE
Support for tab character on focused entry widget

### ISSUE THREAD

**Issue by spatocode** [fyne-io/fyne#487] opened 2019-10-13 19:03 UTC
**Is your feature request related to a problem? Please describe.**
Currently the tab key supports moving through focused items. However, the tab key doesn't support tab characters on a focused entry widget. Also, on pasting a tab character on the entry widget, the result shows that fyne doesn't support tab characters yet.

**Is it possible to construct a solution with the existing API?**
Yea, i think it's quite possible.

**Describe the solution you'd like**
As the tab key is currently supporting moving of focused items on the fyne canvas. It should also support tab characters only on focused entry widget.

**Comment by andydotxyz** [comment] 2019-10-13 22:18
An interesting question - do you have thoughts on how this should work?
Having it on by default seems unwise as form input basically relies on it.

I wonder if it’s a feature of the upcoming “TextGrid” or “CodeEntry” widget as that is where tab is usually needed?

**Comment by spatocode** [comment] 2019-10-15 13:41
Well, this is tricky. 

> Having it on by default seems unwise as form input basically relies on it.

Yes, i think you're right on that as tab characters are not usually needed on basic inputs. If that's the case, i think it's more of a feature of the "CodeEntry" widget.

**Comment by andydotxyz** [comment] 2019-10-15 19:28
Maybe this can be closed as duplicate of #115?

**Closed** 2019-10-15 22:20 UTC
