### ISSUE TITLE
boxLayout crash when items rapidly added and removed

### ISSUE THREAD

**Issue by zdima** [fyne-io/fyne#2481] opened 2021-09-19 02:15 UTC
### Describe the bug:
The boxLayout.MinSize or boxLayout.Layout crashing when items rapidly added and removed from the NewVBox container.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the code from example below and app will crash with "invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation]" at layout/boxlayout.go:63 or layout/boxlayout.go:125.

### Example code:
```go
package main

import (
	"fmt"
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
)

var maxLines = 40

func main() {

	a := app.New()
	w := a.NewWindow("test")

	box := container.NewVBox()
	sc := container.NewVScroll(box)
	w.SetContent(sc)
	w.Resize(fyne.NewSize(400, 400))

	go func() {

		addLine := func(line string) {
			t := canvas.NewText(line, color.Black)
			t.TextStyle = fyne.TextStyle{Monospace: true}
			box.Add(t)
			for len(box.Objects) > maxLines {
				box.Remove(box.Objects[0])
			}
			sc.ScrollToBottom()
		}

		for i := 0; i < 5000; i++ {
			line := fmt.Sprintf("%04d:", i)
			addLine(line)
		}
		addLine("end")
	}()

	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 11.6
 - **Go version:** go1.16.5 darwin/arm64
 - **Fyne version:** 6e90820ea9ca4df836db5a99384c51073415571e

**Comment by andydotxyz** [comment] 2021-09-22 21:27
I think this is probably a duplicate of #1028, but we should keep it open as a clear reproduction case for the underlying issue

**Comment by Jacalz** [comment] 2022-03-11 17:01
Closing as a duplicate of https://github.com/fyne-io/fyne/issues/2826.

**Closed by Jacalz** 2022-03-11 17:01 UTC
Labels: bug, duplicate
