### ISSUE TITLE
Entry cursor is not visible with animations off

### ISSUE THREAD

**Issue by easycat** [fyne-io/fyne#4508] opened 2024-01-03 09:33 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When the Entry box receives focus, CPU usage will increase slightly.  When there are many controls on a poorly configured machine, the window CPU usage can be high, even reaching up to 50%. This can make it difficult or impossible to input text properly.

### How to reproduce

in the centos8 or other linux.

The code you provided compiles and runs on Linux.

﻿When there are no operations performed, the CPU usage can be observed to range from approximately 1% to 3% using top comma.
When the mouse clicks on an Entry control widget, the CPU usage will increase to around 7-8%.
﻿After clicking a button (focus is move out form Entry), the CPU usage will decrease to approximately 3% left or right.

I tried disabling the animation of the Entry widget, but despite the above operations, there was no significant increase in CPU usage. However, the cursor did not show up.

![image](https://github.com/fyne-io/fyne/assets/773169/3df7b7af-0e51-4021-b5b2-834a8715e9e5)

### Screenshots

The focus is not on the Entry.
![image](https://github.com/fyne-io/fyne/assets/773169/ceaff0ae-4a93-4b66-816c-9634496b9046)
The focus on the Entry.
![image](https://github.com/fyne-io/fyne/assets/773169/939a7ef0-7c6e-4daa-bf39-c19940290b3b)
The focus move out Entry.
![image](https://github.com/fyne-io/fyne/assets/773169/873bac8f-8f56-4b28-97d4-315afbcbf2a7)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewEntry()
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Fyne version

2.4.3, 2.4.2, 2.4.1, 2.3.5

### Go compiler version

1.18.10

### Operating system and version

centos8 or other linux

**Comment by andydotxyz** [comment] 2024-01-03 11:18
You could disable animations using the build tag no_animations https://docs.fyne.io/explore/compiling

**Comment by easycat** [comment] 2024-01-04 02:06
> You could disable animations using the build tag no_animations https://docs.fyne.io/explore/compiling

This operation is similar to my commented code. It does not require any changes to the underlying fyne library. It solves the problem of high CPU usage, but there is no input cursor for this operation. 

I see that the above code actually has cursor.Show(). Show() in the code above, but for some reason it doesn't show it.

**Comment by easycat** [comment] 2024-01-04 02:40
> You could disable animations using the build tag no_animations https://docs.fyne.io/explore/compiling

With animation disabled. The cursor doesn't have a color. I don't know if this is the original design intent. The following code change adds a new line and I added a comment. This solves the problem of the cursor not showing up when there is no animation. 

I'm not very familiar with fyne's own code. Please help me to see the right place to add this line and the right parameters.

```go
func (r *entryContentRenderer) Refresh() {
	r.content.entry.propertyLock.RLock()
	provider := r.content.entry.textProvider()
	placeholder := r.content.entry.placeholderProvider()
	focusedAppearance := r.content.entry.focused && !r.content.entry.disabled
	selections := r.selection
	r.updateScrollDirections()
	r.content.entry.propertyLock.RUnlock()

	if provider.len() == 0 {
		placeholder.Show()
	} else if placeholder.Visible() {
		placeholder.Hide()
	}

	if focusedAppearance {
		r.cursor.Show()
		if fyne.CurrentApp().Settings().ShowAnimations() {
			r.content.entry.cursorAnim.start()
		} else {
			r.cursor.FillColor = theme.PrimaryColor() // set a color on no_animations mode
		}
	} else {
		r.content.entry.cursorAnim.stop()
		r.cursor.Hide()
	}
	r.moveCursor()

	for _, selection := range selections {
		selection.(*canvas.Rectangle).Hidden = !r.content.entry.focused
		selection.(*canvas.Rectangle).FillColor = theme.SelectionColor()
	}

	canvas.Refresh(r.content)
}
```

**Comment by andydotxyz** [comment] 2024-01-04 14:39
> With animation disabled. The cursor doesn't have a color. I don't know if this is the original design intent. The following code change adds a new line and I added a comment. This solves the problem of the cursor not showing up when there is no animation.

Thanks for this, that is indeed a bug.

Your proposed solution looks great, you can probably edit the file in GitHub to propose the change.
If the `Show` is moved to after that animation if block then it should ensure the colour is set without causing an additional refresh.

Thanks for the help.

**Comment by dweymouth** [comment] 2024-01-04 17:46
This is a duplicate of #1946 which still needs to be addressed in some way. (EG making the animation faster so there is a short rest period between blink-in and blink-out, or on desktop disabling the cursor animation entirely as it's not standard on desktops)

**Comment by andydotxyz** [comment] 2024-01-05 09:15
It is still tracking a separate bug whereby with animations off the cursor will not be visible - so let's not close as duplicate.
Though the original problem should be addressed too. Though with various optimisations the issue is much less impactful.

**Comment by dweymouth** [comment] 2024-01-07 18:59
Changing title to reflect the bug this will be tracking

**Comment by dweymouth** [comment] 2024-01-07 19:02
>  Though with various optimisations the issue is much less impactful.

It's still pretty impactful though. In Supersonic, if it's sitting idle but with the search bar focused, it uses 2x-3x the CPU load than if it's playing music but without any Entry widget focused

**Closed** 2024-08-02 16:45 UTC
Labels: bug
