### ISSUE TITLE
How could I use FYNE_FONT on a mobile simulator(android arm64)?

### ISSUE THREAD

**Issue by sanguohot** [fyne-io/fyne#2921] opened 2022-04-14 09:10 UTC
This is the error log.
![image](https://user-images.githubusercontent.com/25117034/163351784-12d39118-314d-4730-8a66-72cb0aaafb10.png)
This is my code and I could not found any other api.
```
	dir, _ := os.Getwd()
	os.Setenv("FYNE_FONT", filepath.Join(dir, "assets", "static", "Consolas-with-Yahei Regular Nerd Font.ttf"))
```
Can you give me a example, thanks!

**Comment by andydotxyz** [comment] 2022-04-14 14:13
It would be more portable to bundle the font (using fyne bundle) and reference the font from a custom theme.
More info at https://developer.fyne.io/extend/custom-theme.
The FYNE_THEME was intended as user customisation - to make this part of the application you should follow the steps above.

**Comment by sanguohot** [comment] 2022-04-15 03:07
> It would be more portable to bundle the font (using fyne bundle) and reference the font from a custom theme. More info at https://developer.fyne.io/extend/custom-theme. The FYNE_THEME was intended as user customisation - to make this part of the application you should follow the steps above.

Thank you for your suggestion, but I would like to use **go embed**. Also as ttf is so big, so would you please support to replace the builtin one with other ttf, just like chinese ttf?
This is my example code.
```
package customCmp

import (
	_ "embed"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
	"github.com/sanguohot/sghproxy/assets"
	"image/color"
)

type CustomTheme struct{}

var resourceConsolasWithYaheiRegularNerdFontTtf = &fyne.StaticResource{
	StaticName:    "ConsolasWithYaheiRegularNerdFont.ttf",
	StaticContent: assets.ConsolasWithYaheiRegularNerdFont,
}

var resourceConsolaswithYaheiBoldItalicNerdFontTtf = &fyne.StaticResource{
	StaticName:    "ConsolaswithYaheiBoldItalicNerdFont.ttf",
	StaticContent: assets.ConsolaswithYaheiBoldItalicNerdFont,
}

var resourceConsolasWithYaheiItalicNerdFontTtf = &fyne.StaticResource{
	StaticName:    "ConsolasWithYaheiItalicNerdFont.ttf",
	StaticContent: assets.ConsolasWithYaheiItalicNerdFont,
}

var resourceConsolasWithYaheiBoldNerdFontTtf = &fyne.StaticResource{
	StaticName:    "ConsolasWithYaheiBoldNerdFont.ttf",
	StaticContent: assets.ConsolasWithYaheiBoldNerdFont,
}

func NewCustomTheme() fyne.Theme {
	return &CustomTheme{}
}

func (m CustomTheme) Font(s fyne.TextStyle) fyne.Resource {
	if s.Bold && s.Italic {
		return resourceConsolaswithYaheiBoldItalicNerdFontTtf
	}
	if s.Bold && !s.Italic {
		return resourceConsolasWithYaheiBoldNerdFontTtf
	}
	if !s.Bold && s.Italic {
		return resourceConsolasWithYaheiItalicNerdFontTtf
	}
	// Monospace or Regular
	return resourceConsolasWithYaheiRegularNerdFontTtf
}

func (*CustomTheme) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	return theme.LightTheme().Color(n, v)
}

func (*CustomTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.LightTheme().Icon(n)
}

func (*CustomTheme) Size(n fyne.ThemeSizeName) float32 {
	return theme.LightTheme().Size(n)
}
```
This is my fonts and embed_theme.go
![image](https://user-images.githubusercontent.com/25117034/163510333-db381809-92d4-4ac2-8c67-2303c7218f88.png)
And then
`fyne.CurrentApp().Settings().SetTheme(customCmp.NewCustomTheme())`

**Comment by andydotxyz** [comment] 2022-04-16 21:40
The builtin TTF is quite small, but even so removing it could break internal functionality, so we don’t support that (depending on what your replacement font is).

P.s. you can use go embed instead of fyne embed if you want - whichever is easier for you.

**Comment by Jacalz** [comment] 2023-05-06 10:00
It looks like the question has been answered. I'll close this for now.

**Closed by Jacalz** 2023-05-06 10:00 UTC
Labels: question
