### ISSUE TITLE
APK file keeps closing

### ISSUE THREAD

**Issue by ccpplinux** [fyne-io/fyne#2626] opened 2021-11-06 12:18 UTC
I have created an APK file using program given at https://developer.fyne.io/started/firstapp.html and following command given at https://developer.fyne.io/started/packaging-mobile. I have installed that APK file in my Moto C Plus phone. But when I am opening this app in my mobile then it keeps stopping. It is not running. What could be problem? How to fix it?

**Comment by andydotxyz** [comment] 2021-11-07 20:38
We would need more information than this - the android apps are all logging and you can see what is happening with `adb logcat`.

Please in the future use the bug template so we can get appropriate information about versions and devices.
If your Android device is 32bit and you are using Fyne v2.1.1 there is a known issue and the upcoming v2.1.2 resolves it.

**Comment by ccpplinux** [comment] 2021-11-08 04:54
Thanks for reply. I have checked kernel information of my phone. It is not containing the string x64 and so I think that it is 32 bit. Since I am using the latest version of fyne which is v2.1.1 and so I think it is creating problem. Can you please tell me which version should I try which will generate correct APK file for both 32 bit and 64 bit devices?

**Comment by andydotxyz** [comment] 2021-11-08 10:17
The latest commit on that branch is `cb91a71`, give that a shot as the version number.

**Comment by andydotxyz** [comment] 2021-12-07 03:18
@ccpplinux we have now released `v2.1.2`, can you please test with that version?

**Comment by ccpplinux** [comment] 2021-12-07 03:59
> @ccpplinux we have now released `v2.1.2`, can you please test with that version?

Thanks for letting me know. I will test the latest version and then let you know.

**Comment by ccpplinux** [comment] 2021-12-07 04:10
Is there any possibility of making use of web assembly to generate web app from the same code base of fyne similar to https://gioui.org/ so that we can generate both mobile and web app?

**Comment by Bluebugs** [comment] 2021-12-07 16:06
> Is there any possibility of making use of web assembly to generate web app from the same code base of fyne similar to https://gioui.org/ so that we can generate both mobile and web app?

We are currently working on it. I am hoping to land that support in the develop branch in the coming weeks. Hopefully a Christmas gift :-)

**Comment by ccpplinux** [comment] 2021-12-07 18:16
> > Is there any possibility of making use of web assembly to generate web app from the same code base of fyne similar to https://gioui.org/ so that we can generate both mobile and web app?
> 
> We are currently working on it. I am hoping to land that support in the develop branch in the coming weeks. Hopefully a Christmas gift :-)

Great news. If it will really happen then it will be a milestone for this framework. I am eagerly waiting for it.

**Comment by andydotxyz** [comment] 2022-02-10 02:31
> Great news. If it will really happen then it will be a milestone for this framework. I am eagerly waiting for it.

Early versions (working well on Firefox and Safari) are working on `develop` branch now.

**Comment by andydotxyz** [comment] 2022-02-10 02:32
> Thanks for letting me know. I will test the latest version and then let you know.

Can you please let me know whether the issue is resolved in the latest release?

**Comment by andydotxyz** [comment] 2023-01-03 09:56
Closing due to lack of activity

**Closed** 2023-01-03 09:56 UTC
Labels: information-needed
