### ISSUE TITLE
Android Preferences() not saved?

### ISSUE THREAD

**Issue by DaleEMoore** [fyne-io/fyne#3062] opened 2022-06-11 20:43 UTC
### Describe the bug:
This code works as expected on Linux. It saves Preferences and the saved Preferences are present on the next execution of the program. The same program "fyne-cross android" appears to function correctly, but on the next program invocation the previous execution's preferences had not been written.

### To Reproduce:
1. Each time you tap the "Test button" resp.After grows a few characters.
2. Exit the program.
3. Open the program again.
4. See error... there is nothing in the resp.After Preferences() item. Tapping "Test button" appears to work correctly but on next execution there's nothing there.

### Example code:
```go
// prefs.go by DaleEMoore@gMail.Com to clarify Fyne Preferences usage.

// It appears that app.Preferences().SetString() might not ALWAYS write the preferences.json file.

package main

import (
	"errors"
	"fmt"
	app "fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"log"
	"os"
	"runtime"
)

var version = "prefs version 0.0.4"
var theApp = "net.mooreworks.prefs"
var appZ = app.NewWithID(theApp)
var prefLoc = appZ.Storage().RootURI().Path() + fmt.Sprintf("%c", os.PathSeparator) + "preferences.json"

func init() {
	log.SetFlags(log.LstdFlags | log.Llongfile) // Path and File name
	log.Println("init log with path and file name")
	log.SetFlags(log.LstdFlags | log.Lshortfile) // File name
	log.Println("init log with file name")

	s1, err := os.Hostname()
	if err != nil {
		log.Println("Hostname err: ", err)
	}
	log.Println("hostname: ", s1)

	s1, err = os.Getwd()
	if err != nil {
		log.Println("Getwd err", err)
	}
	log.Println("cwd:", s1)
}

func isFilePresent(pathAndFile string) {
	if _, err := os.Stat(pathAndFile); err == nil {
		// path/to/whatever exists
		log.Println(pathAndFile + " exists")
	} else if errors.Is(err, os.ErrNotExist) {
		// path/to/whatever does *not* exist
		log.Println(pathAndFile + " does NOT exist")
	} else {
		// Schrödinger: file may or may not exist. See err for details.
		// Therefore, do *NOT* use !os.IsNotExist(err) to test for file existence
		log.Println(pathAndFile + " MIGHT exist")
	}
}

func prefsStuff() {
	log.Println("Preferences path", appZ.Storage().RootURI().Path())
	isFilePresent(prefLoc)
	//s1 := appZ.Storage().RootURI().Path() + fmt.Sprintf("%c", os.PathSeparator) + "preferences.json"
	//log.Println("Remove ", s1)
	//os.Remove(s1)

	log.Println("Test_preferences")
	respAfter := appZ.Preferences().StringWithFallback("resp.After", "")
	log.Println("resp.After", respAfter)

	appZ.Preferences().SetString("resp.After", respAfter+"1")
	respAfter = appZ.Preferences().String("resp.After")
	log.Println("resp.After", respAfter)

	appZ.Preferences().SetString("resp.After", respAfter+"2")
	respAfter = appZ.Preferences().String("resp.After")
	log.Println("resp.After", respAfter)

	appZ.Preferences().SetString("resp.After", respAfter+"3")
	respAfter = appZ.Preferences().String("resp.After")
	isFilePresent(prefLoc)
	log.Println("resp.After", respAfter)
}

func main() {
	log.Printf(version + " start")
	log.Printf("GOOS: %s.\n", runtime.GOOS)
	win3 := appZ.NewWindow("Test window")
	respAfter := appZ.Preferences().StringWithFallback("resp.After", "")
	log.Println("resp.After", respAfter)
	l1 := widget.NewLabel("resp.After:" + respAfter)
	win3.SetContent(container.NewVBox(widget.NewLabel("Test label"), l1,
		widget.NewLabel("version "+version),
		widget.NewButton("Test button", func() {
			prefsStuff()
			respAfter = appZ.Preferences().StringWithFallback("resp.After", "")
			l1.Text = "resp.After" + respAfter
			l1.Refresh()
		}),
	))
	// TODO, how do I auto-run something inside win3?
	win3.ShowAndRun()
	appZ.Quit()
	log.Printf(version + " end")
}
```

### Device (please complete the following information):
 - **OS:**  Android
 - **Version:**  12 
 - **Go version:**  1.18.1
 - **Fyne version:**  v2.1.4

**Comment by Jacalz** [comment] 2022-06-12 07:34
Can you please clean up the example code sot hat it only has the necessary code to replicate this issue and not anything else? It makes it a lot easier to debug and see where something is going wrong. 
 
I would also strongly recommend against creating the application as a global variable (see http://stackoverflow.com/questions/484635/ddg#485020). The reason that I bring it up here is basically because I know before that we have had some issues with in which order Go crates the values for the global variables. It probably isn’t the cause of this issue but it would certainly eliminate one more possible source of the issue.

**Comment by Jacalz** [comment] 2022-06-12 07:35
Also, can you please test with the v2.2.0 release? There might be something that has changed.

**Comment by DaleEMoore** [comment] 2022-06-12 10:35
v2.2.0 did not fix my problem.

Hurrah YOU for recognizing my possible misuse of Global Variables. I got rid of my Global Variables and the code now works properly on Android. 
`// prefs.go by DaleEMoore@gMail.Com to clarify Fyne Preferences usage.

// It appears that app.Preferences().SetString() might not ALWAYS write the preferences.json file.

/* gitHub issue with example code and slack not pointing Andy at the issue.
https://github.com/fyne-io/fyne/issues/3062
https://app.slack.com/client/T029RQSE6/CB4QUBXGQ/thread/CB4QUBXGQ-1654267000.229899
*/

package main

import (
	"errors"
	"fmt"
	fyne "fyne.io/fyne/v2"
	app "fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"log"
	"os"
	"runtime"
)

/* There is a case to be made that Global Variables are BAD!
   https://stackoverflow.com/questions/484635/are-global-variables-bad#485020
var version = "prefs version 0.0.4"
var theApp = "net.mooreworks.prefs"
var appZ = app.NewWithID(theApp)
var prefLoc = appZ.Storage().RootURI().Path() + fmt.Sprintf("%c", os.PathSeparator) + "preferences.json"
*/

func init() {
	log.SetFlags(log.LstdFlags | log.Llongfile) // Path and File name
	log.Println("init log with path and file name")
	log.SetFlags(log.LstdFlags | log.Lshortfile) // File name
	log.Println("init log with file name")

	s1, err := os.Hostname()
	if err != nil {
		log.Println("Hostname err: ", err)
	}
	log.Println("hostname: ", s1)

	s1, err = os.Getwd()
	if err != nil {
		log.Println("Getwd err", err)
	}
	log.Println("cwd:", s1)
}

func isFilePresent(pathAndFile string) {
	if _, err := os.Stat(pathAndFile); err == nil {
		// path/to/whatever exists
		log.Println(pathAndFile + " exists")
	} else if errors.Is(err, os.ErrNotExist) {
		// path/to/whatever does *not* exist
		log.Println(pathAndFile + " does NOT exist")
	} else {
		// Schrödinger: file may or may not exist. See err for details.
		// Therefore, do *NOT* use !os.IsNotExist(err) to test for file existence
		log.Println(pathAndFile + " MIGHT exist")
	}
}

func prefsStuff(appZ fyne.App, prefLoc string) {
	log.Println("Preferences path", appZ.Storage().RootURI().Path())
	isFilePresent(prefLoc)
	//s1 := appZ.Storage().RootURI().Path() + fmt.Sprintf("%c", os.PathSeparator) + "preferences.json"
	//log.Println("Remove ", s1)
	//os.Remove(s1)

	log.Println("Test_preferences")
	respAfter := appZ.Preferences().StringWithFallback("resp.After", "")
	log.Println("resp.After", respAfter)

	appZ.Preferences().SetString("resp.After", respAfter+"1")
	respAfter = appZ.Preferences().String("resp.After")
	log.Println("resp.After", respAfter)

	appZ.Preferences().SetString("resp.After", respAfter+"2")
	respAfter = appZ.Preferences().String("resp.After")
	log.Println("resp.After", respAfter)

	appZ.Preferences().SetString("resp.After", respAfter+"3")
	respAfter = appZ.Preferences().String("resp.After")
	isFilePresent(prefLoc)
	log.Println("resp.After", respAfter)
}

func main() {
	var version = "prefs version 0.0.4"
	var theApp = "net.mooreworks.prefs"
	var appZ = app.NewWithID(theApp)
	var prefLoc = appZ.Storage().RootURI().Path() + fmt.Sprintf("%c", os.PathSeparator) + "preferences.json"

	log.Printf(version + " start")
	log.Printf("GOOS: %s.\n", runtime.GOOS)
	win3 := appZ.NewWindow("Test window")
	respAfter := appZ.Preferences().StringWithFallback("resp.After", "")
	log.Println("resp.After", respAfter)
	l1 := widget.NewLabel("resp.After:" + respAfter)
	win3.SetContent(container.NewVBox(widget.NewLabel("Test label"), l1,
		widget.NewLabel("version "+version),
		widget.NewButton("Test button", func() {
			prefsStuff(appZ, prefLoc)
			respAfter = appZ.Preferences().StringWithFallback("resp.After", "")
			l1.Text = "resp.After" + respAfter
			l1.Refresh()
		}),
	))
	// TODO, how do I auto-run something inside win3?
	win3.ShowAndRun()
	appZ.Quit()
	log.Printf(version + " end")
}
`

THANK YOU!

**Comment by Jacalz** [comment] 2022-06-12 11:57
Wonderful. I’ll close this then. I’m glad that the removal of global variables solved your issue. Feel free to reopen if the issue appears again.

**Closed by Jacalz** 2022-06-12 11:57 UTC
Labels: unverified
