### ISSUE TITLE
Memory leak when switching the theme

### ISSUE THREAD

**Issue by zjcscut** [fyne-io/fyne#3640] opened 2023-02-08 07:10 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Here is my demo project repository => [passwdgen](https://github.com/zjcscut/passwdgen). When I try to switch the theme, the memory usage will increase 100~200 MB each time. 

### How to reproduce

1. Checkout the 'passwdgen' project code
2. Run the project
3. Click the Settings tab panel, switch the theme

### Screenshots

Init

![image](https://user-images.githubusercontent.com/13879735/217458997-6299b426-7504-433a-a14d-27e5a0903306.png)

Switch to Light

![image](https://user-images.githubusercontent.com/13879735/217459064-7e0f580a-56e8-46df-8c82-8e9caea30e78.png)

Switch to Dark

![image](https://user-images.githubusercontent.com/13879735/217459162-ece1d35b-bdb6-4c9e-9420-736276fbab3b.png)

Switch to Light again

![image](https://user-images.githubusercontent.com/13879735/217459270-2a51916d-2c2e-48cd-8353-6b8d05623af0.png)

### Example code

Custom theme: 

```go
package theme

import (
	"fyne.io/fyne/v2"
	fyneTheme "fyne.io/fyne/v2/theme"
	"image/color"
	"strings"
)
import _ "embed"

//go:embed assets/fonts/PingFang.ttf
var fontBytes []byte

var font = &fyne.StaticResource{
	StaticName:    "PingFang.ttf",
	StaticContent: fontBytes,
}

//go:embed assets/logo.ico
var logoBytes []byte

var Logo = &fyne.StaticResource{
	StaticName:    "icon.ico",
	StaticContent: logoBytes,
}

type SelectableTheme struct {
	Theme string
}

var _ fyne.Theme = (*SelectableTheme)(nil)

func (st SelectableTheme) Color(colorName fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
	if strings.Contains(st.Theme, "Light") {
		variant = fyneTheme.VariantLight
	} else {
		variant = fyneTheme.VariantDark
	}
	return fyneTheme.DefaultTheme().Color(colorName, variant)
}

func (st SelectableTheme) Icon(iconName fyne.ThemeIconName) fyne.Resource {
	return fyneTheme.DefaultTheme().Icon(iconName)
}

func (st SelectableTheme) Font(_ fyne.TextStyle) fyne.Resource {
	return font
}

func (st SelectableTheme) Size(sizeName fyne.ThemeSizeName) float32 {
	return fyneTheme.DefaultTheme().Size(sizeName)
}
```

Switch theme:

```go
app := fyne.CurrentApp()
themeGroup := widget.NewRadioGroup([]string{
	"Dark(暗黑)",
	"Light(白色)",
}, func(st string) {
	app.Settings().SetTheme(&pm.SelectableTheme{Theme: st})
})
```

### Fyne version

2.3.0

### Go compiler version

1.19.3

### Operating system

Windows

### Operating system version

Windows 10

**Comment by andydotxyz** [comment] 2023-02-09 19:00
I can replicate this with fyne_demo.
Probably a duplicate of other texture cache bugs, but not sure at this stage.

**Comment by alexballas** [comment] 2023-03-22 08:46
```
$ go tool pprof --inuse_objects heap.out 
File: dlnaflags
Build ID: 4e7ded35b20539aa3303e1779dc78eff9e85e077
Type: inuse_objects
Time: Mar 22, 2023 at 10:34am (EET)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 4079651, 97.37% of 4189965 total
Dropped 52 nodes (cum <= 20949)
Showing top 10 nodes out of 48
      flat  flat%   sum%        cum   cum%
   1312032 31.31% 31.31%    1870172 44.63%  github.com/benoitkugler/textlayout/fonts/truetype.parseGPOSMarkToBase
    729676 17.41% 48.73%    1660025 39.62%  github.com/benoitkugler/textlayout/fonts/truetype.parseGlyphData
    557064 13.30% 62.02%     557064 13.30%  github.com/benoitkugler/textlayout/fonts/truetype.parseGPOSAnchor
    415471  9.92% 71.94%     415471  9.92%  github.com/benoitkugler/textlayout/fonts/truetype.parseCompositeGlyphData
    383804  9.16% 81.10%     514878 12.29%  github.com/benoitkugler/textlayout/fonts/truetype.parseSimpleGlyphData
    317224  7.57% 88.67%     317224  7.57%  github.com/benoitkugler/textlayout/fonts/truetype.parseNameFormat20
    163842  3.91% 92.58%     163842  3.91%  github.com/benoitkugler/textlayout/fonts/truetype.parseUint16s (inline)
    110397  2.63% 95.22%     110397  2.63%  github.com/benoitkugler/textlayout/fonts/truetype.parseGPOSPairSet
     57373  1.37% 96.59%      73953  1.77%  github.com/benoitkugler/textlayout/fonts/truetype.parseGPOSMarkToLigature
     32768  0.78% 97.37%      32768  0.78%  github.com/benoitkugler/textlayout/fonts/truetype.parseFeature
```

**Comment by Bluebugs** [comment] 2023-03-22 16:40
Looking at this trace, it seems to be font related and maybe it is the same issue as #3499 , but with more actionable data.

**Comment by andydotxyz** [comment] 2023-03-25 19:12
I cannot replicate this on other OS, just like the font issue that is suspected to relate...

**Comment by alexballas** [comment] 2023-03-25 19:15
@andydotxyz this issue was originally raised for Windows as per the screenshots provided. I was able to replicate it on Linux with the example in https://github.com/fyne-io/fyne/issues/3755. Which OS are you referring to?

**Comment by Bluebugs** [comment] 2023-03-25 19:27
The example in #3755 is actually putting a lot of pressure on the gc which would explain that you could reproduce it in that case. The other things that might have an impact here is how much can your cpu process during a gc cycle. I would suspect that higher end system are less likely to see this problem. 

I think the problem is not so much a memory leak as it is a memory storm allocation that the gc on some system has trouble cleaning up fast enough.

**Comment by alexballas** [comment] 2023-03-25 19:31
The https://github.com/fyne-io/fyne/issues/3755 has no increase in memory in v2.2.4. It stays ~45MiB at all times. So there is certainly a regression here. I understand that the new font functionality should increase the average memory in general, but it should not justify this gradual increase in the new version v2.3.x

**Comment by Bluebugs** [comment] 2023-03-25 19:36
Sorry, I am not saying that there is no problem just that the problem is not a leak in the sense of some piece of code keeping a reference to some data when it shouldn't, but that the code is allocating and discarding data too fast making it impossible for the gc on some system to keep up.

**Comment by alexballas** [comment] 2023-03-25 19:39
Given that the GC is invoked every 2 minutes anyway, shouldn't I see a decrease in memory after a bit? I tested this with my main application. I manually invoked the theme change ~ 5-10 times and left it there. The memory stayed the same and never went down even if I left my application idle for more than 1hour.

**Comment by andydotxyz** [comment] 2023-03-25 20:06
It would seem that somehow a reference to the font files is keeping them in memory after the cache clears!

**Comment by andydotxyz** [comment] 2023-03-25 21:27
Aha! I have tracked it down to a font leak that I can replicate in the shaper without any Fyne code.
https://github.com/go-text/typesetting/issues/47

**Comment by andydotxyz** [comment] 2023-03-25 22:12
In my testing it is resolved by https://github.com/go-text/typesetting/pull/48.
It does need an update of gotext/shaping to be able to use it, but it's not a big deal (lots of files changed but it's just a refactor prior to the leak fix).

**Comment by andydotxyz** [comment] 2023-03-26 15:02
> Sorry, I am not saying that there is no problem just that the problem is not a leak in the sense of some piece of code keeping a reference to some data when it shouldn't

Actually that is exactly what it was - we shouldn't jump to conclusions. The fix upstream to go-text should resolve this completely.

**Closed** 2023-03-28 09:05 UTC
Labels: bug

**Comment by andydotxyz** [comment] 2023-06-28 17:06
This ticket is about switching theme.

When you draw more items the memory will increase slightly. It will either be re-used or freed after a delay.
