### ISSUE TITLE
Android dialog.NewFileOpen can not get file size

### ISSUE THREAD

**Issue by shvc** [fyne-io/fyne#2779] opened 2022-02-14 11:31 UTC
### Describe the bug:
 I want select a file then uplaod to http Server, the Content-Langth is  required.
 Android can not get file size from fyne.URIReadCloser
1.  fyne.URIReadCloser not impls io.ReadSeeker(https://github.com/fyne-io/fyne/issues/2352)
2.  can os.not Stat a fyne.URI

So, How can I get the file size?

### Example code:
The following code not work an Android, but works on Windows/Linux/Macos 
```go
func main() {
	a := app.New()
	w := a.NewWindow("Test")

	content := widget.NewButton("File", func() {
		dialog.NewFileOpen(func(uc fyne.URIReadCloser, e error) {
			if e != nil {
				dialog.ShowInformation("Open Error", uc.URI().Path(), w)
				return
			}
			if _, ok := uc.(io.ReadSeeker); ok {
				dialog.ShowInformation("Seeker OK", uc.URI().Path(), w)
			}
			stat, err := os.Stat(uc.URI().Path())
			if err != nil {
				dialog.ShowInformation("Stat Error", uc.URI().Path()+err.Error(), w)
			} else {
				dialog.ShowInformation("Stat Success", fmt.Sprintf("%s %v", uc.URI().Path(), stat.Size()), w)
			}
		}, w).Show()
	})
	w.Resize(fyne.NewSize(800, 400))
	w.SetContent(content)
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:**  Android
 - **Go version:** 1.17.7
 - **Fyne version:**  2.1.2

**Comment by andydotxyz** [comment] 2022-02-15 16:54
> Until #2352 or #2134 have been solved, the only sensible option to get the file size is probably to read through the whole stream and count the bytes. That does unfortunately require opening the file again, so it is quite far from a perfect solution.

Actually you should not have to read it twice, you could cache it in memory if the file isn't too huge, and pass the second usage a reader into the cache.

I'm not certain that this can be solved. When we are passed data from other apps it cannot support `seek` without caching the whole data stream in memory. If we did that by default then cases that don't need seeking would have performance impacts.

Either way, closing as duplicate of #2352

**Closed by andydotxyz** 2022-02-15 16:54 UTC
Labels: question, Driver:mobile, Storage
