### ISSUE TITLE
android: App crashes when drag up entry in scroll container

### ISSUE THREAD

**Issue by pymq** [fyne-io/fyne#963] opened 2020-05-10 12:29 UTC
### To Reproduce:
Steps to reproduce the behaviour:
1. Open Fyne demo
2. Open Text tab in Widgets tab
3. Try to scroll Lorem ipsum entry (it should not fit into the screen)
4. The app is closing

### Device (please complete the following information):
 - OS: Android
 - Version: 8.0
 - Go version: 1.14.2
 - Fyne version: develop 04d654b06855c53d2a7c18caafbcca2161baff73

**Comment by stuartmscott** [comment] 2020-05-11 15:55
I could not reproduce locally :(

@pymq is there a stack trace, could you attach a screen capture?

**Comment by pymq** [comment] 2020-05-12 11:03
@stuartmscott It could be reproduced on desktop with `-tags mobile` too, but harder
Here is [video](https://imgur.com/a/FgKQ8oS)

Stacktrace
```
panic: runtime error: index out of range [17] with length 7

goroutine 38 [running]:
fyne.io/fyne/widget.(*entryRenderer).buildSelection(0xc0000c43c0)
        /home/max/Projects/fyne/widget/entry.go:1079 +0x63c
fyne.io/fyne/widget.(*entryRenderer).moveCursor(0xc0000c43c0)
        /home/max/Projects/fyne/widget/entry.go:1092 +0xc0
fyne.io/fyne/widget.(*entryRenderer).Refresh(0xc0000c43c0)
        /home/max/Projects/fyne/widget/entry.go:984 +0x1bb
fyne.io/fyne/widget.(*BaseWidget).Refresh(0xc0000ce900)
        /home/max/Projects/fyne/widget/widget.go:107 +0x51
fyne.io/fyne/widget.(*Entry).updateMousePointer(0xc0000ce900, 0xc0013f2b10, 0x0)
        /home/max/Projects/fyne/widget/entry.go:879 +0x113
fyne.io/fyne/widget.(*Entry).Dragged(0xc0000ce900, 0xc0013f2b10)
        /home/max/Projects/fyne/widget/entry.go:161 +0x43
created by fyne.io/fyne/internal/driver/gomobile.(*mobileDriver).tapMoveCanvas.func1
        /home/max/Projects/fyne/internal/driver/gomobile/driver.go:229 +0x4d
exit status 2
```

**Comment by mrjrieke** [comment] 2020-05-13 23:39
I found a change that seems to keep it from crashing, but still end up with black screen now.

**Comment by andydotxyz** [comment] 2020-05-19 12:34
I found the issue.
I also realised that drag to select was a bit broken due to some strange offset calculations, I'll get that addressed in this fix as well.

**Comment by andydotxyz** [comment] 2020-05-19 17:09
On develop for testing

**Closed by andydotxyz** 2020-05-19 17:09 UTC
Labels: OS:Android, bug
