### ISSUE TITLE
Dialog.Resize() has no effect if called before Dialog.Show()

### ISSUE THREAD

**Issue by jens1205** [fyne-io/fyne#1863] opened 2021-01-25 21:23 UTC
### Describe the bug:
Dialog.Resize() only has an effect on the created dialog if it is called after Dialog.Show(). This is not consistent with window.Resize() which can be used before or after Show()

### Example code:
```go
package main

import (
	"log"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()

	w := a.NewWindow("testwindow")

	button := widget.NewButton("dialog", func() {
		username := widget.NewEntry()
		password := widget.NewPasswordEntry()

		items := []*widget.FormItem{
			widget.NewFormItem("username", username),
			widget.NewFormItem("password", password),
		}

		form := dialog.NewForm("mydialog", "OK", "Cancel", items,
			func(ok bool) {
				if !ok {
					return
				}
				log.Println(username.Text, username.Password)
			}, w)

		// no effect
		form.Resize(fyne.NewSize(1000, 200))

		form.Show()

		// would work
		// form.Resize(fyne.NewSize(1000, 200))

	})

	w.SetContent(container.NewMax(button))

	// has an effect
	w.Resize(fyne.NewSize(1900, 1080))

	w.Show()

	// would also work
	// w.Resize(fyne.NewSize(1900, 1080))

	a.Run()

}


```
-->

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Ubuntu 20.04.1 LTS
 - **Go version:** 1.15.7 linux/amd64
 - **Fyne version:** v2.0.0

**Comment by AlbinoGeek** [comment] 2021-01-26 02:03
Related to (but not a duplicate of): #1570 , #1565

Also possibly #1692 and #1382

**Comment by andydotxyz** [comment] 2021-01-27 19:01
The fix for this is now on the `develop` branch

**Closed by andydotxyz** 2021-01-27 19:01 UTC
Labels: bug
