### ISSUE TITLE
Add rounded border corner attribute

### ISSUE THREAD

**Issue by qianniancn** [fyne-io/fyne#2377] opened 2021-08-14 15:40 UTC
### Is your feature request related to a problem? Please describe:

YES. We can use border-radius in the CSS. Whether you can add the rounded corner property to the widget. This makes the widget more aesthetically pleasing
### Is it possible to construct a solution with the existing API?

No solution 
### Describe the solution you'd like to see:

Button rounded corners 

![20210814233618](https://user-images.githubusercontent.com/5478237/129451468-8f739512-792b-4834-b13a-8c4b0bdd5eaa.png)
Rounded corners of input box 

![20210814235016](https://user-images.githubusercontent.com/5478237/129451887-d01cda41-6cf3-464e-941d-93e6957f4f3a.png)

Rounded corners of progress bar 

![20210814235247](https://user-images.githubusercontent.com/5478237/129451941-96f628bb-89b4-4f42-a165-71d6d2d2ed34.png)

**Comment by andydotxyz** [comment] 2021-08-15 09:12
Is this a duplicate of #1090

**Comment by dweymouth** [comment] 2024-01-08 19:48
This is resolved in 2.4 with the CornerRadius property and new theme sizes

**Closed by dweymouth** 2024-01-08 19:48 UTC
