### ISSUE TITLE
--appendPerm flag on fyne/cmd/fyne

### ISSUE THREAD

**Issue by raifpy** [fyne-io/fyne#1335] opened 2020-09-24 18:44 UTC
Hi there . 
I use your library for android applications .
When i need to access internet , i must create AndroidManifest.xml and use it *

ls :
AndroidManifest.xml
fyneCode.go
Icon.png

So , when i create my AndroidManifest.xml and add custom permissions my android application's like is breaked ;
![image](https://user-images.githubusercontent.com/50047969/94186197-0da6f980-feaf-11ea-9172-1f948b26fa02.png)
They are 2 fyne application on screenshot .
First application don't need internet so i don't add any manifest for this project .
But when i add manifest.xml (jadx-gui fyne.apk (get orginial manifes)) and add permissions :

![image](https://user-images.githubusercontent.com/50047969/94186227-1992bb80-feaf-11ea-9ee2-6e9475cf1da9.png)
fyne package -os android/arm -appID "my.app.app" .

It's compiled successfully . 
But deteriorating appearance on android

Maybe you can add --appendPerm param for fyne/cmd/fyne

I hope , you can understand me :D 

 (i edit fyne's original manifest.xml for add permission)

**Comment by andydotxyz** [comment] 2020-09-24 20:41
I think this is a duplicate of #665 - the strange resolution is to change the order of android:name and android:label on some systems. Does this fix the issue for you?

**Comment by raifpy** [comment] 2020-09-24 21:00
Yes !
I just chance my permissions line ;
![image](https://user-images.githubusercontent.com/50047969/94199822-17862800-fec2-11ea-89c6-b39c6d303196.png)
Solved , thanks ...

**Closed** 2020-09-24 21:00 UTC
Labels: duplicate
