### ISSUE TITLE
How do I open a folder like the dialog.showFileopen function, and then get the folder path

### ISSUE THREAD

**Issue by yanyuxuanz** [fyne-io/fyne#1377] opened 2020-10-09 13:13 UTC
I am not found this function it can Open the folder dialog and you can choose the folder to getting it's path.

**Comment by Jacalz** [comment] 2020-10-09 15:29
This feature has not yet been implemented. We are looking to hopefully have it done sometime between either the next release or 2.0. 

This issue is a duplicate of #941. To make life easier for us, please search for issues before opening a new one :)

**Closed by Jacalz** 2020-10-09 15:29 UTC
