### ISSUE TITLE
Arabic letters do not display correctly

### ISSUE THREAD

**Issue by m-abdalrahman** [fyne-io/fyne#2189] opened 2021-04-23 16:01 UTC
### Describe the bug:
Arabic letters are not displayed correctly, and the lettering must be from right to left
### Screenshots:
![Screenshot from 2021-04-23 17-42-28](https://user-images.githubusercontent.com/19738046/115897615-e4f2dc80-a45c-11eb-972e-7135f010978c.png)
![Screenshot from 2021-04-23 17-42-30](https://user-images.githubusercontent.com/19738046/115897633-e8866380-a45c-11eb-829d-2be63f8d01aa.png)

### Example code:
```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("مرحباً")

	hello := widget.NewLabel("مرحب بالعالم")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("مرحباً!", func() {
			hello.SetText("مرحباً :)")
		}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Ubuntu 18.04
 - **Go version:** go1.16.2 linux/amd64
 - **Fyne version:** v2.0.2 h1:6pDvFuCmL1odyT/fPI+2L54hMJW1Zt9Dno41HmLInRs=

**Comment by Jacalz** [comment] 2021-04-23 16:44
Thanks to opening the issue. It does look like this most likely is a duplicate of https://github.com/fyne-io/fyne/issues/598. Might also be related to https://github.com/fyne-io/fyne/issues/2115. You will have to set the `FYNE_FONT=` variable to a font that has support for the characters.

**Closed by Jacalz** 2021-04-23 16:44 UTC
Labels: duplicate

**Comment by javad-majidi** [comment] 2022-08-10 13:48
i have made a simple farsi/arabic [package](https://github.com/javad-majidi/farsi-reshaper) that solves this issue

**Comment by Sendipad** [comment] 2024-05-04 17:45
Using version="v2.4.5"
On Ubuntu and Setting FYNE_FONT to use one of the supported fonts .ttf,
Howver Arabic Letters is Shown But order and Glyphs is not correct.
Does this a bug in Go-Text/typesetting/shapping pkg  or is it a bug in Fyne rendering Text?!
Thanks

**Comment by andydotxyz** [comment] 2024-05-04 21:38
Please try @develop version as we are actively working on this area.

**Comment by mustafa9514** [comment] 2024-05-12 23:40
Arabic character problem. Arabic letters cannot be displayed.

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()

	w := a.NewWindow("Arabic letters")

	label := widget.NewLabel("كتاب")
	tedit := widget.NewEntry()
	tedit.SetText("كتاب")

	w.SetContent(container.NewVBox(
		widget.NewLabel("Arabic letters:"),
		label, tedit,
	))

	w.ShowAndRun()
}

**Comment by andydotxyz** [comment] 2024-05-13 16:28
Instead of commenting on a closed issue it would be a good idea to follow the issue this was a duplicate of, and see the resolution of that too.

If you have tried them all and still think you have found a problem then open a new ticket.
