### ISSUE TITLE
Compiler warning in fyne_demo (related to /usr/include/X11/Xcursor/Xcursor.h)

### ISSUE THREAD

**Issue by sq16** [fyne-io/fyne#670] opened 2020-02-11 08:38 UTC
I did go get the fyne_demo twice:

1) first time: Xcursor.h missing; so I did:
    sudo apt install xorg-dev
    and that issue was gone

2) but then I get a complex warning (which I do not understand).
    See error in attached file please.
[fyne_demo_error.txt](https://github.com/fyne-io/fyne/files/4184697/fyne_demo_error.txt)

**Comment by andydotxyz** [comment] 2020-02-11 08:49
Yes sorry, this is a duplicate of #365 and will go away in 1.3 release. Nothing to worry about

**Closed by andydotxyz** 2020-02-11 08:49 UTC

**Comment by sq16** [comment] 2020-02-11 11:52
OK, thx!
