### ISSUE TITLE
dialog.NewFileOpen - select multiple files?

### ISSUE THREAD

**Issue by squash** [fyne-io/fyne#2622] opened 2021-11-05 13:17 UTC
### Is your feature request related to a problem? Please describe:
It would be helpful to be able to select multiple files with the file chooser dialog. For example, selecting multiple attachments for an email, or multiple files to be added to an archive. 

### Is it possible to construct a solution with the existing API?
Currently it appears that you need to select them individually, and possibly use/abuse the filter to prevent showing files previously selected.  Alternatively I think cobbling together something with a widget.List with would be a better user experience than doing multiple file open dialogs.

### Describe the solution you'd like to see:
Being able to select a file, then using the familiar shit-click or control-click be able to add one or more additional files to the selection, and callback with  []fyne.URIReadCloser containing each member.

**Comment by Jacalz** [comment] 2021-11-05 13:52
Closing as duplicate of https://github.com/fyne-io/fyne/issues/1082.

**Closed by Jacalz** 2021-11-05 13:52 UTC
Labels: duplicate
