### ISSUE TITLE
Resize crash

### ISSUE THREAD

**Issue by Fruchtgummi** [fyne-io/fyne#3313] opened 2022-10-07 04:02 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

OSX on M1 Max with golang 19.2

Error:

```
goroutine 31 [GC worker (idle)]:
runtime.gopark(0x1e7872e39245b?, 0x1?, 0x6e?, 0x9a?, 0x0?)
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/proc.go:363 +0xd6 fp=0xc0004dc750 sp=0xc0004dc730 pc=0x10003aad6
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/mgc.go:1235 +0xf1 fp=0xc0004dc7e0 sp=0xc0004dc750 pc=0x10001e8f1
runtime.goexit()
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0004dc7e8 sp=0xc0004dc7e0 pc=0x1000682a1
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/mgc.go:1159 +0x25

goroutine 6 [chan receive]:
runtime.gopark(0xc0004dcea8?, 0x1006086c0?, 0x4?, 0x0?, 0xc0001aac44?)
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/proc.go:363 +0xd6 fp=0xc0004dce70 sp=0xc0004dce50 pc=0x10003aad6
runtime.chanrecv(0xc0001a8d20, 0x0, 0x1)
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/chan.go:583 +0x49b fp=0xc0004dcf00 sp=0xc0004dce70 pc=0x100009dbb
runtime.chanrecv1(0xc0001be780?, 0xc0001a8cc0?)
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/chan.go:442 +0x18 fp=0xc0004dcf28 sp=0xc0004dcf00 pc=0x1000098b8
fyne.io/fyne/v2/internal/animation.(*Runner).runAnimations.func1()
	/Users/moo/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/animation/runner.go:69 +0x4f fp=0xc0004dcfe0 sp=0xc0004dcf28 pc=0x100413a2f
runtime.goexit()
	/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0004dcfe8 sp=0xc0004dcfe0 pc=0x1000682a1
created by fyne.io/fyne/v2/internal/animation.(*Runner).runAnimations
```

### How to reproduce

Write a go-project with "fyne.io/fyne/v2". Start the app. Put with the mouse a windows border from the app and drag the size bigger.

### Example code

Get the XKCD example from your repo.

### Fyne version

2.2.3

### Go compiler version

1.19

### Operating system

macOS

### Operating system version

12.6 monterey

### Additional Information

my system:

Apple M1 Max with 32GB

**Comment by andydotxyz** [comment] 2022-10-16 16:57
This looks like a duplicate of #2933

**Closed by andydotxyz** 2022-10-16 16:57 UTC
Labels: unverified
