### ISSUE TITLE
When Canvas is being updated and refreshed frequently from an image.Image, it sometimes blanks

### ISSUE THREAD

**Issue by paultag** [fyne-io/fyne#863] opened 2020-04-15 02:25 UTC
### Describe the bug:

I'm unclear on the root cause. An App I wrote relies on mutating an `image.Image`, and calling `canvas.Refresh()` to blit that to the UI. The exact conditions that cause this to blank the canvas out are not entirely clear to me, and it's a bit of a devil to dig further into.

Since my app is a bit complex and unwidly, I've rewritten a minimal reproducer that runs on my system. I'm running Debian GNU/Linux, sid, under GNOME using Wayland as my compositor, not X11. No other system apps have behaved this way as far as I can tell.

Thank you for maintaining Fyne, it's a true pleasure to use!

### To Reproduce:

Program below

### Screenshots:

[video of this bug](https://i.imgur.com/yAPyTAT.mp4)

```
package main

import (
	"context"
	"image"
	"image/color"
	"image/draw"
	"time"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
)

var (
	height      int = 200
	windowWidth int = 1000
)

type testLayout struct {
	window fyne.Window
	canvas fyne.CanvasObject
}

func (tl testLayout) MinSize(objects []fyne.CanvasObject) fyne.Size {
	return fyne.NewSize(windowWidth, height)
}

func (tl testLayout) Layout(objects []fyne.CanvasObject, size fyne.Size) {
	tl.canvas.Resize(size)
}

func main() {
	app := app.New()
	window := app.NewWindow("Test Program")
	window.SetPadded(false)

	canvasImg := image.NewRGBA(image.Rect(0, 0, windowWidth, height))
	canvas := canvas.NewRasterFromImage(canvasImg)

	i := testLayout{canvas: canvas, window: window}
	window.SetContent(fyne.NewContainerWithLayout(i, i.canvas))

	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	go func() {
		<-ctx.Done()
		app.Quit()
	}()

	go func() {
		defer cancel()
		window.Show()
		app.Run()
	}()

	row := 0
	test := image.NewRGBA(image.Rect(0, 0, windowWidth, height))

	time.Sleep(time.Second)

	for {
		if err := ctx.Err(); err != nil {
			panic(err)
		}

		for x := 0; x < windowWidth; x++ {
			test.Set(x, row, color.RGBA{
				R: 0xFF,
				A: 0xFF,
			})
		}

		draw.Draw(canvasImg, image.Rect(0, 0, windowWidth, height), test, image.ZP, draw.Src)

		// time.Sleep(time.Second / 10)
		canvas.Refresh()

		row = (row + 1) % height
	}
}
```

### Device (please complete the following information):
 - OS: Debian GNU/Linux, GNOME 3.36.1 under Wayland
 - Version: sid, current as of 2020-04-14
 - Go version: go1.14.2
 - Fyne version: v1.2.4

**Comment by paultag** [comment] 2020-04-15 03:54
I had a few extra moments - I was able to reproduce this on GNOME running under X11, as well as Sway (an i3 clone written against Wayland)

**Comment by paultag** [comment] 2020-04-15 04:44
If I leave the app up when it's Grey, here's the state of the world

```
(dlv) goroutines -t
* Goroutine 1 - User: /usr/lib/go-1.14/src/image/color/color.go:160 image/color.(*modelFunc).Convert (0x4bb48f) (thread 63376)
	0  0x00000000004bb48f in image/color.(*modelFunc).Convert
	    at /usr/lib/go-1.14/src/image/color/color.go:160
	1  0x00000000004cb0fe in image.(*RGBA).Set
	    at /usr/lib/go-1.14/src/image/image.go:98
	2  0x000000000076634e in main.main
	    at ./test.go:70
	3  0x0000000000459012 in runtime.main
	    at /usr/lib/go-1.14/src/runtime/proc.go:203
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 2 - User: /usr/lib/go-1.14/src/runtime/proc.go:305 runtime.gopark (0x4593f0)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x00000000004592a7 in runtime.goparkunlock
	    at /usr/lib/go-1.14/src/runtime/proc.go:310
	2  0x00000000004592a7 in runtime.forcegchelper
	    at /usr/lib/go-1.14/src/runtime/proc.go:253
	3  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 3 - User: ./go/src/fyne.io/fyne/internal/painter/svg_cache.go:104 fyne.io/fyne/internal/painter.SvgCacheMonitorTheme.func1 (0x7105f4)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x0000000000429d17 in runtime.chanrecv
	    at /usr/lib/go-1.14/src/runtime/chan.go:525
	2  0x00000000004299db in runtime.chanrecv1
	    at /usr/lib/go-1.14/src/runtime/chan.go:407
	3  0x00000000007105f4 in fyne.io/fyne/internal/painter.SvgCacheMonitorTheme.func1
	    at ./go/src/fyne.io/fyne/internal/painter/svg_cache.go:104
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 18 - User: /usr/lib/go-1.14/src/runtime/proc.go:305 runtime.gopark (0x4593f0)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x0000000000446381 in runtime.goparkunlock
	    at /usr/lib/go-1.14/src/runtime/proc.go:310
	2  0x0000000000446381 in runtime.bgsweep
	    at /usr/lib/go-1.14/src/runtime/mgcsweep.go:89
	3  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 19 - User: /usr/lib/go-1.14/src/runtime/proc.go:305 runtime.gopark (0x4593f0)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x00000000004447ef in runtime.goparkunlock
	    at /usr/lib/go-1.14/src/runtime/proc.go:310
	2  0x00000000004447ef in runtime.scavengeSleep
	    at /usr/lib/go-1.14/src/runtime/mgcscavenge.go:214
	3  0x00000000004449a5 in runtime.bgscavenge
	    at /usr/lib/go-1.14/src/runtime/mgcscavenge.go:315
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 34 - User: /usr/lib/go-1.14/src/runtime/proc.go:305 runtime.gopark (0x4593f0)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x000000000043c0d3 in runtime.goparkunlock
	    at /usr/lib/go-1.14/src/runtime/proc.go:310
	2  0x000000000043c0d3 in runtime.runfinq
	    at /usr/lib/go-1.14/src/runtime/mfinal.go:175
	3  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 35 - User: /usr/lib/go-1.14/src/runtime/time.go:188 time.Sleep (0x474f0a)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x0000000000474f0a in time.Sleep
	    at /usr/lib/go-1.14/src/runtime/time.go:188
	2  0x00000000007104f6 in fyne.io/fyne/internal/painter.svgCacheJanitor.func1
	    at ./go/src/fyne.io/fyne/internal/painter/svg_cache.go:51
	3  0x00000000004902cc in sync.(*Once).doSlow
	    at /usr/lib/go-1.14/src/sync/once.go:66
	4  0x00000000004901d5 in sync.(*Once).Do
	    at /usr/lib/go-1.14/src/sync/once.go:57
	5  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 36 - User: ./go/src/fyne.io/fyne/app/app.go:108 fyne.io/fyne/app.NewAppWithDriver.func1 (0x76518d)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x0000000000429d17 in runtime.chanrecv
	    at /usr/lib/go-1.14/src/runtime/chan.go:525
	2  0x00000000004299db in runtime.chanrecv1
	    at /usr/lib/go-1.14/src/runtime/chan.go:407
	3  0x000000000076518d in fyne.io/fyne/app.NewAppWithDriver.func1
	    at ./go/src/fyne.io/fyne/app/app.go:108
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 37 - User: /usr/lib/go-1.14/src/syscall/asm_linux_amd64.s:50 syscall.Syscall6 (0x49a2aa) (thread 63378)
	0  0x000000000049a2aa in syscall.Syscall6
	    at /usr/lib/go-1.14/src/syscall/asm_linux_amd64.s:50
	1  0x0000000000760872 in fyne.io/fyne/vendor/golang.org/x/sys/unix.EpollWait
	    at ./go/src/fyne.io/fyne/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1760
	2  0x0000000000762921 in fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.(*fdPoller).wait
	    at ./go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86
	3  0x0000000000761b28 in fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents
	    at ./go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify.go:192
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 38 - User: ./go/src/fyne.io/fyne/app/settings_desktop.go:42 fyne.io/fyne/app.watchFile.func1 (0x7652c8)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x0000000000429d17 in runtime.chanrecv
	    at /usr/lib/go-1.14/src/runtime/chan.go:525
	2  0x0000000000429a1b in runtime.chanrecv2
	    at /usr/lib/go-1.14/src/runtime/chan.go:412
	3  0x00000000007652c8 in fyne.io/fyne/app.watchFile.func1
	    at ./go/src/fyne.io/fyne/app/settings_desktop.go:42
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 50 - User: ./go/src/fyne.io/fyne/internal/driver/glfw/window.go:1051 fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue (0x7450e6)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x0000000000429d17 in runtime.chanrecv
	    at /usr/lib/go-1.14/src/runtime/chan.go:525
	2  0x0000000000429a1b in runtime.chanrecv2
	    at /usr/lib/go-1.14/src/runtime/chan.go:412
	3  0x00000000007450e6 in fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue
	    at ./go/src/fyne.io/fyne/internal/driver/glfw/window.go:1051
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 51 - User: ./go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:409 fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1 (0x745c97)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x0000000000429d17 in runtime.chanrecv
	    at /usr/lib/go-1.14/src/runtime/chan.go:525
	2  0x00000000004299db in runtime.chanrecv1
	    at /usr/lib/go-1.14/src/runtime/chan.go:407
	3  0x0000000000745c97 in fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1
	    at ./go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:409
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 53 - User: ./test.go:49 main.main.func1 (0x766568)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x0000000000429d17 in runtime.chanrecv
	    at /usr/lib/go-1.14/src/runtime/chan.go:525
	2  0x00000000004299db in runtime.chanrecv1
	    at /usr/lib/go-1.14/src/runtime/chan.go:407
	3  0x0000000000766568 in main.main.func1
	    at ./test.go:49
	4  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 54 - User: ../sysdeps/unix/sysv/linux/poll.c:29 C.__poll (0x7fb19970bb4f) (thread 63389)
	0  0x00007fb19970bb4f in C.__poll
	    at ../sysdeps/unix/sysv/linux/poll.c:29
	    error: input/output error
	(truncated)
  Goroutine 55 - User: /usr/lib/go-1.14/src/runtime/proc.go:305 runtime.gopark (0x4593f0)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x000000000043f91f in runtime.gcBgMarkWorker
	    at /usr/lib/go-1.14/src/runtime/mgc.go:1873
	2  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 56 - User: /usr/lib/go-1.14/src/runtime/proc.go:305 runtime.gopark (0x4593f0)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x000000000043f91f in runtime.gcBgMarkWorker
	    at /usr/lib/go-1.14/src/runtime/mgc.go:1873
	2  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 57 - User: /usr/lib/go-1.14/src/runtime/proc.go:305 runtime.gopark (0x4593f0)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x000000000043f91f in runtime.gcBgMarkWorker
	    at /usr/lib/go-1.14/src/runtime/mgc.go:1873
	2  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
  Goroutine 58 - User: /usr/lib/go-1.14/src/runtime/proc.go:305 runtime.gopark (0x4593f0)
	0  0x00000000004593f0 in runtime.gopark
	    at /usr/lib/go-1.14/src/runtime/proc.go:305
	1  0x000000000043f91f in runtime.gcBgMarkWorker
	    at /usr/lib/go-1.14/src/runtime/mgc.go:1873
	2  0x0000000000485c21 in runtime.goexit
	    at /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
[18 goroutines]
(dlv) 
```

**Comment by andydotxyz** [comment] 2020-04-15 09:30
Sorry but Run() (or ShowAndRun()) must be called from the main routine, not from a separate goroutine.
We have a patch in the next release to panic if the framework is not run correctly, I hope this will help.

**Comment by paultag** [comment] 2020-04-15 13:22
@andydotxyz Ah! That will very much help indeed, thank you for your help!

Is there a best practice for how apps manage this? The issue I'm facing is this isn't a `main·main`, it's a function that's invoked by a caller I don't control, and I may already be on a goroutine by the time I get called. 

Is it import that I am the main PID (if so can I `init` and `LockOSThread`? That may not work with multiple apps though).

Is it an issue of threads / thread locals or is it an issue of being on the main thread, out of curiosity?

Many thanks again for your help!

**Comment by paultag** [comment] 2020-04-15 13:32
@andydotxyz Just from a few tests this appears to be working, but I'm not sure if it's still broken somehow. Will this be a supported way to use Fyne?

```
package main

import (
	"context"
	"image"
	"image/color"
	"image/draw"
	"runtime"
	"sync"
	"time"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
)

var (
	height      int = 200
	windowWidth int = 1000
)

type testLayout struct {
	window fyne.Window
	canvas fyne.CanvasObject
}

func (tl testLayout) MinSize(objects []fyne.CanvasObject) fyne.Size {
	return fyne.NewSize(windowWidth, height)
}

func (tl testLayout) Layout(objects []fyne.CanvasObject, size fyne.Size) {
	tl.canvas.Resize(size)
}

func Main(wg sync.WaitGroup) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	defer wg.Done()

	app := app.New()
	window := app.NewWindow("Test Program")
	window.SetPadded(false)

	canvasImg := image.NewRGBA(image.Rect(0, 0, windowWidth, height))
	canvas := canvas.NewRasterFromImage(canvasImg)

	i := testLayout{canvas: canvas, window: window}
	window.SetContent(fyne.NewContainerWithLayout(i, i.canvas))

	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	go func() {
		<-ctx.Done()
		app.Quit()
	}()

	row := 0
	test := image.NewRGBA(image.Rect(0, 0, windowWidth, height))

	time.Sleep(time.Second)

	go func() {
		for {
			if err := ctx.Err(); err != nil {
				panic(err)
			}

			for x := 0; x < windowWidth; x++ {
				test.Set(x, row, color.RGBA{
					R: 0xFF,
					A: 0xFF,
				})
			}

			draw.Draw(canvasImg, image.Rect(0, 0, windowWidth, height), test, image.ZP, draw.Src)

			// time.Sleep(time.Second / 10)
			canvas.Refresh()

			row = (row + 1) % height
		}
	}()

	window.Show()
	app.Run()
}

func main() {
	wg := sync.WaitGroup{}
	wg.Add(1)
	go Main(wg)
	wg.Wait()
}
```

**Comment by andydotxyz** [comment] 2020-04-15 16:56
This will still break on some systems and in the future will not be allowed.
Sorry but unfortunately the Run() must be called in main() or from a function on the same goroutine.

You could put the app := app.New() and app.Run() into the main() and leave the rest in a goroutine without issue. It's just that the mainloop must run on main. It's a requirement of the underlying OS draw systems sorry.

**Comment by andydotxyz** [comment] 2020-04-15 16:57
Best practice would be to have all other systems or services run on goroutines and leave the GUI to run at the end of main(). This is a requirement of all GUIs as far as I am aware.

**Comment by paultag** [comment] 2020-04-15 17:13
@andydotxyz Hurm, will think about it accordingly. My hopes were up, it's been stable all day! Oh well. Thanks again for your help - would you like me to change this to a documentation issue, mark it a dupe of the panic on non-main, or leave it as is?

Thanks again!

**Comment by andydotxyz** [comment] 2020-04-15 17:26
Sorry about this. The problem is that the behaviour is a little undefined so your Linux box may be fine but it will crash on macOS :(

I'll mark it as a dupe if you are happy with that. Feel free to ask more about it if you want. It is usually possible to work this into a design - we've managed to for the issues raised so far :)

**Comment by andydotxyz** [comment] 2020-04-15 17:27
Duplicate of #829

**Closed** 2020-04-15 17:27 UTC
Labels: duplicate

**Comment by paultag** [comment] 2020-04-15 17:29
Lovely, thanks again @andydotxyz! Have a great day, and thanks again!

**Comment by paultag** [comment] 2020-04-17 15:15
In case someone comes across the issue in the future, my tactic for working around this was as follows:

  - Since I don't control the runtime, I can't be on main.
  - When my function is invoked, I take the resource(s) I need (in my case an io.Reader) and pass that via `os/exec.Command` to a program which runs the Fyne bits as a subprocess. The function call blocks, and can happily be on a goroutine.

The ugly bit here is you have to ensure the binary is on `${PATH}`. If that's not possible, it is possible to get around this by adding an `init` to read `os.Args`, and run your Fyre code in the `init` (ugly, but again, if you don't control `main·main`, this isn't easy) if you pass some special flag as `os.Args[1]` (like `___ugly_hack_plugin_name`).

Good luck to anyone coming across this!

**Comment by andydotxyz** [comment] 2020-04-20 08:41
Cunning, thanks for the tips - I'm sure they will be helpful to others trying to overcome this situation.
