### ISSUE TITLE
The taskbar displays garbled characters

### ISSUE THREAD

**Issue by zzwl0219** [fyne-io/fyne#3876] opened 2023-05-08 12:43 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

In ubuntu, the taskbar cannot display Chinese.

### How to reproduce

Garbled code appears in the top taskbar

### Screenshots

![2023-05-08 20-37-51屏幕截图](https://user-images.githubusercontent.com/97720085/236825952-b940fc19-7112-4002-94ac-e495888bc588.png)

### Example code

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"gowin/env"
)

func init() {
	fontPath, err := findfont.Find("resources/fonts/song.ttf")
	if err != nil {
		panic(err)
	}
	fontData, err := os.ReadFile(fontPath)
	if err != nil {
		panic(err)
	}
	_, err = truetype.Parse(fontData)
	if err != nil {
		panic(err)
	}
	os.Setenv("FYNE_FONT", fontPath)
}
func main() {
	a := app.New()
	w := a.NewWindow("哈哈")

	hello := widget.NewLabel("你好世界!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("嘎嘎", func() {
			hello.SetText("欢迎 :)")
		}),
	))

	w.ShowAndRun()
}

### Fyne version

2.3.4

### Go compiler version

1.19

### Operating system and version

22.04.1-Ubuntu

**Comment by Jacalz** [comment] 2023-05-08 16:15
My best guess is that the font that Ubuntu is using for the Gnome desktop isn’t providing the adequate characters for you

**Comment by andydotxyz** [comment] 2023-05-08 17:11
I think it's an encoding issue. As you can see from the window menu we have set the information correctly.

Additionally this is a duplicate of a similar issue opened years ago.

**Comment by zzwl0219** [comment] 2023-05-09 02:13
非常感谢您的解答,我已经了解此问题.

**Closed** 2023-05-09 02:26 UTC
Labels: unverified

**Comment by zzwl0219** [comment] 2023-05-09 02:27
closed
