### ISSUE TITLE
Apps cannot launch in iOS simulator

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#1917] opened 2021-02-07 15:04 UTC
It seems to relate to invalid codesign signature

**Comment by changkun** [comment] 2021-09-21 07:11
I don't have the problem when I am using darwin/amd64, but the app indeed cannot launch in the iOS simulator when using darwin/arm64. Hence I assume the issue is targeting M1 macs?

<img width="564" alt="Screen Shot 2021-09-21 at 9 11 07 AM" src="https://user-images.githubusercontent.com/5498964/134127142-3667963d-93b3-42d2-b62e-9923ef6105dc.png">

**Comment by andydotxyz** [comment] 2021-09-21 09:01
I have this problem in `darwin/amd64` as well - what steps did you follow to get it working? (maybe I have some broken cert?)

**Comment by changkun** [comment] 2021-09-21 09:06
> I have this problem in `darwin/amd64` as well - what steps did you follow to get it working? (maybe I have some broken cert?)

What's the expected procedure to access the Xcode project? or what's the current procedure to run apps in iOS simulator?

I can run on darwin/amd64 via:

1. Turn on -x and -work build tag in the cmd/fyne/internal/mobile/build.go
2. fyne package -os ios
3. Open the temp folder for building the Xcode project, then run it on a simulator.

It might be a problem with the cert, some suggests to turn cert to a always trust, but I don't see myself need their suggested steps: https://developer.apple.com/forums/thread/106711

**Comment by andydotxyz** [comment] 2021-09-21 16:18
I get `signature not valid: -67050`. Did you certainly build without an `-profile` parameter?
When I execute the package command you issued I see 
```
 No profiles for 'io.fyne.demo' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'io.fyne.demo'. (in target 'main' from project 'main')
```

**Comment by changkun** [comment] 2021-09-21 20:24
This is my build process:

https://user-images.githubusercontent.com/5498964/134242085-dca442f1-e691-45b5-9c5c-812234caacaa.mp4

**Comment by andydotxyz** [comment] 2021-09-22 11:57
Oh I see - running the temporary folder is the key here.
I guess we need a better process overall - what I would like is if the build asset can be dragged onto the simulator to run.
Is that what #2495 fixes?

**Comment by changkun** [comment] 2021-09-22 15:35
I see the issue. I also pushed a new commit in #2495, which should solve the issue for me. Does the latest #2495 solve the problem for you?

**Comment by andydotxyz** [comment] 2021-09-22 21:12
> I just noticed there is a install subcommand in the fyne command, is that an expected official approach to deploy to a target system?

Yes :)

Adding that for simulator builds would be ideal - do you have ideas about how we could make that happen?

**Comment by changkun** [comment] 2021-09-22 21:36
I just pushed a new commit in #2495 

This is how it works in a video:

https://user-images.githubusercontent.com/5498964/134425310-5996428a-45ee-4f10-affa-2a3de7c2382f.mp4


Does this match what we want to do here?

**Comment by andydotxyz** [comment] 2021-09-23 08:38
> Does this match what we want to do here?

Slick, that looks exactly like the trick :)

**Comment by changkun** [comment] 2021-12-07 06:47
Close because #2495 is merged in develop

**Closed by changkun** 2021-12-07 06:47 UTC
Labels: bug, help wanted, OS:macOS, OS:iOS, Hacktoberfest, Driver:mobile

**Comment by andydotxyz** [comment] 2022-02-10 02:29
(fixed the milestone as this solution adds a build option so isn't in the bugfix release)
