### ISSUE TITLE
Can't use it on my linux

### ISSUE THREAD

**Issue by ikouchiha47** [fyne-io/fyne#5192] opened 2024-10-13 06:29 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Module dependency resolution bug, coming from github.com/go-text/typesetting/opentype/api/metadata

### How to reproduce

With the Provided Code below.

```shell
go mod tidy
```

```shell
# output

go: finding module for package fyne.io/fyne/v2/theme
go: finding module for package fyne.io/fyne/v2/canvas
go: finding module for package fyne.io/fyne/v2
go: finding module for package fyne.io/fyne/v2/app
go: found fyne.io/fyne/v2 in fyne.io/fyne/v2 v2.5.1
go: found fyne.io/fyne/v2/app in fyne.io/fyne/v2 v2.5.1
go: found fyne.io/fyne/v2/canvas in fyne.io/fyne/v2 v2.5.1
go: found fyne.io/fyne/v2/theme in fyne.io/fyne/v2 v2.5.1
go: finding module for package github.com/go-text/typesetting/opentype/api
go: finding module for package github.com/go-text/typesetting/opentype/api/metadata
go: font-browser/render imports
	fyne.io/fyne/v2/app imports
	fyne.io/fyne/v2/internal/driver/glfw imports
	fyne.io/fyne/v2/internal/painter imports
	github.com/go-text/typesetting/opentype/api/metadata: module github.com/go-text/typesetting@latest found (v0.2.0), but does not contain package github.com/go-text/typesetting/opentype/api/metadata
go: font-browser/render imports
	fyne.io/fyne/v2/app imports
	fyne.io/fyne/v2/internal/driver/glfw imports
	fyne.io/fyne/v2/internal/painter imports
	github.com/go-text/render imports
	github.com/go-text/typesetting/opentype/api: module github.com/go-text/typesetting@latest found (v0.2.0), but does not contain package github.com/go-text/typesetting/opentype/api
```

### Example code

```go
package render

import (
	"log"
	"os"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/theme"
)

type GioRenderer struct {
	PreviewText string
}

func (gr *GioRenderer) Render(fontPath string) {
	a := app.New()
	w := a.NewWindow("Font Preview")

	fontData, err := os.ReadFile(fontPath)
	if err != nil {
		log.Fatal(err)
	}

	customTheme := theme.DefaultTheme()
	customTheme.Font = func() fyne.Resource { return theme.NewStaticResource("CustomFont", fontData) }

	textObj := canvas.NewText(gr.PreviewText, theme.TextColor())
	textObj.TextStyle.Monospace = true

	w.SetContent(textObj)
	w.Resize(fyne.NewSize(800, 600))
	w.ShowAndRun()
}
```

### Fyne version

2.5.1

### Go compiler version

go version go1.22.3 linux/amd64

### Operating system and version

Linux 6.6.35-gentoo-dist #1 SMP PREEMPT_DYNAMIC Fri Jun 21 15:41:29 -00 2024 x86_64 Intel(R) Core(TM)

**Comment by andydotxyz** [comment] 2024-10-13 14:20
It looks like you have updated dependencies, or are requesting a newer version of go-text than the one in the fyne dependency. There was a breaking change in that project, which will be resolved in our upcoming v2.5.2 - until then make sure that your go.mod returns to asking for github.com/go-text/typesetting v0.1.0.

**Comment by andydotxyz** [comment] 2024-10-13 14:21
Duplicate of #5170

**Closed by andydotxyz** 2024-10-13 14:21 UTC
Labels: unverified

**Comment by ikouchiha47** [comment] 2024-10-13 18:21
```go.mod
replace github.com/go-text/typesetting v0.2.0 => github.com/go-text/typesetting v0.1.0
```

**Comment by andydotxyz** [comment] 2024-10-15 10:52
That is no longer needed, the v2.5.2 release of Fyne is out and it resolves the break in go-text usage.
