### ISSUE TITLE
 Fyne error:  Custom filter types not supported on mobile (Android)

### ISSUE THREAD

**Issue by yml** [fyne-io/fyne#2012] opened 2021-02-23 09:07 UTC
### Describe the bug:

When I try to select a picture in wormhol-gui to send it the app crash with the following message logs:

```
02-23 09:56:17.462  6143 14200 I Fyne    : Fyne error:  Custom filter types not supported on mobile
02-23 09:56:17.462  6143 14200 I Fyne    :   At: /app/vendor/fyne.io/fyne/v2/internal/driver/gomobile/file.go:40
02-23 09:56:23.511 25043 25081 D AppsModelWriter: normalizeVisibleItems(visibleItems)> 0, 166, 0, -102, 4, 3, UserHandle{0}, 0, Fyne_demo, -1, -1
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Install wormhole-gui mobile branch (009edb2430d71eb9ddfb24b21c848f5d2deeb087)
2. Open the app
3. Click on Send
4. Select a file

### Device (please complete the following information):

 - **OS:** android
 - **Version:** 
 - **Go version:** 
 - **Fyne version:** fyne.io/fyne/v2 v2.0.1-0.20210221193418-ec32c77b3ce4

**Comment by Jacalz** [comment] 2021-02-23 09:13
To be clear here, I asked @yml to open this issue because it came up in his testing and did not seem to be an error I my code as I don’t define any custom filter types in wormhole-gui 🙂

**Comment by Jacalz** [comment] 2021-02-23 11:09
My best guess is that the function is getting a `nil` filter and the else block in https://github.com/fyne-io/fyne/blob/c29a0624ed96ba1b8f45d903b6941824d50e0502/internal/driver/gomobile/file.go#L40 flags that as not being a valid filter.

**Comment by andydotxyz** [comment] 2021-02-23 11:23
> app crash with the following message logs

Are you certain the app crashed? That logged error should not be the cause of a crash.

**Comment by andydotxyz** [comment] 2021-02-23 11:25
> My best guess is that the function is getting a nil filter and the else block in

I can't see a `nil` filter, it is simply not setting any fields...

**Comment by andydotxyz** [comment] 2021-02-23 11:27
> flags that as not being a valid filter.

Agreed. But that should not cause a crash...

**Comment by Jacalz** [comment] 2021-02-23 12:11
> > flags that as not being a valid filter.
> 
> Agreed. But that should not cause a crash...

Indeed, certainly not. I guess we need to figure out what’s causing the crash. In the meantime, it looks like we squashed a little bug 🙂

**Comment by Jacalz** [comment] 2021-02-24 11:58
Fixed as of https://github.com/fyne-io/fyne/commit/fcad6b2d20023a5b99f45332f1fc85c5bd79b9a9. Closing this.

**Closed by Jacalz** 2021-02-24 11:58 UTC
Labels: bug
