### ISSUE TITLE
The paste does not trigger the Validator.

### ISSUE THREAD

**Issue by aohanhongzhi** [fyne-io/fyne#5060] opened 2024-08-09 05:57 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

 when I paste the text to ` widget.NewEntry()`, The paste does not trigger the Validator.

### How to reproduce

1. copy text 
2.  paste it to ` widget.NewEntry()`
3. The paste does not trigger the Validator.

### Screenshots

![image](https://github.com/user-attachments/assets/407e0b45-20d2-4238-9728-6242be2a2818)

### Example code

```go
	username := widget.NewEntry()
	username.SetPlaceHolder("输入账号")
	// 设置自定义验证器
	username.Validator = func(s string) error {
		if len(s) < 2 {
			return fmt.Errorf("账号长度必须大于1")
		}
		if len(s) > 24 {
			return fmt.Errorf("账号长度必须小于24")
		}
		return nil
	}
```

### Fyne version

2.5.0

### Go compiler version

go1.22.4

### Operating system and version

ubuntu 22.04 , windows

**Comment by andydotxyz** [comment] 2024-08-09 07:44
This looks like a duplicate of #5058

**Closed by andydotxyz** 2024-08-09 07:44 UTC
Labels: unverified
