### ISSUE TITLE
Window sometimes freezes on startup and doesn't scale properly on wayland (sway)

### ISSUE THREAD

**Issue by Rasmustex** [fyne-io/fyne#3200] opened 2022-08-10 17:21 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I've created a simple program for creating a dialog box from command line arguments using fyne. It works great, but sometimes (maybe 1/4 if I had to guess) when I run it under the sway window manager, the window contents fail to scale at all, and the window in general seems to freeze. I cannot close the window unless I kill the program from the terminal. I get no output to the terminal from which the program is run. Other times, it works just fine. This also happens with the "hello world" example provided in the docs.

### How to reproduce

1. Build and run the hello world example from the fyne docs under sway.
2. Repeat until issue occurs. Shouldn't take more than 10 tries.

### Screenshots

![image](https://user-images.githubusercontent.com/71628935/183903690-60b08d15-eed9-47c3-a171-d913390da79f.png)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}

```

### Fyne version

2.2.3

### Go compiler version

1.19

### Operating system

Linux

### Operating system version

Arch linux using sway

**Comment by andydotxyz** [comment] 2022-08-11 20:29
I think this is a duplicate of #2850

**Closed** 2022-08-11 20:34 UTC
Labels: unverified

**Comment by Jacalz** [comment] 2022-08-11 20:53
Agreed. I updated the labels accordingly.
