### ISSUE TITLE
congratulations on 2.0 release , is it time to bring up the multimedia support ? 

### ISSUE THREAD

**Issue by c1ngular** [fyne-io/fyne#1869] opened 2021-01-27 01:36 UTC
as discussed in #449 ,  multimedia support based on libmpv , it would be a killer feature .

**Comment by AlbinoGeek** [comment] 2021-01-27 01:45
That's 3.0, as it requires full GPU raster and shaders to be performant imo.

**Comment by c1ngular** [comment] 2021-01-27 02:13
@AlbinoGeek  so it is expecting some work on gl/glfw upstream before start implementing or experimenting ?  i have tried to integrate libmpv into a qt(qml) app , it is working pretty well, so i may have underestimated the work amount and difficulty to do the same on fyne .

**Comment by AlbinoGeek** [comment] 2021-01-27 02:20
Honestly, I do not think any work has to be done upstream, but I am not
sure. I'm not the one to ask.

My understanding, is that currently the framework doesn't do much with the
graphics card.

Having implemented transcoding in other frameworks, I can definitely tell
you that software rendered you so far, 2160p60 on modern hardware without
too much issue.

That being said, even implementing this, requires a concept of a stream,
and some communication with the graphics card, neither of which we have
much of in the framework at the moment.

That being said, I was able to render a small gif it over 40 FPS using code
that someone else posted here, but I couldn't get much further than that.

When I tried converting a video into a sequence of `fyne.Resource` based on
golang Image, I could not display full frames at even 30 FPS.

---

It's also worth that currently within this framework, every widget will
work on every platform, which means that they not only need to implement
this on desktop, but on both mobile platforms as well.

**Comment by c1ngular** [comment] 2021-01-27 02:32
@AlbinoGeek  good to know your thinking and finding , thanks .

**Comment by andydotxyz** [comment] 2021-01-27 10:17
LibMPV is LGPL and so we cannot statically link to it, meaning it cannot be bundled.
We will not add runtime dependencies to this project as it reduces portability.
A full solution is a way off for these, and many other, reasons. 3.0 is still the best estimate of when it would be possible.

In the shorter-term you could consider building a widget for the `fyne-io/fyne-x` repository where the same dependency restrictions do not exist.

**Comment by andydotxyz** [comment] 2021-01-27 10:17
Closing as duplicate of #449

**Closed by andydotxyz** 2021-01-27 10:17 UTC
