### ISSUE TITLE
Text selection does not place cursor at mouse up position

### ISSUE THREAD

**Issue by pbarnum** [fyne-io/fyne#419] opened 2019-08-27 03:09 UTC
Most (if not all) software sets the cursor position at the place you stopped when selecting text.

**Comment by andydotxyz** [comment] 2019-08-27 19:07
Can you please expand on how to replicate this? Looking at it I can't immediately see what is wrong.

**Comment by andydotxyz** [comment] 2019-08-28 21:44
How does this bug manifest? In my mind after selection the cursor position will be reset because you are either replacing a block or moving out of it.
Do you have steps to reproduce the resulting bug rather than just the selected state missmatch?

**Comment by andydotxyz** [comment] 2019-09-24 03:33
Perhaps you can confirm how it is that you are checking the cursor position? right now i can't see the cursor when text is selected

**Comment by pbarnum** [comment] 2019-10-11 23:55
Sorry for the late reply, I haven't found time to provide a way to recreate it. I'll comment again when I get the chance.

**Comment by andydotxyz** [comment] 2020-02-26 22:42
Can we perhaps close it off - it's been a while? It could always be re-opened if you can recreate it

**Comment by pbarnum** [comment] 2020-02-27 07:31
Hey sorry, I haven't had time to come back to this project. Feel free to close the issue, it can always be re-opened.

**Comment by andydotxyz** [comment] 2020-02-27 10:19
thanks

**Closed by andydotxyz** 2020-02-27 10:19 UTC
Labels: question
