### ISSUE TITLE
list.ScrollToBottom not scrolling to show the totality of the last Item

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3829] opened 2023-04-16 13:34 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When calling .ScrollToBottom, the last list item should be entirely displayed, not only it's top part.

It works well if the last item height is the same as when createItem() function is called.

### How to reproduce

Run the code and tap the button

### Screenshots

Bad
![test_wmfQqVhywX](https://user-images.githubusercontent.com/1791230/232314970-fce2e9d8-e503-4141-b71e-8fd9bdff88bf.png)
Good
![test_8iQtxyKCrn](https://user-images.githubusercontent.com/1791230/232314974-bb6e357c-dd6e-468d-8c38-e99f2274c1fd.png)

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")

	var data []string
	for i := 1; i < 100; i++ {
		data = append(data, fmt.Sprintf("This is item N°%02d\nSpaning on 3 lines\nHere the last one", i))
	}

	var list *widget.List
	list = widget.NewList(
		func() int { return len(data) },
		func() fyne.CanvasObject { return widget.NewLabel("") }, // <=== change this line to .NewLabel("\n\n") to correct scrolling
		func(lii widget.ListItemID, co fyne.CanvasObject) {
			co.(*widget.Label).SetText(data[lii])
			list.SetItemHeight(lii, co.MinSize().Height)
		},
	)

	w.SetContent(container.NewBorder(nil, widget.NewButton("ScrollToBottom", func() { list.ScrollToBottom() }), nil, nil, list))

	w.ShowAndRun()
}
```

### Fyne version

2.3.2

### Go compiler version

1.20

### Operating system and version

Windows 10

**Comment by Jacalz** [comment] 2023-04-22 13:37
I think this might be a duplicate of https://github.com/fyne-io/fyne/issues/2917.

**Comment by matwachich** [comment] 2023-04-29 18:31
As mentioned in slack (but it should have been done here), I think this has somerhing to do with item heights.

I mean it's like the scrolling considers the initial item height, as when calling CreateItem callback.

If I return a 3 lines label in this example, the scrolling is done correctly.

**Comment by andydotxyz** [comment] 2023-04-30 17:32
Yes, not scrolling and most scrolling far enough are likely different.

**Comment by andydotxyz** [comment] 2023-08-19 07:52
This issue was resolved. But I see it is possible still to reproduce it.
If the bottom row has never been shown we do not know how long it is. We scroll as far as we think we need to given the template * rows & any known unusually sized rows.
It isn't until after scrolling that the item is shown and the `SetItemHeight` call is made - so we are doing the best we can.

I don't see a way to "fully resolve" this without adding a "read all lines and lay out my whole table" call, which may be useful for small tables where people just don't care about the performance it was built for.

The solution is to either a) correct the template size to be representative, or b) to load your data and set the sizes before each item is shown.
I guess this is why apps like iMessage or Slack sometimes don't get scrolling right too?

**Closed by andydotxyz** 2023-08-19 07:52 UTC
Labels: bug
