### ISSUE TITLE
writing this will crash

### ISSUE THREAD

**Issue by junmaqiang** [fyne-io/fyne#3129] opened 2022-07-08 10:35 UTC
Write like this, the computer will crash

### Example code:
is ok
```go
func (DIYTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	switch name {
	case theme.IconNameFolder:
		return resourceLogoPng
	// case theme.IconNameContentAdd:
	// 	return resourceEmptyinfoSvg
	default:
		return theme.DefaultTheme().Icon(name)
	}
}
```

is bad
```go
func (DIYTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	switch name {
	case theme.IconNameFolder:
		return resourceLogoPng
	case theme.IconNameContentAdd:
		return resourceEmptyinfoSvg
	default:
		return theme.DefaultTheme().Icon(name)
	}
}
```

### Device (please complete the following information):
 - **OS:**  MacOS 
 - **Go version:**  1.18.1
 - **Fyne version:**  2.2.1

**Comment by Jacalz** [comment] 2022-07-08 13:37
Please fill out the template with an full example code. There is not sufficient information to know why it crashes.

**Comment by Jacalz** [comment] 2022-07-08 13:38
> the computer will crash

Are you sure that the whole computer crashes? An application should almost never crash the whole computer.

**Comment by junmaqiang** [comment] 2022-07-09 00:12
@

> > 电脑会崩溃
> 
> 你确定整个电脑都崩溃了？一个应用程序几乎不应该让整个计算机崩溃。

yes i am sure and a lot

**Comment by junmaqiang** [comment] 2022-07-09 00:17
> 请使用完整的示例代码填写模板。没有足够的信息知道它为什么会崩溃。
![WX20220709-081656](https://user-images.githubusercontent.com/1819457/178084108-16dca902-6c4b-4728-9c33-b8a07eced9ce.png)

**Comment by Jacalz** [comment] 2022-07-09 08:06
I understand that for that it is there but it still isn't a full runnable code example. There could be an issue in how you define `resourceEmptyinfoSvg` and we'd have no way of knowing.

**Comment by andydotxyz** [comment] 2022-07-09 15:22
You have specified that returning `resourceEmptyinfoSvg` will crash your computer - but not shown what that variable contains. @Jacalz is right there is not enough information to progress yet.

**Comment by junmaqiang** [comment] 2022-07-10 01:09
fyne bundle -append "${srcPath}/emptyinfo.svg" >> $srcName

resourceEmptyinfoSvg 

![emptyinfo](https://user-images.githubusercontent.com/1819457/178127501-8de2d78f-8a02-4fe5-b516-b0ca5d7b5a0d.svg)

**Comment by Jacalz** [comment] 2022-07-10 11:00
That still isn’t any code that we can run. We want a single file of Go code (inside a code block here on GitHub) that we easily can run to test out the problem locally. Screenshots of small pieces of code is impossible to debug.

**Comment by Jacalz** [comment] 2022-07-10 11:40
Also, please attach the stack trace from the crash. It should contain more information on where it crashes.

**Comment by andydotxyz** [comment] 2022-07-15 00:48
I cannot replicate the error, resource loads OK.
Admittedly gradients are missing, but that is a separate issue.
<img width="848" alt="Screenshot 2022-07-14 at 17 47 21" src="https://user-images.githubusercontent.com/294436/179124730-445488be-cf3b-4c80-accf-a892139197ca.png">

**Comment by junmaqiang** [comment] 2022-07-15 04:59
The problem is not in the picture, but when there are two cases in the switch  @andydotxyz

**Comment by Jacalz** [comment] 2022-07-15 05:04
> The problem is not in the picture, but when there are two cases in the switch
> 
> Because both of my cases are custom resources
> 
>   @andydotxyz 

That is precisely why you should share the full code with us. We are having a hard time reproducing without it...

**Comment by andydotxyz** [comment] 2022-07-15 15:41
There is no limit to the number of custom resources, there is no obvious reason why adding a switch would cause an app to crash. As @Jacalz says unless you can provide the code we can execute to replicate the issue we will have to close this because we have no ability to see the problem.

**Comment by junmaqiang** [comment] 2022-07-17 12:52
I changed a picture and tested it, is it because the name has empty

![999](https://user-images.githubusercontent.com/1819457/179399156-09ef1099-4e54-46a3-964a-b6b9f1d16e72.png)

**Comment by Jacalz** [comment] 2022-07-17 13:11
We have absolutely no way of knowing as we don’t have the code. We can’t help you without it. Feel free to reopen if you have something that we can look at.

**Closed by Jacalz** 2022-07-17 13:12 UTC
Labels: unverified, information-needed
