### ISSUE TITLE
entry can't handle large text input very well.

### ISSUE THREAD

**Issue by 0x414a** [fyne-io/fyne#4380] opened 2023-11-12 00:37 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

entry can't handle large text input very well. First, large text renders very slowly (stalls, high memory usage). Second, when you add or delete a large text after writing it, you render the whole text instead of partial text, which again leads to high memory usage, stalls, And after the entry is lost, the focus will be re-rendered, which is very repetitive and wasteful of resources. Could GOTK3 provide a more fine-grained control over text display and update via GtkTextView and GtkTextBuffer? entry doesn't handle large text input very well. Secondly, adding and deleting after writing a large amount of text is to render the whole text rather than the part, so that there will be a high memory occupation and stagnation. I wonder if GOTK3 provides a more fine-grained control over the display and update of text via GtkTextView and GtkTextBuffer``

### How to reproduce

When you write 2662 lines of 208,125 characters or more into entry, you get a stutter, a high memory footprint, and the addition or deletion of parts at any point renders not partially, but fully

### Screenshots

<img width="1675" alt="image" src="https://github.com/fyne-io/fyne/assets/51728752/962f054b-4c40-46b1-822d-b3ea5e5ea7ae">

### Example code

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Entry Example")

	entry := widget.NewEntry()
	entry.MultiLine = true
	entry.Wrapping = fyne.TextWrapWord

	myWindow.SetContent(entry)
	myWindow.Resize(fyne.NewSize(400, 600))
	myWindow.ShowAndRun()
}

### Fyne version

fyne version v2.4.0

### Go compiler version

go version go1.20.2

### Operating system and version

darwin/arm64

**Comment by andydotxyz** [comment] 2023-11-13 08:13
I think this is a duplicate of #2969.
We are working to make Entry more like List behind the scenes so it does not have to render the entire document to get the text positions and scroll height calculated.

**Closed** 2023-11-13 08:13 UTC
Labels: duplicate

**Comment by 0x414a** [comment] 2023-11-14 00:17
> I think this is a duplicate of #2969. We are working to make Entry more like List behind the scenes so it does not have to render the entire document to get the text positions and scroll height calculated.

Thanks, it's similar to #2969, the main problem is that the rendering of a lot of text is stutty and not smooth enough.

**Comment by 0x414a** [comment] 2023-11-14 07:23
> I think this is a duplicate of #2969. We are working to make Entry more like List behind the scenes so it does not have to render the entire document to get the text positions and scroll height calculated.

I noticed that issue #2969 has been unresolved since May 2022, and I'm uncertain how much longer it might take now that I've brought it up again.   I'm in the business of developing penetration testing tools and have transitioned from GOTK3 to Fyne.   While GOTK3 is much more feature-rich, its cross-platform compilation is quite cumbersome, leading me to opt for Fyne.   However, I'm urgently in need of better large text rendering capabilities.   I'm hoping for an early enhancement in the handling of large texts.

**Comment by 0x414a** [comment] 2023-11-14 07:23
> I think this is a duplicate of #2969. We are working to make Entry more like List behind the scenes so it does not have to render the entire document to get the text positions and scroll height calculated.

I noticed that issue #2969 has been unresolved since May 2022, and I'm uncertain how much longer it might take now that I've brought it up again.   I'm in the business of developing penetration testing tools and have transitioned from GOTK3 to Fyne.   While GOTK3 is much more feature-rich, its cross-platform compilation is quite cumbersome, leading me to opt for Fyne.   However, I'm urgently in need of better large text rendering capabilities.   I'm hoping for an early enhancement in the handling of large texts.

**Comment by andydotxyz** [comment] 2023-11-14 22:15
Like I said we are working on it. And on the linked issue I noted that it is no longer blocked.
However there is no specific timescale and, as many open source projects, contributors generally work on what matters to them.

> However, I'm urgently in need of better large text rendering capabilities

If you wish to influence our priorities the project accepts sponsorships and may of our developers are open to paid work that accelerates the project forward.
