### ISSUE TITLE
when use keypad entry input non-English text that cannot be focus it doesn't like many software do.

### ISSUE THREAD

**Issue by conero** [fyne-io/fyne#360] opened 2019-07-12 01:46 UTC
_when use **[keypad entry]** input non-English text that cannot be focus it like many software do. Did I missed something or? How to fix it out._

_example Like: _

> unfocus
![unfocus-1](https://user-images.githubusercontent.com/19564821/61096179-3d740800-a489-11e9-8a9e-48f25cd5a14b.png)

> focus: this is what I want
*image 1*
![focus-1](https://user-images.githubusercontent.com/19564821/61096205-58467c80-a489-11e9-9a43-287b02b51e77.png)

*image 2*
![focus-2](https://user-images.githubusercontent.com/19564821/61096284-8f1c9280-a489-11e9-8308-7a8f80eed5a5.png)

**Comment by andydotxyz** [comment] 2019-07-12 08:34
Focus was added with the 1.1.0 release, it looks like you are using 1.0.x, just update your version and it should work as expected. (go get -u fyne.io/fyne)

**Comment by conero** [comment] 2019-07-13 01:43
*sorry, that man! I use the v1.1.0 still don't work！*
![20190713094101](https://user-images.githubusercontent.com/19564821/61165399-95c30c80-a552-11e9-82a6-e4422a7582ec.png)

**Comment by andydotxyz** [comment] 2019-07-13 21:17
Oh, I am sorry I misunderstood. Is this a duplicate of #73?

**Comment by conero** [comment] 2019-07-15 01:05
@andydotxyz it's not duplicate. The case is that input can enter text but cannot focus when enter.

**Comment by andydotxyz** [comment] 2019-07-15 08:35
Sorry I’m confused - the entry looks focused on your screenshot. In what way is it not focused?

**Comment by conero** [comment] 2019-07-15 15:30
@andydotxyz I am sorry that can't descrip the issue accurately too. If you can maybe try enter non-English Words and English just to find what is different.

**Comment by ohir** [comment] 2019-07-15 17:01
> can't descrip the issue accurately too. If you can maybe try enter non-English Words and English just to find what is different.

Make a screencast and post to youtube then. It can be something that manifests only under Asian locales (you seem to use) so developers on OS equipped only in latin based locales can not experience this behavior you see (eg. we have no IME layer).

**Comment by conero** [comment] 2019-07-16 00:49
@ohir Ok, and thank for that tips. Yep, the issue was happen on IME layer.

**Comment by andydotxyz** [comment] 2019-07-16 09:50
Perhaps you can try some of the tips on #63?

**Closed** 2019-07-16 09:51 UTC
