### ISSUE TITLE
Compilation warnings on MacOS Big Sur

### ISSUE THREAD

**Issue by kargirwar** [fyne-io/fyne#1900] opened 2021-02-04 06:04 UTC
### Describe the bug:
When building any Fyne app on MacOS Bug Sur a number of warnings related to notification are displayed.

### To Reproduce:
Try to compile following using go build.
```
package main
import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}

```
Many warnings are printed on console:

```
app_darwin.m:10:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:11:32: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:17:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:18:32: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:37:5: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:37:66: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:43:5: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:43:61: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here

```
### Screenshots:
![image](https://user-images.githubusercontent.com/33156462/106851652-a6ab1400-66dc-11eb-805f-2453995fb07d.png)

### Example code:
See above

### Device
 - **OS:** MacOS
 - **Version:** Big Sur
 - **Go version:** go1.15.6 darwin/amd64
 - **Fyne version:** 2.0.0

**Comment by andydotxyz** [comment] 2021-02-04 15:34
Yes, it seems they have deprecated more APIs.
Duplicate of #1549

**Closed by andydotxyz** 2021-02-04 15:34 UTC
Labels: bug

**Comment by khaelou** [comment] 2021-04-17 01:08
@andydotxyz Just an idea but couldn't this temporally be suppressed via code for BigSur OS types? It's a bit annoying seeing this each execution, not the first thing you'd hope for when checking logs..

**Comment by andydotxyz** [comment] 2021-04-19 10:38
We don't generally hide deprecation warnings, we try to resolve them through updating the code to support newer OS properly, this helps avoid unexpected broken code in future releaes.
If you have some code that works please consider opening a pull request.
