### ISSUE TITLE
[OsX] Unable to create basic Accelerated OpenGL renderer

### ISSUE THREAD

**Issue by IGLOU-EU** [fyne-io/fyne#2177] opened 2021-04-15 21:30 UTC
My first tiny fyne project not run

### To Reproduce:
1. go get git.iglou.eu/adrien/inadl
2. exec inadl

### Screenshots:
```
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0xc0000c3bb0, 0x2, 0x2, 0x0, 0x0)
	/Users/null/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/error.go:178 +0x20c
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x226, 0xd7, 0x449bb3c, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/null/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/window.go:350 +0x197
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func1()
	/Users/null/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/internal/driver/glfw/window.go:1309 +0x14b
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0000c6370)
	/Users/null/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/internal/driver/glfw/loop.go:97 +0x16c
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0000c6370)
	/Users/null/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/internal/driver/glfw/driver.go:79 +0x3a
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc000320000)
	/Users/null/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/internal/driver/glfw/window.go:449 +0x57
main.main()
	/Users/null/go/pkg/mod/git.iglou.eu/adrien/inadl@v0.0.2/main.go:270 +0x1109
```

### Example code:
git.iglou.eu/adrien/inadl

### Device (please complete the following information):
- **Warning:** Run under VirtualBox
 - **OS:** Mac OsX
 - **Version:** 10.15.7
 - **Go version:** 1.16.3
 - **Fyne version:** v2.0.1

**Comment by andydotxyz** [comment] 2021-04-15 22:05
You will need to turn on the OpenGL support inside VirtualBox.
Closing as duplicate of #2046

**Closed by andydotxyz** 2021-04-15 22:05 UTC
Labels: bug

**Comment by IGLOU-EU** [comment] 2021-04-15 22:10
This is already the case. But it seemed to me that OsX had aborted OpenGL

![scr_000831](https://user-images.githubusercontent.com/15379333/114944449-e6624a80-9e47-11eb-85e6-4988dd9ce7d8.png)
