### ISSUE TITLE
App.NewWindow() hangs on new App instance

### ISSUE THREAD

**Issue by ark3us** [fyne-io/fyne#2741] opened 2022-01-15 19:41 UTC
I'm not sure this is a bug or intended behavior, thank you for your attention in any case!

### Describe the bug:
App.NewWindow() hangs on new App instance after the first App instance has terminated.

### To Reproduce:
Steps to reproduce the behaviour:
Put the example code in a loop.

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	for {
		a := app.New()
		w := a.NewWindow("Hello") // <-- hangs here after the first loop

		hello := widget.NewLabel("Hello Fyne!")
		w.SetContent(container.NewVBox(
			hello,
			widget.NewButton("Hi!", func() {
				hello.SetText("Welcome :)")
			}),
		))

		w.ShowAndRun()
	}
}
```

### Device (please complete the following information):
 - **OS:** Ubuntu Linux
 - **Version:** Ubuntu 21.10, kernel 5.15.4-051504-generic
 - **Go version:** 1.17
 - **Fyne version:** 2.1.2
 ---
 - **OS:** Windows
 - **Version:** Windows 11 build 22000
 - **Go version:** 1.17.6
 - **Fyne version:** 2.1.2

**Comment by Jacalz** [comment] 2022-01-15 20:39
I don’t think we support creating more than one application. It is best to just crate one application and then open and close the windows as necessary instead.

**Comment by andydotxyz** [comment] 2022-01-16 20:38
Yeah, I think this is a duplicate of #920.
However your code should put the `NewApp` outside of the loop, re-use one application and one runloop so that caches etc work correctly.

**Closed** 2022-01-16 20:39 UTC
Labels: duplicate
