### ISSUE TITLE
FileOpen and FoldOpen:The window will always go into a subfolder automatically

### ISSUE THREAD

**Issue by 874808039** [fyne-io/fyne#5080] opened 2024-08-19 02:28 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

in  FileOpen and FoldOpen:,   When I click on a folder, the window always automatically goes to a subfolder

### How to reproduce

1,Open a FileOpen  Window
2, Click  a  dir
3,you can  see this bug, if i  click  "www" dir,  it go to  "www/file"  or other  dir

### Screenshots

none

### Example code

none

### Fyne version

2.5.0

### Go compiler version

go version go1.22.4 windows/amd64

### Operating system and version

win11

**Comment by 874808039** [comment] 2024-08-19 02:35
![image](https://github.com/user-attachments/assets/7ab8a1e0-8946-4ff9-9b06-1c1063177ee2)
![image](https://github.com/user-attachments/assets/132b02ea-887a-4542-9a7a-ceeb1728e457)
![image](https://github.com/user-attachments/assets/e77c9ec7-69ad-43c2-b24b-4d9b827ec53b)

**Comment by andydotxyz** [comment] 2024-08-19 11:36
This is a duplicate of #5053 and is resolved on the release branch already.
It will be in v2.5.1

**Closed** 2024-08-19 11:36 UTC
Labels: unverified
