### ISSUE TITLE
Bad scrolling performance on Android (Am I doing something wrong?)

### ISSUE THREAD

**Issue by nortio** [fyne-io/fyne#2350] opened 2021-08-04 11:44 UTC
### Describe the bug:

Scrolling in a List feels very choppy on Android, while it works fine on desktop. Right now I've tested the same code on three different devices with Android 10, as you can see by the three screen recordings I've left. Am I doing something wrong in the code?

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a list as shown in the tutorial in the official documentation
2. Package the application with the cli tool fyne (I've tried with release and debug, same behaviour)
3. Scroll the list

### Screen recordings

- Android 10, Honor 6x (custom rom)
https://user-images.githubusercontent.com/22685799/128174342-b158a04f-faab-415b-ae4a-078893308cd9.mp4

- Android 10, Huawei P30 (stock rom without modifications)
https://user-images.githubusercontent.com/22685799/128174448-41fe60d6-c21c-48e9-8dce-fae2d89c0445.mp4

- Android 10, Samsung J4+ (custom rom)
https://user-images.githubusercontent.com/22685799/128174533-edfad0b4-954f-49b7-b304-226ce7f6fe7c.mp4

### Example code:

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	a.Settings().SetTheme(theme.DarkTheme())
	w := a.NewWindow("Hello")
	toolbar := widget.NewToolbar(
		widget.NewToolbarAction(theme.ViewRefreshIcon(), func() {
			fmt.Println("refresh")
		}),
		widget.NewToolbarAction(theme.SearchIcon(), func() {
			fmt.Println("Search")
		}),
	)
	var data = []string{"fdsfdsf", "hgfhfgh", "khjkj", "kgjkhgjh", "uytrutyu", "ruyutyu", "3", "fdsfsdf", "3", "ehrthert", "3", "nytntrn", "3", "rtewter", "3", "3"}
	list := widget.NewList(
		func() int {
			return len(data)
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i widget.ListItemID, o fyne.CanvasObject) {
			o.(*widget.Label).SetText(data[i])
		})
	hello := widget.NewLabel("1")
	w.SetContent(
		container.NewBorder(
			container.NewHBox(
				hello,
				widget.NewButton("Test", func() {
						hello.SetText("test2")
				}),
				layout.NewSpacer(),
				toolbar,
			),
			widget.NewButtonWithIcon("New", theme.ContentAddIcon(), func() {
				fmt.Println("test")
			}),
			nil,
			nil,
			list,
		),
	)

	w.ShowAndRun()
}
```
This is basically the same code shown in the tutorials (apart from the last part)

### Device (please complete the following information):
**(this is the host device)**
 - **OS:** Manjaro
 - **Version:** 5.13
 - **Go version:** 1.16.6 
 - **Fyne version:** 2.0.3

**(these are the android devices)**
#### First device 
- Android 10, Honor 6x (custom rom); arm64-v8a; gles 3.2 (mali g76)

#### Second device
- Android 10, Huawei P30 (stock rom without modifications); arm64-v8a; gles 3.2 (mali t830)

#### Third device
- Android 10, Samsung J4+ (custom rom); armeabi-v7a; gles 3.0 (adreno 308)

**Comment by andydotxyz** [comment] 2021-08-04 12:43
I think this is a duplicate of #1062, we have not yet found the root cause - iOS is fine so it's not the driver itself but something about how our code/painting runs through Android GLES.

**Comment by andydotxyz** [comment] 2021-08-04 12:44
(closing as dupe)

**Closed by andydotxyz** 2021-08-04 12:44 UTC
Labels: duplicate
