### ISSUE TITLE
Drag option for borderless window?

### ISSUE THREAD

**Issue by Patamen** [fyne-io/fyne#3615] opened 2023-01-30 15:57 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Default windows theme is just messing with my eyes
I tried to create custom draggable bar, but there's no any exposed method to change window position

### Describe the solution you'd like to see.

Any exposed method that would let change window pos
Or any configurable object that describes for a specifis object to be a title bar that would act as window-draggable object

**Comment by Jacalz** [comment] 2023-01-30 18:19
Kind of a possible duplicate of https://github.com/fyne-io/fyne/issues/1155 (at least partly)?

The window without borders is a splash window and I believe the idea is to only have it centered in the screen. If you want to move around the window by dragging it, does it not make sense to keep the window borders instead of removing them?

**Comment by andydotxyz** [comment] 2023-01-30 19:55
Given our push for a clean and consistent user experience I don't think we should start adding ways to change how window borders look - that is set by your OS. If you want to change it use the settings it provides.

**Comment by Patamen** [comment] 2023-01-31 10:38
> Given our push for a clean and consistent user experience I don't think we should start adding ways to change how window borders look - that is set by your OS. If you want to change it use the settings it provides.

There's quite many examples where good apps try to achieve more non-windows looking style

This is up to you of course
But if there were other issues that stand "Please let me write code to move the window" 
Maybe it would be not that bad idea

**Comment by andydotxyz** [comment] 2023-01-31 14:53
There is a long discussion about why we have not added the ability to add code to move windows already at #1155.
Maybe this issue should be closed as a duplicate?

**Comment by Jacalz** [comment] 2023-01-31 17:41
I agree. Seems like a duplicate of that. Will close

**Closed** 2023-01-31 17:41 UTC
