### ISSUE TITLE
Error building Android package

### ISSUE THREAD

**Issue by db-tech** [fyne-io/fyne#3682] opened 2023-02-25 22:04 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I tried to build a android package with this:

```
fyne package -os android -appID com.example.myapp
```

But i get this error message:
```
go build -buildmode=c-shared -o /tmp/fyne-work-1285588444/lib/armeabi-v7a/libconbee2controller.so conbee2controller failed: exit status 1
# runtime/cgo
error: unknown warning option '-Wno-return-local-addr'; did you mean '-Wno-return-stack-address'? [-Werror,-Wunknown-warning-option]
```

I tried to point `ANDROID_NDK_HOME` to different ndk versions, but that didn't change anything

### How to reproduce

```
git clone https://github.com/db-tech/fynedemo.git
cd fynedemo/
fyne package -os android -appID com.example.myap
```

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}
```

### Fyne version

v2.3.1

### Go compiler version

1.20

### Operating system and version

Manjaro Linux

**Comment by Bluebugs** [comment] 2023-02-25 22:20
What ndk version have you tested?

**Comment by andydotxyz** [comment] 2023-02-25 22:21
Do you use any C code or native libraries?

**Comment by db-tech** [comment] 2023-02-25 22:34
> What ndk version have you tested?

I tried:

- 21.1.6352462
- 21.3.6528147
- 21.4.7075529
- 22.0.6917172
- 25.2.9519653





> Do you use any C code or native libraries?

No, just the hello world

**Comment by andydotxyz** [comment] 2023-02-27 21:39
It might be a random question but what architecture is your Linux host?

**Comment by db-tech** [comment] 2023-02-28 06:40
X86_64.. Standard

**Comment by andydotxyz** [comment] 2023-02-28 09:03
Reading up on this it could be because the C compiler used is not the one in the NDK somehow. Do you have `CC` or any compiler related parameters set on your environment perhaps?

**Comment by db-tech** [comment] 2023-03-01 17:39
I don't think so, at least I don't have CC or CXX set.. any other variables I should check? How can I test if the right compiler is being used ?

**Comment by andydotxyz** [comment] 2023-03-01 22:37
Maybe typing "which gcc" can tell us more?

**Comment by andydotxyz** [comment] 2023-03-01 22:41
Quick questions perhaps - how did you install the NDK, and what is ANDROID_NDK_HOME set to?

**Comment by db-tech** [comment] 2023-03-02 21:58
I've installed the ndk with the help of the Android Studio and the SDK Manager.
ANDROID_NDK_HOME is pointing to the ndk directory. I tried multiple versions. 
e.g. ~/Android/Sdk/ndk/22.0.6917172

I am also using the ndk for some C development, independent of fyne, this usually works.

**Comment by Bluebugs** [comment] 2023-03-02 22:08
I can't manage to reproduce this. I think the next step would be to share the content of your environment variable with us. Use the command `export` for that, check that their isn't any secret key or anything you wouldn't want to share and paste it here.

**Comment by db-tech** [comment] 2023-03-02 22:14
Wow, I was not aware of the `export` command. This gave me the chance to check all my variables.
And I found the problem right away... for some reason (don't ask me why) I've got CGO_CFLAGS set to this:
```
CGO_CFLAGS="-g -O2 -Wno-return-local-addr"
```

Thanks, this command will be really helpful in the future !

**Comment by Bluebugs** [comment] 2023-03-02 22:21
Oh, excellent! If the problem is solved for you, feel free to close this issue.

**Closed** 2023-03-02 22:22 UTC
Labels: unverified
