### ISSUE TITLE
Rich text hyperlink segment: add OnTapped callback (like widget.Hyperlink)

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3619] opened 2023-01-31 01:23 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

There is no API for assigning a custom handler to a HyperlinkSegment in a RichText display. This functionality exists in the standard widget.Hyperlink

### Is it possible to construct a solution with the existing API?

not without extending rich text widget

### Describe the solution you'd like to see.

Add an `OnTapped func()` to the HyperlinkSegment struct, just like the one on the Hyperlink widget.

**Comment by Jacalz** [comment] 2023-01-31 08:30
This has already been solved on develop for https://github.com/fyne-io/fyne/issues/3335. Closing as duplicate of that issue.

**Closed by Jacalz** 2023-01-31 08:30 UTC
