### ISSUE TITLE
v2.3.0 load ttc font file error

### ISSUE THREAD

**Issue by chindev2012** [fyne-io/fyne#3509] opened 2022-12-28 06:36 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

2022/12/28 14:09:20 Fyne error:  font load error
2022/12/28 14:09:20   Cause: unsupported font format
2022/12/28 14:09:20   At: C:/Users/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/font.go:150
panic: runtime error: invalid memory address or nil pointer dereference

### How to reproduce

Install fyne v2.3.0
Use code from example

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"os"
)

func init(){
	os.Setenv("FYNE_FONT", "C:\\windows\\fonts\\msyh.ttc")
}

func main() {
	a := app.New()
	w := a.NewWindow("demo")
        w.Resize(fyne.Size{300, 200})
	w.CenterOnScreen()
	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}
```

### Fyne version

2.3.0

### Go compiler version

1.19.3

### Operating system

Windows

### Operating system version

Windows 11 22H2 Build 22621.963

**Comment by andydotxyz** [comment] 2022-12-28 20:18
Seems like a dupe of #3245 - we only support .ttf at this time.

**Closed** 2022-12-28 20:18 UTC
Labels: duplicate
