### ISSUE TITLE
Rendering model is broken with regard to updates

### ISSUE THREAD

**Issue by pjanx** [fyne-io/fyne#5265] opened 2024-11-13 09:59 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

See the screencaps.

### How to reproduce

Make some compute-expensive changes within Fyne while updating different widgets.

### Screenshots

[Peek 2024-11-13 10-54.webm](https://github.com/user-attachments/assets/edddf5cd-f4b6-4a30-aaac-cee0787986fb)

https://github.com/user-attachments/assets/f8b65732-41fc-46e4-bacc-52ab522b0a28

### Example code

Adjust the string repeat counts to make it appropriately slow.
```
package main

import (
	"strings"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Bugs")
	w.Resize(fyne.NewSize(480, 360))
	me := widget.NewMultiLineEntry()
	l := widget.NewLabel("")
	w.SetContent(container.NewBorder(nil, nil, l, nil, me))

	long := strings.Repeat("Lorem ipsum dolor sit amet\n", 260)
	short := strings.Repeat("Lorem ipsum dolor sit amet\n", 240)
	var which bool
	t := time.NewTicker(time.Second / 2)
	go func() {
		for {
			<-t.C
			which = !which
			if which {
				me.SetText(long)
				l.SetText(":DDDDDDDDD")
			} else {
				me.SetText(short)
				l.SetText(":D")
			}
			me.TypedKey(&fyne.KeyEvent{Name: fyne.KeyPageDown})
		}
	}()
	w.ShowAndRun()
}
```

### Fyne version

2.5.2

### Go compiler version

1.23.2

### Operating system and version

Linux, macOS

**Comment by dweymouth** [comment] 2024-12-19 19:36
This seems like a duplicate of #5059 to me

**Closed by dweymouth** 2024-12-19 19:36 UTC
Labels: unverified

**Comment by pjanx** [comment] 2024-12-20 03:11
The main point is that rendering should in no circumstances at all overlap, nor should textures ever be stretched like this.

**Comment by andydotxyz** [comment] 2024-12-20 08:51
When the CPU was pushed really hard it was possible that ordering of execution changed.
In 2.6 we have changed the model so it is no longer possible.
