### ISSUE TITLE
widget.Select -ClearSelect() causes run time error if "" string not handled by OnChanged function.

### ISSUE THREAD

**Issue by datboy-design** [fyne-io/fyne#2158] opened 2021-04-11 11:28 UTC
### Describe the bug:
widget.Select.ClearSelect() passes a "" string back to updateSelect() which in turn passes a "" value to the OnChanged function, if present. This means it is not a simple clearance and could cause unwanted side effects as well as runtime errors if not handled correctly by the OnChanged function when presented with a "" value. I think this should either be clearly documented or preferably prevented.

### To Reproduce:
Steps to reproduce the behaviour:

### Device (please complete the following information):
 - **OS:** 
 - **Version:** 
 - **Go version:** 
 - **Fyne version:**

**Comment by andydotxyz** [comment] 2021-04-11 17:53
Thanks for the report, though next time please complete the template as it helps.
From your description it is not clear what the issue is?
We are considering setting a “Required” flag that shows fields cannot be set to empty, but currently all input can allow the user to delete their selection...

**Comment by Jacalz** [comment] 2021-07-27 20:25
I think this is more about the case that calling `ClearSelection()` calls `OnChanged()` with an empty string which might take some users by surprise.

However, I am not sure what the claims about runtime errors are about. If the user has defined the `OnChanged()` function, it is up to the user to verify that the input is correct and won’t cause a panic.

**Comment by andydotxyz** [comment] 2021-07-28 13:01
Yes I agree that it is reasonable to expect that Clear sets "". At most we could improve documentation, otherwise this is probably won't-fix

**Comment by Jacalz** [comment] 2021-11-21 16:12
Closing as wontfix per the above comments. Passing "" is perfectly reasonable.

**Closed by Jacalz** 2021-11-21 16:12 UTC
Labels: not an issue, wontfix
