### ISSUE TITLE
no required module provides package fyne.io/fyne/v2/app: go.mod file not found in current directory or any parent directory

### ISSUE THREAD

**Issue by sudokit** [fyne-io/fyne#2537] opened 2021-10-07 19:16 UTC
`go run main.go 
main.go:4:2: no required module provides package fyne.io/fyne/v2/app: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:5:2: no required module provides package fyne.io/fyne/v2/container: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:6:2: no required module provides package fyne.io/fyne/v2/widget: go.mod file not found in current directory or any parent directory; see 'go help modules'`
I tried doing all installation steps and everything. Still getting this problem...

**Comment by Jacalz** [comment] 2021-10-08 06:36
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

**Comment by andydotxyz** [comment] 2021-10-08 12:53
It sounds like the error is quite helpful:
`go.mod file not found in current directory or any parent directory`
You must be using a version of Go that requires modules, but your project does not have one.
As @Jacalz says please provide the information requested so we're not just guessing.

**Comment by sudokit** [comment] 2021-10-08 16:19
Go complains about not finding the included package
```"fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/widget"```

### To Reproduce:
Steps to reproduce the behaviour:
1. Install go
2. Proceed with fyne installation steps
3. import the packages:
```"fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/widget"```
4. It errors with
```main.go:4:2: no required module provides package fyne.io/fyne/v2/app: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:5:2: no required module provides package fyne.io/fyne/v2/container: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:6:2: no required module provides package fyne.io/fyne/v2/widget: go.mod file not found in current directory or any parent directory; see 'go help modules'```


```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}

```
-->


### Device (please complete the following information):
 - **OS:** Linux
 - **Go version:** go version go1.17.1 linux/amd64
 - **Fyne version:** latest

**Comment by andydotxyz** [comment] 2021-10-09 09:31
> What go version requires modules?

1.16

This is not a bug in the Fyne toolkit, your app needs a go.mod file with your version of go.

**Closed as completed** 2021-10-09 09:32 UTC
Labels: not an issue

**Comment by metacortexplus** [comment] 2021-11-18 13:21
Still not mentioned in various Fyne docs.

**Comment by Jacalz** [comment] 2021-11-18 13:31
> Still not mentioned in various Fyne docs.

I really don't think this should have to be mentioned in our docs. This is a problem that the Go developers introduced when making modules required in Go 1.16. This might sound a bit harsh, but I think it's up to them to educate developers on how to use the language and it's tools.

**Comment by andydotxyz** [comment] 2021-11-18 18:09
Maybe we need a new tutorial - not just a "here's the code" but a "how do I make my first Go GUI" which could include it?

**Comment by metacortexplus** [comment] 2021-11-18 18:09
That sound like avoiding success at any cost.
Currently so called tutorial on getting started provide info that leads to an error. Is that OK?

**Comment by Jacalz** [comment] 2021-11-19 12:03
I see now that the docs need to be updated. I’ll get a PR up for that. However, I still think that Go kind of has made it worse for the users. I have seen many people getting confused about modules.

**Comment by ChinmayGopal931** [comment] 2021-11-21 13:09
> `go run main.go main.go:4:2: no required module provides package fyne.io/fyne/v2/app: go.mod file not found in current directory or any parent directory; see 'go help modules' main.go:5:2: no required module provides package fyne.io/fyne/v2/container: go.mod file not found in current directory or any parent directory; see 'go help modules' main.go:6:2: no required module provides package fyne.io/fyne/v2/widget: go.mod file not found in current directory or any parent directory; see 'go help modules'` I tried doing all installation steps and everything. Still getting this problem...

How did you end of solving the error? I am facing the same issue

**Comment by Jacalz** [comment] 2021-11-21 14:18
> 

I think it's the exact same solution. You need to set up your modules correctly. The https://golang.org/doc/tutorial/getting-started tutorial is good, but in short, you have to do `go mod init` (if you haven't done that already), `go get fyne.io/fyne/v2` (might not be required any more but shouldn't hurt) and `go mod tidy`.

**Comment by Jacalz** [comment] 2021-11-21 15:43
I have now opened https://github.com/fyne-io/developer.fyne.io/pull/57. I hope that solves these issue for you.
