### ISSUE TITLE
TextGrid is very slow. In combination with ScrollContainer, the problem is much worse

### ISSUE THREAD

**Issue by Ragin-LundF** [fyne-io/fyne#1142] opened 2020-06-27 01:38 UTC
### Describe the bug:
When I use a TextGrid inside a ScrollContainer it will become very slow.
Text length
- `<` 50 are fast
- `<` 200 are acceptable, but slow
- `<` 500 are unusable
- `>` 800 crashs my system

Without a ScrollContainer it is much faster, but when I add too many lines (currently ~27) to the TextGrid it becomes also very slow, but in this case, the system still responds.

### Example code:
```go
// textContent contains log-like data
grid := widget.NewTextGridFromString(textContent)
scrollContainer := widget.NewScrollContainer(grid)
scrollContainer.SetMinSize(fyne.NewSize(700, 400))
```

### Device (please complete the following information):
 - OS: MacOS
 - Version: Catalina
 - Go version: 1.14.0
 - Fyne version: 1.3.0 (clone of https://github.com/andydotxyz/fyne/tree/fix/1118 branch)

**Comment by andydotxyz** [comment] 2020-07-03 19:18
Scroller speed improvements can be tested in PR #1163.
The speed of textgrid itself is much more complicated but needs progress as well.
Not certain yet what the cause it, may even be the size of the object tree... investigating further

**Comment by andydotxyz** [comment] 2020-10-27 08:59
Big improvements on `develop` branch ready for release, marking this as resolved .

**Closed by andydotxyz** 2020-10-27 08:59 UTC
Labels: bug, optimization

**Comment by Coollision** [comment] 2020-11-09 08:17
seems like the issue still exists.
I just tried to create a text grid with about 600 lines (a usual JSON file for the data I'm working with)
I was using the latest develop branch (go mod import line: "fyne.io/fyne v1.4.1-0.20201105193851-70367fbf5ce5")

and the whole app freezes as soon as I tried to load the JSON.

I'm using the same setup as @Ragin-LundF a text grid inside a scroll container.

**Comment by andydotxyz** [comment] 2020-11-10 16:32
Oh I see, yes this widget is not yet optimised for large content.
By putting it in a scroll container you are asking for the entire file to be rendered, rather than just the visible portion. 
As we learned with the new collections widgets we can do a great job with caching if we move the scroll into the widget. This is what we plan to do with Entry and TextGrid in 2.0 - we could not do it sooner as it breaks apps that have them inside scroll containers already.

Hopefully we can get 1.4.1 out of the door soon and move on with the larger 2.0 work so you can get this improvement. 
Linking this issue to #471.

**Comment by Coollision** [comment] 2020-11-10 16:40
@andydotxyz thanx for the update, for now, I can handle it by using the `widget.Entry` and a `scroll container`. but definitely looking forward to v2
