### ISSUE TITLE
How to add head to table or list, and fix head

### ISSUE THREAD

**Issue by x931890193** [fyne-io/fyne#3222] opened 2022-08-25 17:59 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I want to add a table head and fixd it, how to do this?
![image](https://user-images.githubusercontent.com/24632574/186736328-119ee8bf-e706-4a6f-8961-588d6a7a9d3e.png)

### Describe the solution you'd like to see.

Is there have any solution?

**Comment by Jacalz** [comment] 2022-08-25 20:00
This looks to be a duplicate of https://github.com/fyne-io/fyne/issues/1658. 

Also, I just want to say that we prefer questions to either use the discussions here on GitHub or one of the support channels on https://fyne.io/support.

**Closed by Jacalz** 2022-08-25 20:00 UTC
