### ISSUE TITLE
GLFW poll event error

### ISSUE THREAD

**Issue by dht-hedaihua** [fyne-io/fyne#3010] opened 2022-05-27 00:52 UTC
### Describe the bug:
The program will occasionally report the following errors on the console:
```
hedaihua@bogon youkecy-teacher-client % go run .                     
2022/05/27 08:28:25 Fyne error:  GLFW poll event error: InvalidValue: Invalid scancode
2022/05/27 08:28:25   At: /Users/hedaihua/go_projects/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/loop.go:257
```
But now I can't locate how it is caused, and I can't reproduce the error 100% every time. Is it because I used the wrong grammar?

### To Reproduce:
Steps to reproduce the behaviour:
1. run  `go run .` .
2. The program interface operates normally.
3. After a while, the upper error will appear in the program.

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 12.2.1
 - **Go version:** 1.17
 - **Fyne version:** 2.1.4

**Comment by andydotxyz** [comment] 2022-05-27 21:12
Maybe this is a duplicate of #1024?

**Comment by nowsdt** [comment] 2022-06-13 12:07
It's easy to replicate，code here [Widget](https://developer.fyne.io/explore/canvas), the last demo [Widget], run it, and focus on the input area, then press the keyborad [fn], the console display the err
@Jacalz 

device: MacBook
OS version: MacOS 11.4
Go version :1.18
Fyne version: 2.2.1

```
2022/06/13 19:56:59 Fyne error:  GLFW poll event error: InvalidValue: Invalid scancode 63
2022/06/13 19:56:59   At: /Users/star/go/pkg/mod/fyne.io/fyne/v2@v2.2.1/internal/driver/glfw/loop_desktop.go:35
```

```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {

	myApp := app.New()
	w1 := myApp.NewWindow("Widget")
	w1.SetContent(widget.NewEntry())

	w1.ShowAndRun()
}
```

**Comment by andydotxyz** [comment] 2022-06-13 13:28
Ah, the old Fn error, then this is a duplicate of #1024

**Closed by andydotxyz** 2022-06-13 13:28 UTC
Labels: unverified
