### ISSUE TITLE
[BUG] Modal Shadow Mismatch and can't Resize

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1545] opened 2020-11-15 10:37 UTC
### Describe the bug:
The shadow of a Modal does not match up with it's size/contents when it contains a long label.

### To Reproduce:

Full code attached.

#### Without Wrap

![image](https://user-images.githubusercontent.com/1910461/99182595-a0fbee80-26ea-11eb-96f1-61417cf4a2d0.png)

#### With Wrap

![image](https://user-images.githubusercontent.com/1910461/99182635-eb7d6b00-26ea-11eb-800a-1d6c1a661d99.png)

#### With Reload
( no change )

#### With Resize then Reload
( no change )

#### Putting `modal.Show()` Last
( no change )

### Example code:

```golang
func main() {
	fyneApp = app.New()
	fyneApp.Settings().SetTheme(theme.DarkTheme())

	mainWindow = fyneApp.NewWindow("Hello, Fyne!")
	hello := widget.NewLabel("Hello Fyne!")
	mainWindow.SetContent(widget.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	mainWindow.Resize(fyne.NewSize(420, 360))
	mainWindow.CenterOnScreen()
	mainWindow.Show()

	label := widget.NewLabel("This is some really long text, and we know it will not fit on the screen, because this does not wrap by default.")
	modal := widget.NewModalPopUp(
		widget.NewCard("Welcome!", "First-Time Setup",
			widget.NewVBox(
				label,
			),
		), mainWindow.Canvas())
	// label.Wrapping = fyne.TextWrapWord
	modal.Show()

	// modal.Resize(fyne.NewSize(400, 340))
	// mainWindow.Canvas().Refresh(modal)
	// modal.Refresh()

	fyneApp.Run()
}
```

### Device (please complete the following information):
 - OS: Fedora
 - Version: 33
 - Go version: 1.15.2 linux/amd64
 - Fyne version: 1.4.0

**Comment by andydotxyz** [comment] 2020-11-15 10:41
I am pretty confident that this is because the label will resize to accomodate the wrap.
That makes this a duplicate of a ticket we hoped to resolve soon, #1370

**Closed** 2020-11-15 10:41 UTC
Labels: duplicate

**Comment by andydotxyz** [comment] 2020-11-27 14:53
Tested locally and #1613 resolves this issue
