### ISSUE TITLE
Entry without scrollable content prevents scrolling of outside scroller

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1939] opened 2021-02-10 15:47 UTC
### Describe the bug:

An empty (or just not with enough content to scroll) will prevent the scrolling of an external scroller even though there is nothing to scroll within it.

### To Reproduce:
1. Make the window large enough that it can be scrolled.
2. Move the mouse to be over the label.
3. Scroll and notice that it works as expected.
4. Move the mouse to be over the entry.
5. Scroll and notice that it does not scroll.

### Screenshots:

![scolling-not-in-entry](https://user-images.githubusercontent.com/25466657/107533551-57268580-6bbf-11eb-9379-006550839efe.gif)

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Entry scroll")

	w.SetContent(container.NewScroll(
		container.NewVBox(
			widget.NewEntry(),
			widget.NewLabel("Scroll on me!"),
		),
	),
	)

	w.ShowAndRun()
}
```

### Device (please complete the following information):
- **OS:**  Linux
- **Version:**  5.10.12
- **Go version:** 1.15.7
- **Fyne version:** 2.0.0

**Comment by stuartmscott** [comment] 2021-02-10 16:39
Agreed this is an issue, though it is not specific to Entry - any nested scrollers will encounter this problem where the inner scroller reaches its limit but cannot defer the scroll event to the outer scroller

**Comment by andydotxyz** [comment] 2021-02-10 16:50
I think you would avoid it by specifying `Entry.Wrapping = fyne.TextWrapNone`

**Comment by andydotxyz** [comment] 2021-02-10 21:41
I don't really think this is a blocking bug.
I'm even tempted to say it's not a bug, this is a (poor?) design.
Is this an enhancement?

I don't think we should change this behaviour under a bug fix release, it is a larger issues at work here that could result in bahaviour changes not intended.

**Comment by Jacalz** [comment] 2021-02-11 08:22
Sure, maybe not a bug, but certainly very annoying. While the example gif above might not show it, this is making Sparta almost unusable when you try to scroll the form full of entry widgets.

I'd almost say that it is a block just because the entry widgets make the issue so much more noticeable.

**Comment by andydotxyz** [comment] 2021-02-11 12:23
Turning off wrapping did not help?

**Comment by Jacalz** [comment] 2021-02-11 13:11
> Turning off wrapping did not help?

Haven’t tried yet. Just posting a reply from my phone.

**Comment by andydotxyz** [comment] 2021-02-12 10:50
It won't fix it, I realised that the type of scroll is not checked - only the presence of a scroller.

I would propose that this is downgraded from blocker by adding something like
```
	objects := []fyne.CanvasObject{box, line, e.content}
	if e.Wrapping != fyne.TextWrapOff {
		e.scroll = widget.NewScroll(e.content)
		objects = []fyne.CanvasObject{box, line, e.scroll}
	}
```

This goes in `Entry.CreateRenderer` for now, it may need to be addressed in `updateScrollDirections` as well for a complete solution.

**Comment by andydotxyz** [comment] 2021-02-12 10:56
The alternative would be to add some smarts to `mouseScrolled` in `internal/driver/glfw/window.go` (plus same in mobile).
```
	co, _, _ := w.findObjectAtPositionMatching(w.canvas, w.mousePos, func(object fyne.CanvasObject) bool {
		if s, ok := object.(*intWidget.Scroll); ok {
			return s.Direction != intWidget.ScrollNone
		}

		_, ok := object.(fyne.Scrollable)
		return ok
	})
```

Of course this puts a dependency back on widget, because the direction is not exposed through the `Scrollable` interface...

**Comment by andydotxyz** [comment] 2021-02-26 14:24
The agreed workaround is on `develop` and `release/v2.0.x`

**Closed** 2021-02-26 17:01 UTC
Labels: blocker, bug
