### ISSUE TITLE
Add option to turn off automatic windows building in cmd

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#621] opened 2020-01-18 15:38 UTC
### Is your feature request related to a problem? Please describe:
The latest version of the cmd tool tries to rebuild the windows binary after the icon has been packaged and that rebuild will fail if the user doesn't have relevant windows stuff (guessing MinGW) and thus gives an error.
```bash
/usr/lib64/golang/pkg/tool/linux_amd64/link: running x86_64-solus-linux-gcc failed: exit status 1
x86_64-solus-linux-gcc: error: unrecognized command line option ‘-mwindows’
```

Some users including my self might not have the required windows compiler toolchains (guessing that that's the case here) becuase they might be using fyne-cross instead for the windows packaging and rebuilding.

### Describe the solution you'd like to see:
I Would like to have a flag to pass to have it not try to rebuild because it is doomed to fail.

**Comment by andydotxyz** [comment] 2020-01-18 21:56
Can you please confirm the command that you were running, and the expected outcome?

**Comment by Jacalz** [comment] 2020-01-19 07:55
I ran the following command:
```bash
(cd src && ~/go/bin/fyne package -icon ../assets/icon-512.png -executable ../build/software-windows-amd64.exe -os windows -name software)
```

before updating the cmd tool to the version in 1.2.x, the command just tells me that I have to recompile the application to see the icon bundled for windows. On the latest cmd tool however, the error in the description is shown.

**Comment by andydotxyz** [comment] 2020-01-19 09:26
Hmm, thanks. As you say the old version did not manage to package the icons correctly - so the change we made is almost a bug fix. Without the recompile the package command is not really successful.

It seems to me that it would be better to run the package command on the windows system that must in the end re-build anyhow. I suspect I am missing something about your workflow though, can you outline what process you think would work well? Are you copying the generated resources to a build server or something like that?

Thanks

**Comment by Jacalz** [comment] 2020-01-19 09:36
My whole developer workflow is based on Linux and I am using [fyne-cross](https://github.com/lucor/fyne-cross) for all my cross compiling needs. The docker container used for building using fyne-cross is essentially my build server. Here is a link to the release bash script I run to cross compile packaged versions for MacOS, Windows and Linux: https://gist.github.com/Jacalz/14e7eb9267efd978d32fa09810d8eb2b

**Comment by andydotxyz** [comment] 2020-01-19 21:11
Thanks, I see how this would benefit.
I wonder if, however, the better solution is to have package support in fyne-cross?
Or perhaps to extend the fyne command to invoke fyne-cross if it is found?

Or is that just being too clever? ;)

**Comment by Jacalz** [comment] 2020-01-20 07:44
I think you definitely are on to something great there. I think the best option would be to have packaging support in fyne-cross as you say. I have an issue for that, that I made a long time ago. See https://github.com/lucor/fyne-cross/issues/14

My though about just disabling rebuilds is probably not the best one come to think about it.

**Comment by andydotxyz** [comment] 2020-01-20 10:40
Thanks, I'll close this as duplicate of the fyne-cross ticket above then.
I will keep thinking about this, however as it's an interesting problem.
For now I will continue to think that the default fyne tools cross-platform require appropriate toolchains installed to keep the current separation from fyne-cross which does it for you.

**Closed by andydotxyz** 2020-01-20 10:40 UTC
Labels: question

**Comment by lucor** [comment] 2020-01-20 19:06
Agreed, don't know if make sense add support for mingw compilation/packaging in cmd/fyne at least for now. 
Let's see how we can manage this in fyne-cross :-)
