### ISSUE TITLE
Listbox support

### ISSUE THREAD

**Issue by sk929FFF** [fyne-io/fyne#347] opened 2019-06-27 17:26 UTC
First of all, Fyne is a really nice library and thank you for your work. 
I just have one request: could you guys please add ListBox support? I really need it for my application. 
Example: https://i.imgur.com/F8e3iPc.png

**Comment by andydotxyz** [comment] 2019-06-27 21:41
Thanks for your feedback.
I think this is a duplicate of #157.
Please re-open if you disagree.

**Closed by andydotxyz** 2019-06-27 21:41 UTC
