### ISSUE TITLE
Add system tray support

### ISSUE THREAD

**Issue by jiajunhuang** [fyne-io/fyne#283] opened 2019-05-30 02:55 UTC
sometimes I need the app to minimize, and stay in the system tray, will `fyne` support system tray?

**Comment by andydotxyz** [comment] 2019-05-30 09:18
Yes it will, at some point. Probably not in 1.1 or 1.2 but I would like to see it added soon after.

**Comment by advsets** [comment] 2019-07-19 10:13
I use  [systray](https://github.com/getlantern/systray/blob/master/systray_windows.go)  to achieve this function, first transition

**Comment by ergoz** [comment] 2019-08-08 15:10
+1
i need to create app with only system tray. But systray package cant create multi-level menu

**Comment by andydotxyz** [comment] 2019-08-12 18:26
Currently we don't have sub-menu support either.
We should add it soon, though I don't think it has a ticket so I will add one now.

Systray will come :)

**Comment by prasanna-altair** [comment] 2020-05-13 01:25
> I use [systray](https://github.com/getlantern/systray/blob/master/systray_windows.go) to achieve this function, first transition

When i use systray and fyne. It works perfectly fine on windows OS, but fails on Mac OS. Is there a workaround to this problem? it seems its caused by runtime.LockOSThread() used by fyne and systray in the main. 

Stack trace:

2020-05-12 21:02:57.559 main[12053:8552769] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1455.12/Foundation/Misc.subproj/NSUndoManager.m:361
2020-05-12 21:02:57.560 main[12053:8552769] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff363c8d7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5d664c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff363ceb12 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff384faa30 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Foundation                          0x00007fff38489624 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 469
	5   AppKit                              0x00007fff338ce936 -[NSApplication run] + 997
	6   main                                0x0000000004494b30 nativeLoop + 160
	7   main                                0x0000000004493903 _cgo_cafa63f1ae52_Cfunc_nativeLoop + 35
	8   main                                0x0000000004064200 runtime.asmcgocall + 112
)

**Comment by andydotxyz** [comment] 2020-05-13 07:07
macOS requires that code manipulating graphical elements run on the main thread. Do these things must run within the main() goroutine. Future versions of Fyne will be enforcing this to ensure cross platform consistency.

**Comment by andydotxyz** [comment] 2020-05-13 07:08
Submenu support is now in so it seeme likely that we could include systray in 2.0 late this year

**Comment by doutuiya** [comment] 2021-01-05 13:51
any progress ?

**Comment by andydotxyz** [comment] 2021-01-06 14:45
No, sorry. 2.0 is due this month but we are really up against it and late last year really did not exactly go according to plan (as for many people).

**Comment by grantmoore3d** [comment] 2021-05-12 22:11
Does anyone have a workaround/suggestion for being able to use systray right now? My use case is an always persistent tray that can launch one or more fyne windows, but I haven't had much luck yet getting them working together.

**Comment by andydotxyz** [comment] 2021-05-13 14:22
You will need a system tray API that does not require blocking the main thread @grantmoore3d.
Once you have found one of them it should just work.

**Comment by andydotxyz** [comment] 2021-10-13 20:36
What I am trying to say is that the systray linked above depends on GTK+.
No Fyne or Fyne-x repository should depend on GTK+, it breaks our look, lean-ness and adds runtime dependencies that break our 0-dep promise.

**Comment by dawei101** [comment] 2021-10-15 01:53
Cool done, keep up the good work!!

**Comment by worldxyj** [comment] 2021-12-27 03:47
You can have a look at https://github.com/getlantern/systray,it's easy to add a system tray and works well with Fyne.

**Comment by Jacalz** [comment] 2021-12-27 08:31
> You can have a look at https://github.com/getlantern/systray, it's easy to add a system tray and works well with Fyne.

Thanks but this has been discussed above. See https://github.com/fyne-io/fyne/issues/283#issuecomment-941015552 for more information.

**Comment by andydotxyz** [comment] 2022-01-13 18:46
We have some sponsorship for this ticket. $75 is currently allocated for eligible contributors completing this work (see [Contributing]).

**Comment by andydotxyz** [comment] 2022-02-02 17:45
Proposal for the API (yes it is super simple, but fulfils what was agreed to add at this stage):

```go
type desktop.App interface {
	SetSystemTrayMenu(menu *fyne.Menu)
}
```

Usage:

```go
menu := fyne.NewMenu("Tray menu title", items...)
a := app.New()
if desk, ok := a.(desktop.App); ok {
	desk.SetSystrmTrayMenu(menu)
}
```

**Comment by andydotxyz** [comment] 2022-02-15 16:49
You can track development on `feature/systray` branch on my fork. We have added Windows and macOS support already.
I will open a PR once Linux is complete.

**Comment by qwc** [comment] 2022-02-16 06:04
Thank you for the effort! I think it will come just in time for the continuation of my project. :)

**Comment by riyalol** [comment] 2022-02-17 03:56
Thanks for this excellent integration. I tried to give it a go (I know it is still WIP) for a little project that I am building. 

With this piece of code:

	mi := fyne.NewMenuItem("Login", func() {
		log.Println("System tray menu tapped")
	})

	if desk, ok := a.(desktop.App); ok {
		menu := fyne.NewMenu("Login", mi)
		desk.SetSystemTrayMenu(menu)
	}

However, when I hit the "Login" button, the log message gets printed only once. After that, the "Login" menu does not seem to be active, and repeated presses don't invoke the callback (and hence do not print the log message). Any idea what might be the issue? Thanks in advance.

**Comment by andydotxyz** [comment] 2022-02-17 05:52
Thanks for the report @riyalol I will look into it as I develop the feature further.

**Comment by andydotxyz** [comment] 2022-02-28 12:58
That issue is resolved on the latest commit of the PR @riyalol :)

**Comment by qwc** [comment] 2022-02-28 13:40
> but the library still needs work for Linux - working on it separately.

Damn, my current usecase is Linux only. Fingers crossed for easy solveable problems on Linux. * Impatiently waiting * ;)
My next project needs it for all OSs. ;)

**Comment by qwc** [comment] 2022-02-28 15:42
I as well do only know the basics. 😒
Not enough to use it for programming applications using it.

**Comment by andydotxyz** [comment] 2022-03-10 20:16
Landed in develop :)

**Closed by andydotxyz** 2022-03-10 20:16 UTC
Labels: future, Hacktoberfest, Bounty

**Comment by mvdelt** [comment] 2022-04-20 07:18
> Proposal for the API (yes it is super simple, but fulfils what was agreed to add at this stage):
> 
> ```go
> type desktop.App interface {
> 	SetSystemTrayMenu(*fyne.Menu)
> }
> ```
> 
> Usage:
> 
> ```go
> menu := fyne.NewMenu("Tray menu title", items...)
> a := app.New()
> if desk, ok := a.(desktop.App); ok {
> 	desk.SetSystemTrayMenu(menu)
> }
> ```
> 
> Potentially we also need `SetSystemTrayIcon(fyne.Resource)` to support apps changing the icon and it would default to the app icon.

Hi, thank you so much for developing these features. 
I'm a newbie to Fyne. I just want to test system tray, but I can't figure out how to do it.
I don't know what `desktop.App` is... 
Do I need to `import "fyne.io/fyne/v2@develop"` for system tray?
Or, please let me know if there is any example for system tray implementation.
Dumb question but looking forward to any help. thanks! :)

**Comment by andydotxyz** [comment] 2022-04-20 14:33
The code above is a type query - `ok` is true if the assertion is correct.
To get it working you need to add the import "fyne.io/fyne/v2/driver/desktop" sorry I missed that in the instructions.

Notifications work without anything special as they are on all platforms and are at `App.SendNotification()`

**Comment by mvdelt** [comment] 2022-04-20 23:21
> The code above is a type query - `ok` is true if the assertion is correct. To get it working you need to add the import "fyne.io/fyne/v2/driver/desktop" sorry I missed that in the instructions.
> 
> Notifications work without anything special as they are on all platforms and are at `App.SendNotification()`

Thanks! works like a charm. 
I don't know why there is a squiggly line in `App` in `desktop.App` though. (even after build and run the app successfully).
My IDE (vscode) says *"App not declared by package desktop".* 
Previously I thought I imported a wrong package because of this. 
Anyways, no problem with building. Thanks again :)

**Comment by mei2015** [comment] 2022-06-02 01:50
why not to realese

**Comment by Jacalz** [comment] 2022-06-02 05:49
> why not to realese

This will be in the release very soon.

**Comment by fayfive** [comment] 2022-09-02 11:20
I don't know how to use the API. I'm using the version 2.2.3. Anybody can tell me?

**Comment by Jacalz** [comment] 2022-09-02 12:00
> I need the app to minimize, and stay in the system tray
> I don't know how to use the API. I'm using the version 2.2.3. Anybody can tell me?

Please open a GitHub discussion if you have questions. Posting off-topic questions on issues is best to avoid. I will mark these two comments as off-topic.

**Comment by paboum** [comment] 2022-11-24 03:29
Why is this KDE-dependent? Shouldn't you use the following?
https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/
example https://github.com/remko/go-sni

**Comment by andydotxyz** [comment] 2022-11-24 11:13
It isn't KDE specific - but all the panels we tested supported the kde notation but did not all support the FDO specification.
If you are aware of any panels that this does not work with please open an issue.

**Comment by dosgo** [comment] 2022-12-26 03:49
By the way, does this support Tooltip?
