### ISSUE TITLE
go test fails randomly on develop branch

### ISSUE THREAD

**Issue by jkvatne** [fyne-io/fyne#1006] opened 2020-05-19 07:21 UTC
When I run "go test" on the develop branch, it failes about 20-50% of the time. This seems to be localized to the ~/go/src/fyne.io/fyne/internal/driver/glfw directory.  A short test (run from the above directory) is 
```go test -count=10 -run TestWindow_Focus``` 
It will fail 1-4 of the runns.
The test above is associated with the event queue. It does not fail when stepping through the event callbacks.

I was actualy testing some modifications to the code, but got a lot of errors from other parts of the code, so I tested the unmodified code and got a lot of errors there also. I have tried to find the source of the problems, but it is very difficult because the results are not identical running the debugger (Goland) and running without debugger. And it is very random.

 - OS: Windows 10
 - Go version: 1.14.2
 - Goland version 2020.1
 - Fyne version:  latest from develop branch

**Comment by andydotxyz** [comment] 2020-05-19 09:06
Can you please post the errors that you see? And confirm the SHA of develop for future reference?

**Comment by jkvatne** [comment] 2020-05-19 14:15
```
jkv@Medusa MINGW64 ~/go/src/fyne.io/fyne/internal/driver/glfw (develop)
$ git rev-parse HEAD
553c7a485345511565c40d823f6568920aba1db1

jkv@Medusa MINGW64 ~/go/src/fyne.io/fyne/internal/driver/glfw (develop)
$ go test -run TestWindow_Focus                                                                                                                                                                                    --- FAIL: TestWindow_Focus (0.10s)
    window_test.go:759:
                Error Trace:    window_test.go:759
                Error:          Not equal:
                                expected: "abcd"
                                actual  : "bcd"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -abcd
                                +bcd
                Test:           TestWindow_Focus
FAIL
exit status 1
FAIL    fyne.io/fyne/internal/driver/glfw       0.326s

jkv@Medusa MINGW64 ~/go/src/fyne.io/fyne/internal/driver/glfw (develop)
```

**Comment by jkvatne** [comment] 2020-05-19 14:19
Results from running a full test:
[test errors.txt](https://github.com/fyne-io/fyne/files/4651045/test.errors.txt)

**Comment by jkvatne** [comment] 2020-05-19 14:20
Is there any "go get" that could be missing by me, or any dependencies I have missed?

**Comment by jkvatne** [comment] 2020-05-19 14:33
There is also a strange error in TestWindow_SetIcon, that does not break the test, but is logged as follows:
2020/05/19 10:26:39 Fyne error:  Failed to decode image for window icon
2020/05/19 10:26:39   Cause: image: unknown format
2020/05/19 10:26:39   At: C:/Users/jkv/go/src/fyne.io/fyne/internal/driver/glfw/window.go:216

**Comment by andydotxyz** [comment] 2020-05-19 15:29
Thanks. I have seen these a while ago - I don't think you have done anything wrong.
It seems that something that was fixed on other platforms still has a race condition on Windows.

**Comment by stuartmscott** [comment] 2020-05-21 03:23
Looks like a dupe of #783

**Comment by andydotxyz** [comment] 2020-05-21 09:52
Good catch

**Closed by andydotxyz** 2020-05-21 09:52 UTC
Labels: OS:Windows, bug
