### ISSUE TITLE
support chinese characters and emoji bug

### ISSUE THREAD

**Issue by c0618** [fyne-io/fyne#2065] opened 2021-03-05 04:59 UTC
code ：
main {
fontPaths := findfont.List()
     // set fyne_font env 
	for _, path := range fontPaths {
		if strings.Contains(path, "hei") {
			fmt.Println(path)
			os.Setenv("FYNE_FONT",path)
		}
	}

    
	application := app.New()
	window := application.NewWindow("Hello Fyne 费恩👉👉👉👉👉👉👉")
	he := widget.NewLabel("Hello Fyne 费恩👉👉👉👉👉")
	window.SetContent(container.NewVBox(he,widget.NewButton("Hi!", func() {
		he.SetText("Welcome :) 👉👉👉👉👉👉👉👉👉👉")
	})))
	window.ShowAndRun()

}

runtime：
os：windowos 10
fyne: 2.0,1

question :
Cannot support Chinese and emoji

**Comment by LaPingvino** [comment] 2021-03-06 19:06
Can you write out more clearly what is supported and not supported? (I suspect this is a font issue?)

**Comment by Jacalz** [comment] 2021-03-07 11:36
I see that you have picked the bug template, but then deleted the template. Please use the issue templates when opening bug reports in the future. They are there to give us all the relevant information and thus make it easier for us to diagnose the issues. Thanks for understanding 🙂

I’m going to close this as a duplicate of #598.

**Closed by Jacalz** 2021-03-07 11:36 UTC
Labels: duplicate

**Comment by andydotxyz** [comment] 2021-03-08 09:21
> I’m going to close this as a duplicate of #598.

Alongside #573 for the Emoji.
