### ISSUE TITLE
Add the ability to copy text to markdown.

### ISSUE THREAD

**Issue by GoHippo** [fyne-io/fyne#4233] opened 2023-09-11 09:01 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I wanted to replace html with markdown and sometimes I need to copy text from a page.

### Describe the solution you'd like to see.

I would like to have a more functional markdown module. Or perhaps a simple html visualization.

**Comment by andydotxyz** [comment] 2023-09-11 10:19
Your description does not seem to match the title...

Do you mean that you want to be able to copy text out of the widget created by `NewRichTextFromMarkdown`?

**Comment by GoHippo** [comment] 2023-09-11 19:09
> Your description does not seem to match the title...
> 
> Do you mean that you want to be able to copy text out of the widget created by `NewRichTextFromMarkdown`?

I'm sorry if I wrote inaccurately. 
You are right, I meant the ability to select the desired text segment and copy it in the "NewRichTextFromMarkdown" widget.

**Comment by andydotxyz** [comment] 2023-09-12 09:59
As copyable text is part of `Entry` I guess this is then a duplicate of #21?

**Closed by andydotxyz** 2023-09-12 09:59 UTC
Labels: information-needed
