### ISSUE TITLE
how increase scrolling speed on application ?

### ISSUE THREAD

**Issue by madaxemad** [fyne-io/fyne#2019] opened 2021-02-24 06:14 UTC
hey 
as title
how increase scroll speed on application ?
i'm not saying it's slow 
just increase it speed not with mouse accel speed just want increase speed on application setting

**Comment by andydotxyz** [comment] 2021-02-24 09:59
Can you please provide information about your operating system, version number and Fyne version?
Scrolling and other hardware related questions may vary based on system.

This may be a duplicate of #775?

**Closed** 2021-02-27 12:10 UTC
