### ISSUE TITLE
support chinese characters

### ISSUE THREAD

**Issue by easykoo** [fyne-io/fyne#120] opened 2019-02-14 11:08 UTC
does not display chinese characters yet

**Comment by andydotxyz** [comment] 2019-02-14 22:32
This might be a duplicate of #63. You can show chinese characters by loading a font that supports them. Due to the file sizes I don't think we can embed all of the fonts for every language - but a more streamlined setup for these languages / locales might help.

Does FYNE_FONT solve your issue or do we need to find a better solution?

**Comment by andydotxyz** [comment] 2019-03-19 16:29
Closing this as other reports say this is resolved

**Closed by andydotxyz** 2019-03-19 16:29 UTC
Labels: question
