### ISSUE TITLE
fyne on virtual machine still some problem

### ISSUE THREAD

**Issue by JackySmith** [fyne-io/fyne#2697] opened 2021-12-17 03:18 UTC
On my MacPro, I install Parallels Desktop 17 
and then, I install two virtual machine, the first machine running win10, and i install parallels tools for its driver.
the second machine running osx12.1(macOS Monterey),the newest mac osx version,and install parallels tools too,

after that, i run same fyne app on two platform, which download from https://github.com/fyne-io/calculator/releases/tag/v1.0.0 
download windows-amd64 version  for win10,download darwin-amd64 version for macos, Just for experiment

The result is : in virtual win10  , fyne app run fine , but in virtual macOS Monterey, it failed,both of them drivered
so， this result repeat again and again in other fyne app, although darwin app can run very good on mac osx which is not Virtualized. but i need virutal macosx to run fyne for my work ,so who can help me?

i record a movie for that :

https://drive.google.com/file/d/1ZmrQaSUuWH4opIR5jGFfKiVgkfIzwbpi/view?usp=sharing

### Screenshots:

https://drive.google.com/file/d/1bRnjUBK_lq-VJuiEY7xithWi7jvzeEdY/view?usp=sharing

### Example code:

```
Last login: Fri Dec 17 10:43:08 on ttys000
/Users/apple/Desktop/calculator.app/Contents/MacOS/calculator ; exit;
apple@macos12 ~ % /Users/apple/Desktop/calculator.app/Contents/MacOS/calculator ; exit;
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0xc000315cd8, 0x2, 0x2, 0x0, 0x0)
	/Users/andy/.go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/error.go:178 +0x20c
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x9c, 0xfa, 0x43dfa22, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andy/.go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:350 +0x197
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func1()
	/Users/andy/.go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1327 +0x14b
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0000b6370)
	/Users/andy/.go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:97 +0x5f4
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0000b6370)
	/Users/andy/.go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/driver.go:80 +0x3a
fyne.io/fyne/v2/app.(*fyneApp).Run(0xc00026a230)
	/Users/andy/.go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/app.go:66 +0x95
main.main()
	/Users/andy/Code/Fyne/calculator/main.go:13 +0xec

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by andydotxyz** [comment] 2021-12-17 03:42
> but i need virutal macosx to run fyne for my work ,so who can help me?

Make sure that you have enabled the appropriate options for full graphics acceleration to work inside the virtual machine.

**Comment by andydotxyz** [comment] 2021-12-17 03:43
Closing as duplicate of #2373

**Closed by andydotxyz** 2021-12-17 03:43 UTC
Labels: unverified

**Comment by JackySmith** [comment] 2021-12-18 01:12
In virutal machine, graphics acceleration is worked

![image](https://user-images.githubusercontent.com/7380379/146623957-6cc1cf6a-e970-47ba-b253-83133bb66390.png)

**Comment by andydotxyz** [comment] 2021-12-18 05:53
Something doesn't look right - the VRAM is 42MB instead of 8GB.
Please check that you have full 3D enabled in the VM settings
