### ISSUE TITLE
Problem with generating window height for GridWrapLayout

### ISSUE THREAD

**Issue by kshamiev** [fyne-io/fyne#4332] opened 2023-10-19 15:16 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

For the GridWrapLayout layout:
When changing the size with the horizontal slider, the height increases vertically by the size of the specified widgets height.

And when the window is first displayed, its height also becomes the specified height of the widget multiplied by the number of elements.

### How to reproduce

Launch the program and play with the size with the mouse.
Horizontally

### Screenshots

![Снимок экрана от 2023-10-19 18-09-19](https://github.com/fyne-io/fyne/assets/2145710/538399bc-d462-4329-b38c-1eba14538647)

### Example code

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	content := container.New(layout.NewGridWrapLayout(fyne.NewSize(50, 50)),
		newWidget(20)...,
	)
	myWindow := myApp.NewWindow("GridWrapLayout")
	myWindow.Resize(fyne.NewSize(600.0, 400.0))
	myWindow.CenterOnScreen()
	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}

func newWidget(count int) []fyne.CanvasObject {
	res := make([]fyne.CanvasObject, count)
	for i := 0; i < count; i++ {
		res[i] = widget.NewEntry()
	}
	return res
}

```

### Fyne version

v2.4.1

### Go compiler version

1.19.3

### Operating system and version

OS Linux Ubuntu 22.04 Desktop

### Additional Information

[sample](https://github.com/kshamiev/urok/blob/main/gui/fyne/truble/main.go)

**Comment by metal3d** [comment] 2023-10-19 15:44
The weird part is that resizing after a while works...

```go
package main

import (
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("GridWrapLayout")
	content := container.NewGridWrap(fyne.NewSize(50, 50), newWidget(20)...)
	myWindow.CenterOnScreen()
	myWindow.SetContent(container.NewBorder(
		nil, nil, nil, nil,
		content,
	))
	go func() {
		time.Sleep(1 * time.Second)
		myWindow.Resize(fyne.NewSize(600, 400))
		myWindow.CenterOnScreen()
	}()
	myWindow.ShowAndRun()
}

func newWidget(count int) []fyne.CanvasObject {
	res := make([]fyne.CanvasObject, count)
	for i := 0; i < count; i++ {
		res[i] = widget.NewEntry()
	}
	return res
}
```

Note: use `container.NewGridWrap` which is a nice alias 😃

**Comment by andydotxyz** [comment] 2023-10-19 18:27
This is a duplicate of #3252.
Wrapped base layouts have 2 passes and if that can confuse windows.

**Closed** 2023-10-19 18:28 UTC
Labels: duplicate

**Comment by metal3d** [comment] 2023-10-20 07:31
👍🏻 I had this problem for another app, happy to know that it is/will be fixed

**Comment by andydotxyz** [comment] 2023-10-20 08:54
This ticket was closed as duplicate not as fixed. Apologies is there was confusion.
