### ISSUE TITLE
failed to initialise OpenGL

### ISSUE THREAD

**Issue by EduardoGrtt** [fyne-io/fyne#437] opened 2019-09-04 22:18 UTC
`
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()
	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			app.Quit()
		}),
	))
	w.ShowAndRun()
}
`
Output;
PS C:\GoCode\fyne> go run .\fyne_sample.go
2019/09/04 19:16:37 Fyne error:  failed to initialise OpenGL
2019/09/04 19:16:37   Cause: glGetBufferParameteri64v
2019/09/04 19:16:37   At: C:/Users/eduar/go/src/fyne.io/fyne/internal/driver/gl/window.go:1007
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x54 pc=0x5b394d]

**Comment by andydotxyz** [comment] 2019-09-05 22:31
Please provide your operating system and version.
If possible your graphics card model and the driver you are uisng?

**Comment by andydotxyz** [comment] 2019-09-06 21:32
I suspect this is a duplicate of #191 - do you have a computer with dual graphics cards?

**Comment by zengming00** [comment] 2020-02-07 12:13
'failed to initialise OpenGL'  on my lubuntu 18.04 virtual machine. 
VirtualBox version: 5.2.8 r121009 (Qt5.6.2)
```shell
zengming@zengming:/proc$ cat version
Linux version 4.15.0-72-generic (buildd@lcy01-amd64-026) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019
zengming@zengming:/proc$ cd
zengming@zengming:~$ cat /proc/version
Linux version 4.15.0-72-generic (buildd@lcy01-amd64-026) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019
zengming@zengming:~$ uname -a
Linux zengming 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
zengming@zengming:~$ go version
go version go1.13.5 linux/amd64
zengming@zengming:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
zengming@zengming:~$ cd go/
bin/ pkg/ src/ 
zengming@zengming:~$ cd go/bin
zengming@zengming:~/go/bin$ ./fyne_demo 
2020/02/07 20:09:12 Fyne error:  failed to initialise OpenGL
2020/02/07 20:09:12   Cause: glBeginConditionalRender
2020/02/07 20:09:12   At: /home/zengming/go/pkg/mod/fyne.io/fyne@v1.2.2/internal/painter/gl/gl_core.go:85
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x8c399c, 0x2a)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x79b8b0, 0xc00015dbe0, 0xc0000ae030)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00015d
```

**Comment by andydotxyz** [comment] 2020-11-17 13:08
Closing as request for information over a year old

**Closed by andydotxyz** 2020-11-17 13:08 UTC
Labels: OS:Windows, question

**Comment by ooing** [comment] 2021-07-03 01:08
@andydotxyz   but  It's still happening  in windows
2021/07/03 08:56:05 Fyne error:  failed to initialise OpenGL
2021/07/03 08:56:05   Cause: glGetBufferParameteri64v
2021/07/03 08:56:05   At: C:/Users/king/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/gl/gl_core.go:102

**Comment by andydotxyz** [comment] 2021-07-04 20:07
Perhaps @ooing can help with the question that was not answered before:

> I suspect this is a duplicate of #191 - do you have a computer with dual graphics cards?

We are trying to track down a problem with some laptops that have a "low power" chip and we're not managing to switch to the main GPU.

**Comment by rkmpa** [comment] 2023-02-13 18:54
@andydotxyz I ran into the same issue running an app on an older Windows 10 machine. As far as I can tell there is no dual graphics card. The only graphics card seems to be an integrated Intel graphics card from a ~10 year old processor. 

```
Graphics card/processor : Intel Core i5 CPI M 520 @2.40GHz
``` 

I am just curious if there is something I can do to get this running. If not, its probably not worth fixing.

**Comment by Bluebugs** [comment] 2023-02-13 19:04
I would say short of ensuring you have the latest driver, I don't think there is much possibility.

**Comment by andydotxyz** [comment] 2023-02-13 19:23
Please find out from the graphics driver what OpenGL version it supports.

In general it is better to open a new ticket than to comment on an old one that is closed.

**Comment by rkmpa** [comment] 2023-02-13 19:35
@andydotxyz @Bluebugs I checked and there are no new drivers available. Last one was from EOY 2012. Thanks for your reply. This ticket can be closed from my side.
