### ISSUE TITLE
[Android 11] Light Theme Unusable (no "system safe area")

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#2058] opened 2021-03-03 18:57 UTC
### Describe the bug:

When the system is using the DarkVariant but the application is using the Light Theme, the user experience could be described as "unusable". The hardware navigation buttons and notification area "disappear entirely" due to the use of white on white.

### To Reproduce:

Steps to reproduce the behaviour:

1. Have your system's Dark Mode enabled
1. Run the fyne demo from the appstore

### Screenshots:

https://user-images.githubusercontent.com/1910461/109857042-11356e00-7c0f-11eb-9cfd-8c133b80e2df.mp4

### Device (please complete the following information):
 - **OS:** Android 11 - Samsung Galaxy S20+ Ultra 5G
 - **Go version:** N/A
 - **Fyne version:** v2.0.0 ?

![image](https://user-images.githubusercontent.com/1910461/109856957-f531cc80-7c0e-11eb-8ca2-41ebef7afe63.png)

**Comment by andydotxyz** [comment] 2021-03-04 12:14
This seems like a duplicate of #472

**Comment by AlbinoGeek** [comment] 2021-03-25 18:17
The request for a "system safe area" (e.g: `fyne` has no business theming the hardware buttons, for example) -- still stands, separate of the implementation of reflecting the system theme, I feel.

Whether your app has the right to theme the hardware buttons is up to whether it has the "True Fullscreen" flag set (in Android), and is **not standard behavior.**

**Comment by andydotxyz** [comment] 2021-03-25 19:07
The system safe area is already implemented.
We draw the background colour into that space area so that it does not get random graphics context drawn instead.
Once this is synced with the device theme it should function as you'd expect.

**Comment by AlbinoGeek** [comment] 2021-03-25 19:19
Ahh, thank you for the clarification.

**Comment by andydotxyz** [comment] 2021-03-25 21:48
So, is this a duplicate afterall?

**Comment by AlbinoGeek** [comment] 2021-03-25 21:51
Yes. This can be closed as duplicate.

**Closed** 2021-03-25 22:04 UTC
Labels: bug, duplicate
