### ISSUE TITLE
Run fyne_demo catch fatal error: unexpected signal

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2445] opened 2021-09-08 09:18 UTC
### Describe the bug:
Run fyne_demo catch fatal error: unexpected signal

### To Reproduce:
Steps to reproduce the behaviour:

### Screenshots:
![2021-09-08 at 4 13 PM](https://user-images.githubusercontent.com/4317332/132481860-88e98c5b-d1e8-4549-8318-1c09957cdea4.png)

### Example code:
```shell
go get fyne.io/fyne/v2/cmd/fyne_demo/
fyne_demo
```
-->

### Device (please complete the following information):
 - **OS:** MacOS M1
 - **Version:** 1.5.21 Big Sur
 - **Go version:** go1.16.6 darwin/arm64
 - **Fyne version:** 2.0.4

**Comment by andydotxyz** [comment] 2021-09-08 09:21
Can you please include steps to reproduce?
It would also be super helpful if you could test `develop` branch because we have fixed some M1 bugs ready for v2.1

**Comment by owner888** [comment] 2021-09-08 23:10
yes, this is the same problem https://github.com/fyne-io/fyne/issues/2188

**Comment by andydotxyz** [comment] 2021-09-09 07:24
Thanks, closing as duplicate

**Closed by andydotxyz** 2021-09-09 07:24 UTC
Labels: unverified
