### ISSUE TITLE
Add option to make window floating / always on top

### ISSUE THREAD

**Issue by linkangren** [fyne-io/fyne#3429] opened 2022-11-26 16:48 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I want to keep the fyne window on top all the time

### Describe the solution you'd like to see.

similar:self.setWindowFlags(Qt.WindowStaysOnTopHint)

**Comment by Jacalz** [comment] 2022-11-26 18:05
I think this is very hard to do well cross-platform because all window managers do not support this. I personally also think this should be up to the window manager to control (like it usually is on Linux). Whenever apps decide for themselves that their windows always should be on top, I usually find that it just gets annoying because it is not what I, as in the user, want. If Windows would handle it like on Gnome, or KDE Plasma, that would be best:
![image](https://user-images.githubusercontent.com/25466657/204102811-4c62ea0e-0b85-4e6d-9e50-ed248f874a59.png)

**Comment by phillvancejr** [comment] 2023-08-29 18:22
Is this a feature the developers don't want to add because they don't like it or is it about the difficulty of implementation?
If the former this issue should probably be closed with that answer, but if it is the latter, isn't this just an issue of passing the options to GLFW? GLFW has a hint for this:
```glfw.WindowHint(glfw.Floating,1)```
this sets the window to float above all others. I make internal tools for my fellow designers/coworkers and its useful to have tools always on top so I can continue working in the design software while the app is active. I've forked personally cloned a copy of fyne and added this in just because I find it useful.

**Comment by phillvancejr** [comment] 2023-08-29 20:49
My co workers and I work in Adobe Illustrator and part of our process is to select a bunch of shapes and calculate their total square footage. I've created a tool, currently in Pyqt that allows this. The window floats always on top of the Adobe Illustrator window so that the user can select any shapes they need and also keep the window above Illustrator, that is to say the tool is never dismissed, which is useful because multiple selections sometimes need to be made and clicking back and forth between inactive and active windows would be annoying in this instance. It is a very good setting for tools.

Another application is for media player apps. I used to have a youtube like app that had allowed you to toggle always on top functionality, which was nice because I could always have the window minimized in the corner without the many sub palettes and windows of my design software covering it. The feature was later removed from the app to my disappointment. 

Topmost windows is something that for example C# Avalonia also supports. Avalonia is a cross platform Gui framework targeting desktop, mobile, embedded systems & wasm. I presume on the non desktop platforms the code just does nothing, which is exactly the expected result. Java has supported this as long as I've been aware of in both Swing and JavaFX. JavaFX works on desktop and also on mobile, though I'm not sure what the functionality does on mobile, but I assume it just does nothing, which is expected. 

I think this is a case where adding in Desktop specific functionality does not take away from the other platforms as again I wouldn't expect a topmost function to do anything anywhere other than desktop. In my opinion not working on mobile is not a downside because the idea of a "Window" doesn't even exist on mobile in the same sense it does on desktop. I haven't used Fyne on mobile so I'm speaking out of ignorance here on mobile what do Resize, SetFixedSize, SetTitle and CenterOnScreen do? I wouldn't expect these functions to have any meaning in a mobile app personally. 

I'd be happy to do this myself in any given program if I was given access to the underlying glfw window, but Fyne does not expose the glfw window handle. This could be a valid alternative, just put some function in which exposes the native window handle (*glfw.Window on desktop) and then the developer can modify it as they see fit without having to add many new apis to Fyne. This is actually something that GLFW supports at least in C, in C you can get the native window handle back for example an NSWindow* on mac and then the developer can do any special handling on that. This is the way Flutter

I can appreciate your point about the user deciding whether or not something is topmost, but that choice, as far as I can tell, is OS specific. You seem to be on Gnome where you can chose but for example I work on Mac and I cannot make arbitrary windows topmost, I can only make a window topmost if the developer programmed the application with that ability. I'm not 100% certain but I'm pretty sure that the same is true for Windows, I don't think (again could be wrong) that you can just make any random application topmost unless the developer built the software to do that. At the end of the day if you build an application that is always on top and your users don't like that, they can just not use your app.

**Comment by Jacalz** [comment] 2023-08-29 21:22
Thanks for the input. Your ideas are very useful.

> For what its worth this is the 4th issue opened requesting or inquiring about this feature.

Oh, right. Yeah this should be closed as a duplicate of https://github.com/fyne-io/fyne/issues/1129.

> I haven't used Fyne on mobile so I'm speaking out of ignorance here on mobile what do Resize, SetFixedSize, SetTitle and CenterOnScreen do?

They are kind of there from a legacy perspective. They would probably have been placed in the `driver/desktop` package if they were introduced today but I’m not sure. I believe there is an option open for deprecating `Resize` and moving it into the `driver/desktop` package. Something similar could probably be done with this if we agree on that being the way forward.

**Comment by Jacalz** [comment] 2023-08-29 21:23
Closing as duplicate of https://github.com/fyne-io/fyne/issues/1129.

**Closed by Jacalz** 2023-08-29 21:23 UTC

**Comment by Jacalz** [comment] 2023-08-29 21:26
You mention for issues but I can find only two. Are there more open duplicates that should be closed?

**Comment by phillvancejr** [comment] 2023-08-29 22:31
Sorry, I should have been more clear about that. There were only two open but I came across two other closed issues when I was searching to see if Fyne supported it. Thanks for your time! Don't know if you'll end up supporting it but in any case Fyne is still great, thanks!

**Comment by claytron5000** [comment] 2024-06-06 02:14
@phillvancejr I've been trying to get similar code to (yours)[https://github.com/fyne-io/fyne/issues/3429#issuecomment-1697928145] to work in the user space by importing glfw directly and then typing the method `func Topmost(w *glfw.Window) {`. The compiler is yelling at me, I'm assuming the window type from fyne is different than glfw's window. Any suggestions on implementing this functionality?

**Comment by Jacalz** [comment] 2024-06-06 05:57
The GLFW window type is indeed different from
our Fyne window; it is embedded as a field somewhere inside the struct. Unless you manage to do some field value lookup using `reflect`, I think it will be quite hard to force the window to be topmost.

**Comment by andydotxyz** [comment] 2024-06-06 13:17
Until the PR exposing native window handles lands :)
