### ISSUE TITLE
Add widget.NewButtonWithData

### ISSUE THREAD

**Issue by jdavid5815** [fyne-io/fyne#3390] opened 2022-11-10 16:20 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I'm writing an app in which you can select your preferred language. If you select a different language, then at lot of text needs to be changed, such as messages, dates, etc... While it's possible to use databindings for labels e.g. widgetLabelWithData() to update some content, this is not the case for Buttons. At first sight it does not make any sense to create a databinding for a button, but if the language changes, then the title of the Button also changes. It would be nice if there would be a widget.NewButtonWithData() function, similar to that for labels, in which you can update the title of the button.

### Is it possible to construct a solution with the existing API?

Yes, you can rebuild containers or windows to reflect the language change. This is however, not very efficient.

### Describe the solution you'd like to see.

Something like the following would be nice:

```
package main

import (
        "time"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Language")

	title := binding.NewString()
	title.Set("Continue")

	button := widget.NewButtonWithData(title, func() {})
	w.SetContent(button)

       go func() {
		time.Sleep(time.Second * 2)
                // Switch to Dutch
		title.Set("Ga voort")
	}()
	w.ShowAndRun()
}

```

**Comment by Jacalz** [comment] 2022-11-12 20:16
Is this not just another way, more or less, to achieve the problem of internationalisation? There are a lot more widgets that will require to change the text depending on the language and I think an API or mechanism specific for internationalisation is the better way to go. https://github.com/fyne-io/fyne/issues/605

**Comment by jdavid5815** [comment] 2022-11-13 18:50
I agree, it could be part of a larger effort to include internationalisation in fyne.

**Comment by Jacalz** [comment] 2022-11-13 19:24
What I meant was that I don't quite think that this is right solution for solving the problem. I think it would be better to add broad support for internationalisation in a uniform way; not necessarily by adding data binding to buttons. Sorry if my last comment was a bit unclear

**Comment by jdavid5815** [comment] 2022-11-13 19:29
No problem, I do not really have any preference over how this should be handled, I just noticed that it is currently not straightforward to build an app that supports multiple languages. So, yes internationalisation would be a nice feature to add indeed and it would obviously solve my problem. Thank You.

**Comment by andydotxyz** [comment] 2022-11-13 20:54
Yes we should do it properly and when that is in you won't need new APIs etc to the widgets :).
With regards to the initial request we are designing the `...WithData` is to manage the primary data of a widget - and I'm not sure that the label of a button is it's primary data. Hard to say for sure.
We probably need to revisit this topic when we look at things like disabled states and other properties to be bound, but for now I guess we close it as a duplicate of #605 as @Jacalz suggested.

**Comment by andydotxyz** [comment] 2022-11-13 20:54
Of note is that you can set the button title manually without this new method request

**Closed by andydotxyz** 2022-11-13 20:54 UTC

**Comment by cgruber** [comment] 2024-01-06 17:52
I definitely wasn't looking at this feature (when searching for an issue) as an internationalization fix. Rather, I'm looking to manage game-state and altering the text and icon of various buttons based on the game-state. In other words, I want the source of truth of what text or image shows in the buttons to be extrinsic to the button. I guess I could create the buttons, and try a hack with pointer references, that's fine, but it's gross. And while it's entirely possible to manually set these things, that sort of defeats the purpose behind data binding, as it forces me to keep a bunch of widget control references around and manupulate them in model code. Doable, but also gross.

I can design some facade for some of this to make it less bad, but I think there's a good case, if there is to be any data-binding as a pattern, to fully load the UI with such bound data. If you can call SetFoo() on it, Foo should probably be bindable. So setting a button's click function is probably not reasonable, but the image and text, I think is.

**Comment by andydotxyz** [comment] 2024-01-06 19:14
You can use data binding to have a central source of truth and decouple the UI from logic without a "WithData" or "Bind" for every single feature. Just add your own listener to the data (AddListener) alongside your widget creation and update it when that callback fires.
