### ISSUE TITLE
      Chinese is not supported

### ISSUE THREAD

**Issue by zhosi** [fyne-io/fyne#1178] opened 2020-07-10 02:05 UTC
![image](https://user-images.githubusercontent.com/59554532/87108397-cab48d00-c294-11ea-9823-316df4f8a13e.png)
![image](https://user-images.githubusercontent.com/59554532/87108409-d30cc800-c294-11ea-8b5d-f68f4057ae8f.png)
  Window    Chinese is not supported?

**Comment by adals** [comment] 2020-07-10 19:28
+1 also Arabic

**Comment by Dynamith** [comment] 2020-07-11 00:23
Fyne's default font does not include the Chinese font, you need to customize the font.
![example](https://user-images.githubusercontent.com/64576195/87212166-c6997580-c34f-11ea-91f5-76eab579e613.jpg)

**Comment by andydotxyz** [comment] 2020-07-11 20:42
Looks like a duplicate of #604

**Closed by andydotxyz** 2020-07-11 20:42 UTC
