### ISSUE TITLE
BorderLayout does not respect visibility on mobile

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#2755] opened 2022-01-26 23:47 UTC
On Android, BorderLayout is absolute and does not respond to changes in screen size, such as when a keyboard is opened that effectively shrinks the screen. In this case, the keyboard covers the widgets; if the entry widget is at the bottom of the screen, this can make the entry widget hidden.

### To Reproduce:
Compile the supplied code for Android; install it, and try to use the text widget at the bottom of the screen.

```
fyne package -os android -appId com.test.fynetest -icon someRandomIcon.png
```

### Screenshots:

Full app, with list and text entry widget at bottom:

![Screenshot_20220126-173649](https://user-images.githubusercontent.com/60757196/151265605-c4844592-b046-4caa-97c1-9837da6afdc2.jpg)

App with the keyboard open (after clicking on the text widget):

![Screenshot_20220126-173700](https://user-images.githubusercontent.com/60757196/151265544-ce7708f6-3fda-44c1-9de7-971ebf7c560d.jpg)

### Example code:

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("net.ser1.forage")

	w := a.NewWindow("Forage")

	items := make([]string, 20)
	for i:=0; i<20; i++ {
		items[i] = fmt.Sprintf("Item #%d", i)
	}

	itemList := widget.NewList(
		func() int {
			return len(items)
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("Template")
		},
		func(it widget.ListItemID, o fyne.CanvasObject) {
			c, _ := o.(*widget.Label)
			c.Text = items[it]
			c.Refresh()
		},
	)
	lambda :=  func(val string) {
		items = append(items, val)
		itemList.Refresh()
	}
	addItem := widget.NewEntry()
	addItem.OnSubmitted = lambda
	addButton := widget.NewButtonWithIcon("", theme.ContentAddIcon(), func(){ lambda(addItem.Text) })
	addRow := container.New(layout.NewBorderLayout(nil, nil, nil, addButton), addItem, addButton)

	c := container.New(layout.NewBorderLayout(nil, addRow, nil, nil), itemList, addRow)
	itemList.Refresh()
	w.SetContent(c)
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Android (compiled on Linux)
 - **Version:** 12 (Samsung's version 4.0)
 - **Go version:** 1.17.6
 - **Fyne version:** v2.1.2 h1:avp9CvLAUdvE7fDMtH1tVKyjxEWHWcpow6aI6L7Kvvw=

**Comment by Jacalz** [comment] 2022-01-27 09:20
I'm not sure if this is specific to how borderlayout works. It is probably a general issue with layouts not shrinking when the keyboard pops up.

**Comment by xxxserxxx** [comment] 2022-01-27 15:07
Fair comment; borderlayout is where I noticed it; I didn't try any other layouts.

My work-around is to put entry widgets at the top.

**Comment by Bluebugs** [comment] 2022-01-27 16:35
It might be possible that the window doesn't get resized under Android. Their seems to be a list of different policy for what to do in the application manifest. I do not know where to find it in Fyne code base if anyone knows?

**Comment by Jacalz** [comment] 2022-01-27 16:42
The Android manifest file template can be found [here](https://github.com/fyne-io/fyne/blob/master/cmd/fyne/internal/mobile/manifest.go). It probably should be moved into the template folder sometime.

**Comment by Bluebugs** [comment] 2022-01-27 17:08
Thanks @Jacalz.

@xxxserxxx would you mind changing the manifest and add a line the `<activity>` tag with the attribute: `android:windowSoftInputMode="adjustResize"`.

It might look like:
```
	<activity android:name="org.golang.app.GoNativeActivity"
		android:label="{{.Name}}"
		android:configChanges="orientation|keyboardHidden|uiMode"
		_android:windowSoftInputMode="adjustResize"_
		android:theme="@android:style/Theme">
		<meta-data android:name="android.app.lib_name" android:value="{{.LibName}}" />
		<intent-filter>
			<action android:name="android.intent.action.MAIN" />
			<category android:name="android.intent.category.LAUNCHER" />
		</intent-filter>
	</activity>
```
If that fix your problem, I could do a PR for it that would also address @Jacalz good point that it should be a template and bundled.

**Comment by Bluebugs** [comment] 2022-01-27 17:14
For later reference, the reason why the window doesn't get resized by default might be for performance reason and it might be better to track the area where the keyboard is instead of forcing a resize. Reference example code: https://falsinsoft.blogspot.com/2017/04/qml-resize-controls-when-android.html . This is of course more work, and I would put that on a follow up issue if the manifest change solve the problem.

**Comment by Jacalz** [comment] 2022-01-27 17:47
> If that fix your problem, I could do a PR for it that would also address @Jacalz good point that it should be a template and bundled.

Thanks. I think the reason that it initially wasn't moved to the template folder (when I created the template package some time ago) was to keep our gomobile close to upstream. However, a lot has happened with our mobile package since then and I'm not sure if that argument really stands any more. I think the benefits of having it in the template folder are far larger than any issues with not being close to upstream.

**Comment by andydotxyz** [comment] 2022-01-27 18:09
I think this is a duplicate of #566

**Comment by xxxserxxx** [comment] 2022-01-27 18:54
@andydotxyz I think so too. My search didn't turn that one up, but I may have been focusing on the layout.  I'm testing @Bluebugs' suggestion, but after that do you want me to close this one?

**Comment by xxxserxxx** [comment] 2022-01-28 16:55
@Bluebugs: that didn't address the issue, unfortunately. I did check to make sure the right manifest got used by unzipping the APK and using axmldec.

**Comment by Bluebugs** [comment] 2022-01-28 17:05
@xxxserxxx that's a disappointing news. I guess we will have to implement in code then. I am focusing on the web platform at the moment, but I have on my todo to do some work on Android. In which case, I think we should close this issue and focus on #566.

**Comment by Jacalz** [comment] 2022-01-28 18:32
I agree. Let's close this as a duplicate of that one.

**Closed by Jacalz** 2022-01-28 18:32 UTC
Labels: duplicate
