### ISSUE TITLE
  Unexpected vertical scroll bar in entry 

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2817] opened 2022-03-02 15:19 UTC
### Describe the bug:
As the title describes, when the grid layout is used, the vertical scroll bar appears in the entry

### To Reproduce:
Steps to reproduce the behaviour:
- Run the code below

### Screenshots:
![图片](https://user-images.githubusercontent.com/6658943/156390825-b01704f5-e69f-4a59-b64c-034fb1ad8401.png)

### Example code:
```go
func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Entry Widget")

	input := widget.NewEntry()
	input.SetPlaceHolder("Enter text...")

	content := container.NewGridWithColumns(2, input, widget.NewButton("btn", nil))

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows10
 - **Version:** 19044
 - **Go version:** go1.17.5
 - **Fyne version:** 2.1.3

**Comment by andydotxyz** [comment] 2022-03-02 15:50
I cannot replicate this, can you provide any more info about actions, display scale etc.
The screenshot is not the default window size, did you have to resize it to see the issue?

**Comment by BabySid** [comment] 2022-03-03 02:37
> I cannot replicate this, can you provide any more info about actions, display scale etc. The screenshot is not the default window size, did you have to resize it to see the issue?

Um, yes. Because the default window size is too small, I lengthened the window manually.

However, I have rewritten the following code and still have the same problem.

![图片](https://user-images.githubusercontent.com/6658943/156484305-8c5001e5-1241-4543-aca0-968d6fe7123e.png)

```go
func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Entry Widget")

	input := widget.NewEntry()
	input.SetPlaceHolder("Enter text...")

	top := container.NewGridWithColumns(2, input, widget.NewButton("btn", nil))

	myWindow.SetContent(container.NewBorder(top, nil, nil, nil, widget.NewLabel("hello world")))

	myWindow.Resize(fyne.NewSize(600, 400))
	myWindow.ShowAndRun()
}
```

In addition, if I change layout to HBox, although the input box is too small to meet my expectations, at least the vertical scroll bar does not exist. Very strange.
![图片](https://user-images.githubusercontent.com/6658943/156485279-2b176279-a4b0-40c1-9bdf-f3f1afbf4245.png)

**Comment by BabySid** [comment] 2022-03-03 10:47
> > Um, yes. Because the default window size is too small, I lengthened the window manually.
> 
> Was the bar visible before you resized the window, or did it appear after a certain size?

Yes. The bar is visible as long as i don't stretch the form vertically.

**Comment by ranjith-bhide** [comment] 2022-03-27 06:53
Hi @BabySid,

I was able to replicate this behaviour with below code
```go
func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Window")

	content := container.NewGridWithColumns(1,
		widget.NewEntry(),
		widget.NewEntry(),
	)

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}
```
**OS** : Ubuntu 20.04
**go version** : go1.17.6
**Fyne version** : v2.1.4

Where the second `Entry` always was having a scroll bar.
I think its coming up upon using the grid layout.
Both Entries initially come up with height of 37 px. and later on there is a resize() called for the two entries : 1 with 37 px height and the other with 36 px, its after this resize that the vertical scroll bar is seen.
I did some additional debugging and found that this difference is coming from the function 
`func (g *gridLayout) Layout(objects []fyne.CanvasObject, size fyne.Size)`
where `child.Resize(fyne.NewSize(x2-x1, y2-y1))` is made with with (y1, y2) = (0,37) for one entry and (41,77) for the second one (where scrollbar appears)

Now, I am new to fyne and do not completely grasp the implications, but it looks like if i ensure (g *gridLayout) MinSize() return ceiled integer values for Width and Height the issue is no longer, seen. 
```diff
diff --git a/layout/gridlayout.go b/layout/gridlayout.go
index 1a68779c..61e40ce0 100644
--- a/layout/gridlayout.go
+++ b/layout/gridlayout.go
@@ -137,9 +137,11 @@ func (g *gridLayout) MinSize(objects []fyne.CanvasObject) fyne.Size {
 
        if g.horizontal() {
                minContentSize := fyne.NewSize(minSize.Width*float32(g.Cols), minSize.Height*float32(rows))
-               return minContentSize.Add(fyne.NewSize(theme.Padding()*fyne.Max(float32(g.Cols-1), 0), theme.Padding()*fyne.Max(float32(rows-1), 0)))
+               minContentSize = minContentSize.Add(fyne.NewSize(theme.Padding()*fyne.Max(float32(g.Cols-1), 0), theme.Padding()*fyne.Max(float32(rows-1), 0)))
+               return fyne.NewSize(float32(math.Ceil(float64(minContentSize.Width))), float32(math.Ceil(float64(minContentSize.Height))))
        }
 
        minContentSize := fyne.NewSize(minSize.Width*float32(rows), minSize.Height*float32(g.Cols))
-       return minContentSize.Add(fyne.NewSize(theme.Padding()*fyne.Max(float32(rows-1), 0), theme.Padding()*fyne.Max(float32(g.Cols-1), 0)))
+       minContentSize = minContentSize.Add(fyne.NewSize(theme.Padding()*fyne.Max(float32(rows-1), 0), theme.Padding()*fyne.Max(float32(g.Cols-1), 0)))
+       return fyne.NewSize(float32(math.Ceil(float64(minContentSize.Width))), float32(math.Ceil(float64(minContentSize.Height))))
 }
```

@andydotxyz : Please let me know if this change makes sense and is acceptable. Ill create a pull request if it is.

**Comment by andydotxyz** [comment] 2022-03-31 10:25
> @andydotxyz : Please let me know if this change makes sense and is acceptable. Ill create a pull request if it is.

I'm glad you found the issue but the fix seems like it may be working around a rounding issue in the layout. It seems like there may be a more correct fix if `GridLayout` is assuming ints somewhere...

**Comment by ranjith-bhide** [comment] 2022-04-01 21:28
> > @andydotxyz : Please let me know if this change makes sense and is acceptable. Ill create a pull request if it is.
> 
> I'm glad you found the issue but the fix seems like it may be working around a rounding issue in the layout. It seems like there may be a more correct fix if `GridLayout` is assuming ints somewhere...

Thanks for that insight @andydotxyz.
I did a bit more debugging and I probably think i found the root cause now.
In internal/driver/glfw/scale.go function `calculateScale`
```go
func calculateScale(user, system, detected float32) float32 {
	if user < 0 {
		user = 1.0
	}

	if system == scaleAuto {
		system = detected
	}

	raw := system * user
	return float32(math.Round(float64(raw*10.0))) / 10.0
}
```
There is a rounding off in the scale till 1 decimal place.
I think this rounding off eventually results in the entry widget getting 1 pixel short of its `minsize()` thereby showing the scrollbar.
I was able to see the issue resolved with the rounding off set to 2 decimal places
```diff
diff --git a/internal/driver/glfw/scale.go b/internal/driver/glfw/scale.go
index 90eb62cf..2c9a802e 100644
--- a/internal/driver/glfw/scale.go
+++ b/internal/driver/glfw/scale.go
@@ -37,7 +37,7 @@ func calculateScale(user, system, detected float32) float32 {
        }
 
        raw := system * user
-       return float32(math.Round(float64(raw*10.0))) / 10.0
+       return float32(math.Round(float64(raw*100.0))) / 100.0
 }
 
 func userScale() float32 {
```
That probably explains why it might be reproduced only in certain environments (where glfw is present/used)

Let me know if this seems appropriate.

**Comment by andydotxyz** [comment] 2022-04-01 21:39
Great find, thanks. Being related to precision makes sense. I wonder if this is the same as #2471?
Higher precision could help, the low-precision is less important than it used to be.
As long as it does not lead to less crisp text, which I think was a previous concern...

**Comment by ranjith-bhide** [comment] 2022-04-01 22:27
> Great find, thanks. Being related to precision makes sense.

Awesome :). Thanks for the confirmation.

>Higher precision could help, the low-precision is less important than it used to be.
 As long as it does not lead to less crisp text, which I think was a previous concern...

Can you point me to right Test-Case/Scenario where I can verify this?

> I wonder if this is the same as #2471? 

I tried the #2471 scenario with the above change, and once with precision upto 3 decimal places, I was still able to replicate the issue, so Im guessing the cause for these 2 issues may not be linked.

**Comment by andydotxyz** [comment] 2022-04-03 22:22
> Can you point me to right Test-Case/Scenario where I can verify this?

Sadly not really, text crispness is mostly tested by visually checking at certain low-scale factor values to check it looks good.

> Also, any particular reason we need a rounding off, otherwise preserve the precision completely by doing a

It was to avoid fuzzy text (like 1.01 scale factor looks much less clean than 1.0 multiplier). Or at least that is how things were in the past...

**Comment by andydotxyz** [comment] 2022-04-03 22:35
I did a little experimentation and I think I found a stray `math.Round`. This change worked for me, what do you think @ranjith-bhide?

```go
func getLeading(size float64, offset int) float32 {
	ret := (size + float64(theme.Padding())) * float64(offset)

	return float32(ret)
}
```

**Comment by ranjith-bhide** [comment] 2022-04-04 17:58
Nice catch. I also tried by removing that stray `math.Round`

But Unfortunately it causes the scroll bar to come on both the entries.
![Screenshot from 2022-04-04 23-23-42](https://user-images.githubusercontent.com/30768539/161602786-64f65820-5bd1-429d-a478-08df83a5cfcb.png)

Original Issue looks like this:
![Screenshot from 2022-04-04 23-26-10](https://user-images.githubusercontent.com/30768539/161603169-3394a793-5f64-47aa-a1b2-66603ec59f94.png)

**Comment by andydotxyz** [comment] 2022-04-04 20:34
> But Unfortunately it causes the scroll bar to come on both the entries.

Ah - but not initially... There may be more clues here.
The bars appear after resize here, so something else is going on.

**Comment by andydotxyz** [comment] 2022-04-04 20:44
Yes. I think the other half of the puzzle is that a window can be made smaller than its MinSize, also due to rounding.

For me this combination of changes resolved it:

```diff
diff --git a/internal/scale.go b/internal/scale.go
index 199362da..c0e7e7da 100644
--- a/internal/scale.go
+++ b/internal/scale.go
@@ -8,7 +8,7 @@ import (
 
 // ScaleInt converts a fyne coordinate in the given canvas to a screen coordinate
 func ScaleInt(c fyne.Canvas, v float32) int {
-       return int(math.Round(float64(v * c.Scale())))
+       return int(math.Ceil(float64(v * c.Scale())))
 }
 
 // UnscaleInt converts a screen coordinate for a given canvas to a fyne coordinate
diff --git a/layout/gridlayout.go b/layout/gridlayout.go
index 1a68779c..ba39985b 100644
--- a/layout/gridlayout.go
+++ b/layout/gridlayout.go
@@ -60,7 +60,7 @@ func (g *gridLayout) countRows(objects []fyne.CanvasObject) int {
 func getLeading(size float64, offset int) float32 {
        ret := (size + float64(theme.Padding())) * float64(offset)
 
-       return float32(math.Round(ret))
+       return float32(ret)
 }
 
 // Get the trailing (bottom or right) edge of a grid cell.
```

**Comment by ranjith-bhide** [comment] 2022-04-05 04:29
Cool finding @andydotxyz. This indeed fixes the ScrollBar Issue at my end as well.

Just thinking out loud, If we use `math.Ceil` instead of `math.Round`  in ScaleInt, can it cause some other one-pixel-off problems as I see this ScaleInt function being used extensively for scaling both X,Y co-ordinates as well as Width/Heights of components. Also, I am assuming its expected to work for both c.Scale() >1 and c.Scale() < 1.

If there isnt any potential problem as such, Then this fix looks good to me.

**Comment by andydotxyz** [comment] 2022-04-05 10:02
> Just thinking out loud, If we use `math.Ceil` instead of `math.Round` in ScaleInt, can it cause some other one-pixel-off problems as I see this ScaleInt function being used extensively for scaling both X,Y co-ordinates as well as Width/Heights of components.

Yes this is a good question. At a glance I think that `Ceil` is usually correct as we should not draw things smaller than their min size. I would suggest trying it out and testing hard, see what you find.

> Also, I am assuming its expected to work for both c.Scale() >1 and c.Scale() < 1.

Absolutely. Scaling needs to work both ways. Of course it could become rather pixelated - but it may be desired as this is a user scaling - so a 0.5 scale on an OS with a HiDPI monitor would take it down to 1:1 on pixels.

Are you happy to continue progressing this through PR?

**Comment by ranjith-bhide** [comment] 2022-04-07 16:25
>Are you happy to continue progressing this through PR?

@andydotxyz I am not sure I understood this right. You want me to open PR for this?
Essentially the fix was found by you, So I feel it would be appropriate for this contribution to go with your name :)

**Comment by andydotxyz** [comment] 2022-04-08 09:09
> @andydotxyz I am not sure I understood this right. You want me to open PR for this?
> Essentially the fix was found by you, So I feel it would be appropriate for this contribution to go with your name :)

You did all the hard work, so happy for you to open it. However if you would prefer I do that is OK too.

**Comment by ranjith-bhide** [comment] 2022-04-09 07:57
> You did all the hard work, so happy for you to open it.

Thats awfully kind of you @andydotxyz 
I'll open a PR right away.

**Comment by ranjith-bhide** [comment] 2022-04-09 15:36
Hi @andydotxyz,
I pushed a commit with the discussed changes to [my repo](https://github.com/ranjith-bhide/fyne/tree/Issue_2817_fix).
But I see lot of tests failing in the CI pipeline actions.
I suspect it might be because of the Round -> Ceil change in `ScaleInt()`.

Can you suggest how to go about it ?
Will we have to think of a different fix or should we change the test cases accordingly?

**Comment by andydotxyz** [comment] 2022-04-11 17:01
If they  are the result of a rounding error and differ only by `1` then it should be OK to update the test cases.
Note that for PNG and XML test failures you can drag the file out of `testdata/failed` dir back into the `testdata` rather than manually editing expected results

**Closed** 2022-09-16 17:33 UTC
Labels: unverified, information-needed
