### ISSUE TITLE
啥时候增加webview控件

### ISSUE THREAD

**Issue by dzwvip** [fyne-io/fyne#238] opened 2019-04-30 01:48 UTC
增加webview控件 直接展示 用 echart 绘图网页 就完美了

**Comment by andydotxyz** [comment] 2019-04-30 09:19
ran this through Google translate:

Add webview control Direct display Using echart to draw a web page is perfect

**Comment by andydotxyz** [comment] 2019-04-30 09:21
I think this is a duplicate of #116

**Comment by andydotxyz** [comment] 2019-05-11 17:31
Closing as duplicate of #116

**Closed by andydotxyz** 2019-05-11 17:31 UTC
Labels: question
