### ISSUE TITLE
Android: System UI text is forcefully recolored white

### ISSUE THREAD

**Issue by pjanx** [fyne-io/fyne#5260] opened 2024-11-12 21:24 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Fyne seems to somewhere enforce white text colour for the system UI. With a light theme on my Samsung phone, I can't see anything!

On Android simulator, I've noticed that Fyne sets the background of those UI parts to black. A possibly related issue is that Fyne in my Android simulator gets a black window background on a light theme, making app contents rather than the system UI unreadable.

### How to reproduce

* Use light mode with light theme on an Android device
* Run a Fyne app, and observe the system UI

### Screenshots

Screenshots: light mode, without overlay window, dark mode, without overlay window.

![Screenshot_20241112_220413](https://github.com/user-attachments/assets/4026583c-c95b-4c72-b6d4-1bc0c7633d90)
![Screenshot_20241112_220435](https://github.com/user-attachments/assets/c7b1171f-6d82-4405-9acc-bbf19f56c6c5)
![Screenshot_20241112_221033](https://github.com/user-attachments/assets/c759d238-28ff-448e-8086-5ea0b7b6ca87)
![Screenshot_20241112_221004](https://github.com/user-attachments/assets/743dc44d-75ea-4d05-a26b-ce3cd672d2bb)

### Example code

```
package main

import (
	"net"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/driver/mobile"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Bugs")
	w.Resize(fyne.NewSize(640, 480))
	w.SetContent(widget.NewMultiLineEntry())

	connectAddress := widget.NewEntry()
	connectAddress.SetPlaceHolder("host:port")
	connectAddress.Validator = func(text string) error {
		_, _, err := net.SplitHostPort(text)
		return err
	}
	connectAddress.SetText(string([]byte{3, 2, 1, 65, 66, 67, ':', '1'}))
	connectAddress.TypedKey(&fyne.KeyEvent{Name: fyne.KeyPageDown})

	var wConnect *dialog.FormDialog
	wConnect = dialog.NewForm("Connect to relay", "Connect", "Exit",
		[]*widget.FormItem{
			{Text: "Address:", Widget: connectAddress},
		}, func(ok bool) {
			if ok {
			} else if _, ok := a.Driver().(mobile.Driver); ok {
				wConnect.Show()
			} else {
				a.Quit()
			}
		}, w)
	wConnect.Show()
	w.ShowAndRun()
}
```

### Fyne version

2.5.2

### Go compiler version

1.23.2

### Operating system and version

Android 13 One UI 5.1

**Comment by andydotxyz** [comment] 2024-11-16 08:51
This looks to be a duplicate of #1442. As noted on that issue we are looking for help because it looks like we have set the appropriate theme but it does not take effect.

**Closed by andydotxyz** 2024-11-16 08:51 UTC
Labels: unverified
