### ISSUE TITLE
Error reporting in window minimization

### ISSUE THREAD

**Issue by hq-zhonger** [fyne-io/fyne#3574] opened 2023-01-16 14:01 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

After the product is completed, minimize and maximize the exit test. When the minimize button is pressed, the error program is triggered to exit the other two normal error messages are as follows

### How to reproduce

...

### Screenshots

![1](https://user-images.githubusercontent.com/78897251/212695635-4536919d-d104-423c-8766-e9518667bc23.PNG)
![2](https://user-images.githubusercontent.com/78897251/212695643-9d913948-d7ba-4da1-8c3c-16a0024b2db4.PNG)

### Example code

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff750df6181]

goroutine 1 [running, locked to thread]:
main.(*Music).GetFileList(0x7ff7516dcc40)
        D:/go/mp3/main.go:286 +0x265
PS D:\go\mp3> go build .\main.go
PS D:\go\mp3> .\main.exe        
ok
ok
ok
PS D:\go\mp3> .\main.exe        
PS D:\go\mp3> go build .\main.go
PS D:\go\mp3> .\main.exe        
PS D:\go\mp3> go build .\main.go
PS D:\go\mp3> .\main.exe        
PS D:\go\mp3> go build .\main.go
PS D:\go\mp3> .\main.exe        
PS D:\go\mp3> go build .\main.go
PS D:\go\mp3> .\main.exe        
        D:/go/mp3/main.go:381 +0x2e
fyne.io/fyne/v2/widget.(*Button).Tapped(0xc0003706e0, 0xc000456001)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/widget/button.go:202 +0x53
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:634 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:942 +0x136
PS D:\go\mp3> .\main.exe
[signal 0xc0000005 code=0x0 addr=0x78 pc=0x7ff69c4c0649]

goroutine 36 [running]:
fyne.io/fyne/v2/widget.(*List).Select(0x7ff69c4aff65?, 0x7ff69caf8140?)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/widget/list.go:160 +0x29
main.main.func10()
        D:/go/mp3/main.go:381 +0x2e
fyne.io/fyne/v2/widget.(*Button).Tapped(0xc000370640, 0xc0000ee001)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/widget/button.go:202 +0x53
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:634 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:942 +0x136
PS D:\go\mp3> .\main.exe

goroutine 52 [running]:
fyne.io/fyne/v2/widget.(*List).Select(0x7ff69c4aff65?, 0x7ff69caf8140?)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/widget/list.go:160 +0x29
main.main.func9()
        D:/go/mp3/main.go:359 +0x2e
fyne.io/fyne/v2/widget.(*Button).Tapped(0xc000370500, 0xc000fd6001)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/widget/button.go:202 +0x53
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:634 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:942 +0x136
PS D:\go\mp3> go build .\main.go
PS D:\go\mp3> .\main.exe        
panic: runtime error: slice bounds out of range [:-7047]

goroutine 53 [running, locked to thread]:
golang.org/x/image/vector.(*Rasterizer).setUseFloatingPointMath(0xc000031520, 0x1?)
        E:/go/pkg/mod/golang.org/x/image@v0.3.0/vector/vector.go:143 +0x125
golang.org/x/image/vector.(*Rasterizer).Reset(0x10?, 0xc00a6ff3f0?, 0x7ff79bb8f830?)
        E:/go/pkg/mod/golang.org/x/image@v0.3.0/vector/vector.go:123 +0x65
github.com/srwiley/rasterx.(*ScannerGV).SetBounds(...)
        E:/go/pkg/mod/github.com/srwiley/rasterx@v0.0.0-20220730225603-2ab79fcdd4ef/scan.go:166
github.com/srwiley/rasterx.NewScannerGV(0xd?, 0x0?, {0x7ff79c485130?, 0xc00a93b680}, {{0x0?, 0xc00a6ff470?}, {0x7ff79b953651?, 0x0?}})
        E:/go/pkg/mod/github.com/srwiley/rasterx@v0.0.0-20220730225603-2ab79fcdd4ef/scan.go:173 +0x69
fyne.io/fyne/v2/internal/painter.DrawRectangle(0xc0000becc0, 0x40400000, 0xc00a6ff4d8)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/draw.go:90 +0x16c
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlStrokedRectTexture(0xc00005c340, {0x7ff79c488140?, 0xc0000becc0?})
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:156 +0xa5
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlRectTexture(0x7ff79c30c000?, {0x7ff79c488140?, 0xc0000becc0?})
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:146 +0x4e
fyne.io/fyne/v2/internal/painter/gl.(*painter).getTexture(0xc00005c340, {0x7ff79c488140, 0xc0000becc0}, 0xc00a6ff6a0)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:36 +0x4f
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawTextureWithDetails(0xc00005c340, {0x7ff79c488140?, 0xc0000becc0?}, 0xc00a6ff6b8?, {0x9bd65b7a?, 0x7ff7?}, {0xa94b7e4?, 0xc0?}, {0x41c000?, 0xc0?}, ...)   
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:134 +0x8b
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawRectangle(0xc00005c340, 0xc0000becc0, {0x0?, 0x0?}, {0xa6ff730?, 0xc0?})
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:104 +0x17e
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawObject(0xc00a6ff758?, {0x7ff79c488140?, 0xc0000becc0?}, {0x9b91c0bd?, 0x7ff7?}, {0x9c2ba7c0?, 0x7ff7?})
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:86 +0x16d
fyne.io/fyne/v2/internal/painter/gl.(*painter).Paint(0x7ff79b91e37f?, {0x7ff79c488140, 0xc0000becc0}, {0x9b91c0bd?, 0x7ff7?}, {0x9c2ba7c0?, 0x7ff7?})
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/painter.go:84 +0x74
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint.func1(0x7ff79bb8f2f1?, {0x9bb8f97c?, 0x7ff7?})
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/canvas.go:284 +0x102
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func1({0x7ff79c488140?, 0xc0000becc0}, {0xbecc0?, 0xc0?}, {0xfded20?, 0xc0?}, {0x5b45365d?, 0xe?})
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:438 +0x277
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff79c488140, 0xc0000becc0}, 0x0, {0x7ff79c488860, 0xc000fded20}, {0x9c2ba7c0?, 0x7ff7?}, {0x0?, 0x0?}, {0x436c0000?, ...}, ...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:169 +0x29b
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff79c488860, 0xc000fded20}, 0x0, {0x7ff79c487ea0, 0xc00a5c2690}, {0x5e780?, 0xc0?}, {0x0?, 0x0?}, {0x436c0000?, ...}, ...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff79c487ea0, 0xc00a5c2690}, 0x0, {0x7ff79c487ea0, 0xc00a5c28c0}, {0xa6ffb18?, 0xc0?}, {0x0?, 0x0?}, {0x40c00000?, ...}, ...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff79c487ea0, 0xc00a5c28c0}, 0x0, {0x7ff79c487ea0, 0xc00a5c2910}, {0x9c2daba0?, 0x7ff7?}, {0xa932550?, 0xc0?}, {0x415f50?, ...}, ...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff79c487ea0, 0xc00a5c2910}, 0x0, {0x0, 0x0}, {0x9b953651?, 0x7ff7?}, {0x0?, 0x0?}, {0xa6ffc88?, ...}, ...)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0x7ff79c487ea0?, 0xc00a5c2910?}, 0xc000fc2680?, 0x200000003?)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:134 +0x4c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0xc000000000?, 0xc000427040, 0xc00a6ffdd0, 0xc00a6ffda0)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:459 +0x165
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc0000ac120, 0xc00a6ffda0?, 0x7ff79be8e686?)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:371 +0x3c
fyne.io/fyne/v2/internal/driver/glfw.(*window).platformResize.func1()
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window_notlinux.go:17 +0x48
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc00a6fff90?, 0xc00a93d400)
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:903 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:234 +0x13b
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        E:/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:226 +0xea

### Fyne version

v2.3.0

### Go compiler version

go1.19.5

### Operating system

Windows

### Operating system version

windows 10

**Comment by Jacalz** [comment] 2023-01-16 15:00
Thanks for opening the issue. Closing as duplicate of https://github.com/fyne-io/fyne/issues/3552.

**Closed** 2023-01-16 15:00 UTC
Labels: duplicate
