### ISSUE TITLE
Scrollbars for multiline input(entry) widget

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#471] opened 2019-09-29 08:04 UTC
**Is it possible to construct a solution with the existing API?**
Yes, it possible now if put the widget into ScrollContainer. 

**Describe the solution you'd like**
Entry widget itself can contain scrollbars (vertical and horizontal). It can be set automatically(after resize, after text changing) or always to be shown if corresponding property is set.

**Comment by andydotxyz** [comment] 2019-10-06 09:09
What are the benefits to adding the scrollers into the entry, above doing it the way you describe by putting the entry inside a scrollcontainer?

**Comment by Kvaz1r** [comment] 2019-10-06 09:19
Flexibility(allow use different modes), simplicity/convenient(no need create container by myself).

**Comment by andydotxyz** [comment] 2019-10-15 20:11
Fair enough. I think this is probably duplicate of #378 - the right way may be complex as we look at mobile as you can't really have a scrollcontainer within a scrollcontainer which might mean entry has to be limited based on it's context - any thoughts?

**Comment by Kvaz1r** [comment] 2019-10-15 21:18
I don't think that it's duplicate. 378 describes actual unexpected (and incorrect) behaviour i.e. bug. And this issue about settings i.e. feature request. But it's not really important.

**Comment by andydotxyz** [comment] 2019-10-21 13:25
I think the reverse was true ;) if we fix this the bug goes away.
You're probably right this is something that people will expect

**Comment by andydotxyz** [comment] 2019-11-11 14:20
As per #338 we will need to improve pageup/down handling one scrolling is in.
Obviously changing cursor position should update scroll position so it's visible.

**Comment by andydotxyz** [comment] 2020-04-08 19:03
It was agreed today that this should be added.
However it is a behaviour break so we're not comfortable putting it in until 2.0.
That is currently expected around July so should not be too long to wait.

**Comment by fleshin** [comment] 2020-04-13 14:14
"Obviously changing cursor position should update scroll position so it's visible."
Is this going to happen with single line Entry as well??

**Comment by andydotxyz** [comment] 2020-04-13 15:19
Yes, single and multi line entries are the same widget

**Comment by fleshin** [comment] 2020-04-13 16:11
Great, anxiously waiting for this to appear on the develop branch! Thanks! :)

**Comment by andydotxyz** [comment] 2021-01-09 19:39
On `develop` for testing

**Closed by andydotxyz** 2021-01-09 19:39 UTC
Labels: blocker
