### ISSUE TITLE
No option to disable slider

### ISSUE THREAD

**Issue by syllith** [fyne-io/fyne#4253] opened 2023-09-15 18:07 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The slider widget does not have the ability to disable it. I found this feature request from a while back, but it seems it may have been forgotten:

https://github.com/fyne-io/fyne/issues/3551

### Is it possible to construct a solution with the existing API?

Not as far as I know

### Describe the solution you'd like to see.

The slider should have the Disable / Enable function added to it.

**Comment by Jacalz** [comment] 2023-09-15 19:33
The issue mentioned is not forgotten. No one has worked on it yet. It is only mere months old. You don't need to open a new issue if another one is open. Closing as duplicate of #3551.

**Closed by Jacalz** 2023-09-15 19:33 UTC

**Comment by syllith** [comment] 2023-09-15 19:42
Gotcha, Andy suggested it could have been forgotten and recommended I look into making a feature request. 9 months seemed like a while for something like that so I figured it wouldn't hurt to make another. Apologies.

**Comment by Jacalz** [comment] 2023-09-15 21:10
It's fine, don't worry about it. I suppose he meant that we might have forgotten to open an issue if there isn't one. In July, it was scheduled for the now upcoming release at the end of year. You know, pull requests are always welcome ;)

**Comment by andydotxyz** [comment] 2023-09-15 21:36
That's right - I was using forgotten to mean it hadn't been implemented vs it was left out intentionally. I wasn't sure if there was already an issue open.
