### ISSUE TITLE
calling CanvasObject.Hide()/.Show in Renderer.Layout() function leads to weird behavior

### ISSUE THREAD

**Issue by iamjinlei** [fyne-io/fyne#695] opened 2020-02-22 04:40 UTC
### Describe the bug:
I am not sure if this is a good practice to do so. But calling CanvasObject.Hide()/.Show() in Renderer.Layout() function leads to unexpected rendering results.

I have widget with a lots of shapes, so I am reusing CanvasObject created in the Rendered to avoid frequent allocation. When objects are not needed in the current rendering, I choose to hide them in Layout function and vice versa. In doing so, sometimes and shape color and positions are not correct. I noticed Hide()/Show() functions trigger Refresh(), so I switch to flip Hidden field instead of calling the access function. That issues disappears.

### To Reproduce:
Steps to reproduce the behaviour:
1. create a bunch of rectangles in widget's renderer ctor
2. using another goroutine to periodically update widget parameters and Refresh(). This should trigger Layout() to update size, position, color of these rectangles. Hide() or Show() some of these rectangles.
3 I observe the 2nd refresh is always wrong. Then it becomes ok

### Device (please complete the following information):
 - MacOS
 - Go version: 1.13.1
 - Fyne version: latest

**Comment by andydotxyz** [comment] 2020-02-22 12:10
It's hard to understand exactly what the issue is here, can you provide some more information or a minimal example? The way that widgets are designed is that they expose only the logic aspects of functionality and that the render encapsulates all the graphical elements.
Changes should be made inside Refresh() and the Layout() is really just an algorithm for size and position.

I don't know if that helps but if you could share more detail we could look into where the bug may lie?

**Comment by iamjinlei** [comment] 2020-02-22 14:23
@andydotxyz I am sorry I won't be able to the share more the code at this point. It is indeed hard to clearly state the code. But in a nutshell, I found it is problematic to call a CanvasObject' Show()/Hide() function inside a widget's Layout() function. It behaves normal after I replace Show()/Hide() call with a Hidden field assignment. So I suspect the refresh() inside Show()/Hide() is causing problem in this particular case.

**Comment by andydotxyz** [comment] 2020-02-24 09:15
You are probably right. Show() and Hide() (like other widget functions) trigger a refresh - but when Layout() is called it is already refreshing so there could be a delay. Without knowing more about the details of what is incorrect I don’t know what more to do.

**Comment by iamjinlei** [comment] 2020-02-24 09:19
As a beginner, I just want to confirm I am not doing something terribly wrong. Feel free to close.

**Comment by andydotxyz** [comment] 2020-02-24 09:23
Well, I guess that changing widget content or visibility in Layout() is a bad idea - because then the layout has to change which might impact minsize as well so it’s probably creating a bad redraw. A widget renderer is supposed to be a very dumb rendering of the widget state, any graphical changes should be made in Refresh() to match the state. Any additional changes could be problematic as the renderer has implicit extra state which the widget does not know about.

But you may have found a bug which is why I’d like to know more. If you can’t share more details at the moment we should probably close this for now...

**Comment by iamjinlei** [comment] 2020-02-24 09:33
Feel free to close. If you want to reproduce the scenario, you can try this:
1) create 10 rectangles in renderer's constructor
2) update their colors and toggle their visibility (by calling Show()/Hide()) in Layout
This is essentially what I do.

BTW, I followed some of the widget implementation and they have Refresh() calling Layout(). Are you saying we should prohibit calling Layout() from Refresh()?

**Comment by andydotxyz** [comment] 2020-02-26 22:46
Thanks.
It is quite reasonable for Refresh() to call Layout() if it is sure that the layout could have to change (i.e. widget knows positions are moved). However the reverse is not true - Layout should not trigger a refresh as it's purpose is strictly to move and resize it's child elements.

**Comment by andydotxyz** [comment] 2020-03-13 13:04
Closing as suggested above, recommend that child hide/show is done in Refresh and that Layout is only for managing layout of visible components.

**Closed by andydotxyz** 2020-03-13 13:04 UTC
Labels: question
