### ISSUE TITLE
Does Widget.Entry has a maxLength(size)??

### ISSUE THREAD

**Issue by dufuqsls** [fyne-io/fyne#1797] opened 2021-01-14 02:30 UTC
Hello!

first, I can't speak English well, so i'm sorry about that.

Does Widget.Entry has a MaxLength(like a maxLength in html attribute)??

I already saw the pkg.go.dev/fyne.io/fyne/widget@Entry
So how to Do i set a maxLength in Entry???
My fyne.Form need a entry validation so i used "fyne.io/fyne/data/validation at the entry
also need a scrolling because when i overwrite in entry

when used scrolling + valid in entry, validation can't work

### code
`
package main

import (
	"fmt"

	"fyne.io/fyne"
	"fyne.io/fyne/widget"
	"fyne.io/fyne/app"
	"fyne.io/fyne/container"
	"fyne.io/fyne/data/validation"

	"tutorial"
)
func main() {
	fmt.Println("")

	a := app.New()
	a.Settings().SetTheme(tutorial.MyTheme{})

	w := a.NewWindow("")
	w.Resize(fyne.NewSize(640, 400))

	c := w.Canvas()

	email := widget.NewEntry()
	email.SetPlaceHolder("test@example.com")
	email.Validator = validation.NewRegexp(`\w{1,}@\w{1,}\.\w{1,4}`, "not a valid email")

	sc := container.NewHScroll(email)

	form := widget.NewForm(
		widget.NewFormItem(
			"이메일",
			sc,
		),
	)
	form.OnSubmit = func() {

	}
	form.OnCancel = func() {

	}
	form.SubmitText = "등록하기"
	form.CancelText = "취소하기"

	form.Resize(fyne.NewSize(300, 300))

	g := fyne.NewContainerWithoutLayout(
		form,
	)
	c.SetContent(g)
	w.Show()
	
	a.Run()

}
`

first screenshot worked (Only Validation)
Also second screenshot worked (Only Scrolling)
But third screenshot doesn't work( Validation + Scrolling)
### screenshot

![test1](https://user-images.githubusercontent.com/62934043/104536385-5e5b8180-565b-11eb-85b8-777148eea691.png)
![test2](https://user-images.githubusercontent.com/62934043/104536390-60bddb80-565b-11eb-97c2-49a0491f83e7.png)
![test3](https://user-images.githubusercontent.com/62934043/104536399-61ef0880-565b-11eb-957d-398a30d002ae.png)

**Comment by dufuqsls** [comment] 2021-01-14 05:24
Sorry, I need to close this issue

**Comment by andydotxyz** [comment] 2021-01-14 12:20
In 2.0 we have added scrolling into `Entry`. This will mean you can use your validator as expected.
Closing as a duplicate of #471.

**Closed by andydotxyz** 2021-01-14 12:20 UTC

**Comment by dufuqsls** [comment] 2021-01-15 00:44
> In 2.0 we have added scrolling into `Entry`. This will mean you can use your validator as expected.
> Closing as a duplicate of #471.



> In 2.0 we have added scrolling into `Entry`. This will mean you can use your validator as expected.
> Closing as a duplicate of #471.

Thank for your answer!
