### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by EssGeeEich** [fyne-io/fyne#3607] opened 2023-01-26 00:13 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

At this point in time, there is no one way to handle translations in fyne.

### Is it possible to construct a solution with the existing API?

Currently, translation is partially feasible using external libraries.

### Describe the solution you'd like to see.

It would be nice to have a built-in translation (maybe even localization?) system.

**Comment by andydotxyz** [comment] 2023-01-26 00:20
Absolutely a great idea - something we plan to start work on soon.
I think this is a duplicate of #2928?

**Comment by EssGeeEich** [comment] 2023-01-26 00:28
I do not think that this is, strictly speaking, a duplicate of #2928.
Internationalization is a big project in its entirety - which should be more or less split in, I believe, three topics:
- Translation (obviously)
- Localization (eg. time/date formats vary between different countries, think date format differences between US/EU)
- Unicode/Font support (eg. handling and rendering the characters properly, which I suppose this is mostly good to go thanks to golang strings, but fyne seems to be lacking a system font support, as mentioned in the other topic)

While translation is part of internationalization, I think translation, localization and Unicode/rendering should be split apart and not be mixed up, work-wise, moreover #2928 was mostly about the font side.
Another message will follow with a proposal of what I was thinking.

**Comment by andydotxyz** [comment] 2023-01-26 00:39
Thanks - just FYI the unicode/rendering side should be ready, as of `v2.3.0`.

**Comment by EssGeeEich** [comment] 2023-01-26 00:47
API-wise, I propose the following user-facing APIs:

**fyne/v2/lang**
`lang.Language`
Literally just `type Language int`.
Basically an enumeration that will contain every language.

`lang.*`
Constants that represent a language (with a type of `lang.Language`).

`lang.LoadLanguage(lang.Language, Resource) error`
Loads a Resource as a localization language.
This might be a file format that might allow users to use websites like Crowdin.

`lang.SetCurrentLanguage(lang.Language) error`
Selects a language as the current one.

`lang.CurrentLanguage() lang.Language`
Retrieves the current language.
Should return english by default.

`lang.Tr(text string) string`
Translates a string into the currently selected language.
Falls back to english if available, returns the original string otherwise.

`lang.TrExt(text string, disambiguation string, count int) string`
Translates a string into the currently selected language.
Allows a Disambiguation string to translate words that might have multiple meanings (think of Lead, Left, Date, Fall...).
Also accepts a number which helps in translating strings that vary depending on a number (eg. 0 days / 1 day / 2 days).

**TODO**
Evaluate how to handle a run-time language change.
We should probably emit a language change event.

**Proposed usage**
```
func main() {
    a := app.New()
    
    lang.LoadLanguage(lang.English, fyne.LoadResourceFromPath("lang_en"))
    lang.LoadLanguage(lang.German, fyne.LoadResourceFromPath("lang_de"))
    // ...
    lang.SetLanguage(lang.German)

    log.Print(lang.Tr("Hello")) // Should print "Hallo"
    log.Print(1 + lang.TrExt(" days", "", 1)) // Should print 1 Tag
    log.Print(2 + lang.TrExt(" days", "", 2)) // Should print 2 Tage
}
```

**Comment by andydotxyz** [comment] 2024-01-17 10:45
Great suggestions, thanks for that. I am working on it now and like the idea of a `lang` package.

The following API currently exists in WiP #4545:

`lang.L` - localise a string with optional data
`lang.N` - localise a plural string, as above but with a count parameter

I have also longer names that the above are aliases of for people who prefer long - `lang.Localize` and `lang.LocalizePlural`.

Also included:
`lang.SystemLocal` returning a `lang.Locale`

Lots more to do, but it feels pretty good so far. Working on language packs from app next I think.

**Comment by andydotxyz** [comment] 2024-01-18 10:00
Also added `lang.AddLanguage(Resource)` where the language can be picked from name and `lang.AddLanguageForLocale(Resource, Locale)` to make it explicit...

**Comment by andydotxyz** [comment] 2024-02-18 21:23
This is now on develop, with the exception of the localised number/date formatting

**Closed by andydotxyz** 2024-02-18 21:23 UTC
