### ISSUE TITLE
It's there any way to hide the system default frame border?

### ISSUE THREAD

**Issue by yuchanns** [fyne-io/fyne#721] opened 2020-03-04 13:21 UTC
For example, I can hide the system default frame border in Qt with:
```cpp
this->setWindowFlags(Qt::FramelessWindowHint);
```
So how should I do in fyne?

**Comment by andydotxyz** [comment] 2020-03-04 14:08
We don't expose this as a feature on the main window API, we decided that splash windows were desktop specific. You can use the "develop" branch and access the new feature:

```go
drv := fyne.CurrentApp().Driver()
if drv, ok := drv.(desktop.Driver); ok {
	w := drv.CreateSplashWindow()
}
```

**Comment by andydotxyz** [comment] 2020-03-04 14:08
Closing as duplicate of #231

**Closed by andydotxyz** 2020-03-04 14:08 UTC
