### ISSUE TITLE
Can you support Chinese in the new version, thank you

### ISSUE THREAD

**Issue by careylipu** [fyne-io/fyne#1055] opened 2020-05-31 14:00 UTC
Can you support Chinese in the new version, thank you

**Comment by webluoye** [comment] 2020-06-01 03:29
显示中文可以用字体解决  

```FYNE_FONT ```  用这个全局变量 

或者参考这个 https://github.com/lusingander/fyne-font-example

**Comment by andydotxyz** [comment] 2020-06-01 11:18
We need to resolve this properly with localisation support, this is a big project.
Before then you can use the hint above to bundle font or use FYNE_FONT environment to specify at runtime.
Closing as duplicate of #63

**Closed by andydotxyz** 2020-06-01 11:18 UTC

**Comment by Aquarian-Age** [comment] 2020-06-03 13:26
> 显示中文可以用字体解决
> 
> `FYNE_FONT ` 用这个全局变量
> 
> 或者参考这个 https://github.com/lusingander/fyne-font-example

这样解决的话跨平台怎么解决呢？比如给Android编译．字体问题不好弄了．．．．

**Comment by andydotxyz** [comment] 2020-06-03 14:16
Translation from Google: 
> How to solve the cross-platform solution? For example, compile for Android. The font problem is not easy to get. . . .

**Comment by andydotxyz** [comment] 2020-06-03 14:19
We are working on ways to make this easier. I would suggest you bundle a .ttf file as a resource (https://fyne.io/develop/tutorials/bundle) and then provide a theme that sets the font to this bundled resource.
You can see how BeebUI packages a monospaced font and specifies it in [theme.go](https://github.com/andydotxyz/beebui/blob/master/theme.go).

**Comment by veo** [comment] 2020-08-03 11:09
> 我们正在研究使这一过程更容易的方法。我建议您将.ttf文件作为资源捆绑在一起（https://fyne.io/develop/tutorials/bundle），然后提供将字体设置为此捆绑资源设置的主题。
> 您可以看到BeebUI如何打包等宽字体并在[theme.go中](https://github.com/andydotxyz/beebui/blob/master/theme.go)指定它。

我使用了bundle，并在theme里面设置了font为中文字体的ttf，但是在fyne-cross编译的时候显示
[i] Target: darwin/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /Users/joker/go/src/github.com/veo/Hattrick/fyne-cross/bin/darwin-amd64
[✓] "dist" dir cleaned: /Users/joker/go/src/github.com/veo/Hattrick/fyne-cross/dist/darwin-amd64
[✓] "temp" dir cleaned: /Users/joker/go/src/github.com/veo/Hattrick/fyne-cross/tmp/darwin-amd64
[i] Checking for go.mod: /Users/joker/go/src/github.com/veo/Hattrick/go.mod
[✓] go.mod found
[i] Building binary...
go build github.com/veo/Hattrick/appgui: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
[✗] exit status 1

如果使用正常编译go build则不会出现上面的问题

**Comment by andydotxyz** [comment] 2020-08-03 22:06
For support with fyne-cross you should go to https://github.com/lucor/fyne-cross

**Comment by nevata** [comment] 2021-02-24 10:17
"测试"两个文字不能正确显示，还有其他字体下载吗？

**Comment by andydotxyz** [comment] 2021-02-24 10:45
Google translate:

> The two words "test" cannot be displayed correctly, are there other fonts to download?

**Comment by andydotxyz** [comment] 2021-02-24 10:45
Any ".ttf" file should work
