### ISSUE TITLE
Default Dark/LightTheme does not respect MacOS system preferences

### ISSUE THREAD

**Issue by Gys** [fyne-io/fyne#4874] opened 2024-05-23 18:30 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

My app always shows light text in a dark window (the DarkTheme I know now).

Reading up on theming because I dislike the dark colors, I found there also is a light theme! I also found the Fyne developers have the very outspoken opinion the dark/light choice should be made strictly on the OS level only: https://github.com/fyne-io/fyne/issues/4208...

My MacOS Sonoma 14.1.2 settings are `Appearance` `Light` (other options are `Dark` and `Auto`). Yet my Fyne app always shows the dark theme, whatever option I choose on the OS level.

I really think the user should have the option to choose dark/light for individual apps. I sometimes prefer to work in the dark theme in vscode and I always want dark themes for terminal apps. I only just realized today that MacOS has a system setting for dark / light themes and that mine is set to `Light`...

### How to reproduce

Create a minimal app. In MacOS Sonoma 14.1.2 (Intel) it will always show a dark window. Changing the OS settings and restarting the app in between does not change the theme either. It is always dark.

### Screenshots

![Screenshot 2024-05-23 at 19 29 48](https://github.com/fyne-io/fyne/assets/943251/b7f03ce8-9565-490b-87fc-4549cc16adfb)

### Example code

````
Any minimal app should do
````

### Fyne version

v2.4.5

### Go compiler version

go1.21.5 darwin/amd64

### Operating system and version

MacOS Sonoma 14.1.2 (Intel)

**Comment by andydotxyz** [comment] 2024-05-23 19:39
Look in your environment - maybe you have FYNE_THEME set to "dark" or have run fyne_settings app before.
I can promise that it does work as expected when there is no user preference override.

**Comment by Gys** [comment] 2024-05-24 07:31
Indeed I had a setting for the dark theme! Very sorry for thinking this was a bug.

I looked through the fyne_settings code and found those settings are stored in `~/Library/Preferences/fyne/settings.json`. Removing that file brought back the light theme by default.

That `settings.json` file was more than four years old... A time when I also considered building something in Fyne and did some experimenting. It does not feel right to have some setting deep down in the system (for the average user) which overrides the OS settings for dark and light, though. I can control settings for all Fyne apps by modifying that one settings file, overriding the OS settings...

**Comment by andydotxyz** [comment] 2024-05-24 07:54
How else would you recommend storing the preferences? That is the OS defined location and as you say fyne_settings had been used to set it and could have been used to unset it too.

I'm glad the problem is resolved, but I don't think its existence is a flaw.

**Comment by Gys** [comment] 2024-05-24 09:34
I think there should not be one location where all settings are stored for all applications built with one framework, in this case Fyne. 

Settings for my app should be managed by my app. It should be 'myApp_settings', not 'fyne_settings'. If I delete apps from my system then I also want to delete all related files like their settings.

I cannot image any user is interested in the fact that two applications that he uses are built with the same framework and therefore (?) share their settings. Edge, vscode and the Github app are a few examples of apps built by Microsoft. I would be really displeased if those share their settings. So if I delete the 'microsoft_settings' file created by Edge (a simple user way of thinking) I suddenly would loose all settings in vscode.

**Comment by andydotxyz** [comment] 2024-05-24 12:25
Yes, an app using the Preferences API will store the data per-app. But fyne_settings is a global configuration app and so it stored the setting globally.

Plenty of apps use local storage to specify a theme of choice.
Global storage is capable of a number of things - the main one is text scaling so you can adjust the multiple against which Fyne apps render.
Of course normally this can be ignored because the defaults are designed to be good.

**Comment by Gys** [comment] 2024-05-24 13:17
> fyne_settings is a global configuration app and so it stored the setting globally.

That is a little tricky in my opinion. Because even a simple Fyne app already uses those settings? Without me as a user nor as a developer being aware. I think there should not be an implicit global file. At the very least I as a developer should explicitly choose to use it.

**Comment by Jacalz** [comment] 2024-05-24 13:24
> I think there should not be an implicit global file. At the very least I as a developer should explicitly choose to use it.

But you did choose to use it. You used the global settings app to change the theme; of course it is set globally for your apps.

**Comment by andydotxyz** [comment] 2024-05-24 16:08
Closing as there was no issue here to resolve.

**Closed by andydotxyz** 2024-05-24 16:08 UTC
Labels: not an issue
